begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.receipt_erp_contract() returns setof text language plpgsql as $$
declare boss uuid:=gen_random_uuid();staff uuid:=gen_random_uuid();supervisor uuid:=gen_random_uuid();logistics uuid:=gen_random_uuid();org uuid;s uuid;other_store uuid;data jsonb;
 a uuid; b uuid; foreign_batch uuid; incomplete uuid; payload jsonb; saved jsonb; request uuid:=gen_random_uuid(); erp_request uuid:=gen_random_uuid(); before_upload timestamptz; before_work date; completed jsonb; issue uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) select x,x||'@workflow.invalid',now(),now(),now() from unnest(array[boss,staff,supervisor,logistics]) x;
 perform set_config('request.jwt.claim.sub',boss::text,true);
 data:=public.owner_setup();data:=public.owner_setup('business','{"organization_name":"流程隔離驗收","business_type":"SINGLE_RESTAURANT","store_mode":"SINGLE"}',0);
 data:=public.owner_setup('store',data->'draft'||jsonb_build_object('store_name','流程A','store_code','FLOW'||substr(replace(gen_random_uuid()::text,'-',''),1,12)),(data->>'revision')::int);
 data:=public.owner_setup('identity',data->'draft'||'{"work_role":"OWNER"}',(data->>'revision')::int);
 data:=public.owner_setup('complete',data->'draft',(data->>'revision')::int);s:=(data->>'store_id')::uuid;org:=(data->>'organization_id')::uuid;
 other_store:=(public.app_operation(s,'store.create','{"name":"流程B"}',gen_random_uuid())->>'id')::uuid;
 insert into public.organization_members(organization_id,user_id,role,work_role) values(org,staff,'STAFF','STAFF'),(org,supervisor,'SUPERVISOR','SUPERVISOR'),(org,logistics,'LOGISTICS','LOGISTICS');
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) select org,x,x::text,boss from unnest(array[staff,supervisor,logistics]) x;
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,work_role,assigned_by) values(s,org,staff,'field','STAFF','STAFF',boss),(s,org,supervisor,'manager','SUPERVISOR','SUPERVISOR',boss),(s,org,logistics,'office','LOGISTICS','LOGISTICS',boss);

 update public.organizations set business_type='CHAIN_RESTAURANT',has_erp=true where id=org;
 insert into public.receipt_upload_batches(organization_id,store_id,store_name,uploaded_by,erp_required,work_date) values(org,s,'流程A',staff,true,'2026-08-01') returning id,uploaded_at,work_date into a,before_upload,before_work;
 insert into public.receipt_upload_batches(organization_id,store_id,store_name,uploaded_by,erp_required,work_date) values(org,s,'流程A',staff,true,current_date) returning id into b;
 insert into public.receipt_upload_batches(organization_id,store_id,store_name,uploaded_by,erp_required,work_date) values(org,s,'流程A',staff,true,current_date) returning id into incomplete;
 insert into public.receipt_upload_batches(organization_id,store_id,store_name,uploaded_by,erp_required,work_date) values(org,other_store,'流程B',boss,true,current_date) returning id into foreign_batch;
 insert into public.receipt_ocr_jobs(organization_id,batch_id,requested_by,status) values(org,a,staff,'QUEUED'),(org,b,staff,'QUEUED'),(org,foreign_batch,boss,'QUEUED');
 perform set_config('request.jwt.claim.sub',staff::text,true);
 return next is(public.get_app_dashboard(s)->>'receipt_erp_pending','2','ERP home excludes incomplete uploads');
 return next is((public.get_pilot_receipt(a)->'batch'->'delivery'->>'arrived_on'),null,'legacy arrival remains unspecified');
 return next is(jsonb_array_length(public.get_pilot_receipts(s)),3,'receipt list is scoped to A');
 payload:=jsonb_build_object('batch_id',a,'revision',0,'arrived_on','2026-08-01','arrived_time',null,'issues',jsonb_build_array(jsonb_build_object('id',issue,'name','驗收牛奶','reason','少收貨','quantity',1,'unit','瓶','note','','status','OPEN')));
 saved:=public.app_operation(s,'receipt.delivery',payload,request);
 return next is(public.app_operation(s,'receipt.delivery',payload,request),saved,'delivery retry creates no extra revision');
 return next is(public.get_app_dashboard(s)->>'receipt_issues','1','unresolved previous-month issue is counted');
 return next is(public.get_pilot_receipt(a)->'batch'->'delivery',saved,'detail uses saved delivery data');
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',s,'receipt.delivery',payload,gen_random_uuid()),'40001','REVISION_CONFLICT','stale save cannot overwrite');
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',s,'receipt.erp-bulk',jsonb_build_object('batch_ids',jsonb_build_array(a,foreign_batch)),gen_random_uuid()),'42501','RECEIPT_ACCESS_DENIED','mixed store bulk is denied');
 return next ok((select erp_completed_at is null from public.receipt_upload_batches where id=a),'denied bulk changes no selected receipt');
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',s,'receipt.erp-bulk',jsonb_build_object('batch_ids',jsonb_build_array(a,incomplete)),gen_random_uuid()),'P0001','ORIGINAL_UPLOAD_INCOMPLETE','incomplete upload rejects entire batch');
 return next ok((select erp_completed_at is null from public.receipt_upload_batches where id=a),'validation failure is atomic');
 data:=jsonb_build_object('batch_ids',jsonb_build_array(a,b));
 completed:=public.app_operation(s,'receipt.erp-bulk',data,erp_request);
 return next is(public.app_operation(s,'receipt.erp-bulk',data,erp_request),completed,'ERP retry reuses saved request');
 return next is(public.get_app_dashboard(s)->>'receipt_erp_pending','0','home and pending list both become zero');
 return next is(public.get_app_dashboard(s)->>'receipt_issues','1','ERP completion never closes delivery issue');
 completed:=public.complete_pilot_receipt_erp(a);
 return next is(public.complete_pilot_receipt_erp(a),completed,'single ERP retry retains actor and time');
 return next is((select count(*)::integer from public.audit_logs where entity_id=a::text and action='RECEIPT_ERP_REPORTED'),1,'one ERP completion audit');
 return next ok((select uploaded_at=before_upload and work_date=before_work from public.receipt_upload_batches where id=a),'arrival editing preserves upload and work date');
 return next ok(not exists(select 1 from public.goods_receipts where source_batch_id=a),'exceptions and ERP do not post inventory');
 perform set_config('request.jwt.claim.sub',logistics::text,true);
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',s,'receipt.erp-bulk',data,erp_request),'42501','FIELD_ROLE_REQUIRED','non-field role cannot replay cached batch');
 return next throws_ok(format('select public.complete_pilot_receipt_erp(%L)',a),'42501','ERP_REPORT_NOT_ALLOWED','direct endpoint uses the same role boundary');
 perform set_config('request.jwt.claim.sub',boss::text,true);
 return next throws_ok(format('select public.complete_pilot_receipt_erp(%L)',a),'42501','ERP_REPORT_NOT_ALLOWED','owner remains read-only for field ERP reporting');
 perform set_config('request.jwt.claim.sub',supervisor::text,true);
 payload:=payload||jsonb_build_object('revision',1,'issues',jsonb_build_array((payload->'issues'->0)||jsonb_build_object('status','COMPLETE','note','已補收')));
 saved:=public.app_operation(s,'receipt.delivery',payload,gen_random_uuid());
 return next is(public.get_app_dashboard(s)->>'receipt_issues','0','only explicit resolution clears pending issue');
 return next is(jsonb_array_length(saved->'issues'),1,'resolved history is retained');
 update public.store_memberships set is_active=false where store_id=s and user_id=staff;
 perform set_config('request.jwt.claim.sub',staff::text,true);
 return next throws_ok(format('select public.get_pilot_receipts(%L)',s),'42501','STORE_MEMBERSHIP_REQUIRED','disabled membership cannot read receipt list');
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',s,'receipt.erp-bulk',data,erp_request),'42501','FIELD_ROLE_REQUIRED','disabled membership cannot replay successful ERP');
end $$;
select * from pg_temp.receipt_erp_contract();
select * from finish();
rollback;
