-- Isolated fixtures only. The entire test rolls back, including users and prices.
begin;
do $$
declare a uuid:=gen_random_uuid(); o uuid:=gen_random_uuid(); o2 uuid:=gen_random_uuid(); s uuid:=gen_random_uuid(); t uuid:=gen_random_uuid(); f uuid:=gen_random_uuid(); leaf uuid:=gen_random_uuid(); prep uuid:=gen_random_uuid(); main uuid:=gen_random_uuid(); other uuid:=gen_random_uuid(); req uuid:=gen_random_uuid(); p jsonb; d jsonb; r jsonb; n bigint; v bigint;
begin
 insert into auth.users(id,email,aud,role,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values(a,a::text||'@recipe-fixture.invalid','authenticated','authenticated',now(),'{}','{}',now(),now());
 insert into public.profiles(id,display_name) values(a,'Recipe rollback fixture') on conflict(id) do nothing;
 insert into public.organizations(id,name,business_type,store_mode) values(o,'Recipe rollback fixture','SINGLE_RESTAURANT','MULTI'),(o2,'Other fixture','SINGLE_RESTAURANT','SINGLE');
 insert into public.organization_members(organization_id,user_id,role) values(o,a,'LOGISTICS'),(o2,a,'LOGISTICS');
 insert into public.staff_identities(user_id,organization_id,display_name,created_by) values(a,o,'Fixture',a),(a,o2,'Fixture',a);
 insert into public.stores(id,organization_id,store_code,name,created_by) values(s,o,'fx_'||substr(s::text,1,8),'Source',a),(t,o,'fx_'||substr(t::text,1,8),'Target',a),(f,o2,'fx_'||substr(f::text,1,8),'Other',a);
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,assigned_by,can_manage_business) values(s,o,a,'fixture','LOGISTICS',a,false),(t,o,a,'fixture','LOGISTICS',a,false),(f,o2,a,'fixture','LOGISTICS',a,false);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 perform public.app_operation(s,'recipe.price',jsonb_build_object('name','豬皮','unit','卷','price',30,'source','fixture','effective_date','2026-10-02','purchase',jsonb_build_object('amount',30,'quantity',1,'unit','卷')),gen_random_uuid());
 perform public.app_operation(t,'recipe.price',jsonb_build_object('name','豬皮','unit','卷','price',99,'source','target fixture','effective_date','2026-10-02'),gen_random_uuid());
 d:=jsonb_build_object('name','Leaf','kind','prep','yield','2','unit','卷','notes','規格600g，按卷計價','lines',jsonb_build_array(jsonb_build_object('id','line1','name','豬皮','quantity','2','unit','卷')));
 perform public.app_operation(s,'recipe.save',jsonb_build_object('id',leaf,'revision',0,'document',d),gen_random_uuid());
 assert (private.recipe_cost(s,d)->>'total')::numeric=60,'roll costing';
 d:=jsonb_build_object('name','Shared','kind','prep','yield','2','unit','卷','notes','shared','lines',jsonb_build_array(jsonb_build_object('id','line2','name','Leaf','quantity','2','unit','卷','recipe_id',leaf)));
 perform public.app_operation(s,'recipe.save',jsonb_build_object('id',prep,'revision',0,'document',d),gen_random_uuid());
 d:=jsonb_build_object('name','Main','kind','dish','yield','1','unit','份','notes','main notes','lines',jsonb_build_array(jsonb_build_object('id','line3','name','Shared','quantity','1','unit','卷','recipe_id',prep)));
 perform public.app_operation(s,'recipe.save',jsonb_build_object('id',main,'revision',0,'document',d),gen_random_uuid());
 perform public.app_operation(s,'recipe.save',jsonb_build_object('id',other,'revision',0,'document',d||'{"name":"Other main"}'),gen_random_uuid());
 p:=public.app_workspace(s,'recipe.transfer',jsonb_build_object('id',main,'target_store_id',t));
 assert jsonb_array_length(p->'recipes')=3,'dependency closure';
 assert (select count(*) from jsonb_array_elements(p->'recipes') where value->>'mode'='copy')=2,'shared descendants copied';
 begin perform public.app_workspace(s,'recipe.transfer',jsonb_build_object('id',main,'target_store_id',f));raise exception 'cross-org allowed';exception when sqlstate '22023' then null;end;
 update public.store_memberships set access_mode='VIEW' where store_id=t and user_id=a;
 begin perform public.app_workspace(s,'recipe.transfer',jsonb_build_object('id',main,'target_store_id',t));raise exception 'view allowed';exception when insufficient_privilege then null;end;
 update public.store_memberships set access_mode='EDIT',role='STAFF',work_role='STAFF' where store_id=t and user_id=a;
 begin perform public.app_workspace(s,'recipe.transfer',jsonb_build_object('id',main,'target_store_id',t));raise exception 'staff allowed';exception when insufficient_privilege then null;end;
 update public.store_memberships set role='LOGISTICS',work_role='LOGISTICS' where store_id=t and user_id=a;
 begin perform public.app_operation(s,'recipe.transfer',jsonb_build_object('id',main,'target_store_id',t,'token','stale'),gen_random_uuid());raise exception 'stale token allowed';exception when serialization_failure then null;end;
 select count(*) into n from private.recipe_price_entries;select count(*) into v from private.recipe_versions;
 d:=jsonb_build_object('id',main,'target_store_id',t,'token',p->>'token');
 r:=public.app_operation(s,'recipe.transfer',d,req);
 assert r=public.app_operation(s,'recipe.transfer',d,req),'idempotency';
 assert (select count(*) from private.recipe_price_entries)=n,'prices untouched';
 assert (select count(*) from private.recipe_versions)=v+3,'version count';
 assert (select store_id from private.recipe_cards where id=main)=t,'root moved';
 assert (select store_id from private.recipe_cards where id=prep)=s,'shared source stays';
 assert (select store_id from private.recipe_cards where id=leaf)=s,'shared leaf stays';
 assert (select (private.recipe_cost(t,document,array[main])->>'total')::numeric from private.recipe_cards where id=main)=30,'source adopted price';
 assert (select (private.recipe_cost(s,document,array[other])->>'total')::numeric from private.recipe_cards where id=other)=30,'source recipe intact';
 assert (select count(*) from public.audit_logs where entity_id=main::text and action='recipe.transfer')=1,'one audit';
 begin perform public.app_operation(s,'recipe.transfer',d||'{"token":"changed"}',req);raise exception 'conflicting replay allowed';exception when unique_violation then null;end;
 assert public.app_workspace(s,'recipes')->'moved_recipe_ids' ? main::text,'move tombstone';
 perform set_config('request.jwt.claims','{}',true);
 begin perform public.app_workspace(s,'recipe.transfer',jsonb_build_object('id',other,'target_store_id',t));raise exception 'anonymous allowed';exception when insufficient_privilege then null;end;
end $$;
rollback;
