begin;
select no_plan();
create function pg_temp.isolation_contract() returns setof text language plpgsql as $$
declare boss uuid:=gen_random_uuid();sa uuid:=gen_random_uuid();sb uuid:=gen_random_uuid();org uuid;a uuid;b uuid;empty_store uuid;pa uuid:=gen_random_uuid();pb uuid:=gen_random_uuid();za uuid:=gen_random_uuid();zb uuid:=gen_random_uuid();ca uuid:=gen_random_uuid();cb uuid:=gen_random_uuid();data jsonb;payload jsonb;saved jsonb;prior jsonb;request uuid;batch_a uuid:=gen_random_uuid();batch_b uuid:=gen_random_uuid();move uuid;
begin
 insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) select u,u||'@isolation.invalid',now(),now(),now() from unnest(array[boss,sa,sb]) u;
 perform set_config('request.jwt.claim.sub',boss::text,true);
 data:=public.owner_setup();data:=public.owner_setup('business','{"organization_name":"雙店隔離驗收","business_type":"SINGLE_RESTAURANT","store_mode":"SINGLE"}',0);
 data:=public.owner_setup('store',data->'draft'||jsonb_build_object('store_name','同名店','store_code','ISO'||substr(replace(gen_random_uuid()::text,'-',''),1,12)),(data->>'revision')::int);
 data:=public.owner_setup('identity',data->'draft'||'{"work_role":"OWNER"}',(data->>'revision')::int);
 data:=public.owner_setup('complete',data->'draft',(data->>'revision')::int);a:=(data->>'store_id')::uuid;org:=(data->>'organization_id')::uuid;
 b:=(public.app_operation(a,'store.create','{"name":"同名店"}',gen_random_uuid())->>'id')::uuid;
 insert into public.organization_members(organization_id,user_id,role,work_role) values(org,sa,'SUPERVISOR','SUPERVISOR'),(org,sb,'OWNER','OWNER');
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) values(org,sa,'A 專屬主管',boss),(org,sb,'B 專屬管理者',boss);
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,work_role,assigned_by,can_manage_business) values(a,org,sa,'only-a','SUPERVISOR','SUPERVISOR',boss,true),(b,org,sb,'only-b','OWNER','OWNER',boss,true);
 return next ok(not exists(select 1 from public.store_memberships where user_id=sb and store_id=a),'scoped owner does not expand to A');
 return next is(jsonb_array_length(public.app_workspace(a,'members')->'members'),2,'A members: owner and A only');
 return next is(jsonb_array_length(public.app_workspace(b,'members')->'members'),2,'B members: owner and B only');
 return next ok(exists(select 1 from jsonb_array_elements(public.app_workspace(a,'members')->'members') m where m->>'user_id'=boss::text and (m->>'is_enterprise_admin')::boolean),'genuine enterprise owner labelled');
 return next ok(not exists(select 1 from jsonb_array_elements(public.app_workspace(b,'members')->'members') m where m->>'user_id'=sb::text and (m->>'is_enterprise_admin')::boolean),'store-only owner not labelled enterprise');
 insert into public.receipt_upload_batches(id,organization_id,store_id,store_name,work_date,uploaded_by,batch_number,status) values(batch_a,org,a,'同名店',current_date,sa,'A 貨單','READY_FOR_REVIEW'),(batch_b,org,b,'同名店',current_date,sb,'B 貨單','READY_FOR_REVIEW'),(gen_random_uuid(),org,b,'同名店',current_date,sb,'B 第二張','READY_FOR_REVIEW');
 return next is((private.app_dashboard(a)->>'receipt_pending')::int,1,'A pending is one, not enterprise sum');
 return next is((private.app_dashboard(b)->>'receipt_pending')::int,2,'B pending is two');
 insert into public.products(id,organization_id,product_code,name,base_unit,count_unit) values(pa,org,'A','A 火腿','包','包'),(pb,org,'B','B 麵','袋','袋');
 insert into public.count_zones(id,organization_id,store_id,name) values(za,org,a,'冷藏'),(zb,org,b,'冷藏');
 insert into public.zone_products(zone_id,product_id,count_unit,sort_order) values(za,pa,'包',7),(zb,pb,'袋',3);
 insert into public.inventory_count_sessions(id,organization_id,store_id,started_by,status,snapshot) values(ca,org,a,sa,'IN_PROGRESS',jsonb_build_object('zones',jsonb_build_array(jsonb_build_object('zone_id',za,'product_id',pa,'product_name','A 火腿','unit','包','zone_name','冷藏')))),(cb,org,b,sb,'CLOSED','{}');
 insert into public.count_entries(organization_id,session_id,zone_id,product_id,quantity,unit,entered_by) values(org,ca,za,pa,5,'包',sa);
 insert into private.waste_records(organization_id,store_id,store_name,name,quantity,unit,reason,source,erp_required,created_by,actor_name) values(org,a,'同名店','A 廢棄',1,'包','品質異常','FIELD',false,sa,'A 專屬主管'),(org,b,'同名店','B 廢棄',2,'袋','品質異常','FIELD',false,sb,'B 專屬管理者');
 return next is(jsonb_array_length(public.app_workspace(a,'store-archive')->'receipts'),1,'archive A receipts scoped');
 return next is(jsonb_array_length(public.app_workspace(b,'store-archive')->'receipts'),2,'archive B receipts scoped');
 return next is(public.app_workspace(a,'store-archive')->'waste'->0->>'name','A 廢棄','waste scoped by UUID');
 return next is(jsonb_array_length(public.app_workspace(a,'store-archive')->'counts'),1,'counts scoped by UUID');
 select to_jsonb(p) into data from public.products p where id=pa;payload:=jsonb_build_object('id',pa,'name','A 火腿新名稱','unit','箱','specification','新規格','updated_at',data->'updated_at');request:=gen_random_uuid();
 select to_jsonb(c) into prior from public.count_entries c where session_id=ca;
 perform set_config('request.jwt.claim.sub',sa::text,true);
 saved:=public.app_operation(a,'product.edit-basic',payload,request);
 return next is(public.app_operation(a,'product.edit-basic',payload,request),saved,'product retry idempotent');
 return next is((select name from public.products where id=pa),'A 火腿新名稱','supervisor edits basic product');
 return next is((select count_unit from public.zone_products where zone_id=za and product_id=pa),'箱','future zone unit updated');
 return next is((select sort_order from public.zone_products where zone_id=za and product_id=pa),7,'sort unchanged');
 return next is((select to_jsonb(c) from public.count_entries c where session_id=ca),prior,'quantity and original unit unchanged');
 return next is((select snapshot#>>'{zones,0,product_name}' from public.inventory_count_sessions where id=ca),'A 火腿','historical product snapshot unchanged');
 return next is((select count_unit from public.zone_products where zone_id=zb),'袋','B unit unchanged');
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',a,'product.edit-basic',payload||jsonb_build_object('updated_at','2000-01-01'),gen_random_uuid()),'40001','REVISION_CONFLICT','stale edit rejected');
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',a,'product.edit-basic',payload||jsonb_build_object('id',pb),gen_random_uuid()),'P0002','PRODUCT_NOT_FOUND','A cannot edit B-only product');
 return next throws_ok(format('select public.app_workspace(%L,%L)',b,'members'),'42501','APP_FORBIDDEN','A member cannot read B members');
 return next throws_ok(format('select public.app_workspace(%L,%L)',b,'store-archive'),'42501','APP_FORBIDDEN','A member cannot read B archive');
 perform set_config('request.jwt.claim.sub',boss::text,true);
 payload:=public.app_workspace(a,'store-lifecycle',jsonb_build_object('id',b))->'store';
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',a,'store.delete',payload,gen_random_uuid()),'23503','STORE_REFERENCED_USE_DEACTIVATE','referenced store cannot be deleted');
 insert into public.stores(organization_id,name,store_code,created_by) values(org,'無引用建錯門市','EMPTY'||substr(replace(gen_random_uuid()::text,'-',''),1,12),boss) returning id into empty_store;
 payload:=public.app_workspace(a,'store-lifecycle',jsonb_build_object('id',empty_store))->'store';request:=gen_random_uuid();saved:=public.app_operation(a,'store.delete',payload,request);
 return next ok(not exists(select 1 from public.stores where id=empty_store),'unreferenced store deleted');
 return next is(public.app_operation(a,'store.delete',payload,request),saved,'deleted store retry uses tombstone');
 perform set_config('request.jwt.claim.sub',sa::text,true);
 data:=public.app_operation(a,'movement.create',jsonb_build_object('mode','loan','other_store_id',b,'name','火腿','quantity',2,'unit','包'),gen_random_uuid());move:=(data->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',boss::text,true);
 payload:=public.app_workspace(a,'store-lifecycle',jsonb_build_object('id',a))->'store';request:=gen_random_uuid();saved:=public.app_operation(b,'store.deactivate',payload,request);
 return next is(public.app_operation(b,'store.deactivate',payload,request),saved,'deactivation retry stable');
 return next is(jsonb_array_length(public.get_app_context()->'stores'),1,'inactive A removed from normal switcher');
 return next is(public.get_app_context()->'stores'->0->>'id',b::text,'remaining store is B');
 return next ok(private.app_role(a) is null,'inactive store loses normal operation role');
 return next is(public.app_workspace(a,'store-archive')->'counts'->0->'lines'->0->>'name','A 火腿','archive reads original snapshot');
 return next is(jsonb_array_length(public.app_workspace(b,'archived-stores')->'stores'),1,'inactive store listed in explicit archive');
 return next throws_ok(format('select public.app_workspace(%L,%L)',a,'catalog'),'42501','APP_FORBIDDEN','inactive catalog operations denied');
 perform set_config('request.jwt.claim.sub',sa::text,true);
 return next ok((public.get_app_context()->'stores'->0->>'is_active')::boolean=false,'last inactive membership offers archive recovery');
 payload:=jsonb_build_object('id',move,'quantity',2,'revision',1);request:=gen_random_uuid();saved:=public.app_operation(a,'movement.return',payload,request);
 return next is(saved->>'status','RETURNED','authorized field role settles archived loan');
 return next is(public.app_operation(a,'movement.return',payload,request),saved,'archived return retry idempotent');
 return next is((select count(*) from private.store_movement_events where movement_id=move and action='RETURN'),1::bigint,'one return event');
 update public.store_memberships set is_active=false where user_id=sa and store_id=a;
 return next throws_ok(format('select public.app_operation(%L,%L,%L,%L)',a,'movement.return',payload,request),'42501','APP_FORBIDDEN','revoked member cannot replay archived return');
 return next throws_ok(format('select public.app_workspace(%L,%L)',a,'store-archive'),'42501','APP_FORBIDDEN','revoked member denied archive');
 perform set_config('request.jwt.claim.sub',boss::text,true);
 payload:=public.app_workspace(b,'store-lifecycle',jsonb_build_object('id',a))->'store';perform public.app_operation(b,'store.restore',payload,gen_random_uuid());
 return next is(jsonb_array_length(public.get_app_context()->'stores'),2,'restored store returns after reread');
 return next is((private.app_dashboard(a)->>'receipt_pending')::int,1,'receipt ownership remains A after restoration');
 return next is((select count(*) from public.receipt_upload_batches where store_id=b),2::bigint,'B receipts untouched');
 return next ok(not exists(select 1 from jsonb_array_elements(public.app_workspace(a,'members')->'members') m where m->>'user_id'=sa::text),'revoked member excluded from active list');
end $$;
select * from pg_temp.isolation_contract();
select * from finish();
rollback;
