begin;
select no_plan();
create function pg_temp.store_management_contract(kind text) returns setof text language plpgsql as $$
declare owner_id uuid:=gen_random_uuid(); manager_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); another_owner uuid:=gen_random_uuid();
 a uuid;b uuid;org uuid;request uuid:=gen_random_uuid();data jsonb;draft jsonb;member jsonb;saved jsonb;before_b jsonb;cached_request uuid:=gen_random_uuid();code text:='QAMGMT'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12));
begin
 insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) select u,u||'@store-management.invalid',now(),now(),now() from unnest(array[owner_id,manager_id,staff_id,another_owner]) u;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 data:=public.owner_setup();data:=public.owner_setup('business',jsonb_build_object('organization_name','門市管理隔離驗收','business_type',kind,'store_mode','SINGLE'),0);
 data:=public.owner_setup('store',data->'draft'||jsonb_build_object('store_name','A 店','store_code',code,'staff_login_mode','NAME_OR_NICKNAME'),(data->>'revision')::int);
 data:=public.owner_setup('identity',data->'draft'||'{"work_role":"OWNER"}',(data->>'revision')::int);
 data:=public.owner_setup('complete',data->'draft',(data->>'revision')::int);a:=(data->>'store_id')::uuid;org:=(data->>'organization_id')::uuid;
 saved:=public.app_operation(a,'store.create','{"name":"B 店"}',request);b:=(saved->>'id')::uuid;
 return next is(public.app_operation(a,'store.create','{"name":"B 店"}',request),saved,kind||': name-only creation retry reuses store');
 return next is((select count(*) from public.stores where organization_id=org),2::bigint,kind||': exactly two stores');
 return next ok(saved->'store'->>'store_code' ~ '^S[A-F0-9]{12}$',kind||': server-generated store code');
 return next is((select store_mode from public.organizations where id=org),'MULTI',kind||': second store enables existing multi-store operations');
 return next is(jsonb_array_length(public.get_app_context()->'stores'),2,kind||': owner switcher includes both stores');
 return next is(jsonb_array_length(public.app_workspace(a,'business')->'stores'),2,kind||': cards include both stores');
 return next ok(private.can_manage_business(b),kind||': owner immediately manages new store');
 return next is((select count(*) from public.inventory_count_sessions where store_id=b),0::bigint,kind||': new store has no seeded operation records');
 before_b:=public.app_workspace(b,'settings');data:=public.app_workspace(a,'settings');
 perform public.app_operation(a,'settings.save',jsonb_build_object('revision',data->'revision','settings',jsonb_build_object('count_cadence','MANUAL','erp_waste',false)),gen_random_uuid());
 return next is(public.app_workspace(b,'settings'),before_b,kind||': A settings do not change B');
 return next is(public.app_workspace(a,'settings')->'settings'->>'count_cadence','MANUAL',kind||': A settings reload correctly');
 insert into public.organization_members(organization_id,user_id,role,work_role,can_manage_business) values(org,manager_id,'SUPERVISOR','SUPERVISOR',true),(org,staff_id,'STAFF','STAFF',false),(org,another_owner,'OWNER','OWNER',false);
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) values(org,manager_id,'雙店不同身分',owner_id),(org,staff_id,'本店員工',owner_id),(org,another_owner,'第二位老闆',owner_id);
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,work_role,assigned_by,can_manage_business) values(a,org,manager_id,'manager','SUPERVISOR','SUPERVISOR',owner_id,true),(b,org,manager_id,'manager','STAFF','STAFF',owner_id,false),(a,org,staff_id,'staff','STAFF','STAFF',owner_id,false),(b,org,staff_id,'staff','STAFF','STAFF',owner_id,false),(a,org,another_owner,'second-owner','OWNER','OWNER',owner_id,true);
 return next ok(exists(select 1 from public.store_memberships where store_id=b and user_id=another_owner),kind||': assigned owner gets missing enterprise store');
 select x into member from jsonb_array_elements(public.app_workspace(a,'members')->'members') x where x->>'user_id'=manager_id::text;
 perform public.app_operation(a,'member.save',member||'{"display_name":"A 店主管","extra_permissions":["REPORTS_VIEW"]}',gen_random_uuid());
 return next is((select display_name from public.store_memberships where store_id=b and user_id=manager_id),'雙店不同身分',kind||': member nickname is local to A');
 return next is((select work_role::text from public.store_memberships where store_id=b and user_id=manager_id),'STAFF',kind||': B identity preserved');
 return next is((select extra_permissions from public.store_memberships where store_id=b and user_id=manager_id),'{}'::text[],kind||': B permissions preserved');
 perform set_config('request.jwt.claim.sub',manager_id::text,true);
 return next is(private.app_role(a),'SUPERVISOR',kind||': A identity is supervisor or manager');return next is(private.app_role(b),'STAFF',kind||': switching B applies staff identity');
 return next ok(private.can_manage_members(a) and not private.can_manage_members(b),kind||': member operations only in managed store');
 if kind='CHAIN_RESTAURANT' then
  return next ok(not private.can_manage_business(a),kind||': chain manager has no store settings despite legacy admin flag');
  return next throws_ok(format('select public.app_workspace(%L::uuid,%L)',a,'business'),'42501','APP_FORBIDDEN',kind||': chain settings read denied');
  return next throws_ok(format('select public.app_operation(%L::uuid,%L,%L::jsonb,%L::uuid)',a,'store.create','{"name":"不能建店"}',gen_random_uuid()),'42501','APP_FORBIDDEN',kind||': chain store creation denied');
 else
  return next ok(private.can_manage_business(a),kind||': authorized supervisor manages A');
  return next throws_ok(format('select public.prepare_management_invite(%L::uuid,%L::uuid,%L,%L,%L)',a,manager_id,'no-owner@store-management.invalid','不可建立','OWNER'),'42501','ROLE_NOT_ALLOWED',kind||': supervisor cannot invite owner');
 end if;
 select x into member from jsonb_array_elements(public.app_workspace(a,'members')->'members') x where x->>'user_id'=staff_id::text;
 draft:=member||'{"display_name":"已修改員工"}';saved:=public.app_operation(a,'member.save',draft,cached_request);
 return next is(public.app_operation(a,'member.save',draft,cached_request),saved,kind||': member save retry does not duplicate');
 return next is((select display_name from public.store_memberships where store_id=b and user_id=staff_id),'本店員工',kind||': manager changes stay in A');
 return next throws_ok(format('select public.app_operation(%L::uuid,%L,%L::jsonb,%L::uuid)',a,'member.save',jsonb_build_object('user_id',manager_id,'role','OWNER'),gen_random_uuid()),'42501','CANNOT_CHANGE_OWNER_OR_SELF',kind||': self elevation denied');
 return next throws_ok(format('select public.app_workspace(%L::uuid,%L)',b,'members'),'42501','APP_FORBIDDEN',kind||': B staff cannot read member administration');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 select x into member from jsonb_array_elements(public.app_workspace(a,'members')->'members') x where x->>'user_id'=manager_id::text;
 perform public.app_operation(a,'member.save',member||'{"is_active":false}',gen_random_uuid());
 perform set_config('request.jwt.claim.sub',manager_id::text,true);
 return next throws_ok(format('select public.app_operation(%L::uuid,%L,%L::jsonb,%L::uuid)',a,'member.save',draft,cached_request),'42501','APP_FORBIDDEN',kind||': revoked actor cannot replay save');
 return next is(jsonb_array_length(public.get_app_context()->'stores'),1,kind||': revoked store removed from reloaded list');
 perform set_config('request.jwt.claim.sub',staff_id::text,true);
 return next throws_ok(format('select public.app_workspace(%L::uuid,%L)',a,'members'),'42501','APP_FORBIDDEN',kind||': employee management denied at backend');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.app_operation(a,'business.transfer',jsonb_build_object('user_id',another_owner,'keep_admin',false),gen_random_uuid());
 return next ok(not private.can_manage_business(a) and not private.can_manage_business(b),kind||': owner role cannot restore an explicitly revoked admin grant');
 return next is(private.app_role(a),'OWNER',kind||': revocation preserves prior work identity');
 perform set_config('request.jwt.claim.sub',another_owner::text,true);
 return next ok(private.can_manage_business(a) and private.can_manage_business(b),kind||': successor retains valid management across both stores');
 data:=public.app_operation(a,'store.create','{"name":"交接後新店"}',gen_random_uuid());
 return next ok(not exists(select 1 from public.store_memberships where store_id=(data->>'id')::uuid and user_id=owner_id),kind||': future store does not regrant revoked owner scope');
end $$;
select * from pg_temp.store_management_contract('SINGLE_RESTAURANT');
select * from pg_temp.store_management_contract('CHAIN_RESTAURANT');
select * from finish();
rollback;
