begin;
do $$
declare owner_id uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();org uuid;s uuid;other uuid;product uuid;setup jsonb;v jsonb;r jsonb;r2 jsonb;req uuid:=gen_random_uuid();wid uuid;tid uuid;expected jsonb;before_count bigint;catalog_id uuid;catalog_value jsonb;
begin
 insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values(owner_id,owner_id||'@sheet.invalid',now(),now(),now()),(outsider,outsider||'@sheet.invalid',now(),now(),now());
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 setup:=public.owner_setup();setup:=public.owner_setup('business','{"organization_name":"共用表格隔離驗收","business_type":"SINGLE_RESTAURANT","store_mode":"SINGLE"}',0);
 setup:=public.owner_setup('store',setup->'draft'||jsonb_build_object('store_name','BeApe','store_code','SHEET'||substr(replace(gen_random_uuid()::text,'-',''),1,10)),(setup->>'revision')::int);
 setup:=public.owner_setup('identity',setup->'draft'||'{"work_role":"OWNER"}',(setup->>'revision')::int);
 setup:=public.owner_setup('complete',setup->'draft',(setup->>'revision')::int);s:=(setup->>'store_id')::uuid;org:=(setup->>'organization_id')::uuid;
 other:=(public.app_operation(s,'store.create','{"name":"Gras"}',gen_random_uuid())->>'id')::uuid;
 insert into public.products(organization_id,product_code,name,base_unit,count_unit,is_active) values(org,'SHEETTEST','測試起司','包','包',true) returning id into product;
 v:=jsonb_build_object('name','測試起司','unit','包','quantity','2','price','25','date',(now() at time zone 'Asia/Taipei')::date,'reason','品質異常','note','初始備註','actor','隔離測試');
 r:=public.save_baihuayuan_sheet_row(s,'waste',null,v,'{}',req);wid:=(r->>'id')::uuid;
 if wid is null then raise exception 'TEST: no waste id';end if;
 r2:=public.save_baihuayuan_sheet_row(s,'waste',null,v,'{}',req);if r2<>r then raise exception 'TEST: non-idempotent create';end if;
 select count(*) into before_count from private.waste_records where store_id=s;if before_count<>1 then raise exception 'TEST: duplicate waste';end if;
 begin perform public.save_baihuayuan_sheet_row(s,'waste',null,v||'{"quantity":"3"}','{}',req);raise exception 'TEST: changed retry accepted';exception when serialization_failure then null;end;
 expected:=jsonb_build_object('name','測試起司','quantity',2,'unit','包','price',25,'note','初始備註','reason','品質異常','actor','隔離測試','date',(now() at time zone 'Asia/Taipei')::date);
 r:=public.save_baihuayuan_sheet_row(s,'waste',wid,v||'{"quantity":"3","note":"更正備註"}',expected,gen_random_uuid());
 if (select quantity from private.waste_records where id=wid)<>3 then raise exception 'TEST: correction lost';end if;
 if not exists(select 1 from public.audit_logs where entity_id=wid::text and action='ADMIN_SHEET_CORRECTION' and old_value->'record'->>'note'='初始備註') then raise exception 'TEST: history lost';end if;
 begin perform public.save_baihuayuan_sheet_row(s,'waste',wid,v,expected,gen_random_uuid());raise exception 'TEST: stale edit accepted';exception when serialization_failure then null;end;
 begin perform public.save_baihuayuan_sheet_row(other,'waste',wid,v,expected,gen_random_uuid());raise exception 'TEST: cross store accepted';exception when insufficient_privilege then null;end;
 perform public.set_baihuayuan_record_state(s,'WASTE',wid,'REMOVED','測試移除');
 if not exists(select 1 from private.waste_records where id=wid) then raise exception 'TEST: deleted history';end if;
 perform public.set_baihuayuan_record_state(s,'WASTE',wid,'LIVE',null);
 v:=v||'{"from":"BeApe","to":"Gras"}';req:=gen_random_uuid();r:=public.save_baihuayuan_sheet_row(s,'transfer',null,v,'{}',req);tid:=(r->>'id')::uuid;
 if public.save_baihuayuan_sheet_row(s,'transfer',null,v,'{}',req)<>r then raise exception 'TEST: transfer retry';end if;
 select jsonb_build_object('revision',revision) into expected from private.store_movements where id=tid;
 perform public.save_baihuayuan_sheet_row(s,'transfer',tid,v||'{"price":"30","note":"成本更正"}',expected,gen_random_uuid());
 if (select amount_snapshot from private.store_movements where id=tid)<>60 then raise exception 'TEST: transfer amount';end if;
 req:=gen_random_uuid();v:=v||'{"supplier":"隔離測試供應商"}';r:=public.save_baihuayuan_sheet_row(s,'receipt',null,v,'{}',req);
 if public.save_baihuayuan_sheet_row(s,'receipt',null,v,'{}',req)<>r then raise exception 'TEST: receipt retry';end if;

 if (select subtotal_ex_tax from public.goods_receipts where id=(r->>'receipt_id')::uuid)<>50 then raise exception 'TEST: receipt header total';end if;
 begin update private.waste_records set note='unaudited' where id=wid;raise exception 'TEST: direct history update accepted';exception when raise_exception then if sqlerrm<>'PILOT_HISTORY_IS_APPEND_ONLY' then raise;end if;end;
 req:=gen_random_uuid();r:=public.save_baihuayuan_sheet_row(s,'transfer',null,v||'{"price":""}','{}',req);
 if (select unit_price_snapshot from private.store_movements where id=(r->>'id')::uuid) is not null then raise exception 'TEST: unknown price invented';end if;
 catalog_value:='{"name":"隔離測試新食材","unit":"瓶","price":"12","quantity":"","zone":"未分類"}';req:=gen_random_uuid();
 r:=public.save_baihuayuan_sheet_row(s,'inventory',null,catalog_value,'{}',req);catalog_id:=(r->0->>'product_id')::uuid;
 if catalog_id is null then raise exception 'TEST: catalog not created';end if;
 if public.save_baihuayuan_sheet_row(s,'inventory',null,catalog_value,'{}',req)<>r then raise exception 'TEST: catalog retry';end if;
 if (select count(*) from public.products where organization_id=org and name='隔離測試新食材')<>1 then raise exception 'TEST: duplicate catalog';end if;
 perform public.app_operation(s,'count.catalog-lifecycle',jsonb_build_object('ids',jsonb_build_array(catalog_id),'mode','REMOVE'),gen_random_uuid());
 begin perform public.save_baihuayuan_sheet_row(s,'inventory',null,catalog_value,'{}',gen_random_uuid());raise exception 'TEST: removed catalog silently restored';exception when raise_exception then if sqlerrm<>'PRODUCT_REMOVED_OR_DISABLED' then raise;end if;end;
 if not exists(select 1 from public.products where id=catalog_id and is_active) then raise exception 'TEST: store removal globally disabled product';end if;
 perform public.app_operation(s,'count.catalog-lifecycle',jsonb_build_object('ids',jsonb_build_array(catalog_id),'mode','RESTORE'),gen_random_uuid());
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 begin perform public.save_baihuayuan_sheet_row(s,'waste',null,v,'{}',gen_random_uuid());raise exception 'TEST: unauthorized accepted';exception when insufficient_privilege then null;end;
 raise notice 'PASS: create, correction, audit history, idempotency, stale writes, store isolation and denial';
end $$;
rollback;
