begin;
select no_plan();
create function pg_temp.work_identity_contract(kind text) returns setof text language plpgsql as $$
declare creator uuid:=gen_random_uuid(); backoffice uuid:=gen_random_uuid(); boss uuid:=gen_random_uuid(); stranger uuid:=gen_random_uuid(); employee uuid:=gen_random_uuid(); late_user uuid:=gen_random_uuid();
 org uuid; store uuid; second_store uuid:=gen_random_uuid(); data jsonb; draft jsonb; saved jsonb; invitation jsonb; boss_invite uuid; late_invite uuid; request uuid; member jsonb; initial_orgs bigint; failure boolean;
 code text:='QAWORK'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));
begin
 select count(*) into initial_orgs from public.organizations;
 insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) select x,x||'@work-identity.invalid',now(),now(),now() from unnest(array[creator,backoffice,boss,stranger,employee]) x;
 perform set_config('request.jwt.claim.sub',creator::text,true);
 data:=public.owner_setup();return next is(data->>'step','business',kind||': new creator enters setup');
 draft:=jsonb_build_object('organization_name','Work identity QA','business_type',kind,'store_mode','MULTI');
 data:=public.owner_setup('business',draft,0);
 draft:=data->'draft'||jsonb_build_object('store_name','First QA store','store_code',code,'staff_login_mode','NAME_OR_NICKNAME');
 data:=public.owner_setup('store',draft,(data->>'revision')::int);
 data:=public.owner_setup('identity',data->'draft'||'{"work_role":"SUPERVISOR"}',(data->>'revision')::int);
 return next is(public.owner_setup()->'draft'->>'work_role','SUPERVISOR',kind||': chosen identity survives reopening');
 saved:=public.owner_setup('complete',data->'draft',(data->>'revision')::int);
 org:=(saved->>'organization_id')::uuid;store:=(saved->>'store_id')::uuid;
 return next is(public.owner_setup('complete',data->'draft',(data->>'revision')::int),saved,kind||': duplicate completion is idempotent');
 return next is((select count(*) from public.organizations),initial_orgs+1,kind||': only one merchant created');
 return next is(private.app_role(store),'SUPERVISOR',kind||': creator lands in supervisor identity');
 return next ok(private.can_manage_business(store),kind||': supervisor retains merchant administration');
 return next is(public.get_app_context()->'stores'->0->>'role','SUPERVISOR',kind||': context keeps work identity');
 return next lives_ok(format('select public.app_workspace(%L::uuid,%L)',store,'business'),kind||': supervisor creator can read business setup');
 invitation:=public.prepare_management_invite(store,creator,backoffice||'@work-identity.invalid','Back office','LOGISTICS');
 return next ok(not exists(select 1 from public.store_memberships where store_id=store and user_id=backoffice),kind||': invitation does not grant access before acceptance');
 return next is(public.prepare_management_invite(store,creator,backoffice||'@work-identity.invalid','Back office','LOGISTICS')->>'invite_id',invitation->>'invite_id',kind||': invitation retry reuses one record');
 return next is(public.prepare_management_invite(store,creator,backoffice||'@work-identity.invalid','Back office','LOGISTICS')->>'send_mail','false',kind||': concurrent resend is throttled without cancelling invite');
 perform set_config('request.jwt.claim.sub',stranger::text,true);
 return next throws_ok(format('select public.management_invitation(%L,%L::uuid)','accept',invitation->>'invite_id'),'42501','INVITE_EMAIL_MISMATCH',kind||': another Email cannot accept');
 return next ok(private.app_role(store) is null,kind||': unrelated account has no store access');
 perform set_config('request.jwt.claim.sub',backoffice::text,true);
 return next is(jsonb_array_length(public.management_invitation()->'invitations'),1,kind||': recipient sees pending invitation');
 return next throws_ok('select public.owner_setup()','42501','INVITE_ACCEPT_REQUIRED',kind||': recipient is not sent to new merchant setup');
 data:=public.management_invitation('accept',(invitation->>'invite_id')::uuid);
 return next is(public.management_invitation('accept',(invitation->>'invite_id')::uuid),data,kind||': acceptance retry does not duplicate');
 return next is(private.app_role(store),'LOGISTICS',kind||': accepted backoffice retains assigned identity');
 return next is(public.get_app_context()->'stores'->0->>'organization_id',org::text,kind||': backoffice joins same enterprise');
 return next is(public.owner_setup()->>'required','false',kind||': accepted member skips merchant creation');
 return next ok(not private.can_manage_business(store),kind||': invitation alone does not grant merchant administration');
 perform set_config('request.jwt.claim.sub',creator::text,true);
 invitation:=public.prepare_management_invite(store,creator,boss||'@work-identity.invalid','Boss','OWNER');boss_invite:=(invitation->>'invite_id')::uuid;
 perform set_config('request.jwt.claim.sub',boss::text,true);
 perform public.management_invitation('accept',boss_invite);
 return next is(private.app_role(store),'OWNER',kind||': invited boss gets boss home');
 return next ok(not private.can_manage_business(store),kind||': boss work identity does not confer merchant admin');
 return next throws_ok(format('select public.app_workspace(%L::uuid,%L)',store,'business'),'42501','APP_FORBIDDEN',kind||': boss without administration cannot alter merchant');
 -- A user created by the official Auth invitation also waits for acceptance.
 perform set_config('request.jwt.claim.sub',creator::text,true);
 invitation:=public.prepare_management_invite(store,creator,late_user||'@work-identity.invalid','Late recipient','LOGISTICS');late_invite:=(invitation->>'invite_id')::uuid;
 insert into auth.users(id,email,created_at,updated_at) values(late_user,late_user||'@work-identity.invalid',now(),now());
 return next ok(not exists(select 1 from public.store_memberships where user_id=late_user),kind||': Auth creation does not prematurely activate invitation');
 perform set_config('request.jwt.claim.sub',late_user::text,true);
 return next throws_ok(format('select public.management_invitation(%L,%L::uuid)','accept',late_invite),'42501','VERIFIED_EMAIL_REQUIRED',kind||': unverified recipient is rejected');
 update auth.users set email_confirmed_at=now() where id=late_user;
 perform set_config('request.jwt.claim.sub',creator::text,true);
 perform public.app_operation(store,'invite.cancel',jsonb_build_object('id',late_invite),gen_random_uuid());
 perform set_config('request.jwt.claim.sub',late_user::text,true);
 return next throws_ok(format('select public.management_invitation(%L,%L::uuid)','accept',late_invite),'42501','INVITE_NOT_VALID',kind||': cancelled invitation cannot grant access');
 -- Add a second store using existing identities and explicit scope only.
 insert into public.stores(id,organization_id,store_code,name,created_by) values(second_store,org,code||'B','Second QA store',creator);
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,work_role,assigned_by) values(second_store,org,creator,'creator','SUPERVISOR','SUPERVISOR',creator);
 perform set_config('request.jwt.claim.sub',creator::text,true);
 perform public.app_operation(second_store,'member.assign',jsonb_build_object('user_id',backoffice,'login_identifier','backoffice','role','OWNER'),gen_random_uuid());
 perform set_config('request.jwt.claim.sub',backoffice::text,true);
 return next is(private.app_role(second_store),'LOGISTICS',kind||': adding store ignores attempted role replacement');
 return next is(jsonb_array_length(public.get_app_context()->'stores'),2,kind||': original account now has two authorized stores');
 -- Optional features are independent of identity; ungranted features are denied.
 insert into public.organization_members(organization_id,user_id,role) values(org,employee,'STAFF');
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) values(org,employee,'Employee',creator);
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,assigned_by) values(store,org,employee,'employee','STAFF',creator);
 perform set_config('request.jwt.claim.sub',employee::text,true);
 return next throws_ok(format('select public.authorize_app_feature(%L::uuid,%L)',store,'REPORTS_VIEW'),'42501','APP_FORBIDDEN',kind||': reports denied before extra grant');
 perform set_config('request.jwt.claim.sub',creator::text,true);
 select x into member from jsonb_array_elements(public.app_workspace(store,'members')->'members') x where x->>'user_id'=employee::text;
 perform public.app_operation(store,'member.save',member||'{"extra_permissions":["REPORTS_VIEW"]}',gen_random_uuid());
 perform set_config('request.jwt.claim.sub',employee::text,true);
 return next is(private.app_role(store),'STAFF',kind||': adding reports leaves staff identity intact');
 return next ok(public.authorize_app_feature(store,'REPORTS_VIEW'),kind||': extra report grant works');
 return next lives_ok(format('select public.app_workspace(%L::uuid,%L)',store,'reports'),kind||': granted report data can load');
 return next throws_ok(format('select public.authorize_app_feature(%L::uuid,%L)',store,'DATA_EXPORT'),'42501','APP_FORBIDDEN',kind||': export remains separately denied');
 return next ok(not private.can_read_count_management(store),kind||': report grant does not reveal blind count references');
 -- Revoke store membership and verify existing JWT cannot read/write.
 perform set_config('request.jwt.claim.sub',creator::text,true);
 select x into member from jsonb_array_elements(public.app_workspace(second_store,'members')->'members') x where x->>'user_id'=backoffice::text;
 perform public.app_operation(second_store,'member.save',member||'{"is_active":false}',gen_random_uuid());
 perform set_config('request.jwt.claim.sub',backoffice::text,true);
 return next ok(private.app_role(second_store) is null,kind||': revoked store disappears');
 return next throws_ok(format('select public.app_workspace(%L::uuid,%L)',second_store,'reports'),'42501','APP_FORBIDDEN',kind||': revoked store data denied');
 return next throws_ok(format('select public.app_operation(%L::uuid,%L,%L::jsonb,%L::uuid)',second_store,'record.create','{"kind":"handover","title":"forbidden"}',gen_random_uuid()),'42501','APP_FORBIDDEN',kind||': revoked store write denied');
 -- Transfer responsibility atomically, retain work identity and history.
 perform set_config('request.jwt.claim.sub',creator::text,true);
 request:=gen_random_uuid();draft:=jsonb_build_object('user_id',boss,'keep_admin',false);
 saved:=public.app_operation(store,'business.transfer',draft,request);
 return next is(public.app_operation(store,'business.transfer',draft,request),saved,kind||': responsibility transfer retry is idempotent');
 return next ok(not private.can_manage_business(store),kind||': former responsible manager loses management grant');
 return next is(private.app_role(store),'SUPERVISOR',kind||': former manager keeps chosen work identity');
 return next is(public.owner_setup()->>'required','false',kind||': former manager is not asked to recreate merchant');
 return next throws_ok(format('select public.prepare_management_invite(%L::uuid,%L::uuid,%L,%L,%L)',store,creator,'denied@work-identity.invalid','Denied','LOGISTICS'),'42501','BUSINESS_ADMIN_REQUIRED',kind||': former manager cannot invite after revocation');
 perform set_config('request.jwt.claim.sub',boss::text,true);
 return next is(public.owner_setup()->>'required','false',kind||': successor does not enter merchant setup');
 return next ok(private.can_manage_business(store) and private.can_manage_business(second_store),kind||': successor manages all merchant stores');
 return next is(private.app_role(second_store),'OWNER',kind||': successor work identity unchanged');
 return next is((select count(*) from public.audit_logs where organization_id=org and action='business.transfer'),1::bigint,kind||': transfer has one audit record');
 update public.organization_members set is_active=false where organization_id=org and user_id=backoffice;
 perform set_config('request.jwt.claim.sub',backoffice::text,true);
 return next ok(private.app_role(store) is null,kind||': disabled member cannot access even first store');
 return next is((select count(*) from public.organizations),initial_orgs+1,kind||': invitation and handoff never duplicate merchant');
end $$;
select * from pg_temp.work_identity_contract('SINGLE_RESTAURANT');
select * from pg_temp.work_identity_contract('CHAIN_RESTAURANT');
select * from finish();
rollback;
