with snapshot as (select jsonb_build_object(
  'enums',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schema_name,x.type_name,x.sort_order),'[]'::jsonb) from (select n.nspname schema_name,t.typname type_name,e.enumsortorder sort_order,e.enumlabel label from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid where n.nspname in ('public','private')) x),
  'tables',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schema_name,x.table_name),'[]'::jsonb) from (select n.nspname schema_name,c.relname table_name,c.relrowsecurity rls_enabled,c.relforcerowsecurity rls_forced from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind in ('r','p')) x),
  'columns',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schema_name,x.table_name,x.ordinal_position),'[]'::jsonb) from (select table_schema schema_name,table_name,ordinal_position,column_name,data_type,udt_schema,udt_name,is_nullable,column_default,is_generated,generation_expression from information_schema.columns where table_schema in ('public','private')) x),
  'constraints',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schema_name,x.table_name,x.constraint_name),'[]'::jsonb) from (select n.nspname schema_name,rel.relname table_name,con.conname constraint_name,con.contype constraint_type,pg_get_constraintdef(con.oid,true) definition from pg_constraint con join pg_class rel on rel.oid=con.conrelid join pg_namespace n on n.oid=rel.relnamespace where n.nspname in ('public','private')) x),
  'indexes',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schemaname,x.tablename,x.indexname),'[]'::jsonb) from (select schemaname,tablename,indexname,indexdef from pg_indexes where schemaname in ('public','private')) x),
  'policies',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schemaname,x.tablename,x.policyname),'[]'::jsonb) from (select schemaname,tablename,policyname,permissive,roles,cmd,qual,with_check from pg_policies where schemaname in ('public','private')) x),
  'functions',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schema_name,x.function_name,x.arguments),'[]'::jsonb) from (select n.nspname schema_name,p.proname function_name,pg_get_function_identity_arguments(p.oid) arguments,p.prosecdef security_definer,p.provolatile volatility,p.proacl::text acl,pg_get_functiondef(p.oid) definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')) x),
  'triggers',(select coalesce(jsonb_agg(to_jsonb(x) order by x.schema_name,x.table_name,x.trigger_name),'[]'::jsonb) from (select n.nspname schema_name,c.relname table_name,t.tgname trigger_name,pg_get_triggerdef(t.oid,true) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and not t.tgisinternal) x)
) value)
select jsonb_build_object('fingerprint_sha256',encode(extensions.digest(value::text,'sha256'),'hex'),'snapshot',value)::text from snapshot;
