import{session}from'./services/supabase.js';
import{signIn,signUpOwner,staffPinLogin,signOut,profile,createOwnerBusiness,createStore,createStaff,resetStaffPin,disableStaff}from'./services/auth.js';
import{organization,stores,countWorkspace,receiptWorkbench,uploadReceipts,correctReceiptField,storeStaff,catalogWorkspace,zoneWorkspace,createPilotProduct,createPilotZone,assignPilotProduct,createPilotCountSession,saveCountDraft,completePilotCountZone,resolvePilotCountDiscrepancy}from'./services/data.js';
import{normalizeStoreRole,homeRouteForRole,roleHomeKind}from'./services/roles.js';
import{backButton,layout}from'./components/layout.js';
import{loginPage,storePickerPage,unassignedStorePage,unavailableRolePage}from'./pages/login.js';
import{ownerBusinessOnboardingPage,firstStoreOnboardingPage}from'./pages/onboarding.js';
import{homePage}from'./pages/home.js';
import{countPage}from'./pages/count.js';
import{receivingPage}from'./pages/receiving.js';
import{consignmentPage}from'./pages/consignment.js';
import{utilityPage}from'./pages/utility.js';
import{catalogPage,zonesPage}from'./pages/setup.js';

const root=document.querySelector('#app');
const state={session:null,profile:null,organization:null,stores:[],store:null,page:null,context:{},history:[]};
const build=window.PILOT_BUILD||{branch:'unknown',sha:'unknown',deployedAt:'unknown'};
document.querySelector('#build-banner').textContent='PantryFlow';
document.querySelector('#build-version').textContent=`Branch: ${build.branch}｜Git SHA: ${build.sha}｜部署時間: ${build.deployedAt}`;

function message(error){const raw=String(error?.message||'');if(/PASSWORD_CONFIRMATION_MISMATCH/i.test(raw))return'兩次輸入的密碼不一致。';if(/PIN_CONFIRMATION_MISMATCH/i.test(raw))return'兩次輸入的 PIN 不一致。';if(/invalid login credentials/i.test(raw))return'Email 或密碼不正確。';if(/INVALID_STAFF|INVALID_LOGIN/i.test(raw))return'門市、員工識別或 PIN 不正確。';if(/PIN_LOCKED/i.test(raw))return'PIN 已鎖定 15 分鐘，請稍後再試或請主管重設。';if(/LOGIN_TEMPORARILY_UNAVAILABLE/i.test(raw))return'員工登入暫時無法使用，請稍後再試。';if(/STAFF_ALREADY_EXISTS/i.test(raw))return'此門市已有相同的員工識別，請確認後再試。';if(/INVALID_STAFF_INPUT|EMPLOYEE_NUMBER_REQUIRED/i.test(raw))return'員工資料格式不正確，請檢查姓名、登入識別與 6 位數 PIN。';if(/ROLE_NOT_ALLOWED|STORE_MANAGER_REQUIRED/i.test(raw))return'你沒有管理這間門市或建立此角色的權限。';if(/STORE_NOT_FOUND/i.test(raw))return'找不到有效門市，請重新整理後再試。';if(/OWNER_EMAIL_NOT_VERIFIED/i.test(raw))return'請先完成 Email 驗證。';if(/OWNER_PROFILE_DISPLAY_NAME_REQUIRED/i.test(raw))return'管理帳號缺少顯示名稱，請重新註冊或聯絡管理者。';if(/OWNER_ALREADY_ONBOARDED/i.test(raw))return'此帳號已建立或加入商家，請重新整理。';if(/OWNER_BUSINESS|OWNER_STORE|OWNER_LOGIN_MODE/i.test(raw))return'商家或第一間門市資料格式不正確。';if(/STORE_ALREADY|23505/i.test(raw))return'門市代碼已存在。';if(/COUNT_ZONE_REQUIRED/i.test(raw))return'請先建立至少一個盤點區域。';if(/ZONE_PRODUCTS_REQUIRED/i.test(raw))return'每個啟用區域都必須先加入商品。';if(/OPENING_BALANCE_REQUIRED/i.test(raw))return'商品缺少正式期初數量。';if(/ACTIVE_COUNT_SESSION_EXISTS/i.test(raw))return'已有進行中的盤點任務。';if(/COUNT_ZONE_INCOMPLETE/i.test(raw))return'請輸入此區域全部商品的數量後再完成。';if(/Failed to fetch|NetworkError|Load failed/i.test(raw))return'網路連線失敗，請稍後重試。';return'操作未完成，請確認欄位內容後再試。'}
function bindError(form,work,{log=true}={}){form.addEventListener('submit',async event=>{event.preventDefault();const node=form.querySelector('[data-error]'),submit=form.querySelector('button[type="submit"]');if(submit?.disabled)return;node.textContent='';if(submit)submit.disabled=true;try{await work(new FormData(form))}catch(error){if(log)console.error(error);node.textContent=message(error);if(submit)submit.disabled=false}})}

function renderLogin(options={}){document.body.classList.add('admin-auth-view');root.innerHTML=loginPage(options);const buttons=[...document.querySelectorAll('[data-login-mode]')],panels=[...document.querySelectorAll('[data-login-panel]')];buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active))});panels.forEach(panel=>panel.hidden=panel.dataset.loginPanel!==button.dataset.loginMode);panels.find(panel=>!panel.hidden)?.querySelector('input')?.focus()}));bindError(document.querySelector('#management-login'),async form=>{await signIn(form.get('email'),form.get('password'));await boot()},{log:false});bindError(document.querySelector('#management-sign-up'),async form=>{if(form.get('password')!==form.get('confirmPassword'))throw new Error('PASSWORD_CONFIRMATION_MISMATCH');const result=await signUpOwner(form.get('displayName'),form.get('email'),form.get('password'));if(result.session)await boot();else renderLogin({notice:'註冊完成，請至信箱完成 Email 驗證後登入。',initialMode:'manager'})},{log:false});bindError(document.querySelector('#staff-pin-login'),async form=>{const storeId=await staffPinLogin(form.get('storeCode'),form.get('identifier'),form.get('pin'));await boot(storeId)},{log:false})}
function activeRole(){return normalizeStoreRole(state.store?.role)}
function setRoute(role,page){const home=homeRouteForRole(role);const kind=roleHomeKind(role);const route=page==='home'?home:`#/${kind}/${page}`;if(route&&location.hash!==route)history.replaceState(null,'',route)}
function renderStorePicker(){document.body.classList.add('admin-auth-view');root.innerHTML=storePickerPage(state.stores);root.querySelectorAll('[data-store]').forEach(button=>button.onclick=()=>enterStore(state.stores.find(x=>x.id===button.dataset.store)))}
function enterStore(store,page='home'){state.store=store;state.history=[];state.page=null;const role=activeRole();if(!homeRouteForRole(role))return renderUnavailableRole(role);return renderPage(page)}

async function renderPage(page,context={},options={}){document.body.classList.remove('admin-auth-view');const previous={page:state.page,context:state.context};if(!options.fromBack&&previous.page&&(previous.page!==page||JSON.stringify(previous.context)!==JSON.stringify(context)))state.history.push(previous);state.page=page;state.context=context;const role=activeRole();if(!homeRouteForRole(role))return renderUnavailableRole(role);const canManage=['ADMIN','SUPERVISOR'].includes(role);let content;
  if(page==='home')content=homePage({role});
  else if(page==='count')content=countPage(await countWorkspace(state.store.id,state.profile.id,canManage),{canManage,context});
  else if(page==='catalog')content=catalogPage(await catalogWorkspace(state.store.id));
  else if(page==='zones')content=zonesPage(await zoneWorkspace(state.store.id));
  else if(page==='receiving')content=receivingPage(await receiptWorkbench(state.store.id,context.batchId));
  else if(page==='consignment')content=consignmentPage();
  else content=utilityPage(page,{canManage,canCreateStore:state.profile.is_owner||role==='ADMIN',canCreateSupervisor:state.profile.is_owner||role==='ADMIN',organization:state.organization,store:state.store,staff:page==='profile'&&canManage?await storeStaff(state.store.id):[],currentUserId:state.profile.id});
  if(page!=='home'&&!content.includes('data-back'))content=backButton()+content;
  setRoute(role,page);
  root.innerHTML=layout({storeName:state.store.name,role,page,content,displayName:state.profile.display_name});
  document.querySelector('[data-back]')?.addEventListener('click',()=>{const target=state.history.pop()||{page:'home',context:{}};renderPage(target.page,target.context,{fromBack:true})});
  document.querySelectorAll('[data-route]').forEach(button=>button.onclick=()=>renderPage(button.dataset.route));document.querySelectorAll('[data-feature]').forEach(button=>button.onclick=()=>renderPage(button.dataset.feature));
  document.querySelectorAll('[data-open-count]').forEach(button=>button.onclick=()=>renderPage('count',{sessionId:button.dataset.session,zoneId:button.dataset.zone}));
  document.querySelectorAll('[data-open-receipt]').forEach(button=>button.onclick=()=>renderPage('receiving',{batchId:button.dataset.openReceipt}));
  document.querySelectorAll('[data-create-count]').forEach(button=>button.onclick=async()=>{const errorNode=document.querySelector('[data-action-error]');button.disabled=true;try{await createPilotCountSession(state.store.id);await renderPage('count')}catch(error){console.error(error);if(errorNode)errorNode.textContent=message(error);button.disabled=false}});
  const productForm=document.querySelector('#create-product');if(productForm)bindError(productForm,async form=>{await createPilotProduct(state.store.id,Object.fromEntries(form));await renderPage('catalog')});
  const zoneForm=document.querySelector('#create-zone');if(zoneForm)bindError(zoneForm,async form=>{await createPilotZone(state.store.id,form.get('name'));await renderPage('zones')});
  document.querySelectorAll('[data-assign-product]').forEach(form=>bindError(form,async values=>{await assignPilotProduct(form.dataset.assignProduct,values.get('productId'));await renderPage('zones')}));
  document.querySelector('[data-download-catalog-template]')?.addEventListener('click',()=>{const csv='商品名稱,商品編碼,分類,基本盤點單位,採購單位,換算率,供應商,啟用狀態,期初數量\n';const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));link.download='PantryFlow_商品匯入固定範本.csv';link.click();URL.revokeObjectURL(link.href)});
  document.querySelector('[data-catalog-file]')?.addEventListener('change',event=>{const node=document.querySelector('[data-import-preview]'),file=event.target.files[0];node.innerHTML=file?`<div class="helper">已選擇 ${file.name}。目前只完成固定範本下載；Excel 預覽與正式批次寫入尚未通過，檔案不會被假裝匯入。</div>`:''});
  const countForm=document.querySelector('#blind-count');if(countForm){countForm.querySelectorAll('[data-count-product]').forEach(input=>input.addEventListener('change',async()=>{const saved=countForm.querySelector(`[data-save-state="${input.dataset.countProduct}"]`);if(input.value===''){saved.textContent='尚未輸入';return}saved.textContent='保存中…';try{await saveCountDraft(state.profile,countForm.dataset.session,countForm.dataset.zone,input.dataset.countProduct,input.value,input.dataset.unit);saved.textContent='已自動保存'}catch(error){console.error(error);saved.textContent='保存失敗，請重試'}}));bindError(countForm,async()=>{await completePilotCountZone(countForm.dataset.session,countForm.dataset.zone);await renderPage('count')})}
  document.querySelectorAll('[data-resolve-discrepancy]').forEach(form=>bindError(form,async values=>{await resolvePilotCountDiscrepancy(form.dataset.resolveDiscrepancy,Object.fromEntries(values));await renderPage('count')}));
  document.querySelectorAll('[data-correct-receipt-field]').forEach(form=>bindError(form,async values=>{let oldValue=null;try{oldValue=JSON.parse(values.get('oldValue'))}catch{}await correctReceiptField(state.profile,form.dataset.batch,form.dataset.correctReceiptField,oldValue,values.get('value'));await renderPage('receiving',{batchId:form.dataset.batch})}));
  document.querySelector('[data-store-switch]')?.addEventListener('click',()=>state.stores.length>1?renderStorePicker():renderPage('profile'));document.querySelector('[data-sign-out]')?.addEventListener('click',async()=>{await signOut();renderLogin()});const storeForm=document.querySelector('#create-store');if(storeForm)bindError(storeForm,async form=>{const result=await createStore(Object.fromEntries(form),{isFirstStore:false});state.stores=await stores(state.profile.id);const selected=state.stores.find(item=>item.id===result.store?.id)||state.stores[0];await enterStore(selected,'profile')});const staffForm=document.querySelector('#create-staff');if(staffForm)bindError(staffForm,async form=>{if(form.get('pin')!==form.get('confirmPin'))throw new Error('PIN_CONFIRMATION_MISMATCH');await createStaff(Object.fromEntries(form));form.set('pin','');form.set('confirmPin','');await renderPage('profile')});document.querySelectorAll('[data-reset-pin]').forEach(form=>bindError(form,async values=>{await resetStaffPin(form.dataset.resetPin,values.get('pin'));await renderPage('profile')}));document.querySelectorAll('[data-disable-staff]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await disableStaff(button.dataset.disableStaff);await renderPage('profile')}catch(error){console.error(error);button.disabled=false;button.textContent=message(error)}});const upload=document.querySelector('#receipt-upload');if(upload)bindError(upload,async form=>{const files=[...form.getAll('files')].filter(file=>file.size);await uploadReceipts(state.store,state.profile,files);await renderPage('receiving')})}

function renderUnassignedStore(){document.body.classList.add('admin-auth-view');root.innerHTML=unassignedStorePage();document.querySelector('[data-sign-out]').onclick=async()=>{await signOut();renderLogin()}}
function renderUnavailableRole(role){document.body.classList.add('admin-auth-view');root.innerHTML=unavailableRolePage(role);document.querySelector('[data-sign-out]').onclick=async()=>{await signOut();renderLogin()}}

function bindOnboardingSignOut(){document.querySelector('[data-sign-out]')?.addEventListener('click',async()=>{await signOut();renderLogin()})}
function renderOwnerOnboarding(){document.body.classList.add('admin-auth-view');root.innerHTML=ownerBusinessOnboardingPage(state.profile);bindOnboardingSignOut();bindError(document.querySelector('#create-owner-business'),async form=>{const result=await createOwnerBusiness(Object.fromEntries(form));await boot(result.store_id,'profile')})}
function renderFirstStoreOnboarding(){document.body.classList.add('admin-auth-view');root.innerHTML=firstStoreOnboardingPage(state.organization);bindOnboardingSignOut();bindError(document.querySelector('#create-first-store'),async form=>{const values=Object.fromEntries(form);const result=await createStore({name:values.storeName,storeCode:values.storeCode,loginMode:values.loginMode},{isFirstStore:true});await boot(result.store.id,'profile')})}

async function boot(preferredStoreId,preferredPage='home'){state.session=await session();if(!state.session)return renderLogin();state.profile=await profile(state.session.user.id);state.organization=state.profile.organization_id?await organization(state.profile.organization_id):null;if(!state.organization)return renderOwnerOnboarding();state.stores=await stores(state.profile.id);if(!state.stores.length){if(state.profile.organization_role==='ADMIN')return renderFirstStoreOnboarding();return renderUnassignedStore()}const selected=state.stores.find(x=>x.id===preferredStoreId)||state.stores[0];if(state.stores.length>1&&!preferredStoreId)return renderStorePicker();await enterStore(selected,preferredPage)}

boot().catch(error=>{console.error(error);root.innerHTML=`<section class="center-card"><h1>正式資料載入失敗</h1><p class="error">${message(error)}</p><button class="secondary" onclick="location.reload()">重新載入</button></section>`});
