import test from 'node:test';import assert from 'node:assert/strict';
import {configureDemo,demoClient,resetDemo,activateDemoInvitation} from '../lib/demo-client.mjs';
import {workspaceStorage,clearDemoDrafts} from '../lib/workspace-storage.ts';
import {readFileSync} from 'node:fs';import ts from 'typescript';
const reviewSource=readFileSync(new URL('../lib/inventory-review.ts',import.meta.url),'utf8').replace("'./inventory-import'",JSON.stringify(new URL('../lib/inventory-import.ts',import.meta.url).href));
const {restoreReviewRows,restoreReviewEdits,emptyReviewRow,normalizeReview,reviewPayload,reviewIssues}=await import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(reviewSource,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64'));
const call=async(name,args)=>{const r=await demoClient.rpc(name,args);assert.equal(r.error,null,JSON.stringify(r.error));return r.data;};
const op=(s,a,d,id=crypto.randomUUID())=>call('app_operation',{p_store_id:s,p_action:a,p_data:d,p_request_id:id});
test.beforeEach(()=>resetDemo());
test('blank whitespace remains unprovided while explicit zero remains zero',()=>{for(const text of ['', '  ', '\t']){const row={...emptyReviewRow('原表',2),name:'鮮奶',unit:'瓶',quantityText:text};assert.equal(reviewIssues(row),'');assert.equal(normalizeReview(row).opening_quantity,null);assert.equal(reviewPayload(row).opening_quantity,null);}assert.equal(reviewPayload({...emptyReviewRow('原表',2),quantityText:'0'}).opening_quantity,0);assert.match(reviewIssues({...emptyReviewRow('原表',2),name:'米',unit:'包',quantityText:'-1'}),/非負/);});
test('continued import preserves successful, existing, failed and skipped results in sheet order',()=>{const records=[['乙',1,'FAILED',null],['甲',2,'ADDED','p1'],['甲',3,'EXISTING','p2'],['乙',2,'SKIPPED',null]].map(([sheet,row,status,id])=>({sheet_name:sheet,source_row:row,source_id:`${sheet}:${row}`,status,product_id:id,normalized_values:{name:'米',unit:'袋',opening_quantity:null},reason:'原有原因'}));const restored=restoreReviewRows(records,['甲','乙']);assert.deepEqual(restored.map(r=>r.status),['ADDED','EXISTING','FAILED','SKIPPED']);assert(restored.every(r=>r.quantityText===''));const merged=restoreReviewEdits(restored,{'甲:2':{name:'不可改成功列'},'乙:1':{unit:'包',quantityText:'2'}});assert.equal(merged[0].name,'米');assert.equal(merged[2].unit,'包');assert.equal(merged[2].status,'PENDING');assert.equal(merged[3].status,'SKIPPED');});
test('demo drafts and retry tokens survive another module load and reset never touches real drafts',async()=>{const map=new Map();globalThis.localStorage={get length(){return map.size;},key:i=>[...map.keys()][i],getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};try{workspaceStorage('real-account').setItem('draft','real');workspaceStorage('demo-invited-staff').setItem('draft','demo');const reopened=await import(`../lib/workspace-storage.ts?reload=${Date.now()}`);assert.equal(reopened.workspaceStorage('demo-invited-staff').getItem('draft'),'demo');assert.equal(reopened.workspaceStorage('real-account').getItem('draft'),'real');clearDemoDrafts();assert.equal(workspaceStorage('demo-invited-staff').getItem('draft'),null);assert.equal(workspaceStorage('real-account').getItem('draft'),'real');}finally{delete globalThis.localStorage;}});
test('invited staff cannot query another store or replay operations after revocation',async()=>{const c=configureDemo('SUPERVISOR','SINGLE_RESTAURANT'),s=c.stores[0].id,other=c.stores[1].id;const invitation=await demoClient.functions.invoke('manage-staff',{body:{action:'create',storeId:s,displayName:'隔離新人',loginIdentifier:'scope-new',role:'STAFF'}});assert.equal(invitation.error,null);await activateDemoInvitation(invitation.data.activationCode,'147258');const scoped=await demoClient.from('inventory_count_sessions').select('*');assert(scoped.data.every(x=>x.store_id===s));assert.equal((await demoClient.rpc('get_pilot_count_results',{p_session_id:`${other}-count-history`})).error.code,'FORBIDDEN');const payload={p_store_id:s,p_action:'record.create',p_data:{kind:'incident',title:'隔離測試'},p_request_id:crypto.randomUUID()};assert.equal((await demoClient.rpc('app_operation',payload)).error,null);configureDemo('SUPERVISOR','SINGLE_RESTAURANT');await op(s,'member.offboard',{user_id:invitation.data.staffId});const revokedLink=await demoClient.functions.invoke('manage-staff',{body:{action:'reset_pin',storeId:s,staffId:invitation.data.staffId}});assert.equal(revokedLink.error.code,'FORBIDDEN');
 // The existing staff session must also be denied when replaying its own cached request after revocation.
 configureDemo('STAFF','SINGLE_RESTAURANT');const staffId='demo-user-SINGLE_RESTAURANT-STAFF';const repeat={...payload,p_request_id:crypto.randomUUID()};assert.equal((await demoClient.rpc('app_operation',repeat)).error,null);configureDemo('SUPERVISOR','SINGLE_RESTAURANT');await op(s,'member.offboard',{user_id:staffId});configureDemo('STAFF','SINGLE_RESTAURANT');assert.equal((await demoClient.rpc('app_operation',repeat)).error.code,'FORBIDDEN');});
test('count draft rejects foreign items, wrong units and negatives without partial writes',async()=>{const c=configureDemo('STAFF','SINGLE_RESTAURANT'),s=c.stores[0].id;const session=(await demoClient.from('inventory_count_sessions').select('*').eq('store_id',s)).data.find(x=>x.status==='IN_PROGRESS');const item=session.snapshot.zones[0],valid={zone_id:item.zone_id,product_id:item.product_id,quantity:2,unit:item.unit};for(const invalid of [{...valid,quantity:-1},{...valid,unit:'錯誤單位'},{...valid,product_id:'unrelated'}]){const result=await demoClient.rpc('save_pilot_count_drafts',{p_session_id:session.id,p_entries:[valid,invalid]});assert.equal(result.error.code,'INVALID_COUNT_ENTRY');assert.equal((await demoClient.from('count_drafts').select('*').eq('session_id',session.id)).data.length,0);}});
test('waste reference prevents deletion and missing price stays null',async()=>{const c=configureDemo('SUPERVISOR','SINGLE_RESTAURANT'),s=c.stores[0].id;const p=await op(s,'product.save',{name:'新鮮麵',unit:'袋',is_active:true});await call('save_pilot_expiry_waste',{p_store_id:s,p_action:'WASTE',p_data:{product_id:p.id,name:p.name,quantity:1,unit:'袋',reason:'破損'},p_request_id:crypto.randomUUID()});assert.equal((await op(s,'product.lifecycle',{ids:[p.id],mode:'DELETE'})).results[0].status,'DISABLED');const waste=(await call('get_pilot_expiry_waste',{p_store_id:s})).waste.find(x=>x.product_id===p.id);assert.equal(waste.reference_amount,null);});
test('original demo file remains readable through another client instance and reset clears it',async()=>{const c=configureDemo('SUPERVISOR','SINGLE_RESTAURANT'),s=c.stores[0];const path=`${s.organization_id}/${s.id}/test/original.csv`,bytes=new TextEncoder().encode('品名,單位\n鮮奶,瓶');assert.equal((await demoClient.storage.from('inventory-imports').upload(path,bytes)).error,null);const {createDemoClient}=await import('../lib/demo-client.mjs');const file=await createDemoClient().storage.from('inventory-imports').download(path);assert.equal(await file.data.text(),'品名,單位\n鮮奶,瓶');const link=await demoClient.storage.from('inventory-imports').createSignedUrl(path,60);assert.equal(link.error,null);assert(link.data.signedUrl.startsWith('blob:'));assert.equal(await (await fetch(link.data.signedUrl)).text(),'品名,單位\n鮮奶,瓶');await resetDemo();await assert.rejects(fetch(link.data.signedUrl));assert((await demoClient.storage.from('inventory-imports').download(path)).error);});
