import test from 'node:test';import assert from 'node:assert/strict';
import {configureDemo,demoClient,resetDemo,inspectDemoInvitation,activateDemoInvitation} from '../lib/demo-client.mjs';
import {movementPlan,availability,reminderTone} from '../lib/stock-rules.mjs';
const call=async(name,args)=>{const r=await demoClient.rpc(name,args);assert.equal(r.error,null,JSON.stringify(r.error));return r.data;};
const op=(s,a,d,id=crypto.randomUUID())=>call('app_operation',{p_store_id:s,p_action:a,p_data:d,p_request_id:id});
test.beforeEach(()=>resetDemo());
test('demo loan receipt is atomic, idempotent, unit-separated and remains unreturned',async()=>{const c=configureDemo('STAFF','SINGLE_RESTAURANT'),s=c.stores[0].id;const products=(await call('app_workspace',{p_store_id:s,p_section:'transfers'})).products,p=products[0];const payload={mode:'loan',other_store_id:c.stores[1].id,product_id:p.id,name:p.name,quantity:1,unit:p.unit},id=crypto.randomUUID();const before=await call('get_app_dashboard',{p_store_id:s});assert.equal(before.shortages[0].remaining,2);await op(s,'movement.create',payload,id);await op(s,'movement.create',payload,id);assert.equal((await call('get_app_dashboard',{p_store_id:s})).shortages[0].remaining,1);await op(s,'movement.create',{...payload,quantity:20,unit:'自訂籃'});assert.equal((await call('get_app_dashboard',{p_store_id:s})).shortages[0].remaining,1);await op(s,'movement.create',payload);assert.equal((await call('get_app_dashboard',{p_store_id:s})).shortages.length,0);const w=await call('app_workspace',{p_store_id:s,p_section:'transfers'});assert(w.records.filter(r=>r.status==='OPEN').length>=3);assert(w.units.includes('自訂籃'));const conflict=await demoClient.rpc('app_operation',{p_store_id:s,p_action:'movement.create',p_data:{...payload,quantity:4},p_request_id:id});assert.equal(conflict.error.code,'REQUEST_CONFLICT');});
test('demo movement maintains total and due thaw requires confirmation',async()=>{const c=configureDemo('SUPERVISOR','SINGLE_RESTAURANT'),s=c.stores[0].id;let w=await call('app_workspace',{p_store_id:s,p_section:'stock'});const p=w.products[1];await op(s,'stock.settings',{product_id:p.id,thaw_enabled:true,thaw_minutes:60});w=await call('app_workspace',{p_store_id:s,p_section:'stock'});const pos=w.positions.find(x=>x.product_id===p.id);const payload={position_id:pos.id,revision:pos.revision,quantity:2,zone_id:w.zones[1].id,state:'THAWING'},id=crypto.randomUUID();await op(s,'stock.move',payload,id);await op(s,'stock.move',payload,id);w=await call('app_workspace',{p_store_id:s,p_section:'stock'});const after=w.products.find(x=>x.id===p.id);assert.equal(after.stock.total,p.stock.total);assert.equal(after.stock.available,p.stock.available-2);const thaw=w.positions.find(x=>x.product_id===p.id&&x.state==='THAWING');const denied=await demoClient.rpc('app_operation',{p_store_id:s,p_action:'stock.move',p_data:{position_id:thaw.id,revision:1,quantity:2,zone_id:thaw.zone_id,state:'READY'},p_request_id:crypto.randomUUID()});assert.equal(denied.error.code,'THAW_NOT_DUE');const total=availability(w.positions.filter(x=>x.product_id===p.id),p.unit);assert.equal(total.total,p.stock.total);});
test('invitation binds staff and store, consumes once and old links are revoked',async()=>{const c=configureDemo('SUPERVISOR','SINGLE_RESTAURANT'),s=c.stores[0].id;const created=await demoClient.functions.invoke('manage-staff',{body:{action:'create',storeId:s,displayName:'示範新人',loginIdentifier:'示範新人',role:'STAFF'}});assert.equal(created.error,null);const token=created.data.login.activationCode;assert.equal((await inspectDemoInvitation(token)).status,'VALID');const next=await activateDemoInvitation(token,'147258');assert.equal(next.stores.length,1);assert.equal(next.stores[0].id,s);assert.equal(next.stores[0].role,'STAFF');assert.equal((await inspectDemoInvitation(token)).status,'USED');await assert.rejects(activateDemoInvitation(token,'147258'),/USED/);configureDemo('SUPERVISOR','SINGLE_RESTAURANT');const r=await demoClient.functions.invoke('manage-staff',{body:{action:'reset_pin',storeId:s,staffId:created.data.staffId}});assert.equal(r.error,null);assert.equal((await inspectDemoInvitation(r.data.activationCode)).status,'VALID');assert.notEqual((await inspectDemoInvitation(token)).status,'VALID');});
test('import review corrects failed rows without rebuilding successful or disabled products',async()=>{const c=configureDemo('SUPERVISOR','SINGLE_RESTAURANT'),s=c.stores[0].id;const file={file_sha256:'a'.repeat(64),storage_path:`${c.stores[0].organization_id}/${s}/aaa/source.csv`,original_filename:'驗收.csv',sheet_names:['原表']};const rows=[{source_id:'原表:2',sheet_name:'原表',source_row:2,name:'測試米',count_unit:'袋',opening_quantity:null,product_code:'TEST-米',raw_values:{品名:'測試米'}}];await call('save_inventory_import_review',{p_store_id:s,p_file:file,p_rows:rows.map(r=>({...r,normalized_values:{name:r.name,unit:r.count_unit},status:'PENDING'}))});let result=await call('import_pilot_inventory',{p_store_id:s,p_rows:{file,rows}});assert.equal(result[0].status,'ADDED');let catalog=await call('app_workspace',{p_store_id:s,p_section:'catalog'});const p=catalog.products.find(p=>p.name==='測試米');await op(s,'product.lifecycle',{ids:[p.id],mode:'DISABLE'});result=await call('import_pilot_inventory',{p_store_id:s,p_rows:{file,rows}});assert.equal(result[0].status,'EXISTING');catalog=await call('app_workspace',{p_store_id:s,p_section:'catalog'});assert.equal(catalog.products.filter(p=>p.name==='測試米').length,1);assert.equal(catalog.products.find(p=>p.id===p.id&&p.name==='測試米').is_active,false);const evidence=await demoClient.from('inventory_import_rows').select('*').eq('store_id',s);assert.equal(evidence.data[0].normalized_values.opening_quantity,null);});
test('shared stock validation rejects invalid quantities and highest urgency wins',()=>{assert.throws(()=>movementPlan({quantity:1},2,'READY',null),/INSUFFICIENT/);assert.throws(()=>movementPlan({quantity:1},-1,'READY',null),/INVALID/);assert.equal(reminderTone(0,['immediate']),'neutral');assert.equal(reminderTone(4,['soon','immediate']),'immediate');assert.equal(reminderTone(1,['soon']),'soon');});

test('disabled products leave the next count without changing historical results',async()=>{
 const c=configureDemo('SUPERVISOR','SINGLE_RESTAURANT'),s=c.stores[0].id;
 const sessions=await demoClient.from('inventory_count_sessions').select('*').eq('store_id',s);const active=sessions.data.find(x=>x.status==='IN_PROGRESS');
 for(const zone of [...new Set(active.snapshot.zones.map(x=>x.zone_id))]){const entries=active.snapshot.zones.filter(x=>x.zone_id===zone).map(x=>({zone_id:zone,product_id:x.product_id,quantity:2,unit:x.unit}));await call('save_pilot_count_drafts',{p_session_id:active.id,p_entries:entries});await call('complete_pilot_count_zone',{p_session_id:active.id,p_zone_id:zone});}
 const before=await call('get_pilot_count_results',{p_session_id:active.id});const disabled=before[0].product_id;
 await op(s,'product.lifecycle',{ids:[disabled],mode:'DISABLE'});
 const next=await call('start_pilot_count',{p_store_id:s});const loaded=await demoClient.from('inventory_count_sessions').select('*').eq('id',next);const snapshot=loaded.data[0].snapshot.zones;assert(!snapshot.some(x=>x.product_id===disabled));
 for(const zone of [...new Set(snapshot.map(x=>x.zone_id))]){await call('save_pilot_count_drafts',{p_session_id:next,p_entries:snapshot.filter(x=>x.zone_id===zone).map(x=>({zone_id:zone,product_id:x.product_id,quantity:3,unit:x.unit}))});await call('complete_pilot_count_zone',{p_session_id:next,p_zone_id:zone});}
 assert.deepEqual(await call('get_pilot_count_results',{p_session_id:active.id}),before);
 const current=await demoClient.from('inventory_count_sessions').select('*').eq('id',next);assert.equal(current.data[0].status,'CLOSED');
});
