import test from 'node:test';
import assert from 'node:assert/strict';
import {priceCandidate,priceSearch,isIngredientStopped,priceEdit,supplierOptions} from '../lib/ingredient-price-sheet.ts';
const source=(id,price,date,key='id:a')=>({id,price,effective_date:date,created_at:date,unit:'g',review_status:'confirmed',source_kind:'purchase',supplier_key:key,supplier_name:key==='id:a'?'甲廠商':'乙廠商'});
const row={id:'m',name:'奶油',unit:'g',cost_price:.28,selected_reference:'old',review_status:'confirmed',revision:1,aliases:[{id:'a',name:'無鹽牛油'}],supplier_key:'id:a',supplier_name:'甲廠商',sources:[source('old',.28,'2026-09-01'),source('new',.3,'2026-10-01')]};
test('latest comparable quote only: older differences do not appear after latest equals standard',()=>{assert.equal(priceCandidate(row,[]).id,'new');assert.equal(priceCandidate({...row,cost_price:.3},[]),null);assert.equal(priceCandidate({...row,dismissed_reference:'new',dismissed_value:.3},[]),null);assert.equal(priceCandidate({...row,dismissed_reference:'new',dismissed_value:.4},[]).id,'new');});
test('supplier-specific stop preserves ingredient and alternative supplier; whole stop hides price candidates',()=>{const stopped=[{ingredient_id:'m',supplier_key:'id:a',stopped:true}];assert.equal(isIngredientStopped(row,stopped),false);assert.equal(priceCandidate(row,stopped),null);assert.equal(priceCandidate({...row,sources:[...row.sources,source('b',.29,'2026-10-02','id:b')]},stopped).id,'b');assert.equal(isIngredientStopped(row,[{ingredient_id:'m',supplier_key:'*',stopped:true}]),true);});
test('different units, unrelated store references and unconfirmed sources are never automatically comparable',()=>{assert.equal(priceCandidate({...row,sources:[{...source('q',30,'2026-10-02'),unit:'包'}]},[]),null);assert.equal(priceCandidate({...row,sources:[{...source('q',.3,'2026-10-02'),can_apply:false}]},[]),null);assert.equal(priceCandidate({...row,sources:[{...source('q',.3,'2026-10-02'),review_status:'pending'}]},[]),null);});
test('supplier and every alias are searchable; edit uses package price and stable supplier identity',()=>{assert(priceSearch(row,'無鹽牛油'));assert(priceSearch(row,'甲廠商'));assert.equal(priceEdit(row).supplier_id,'a');assert.equal(supplierOptions(row).length,1);assert.equal(priceEdit({...row,purchase:{amount:280,quantity:1,unit:'公斤'}}).price,'280');});
