import test from 'node:test';
import {createRequire} from 'node:module';
import * as XLSX from 'xlsx';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import React from 'react';
import ts from 'typescript';
import * as model from '../lib/ingredient-price-sheet.ts';
import * as catalog from '../lib/ingredient-catalog.ts';
const source=readFileSync(new URL('../app/pilot/ingredient-price-sheet.tsx',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export default function','function');
const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;
const row={id:'m',name:'奶油',unit:'g',cost_price:.28,review_status:'confirmed',revision:1,aliases:[{id:'a',name:'奶油塊'},{id:'b',name:'無鹽牛油'}],supplier_key:'id:s',supplier_id:'s',supplier_name:'甲商',sources:[]};
function harness(extra={}){const hooks=[],calls=[],storage=new Map();let i=0;const scope={require:createRequire(import.meta.url),React,...model,...catalog,crypto,setTimeout:()=>0,clearTimeout,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{confirm:()=>true,addEventListener(){},removeEventListener(){}},useState:v=>{const n=i++;if(!(n in hooks))hooks[n]=typeof v==='function'?v():v;return [hooks[n],v=>hooks[n]=typeof v==='function'?v(hooks[n]):v];},useRef:v=>{const n=i++;return hooks[n]||(hooks[n]={current:v});},useEffect:()=>{}};runInNewContext(code,scope);const props={data:{...model.emptyPriceSheet,ingredients:[row],suppliers:[{id:'s',name:'甲商'}],can_price:true,...extra},loaded:true,failed:false,canExport:true,draftKey:'test',save:async(...args)=>{calls.push(args);}};const render=()=>{i=0;return scope.IngredientPriceSheet(props);};return {render,calls,props};}
function all(node,predicate){if(!node)return [];if(Array.isArray(node))return node.flatMap(v=>all(v,predicate));if(typeof node!=='object')return [];return [...(predicate(node)?[node]:[]),...all(node.props?.children,predicate)];}
const text=n=>Array.isArray(n)?n.map(text).join(''):typeof n==='object'&&n?text(n.props?.children):String(n??'');
async function flush(){for(let i=0;i<100;i++)await Promise.resolve();}
const button=(tree,label)=>all(tree,n=>n.type==='button'&&text(n)===label)[0];
test('inline edit saves without a side card and preserves blank price',async()=>{const h=harness();button(h.render(),'編輯').props.onClick();let tree=h.render();assert.equal(all(tree,n=>n.props?.role==='dialog').length,0);all(tree,n=>n.props?.['aria-label']==='確認價格')[0].props.onChange({target:{value:''}});await button(h.render(),'儲存修改').props.onClick();await flush();assert.equal(h.calls.length,1);assert.equal(h.calls[0][0],'save');assert.equal(h.calls[0][1].cost_price,null);assert.equal(h.calls[0][1].supplier_id,'s');});
test('supplier stop sends scope and reason and does not write until confirmed',async()=>{const h=harness();button(h.render(),'停用').props.onClick();await flush();assert.equal(h.calls.length,0);let tree=h.render();const select=all(tree,n=>n.type==='select'&&n.props.value==='*')[0];select.props.onChange({target:{value:'id:s'}});await button(h.render(),'確認停用並留紀錄').props.onClick();await flush();assert.equal(h.calls[0][0],'stop');assert.equal(h.calls[0][1].supplier_key,'id:s');assert.equal(h.calls[0][1].reason,'價格偏高');});
test('removed tab shows reason and requires restore explanation',async()=>{const h=harness({supply_states:[{ingredient_id:'m',supplier_key:'id:s',supplier_name:'甲商',stopped:true,reason:'品質不佳',disposition:'不建議再採購',note:'退貨兩次',revision:1,updated_at:'2026-10-08'}]});const tab=all(h.render(),n=>n.type==='button'&&text(n).startsWith('已移除'))[0];tab.props.onClick();await flush();assert(text(h.render()).includes('品質不佳'));button(h.render(),'恢復').props.onClick();await button(h.render(),'確認恢復並留紀錄').props.onClick();await flush();assert.equal(h.calls.length,0);assert(text(h.render()).includes('請簡短記錄恢復採購的原因'));});

test('partial save retry does not resend successful rows and retains request identity',async()=>{const h=harness({ingredients:[row,{...row,id:'n',name:'麵粉'}]});const requests=[];let fail=true;h.props.save=async(a,d,id)=>{requests.push({a,d,id});if(d.id==='n'&&fail)throw Error('network');};button(h.render(),'編輯本頁全部').props.onClick();await button(h.render(),'儲存修改').props.onClick();await flush();assert.equal(requests.length,2);fail=false;await button(h.render(),'儲存修改').props.onClick();await flush();assert.equal(requests.length,3);assert.equal(requests[2].d.id,'n');assert.equal(requests[2].id,requests[1].id);});
function file(rows){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(rows),'價格');const bytes=XLSX.write(book,{type:'buffer',bookType:'xlsx'});return {arrayBuffer:async()=>bytes};}
test('multi-file first import stages rows, duplicate files do not create duplicate drafts, explicit save writes',async()=>{const h=harness({ingredients:[]});let tree=h.render();const upload=all(tree,n=>n.type==='input'&&n.props.type==='file')[0];const f=file([{食材:'測試麵粉',單位:'公斤',價格:32}]);await upload.props.onChange({target:{files:[f,f]}});await flush();assert.equal(h.calls.length,0);await button(h.render(),'儲存修改').props.onClick();await flush();assert.equal(h.calls.length,1);assert.equal(h.calls[0][1].name,'測試麵粉');});
test('removed-file reimport cannot resurrect a removed item',async()=>{const h=harness({supply_states:[{ingredient_id:'m',supplier_key:'*',stopped:true}]});const upload=all(h.render(),n=>n.type==='input'&&n.props.type==='file')[0];await upload.props.onChange({target:{files:[file([{識別碼:'m',食材:'奶油',單位:'g',價格:.28}])]}});await flush();assert.equal(h.calls.length,0);assert(text(h.render()).includes('匯入不會自動恢復'));});
