import test from 'node:test';
import assert from 'node:assert/strict';
import {settleLoginDevice,rememberOAuthDevice,takeOAuthDevice} from '../lib/login-device-setup.ts';
const base={authorized:false,device_type:'SHARED',remember_device:true,reauth_days:7,choice_required:true,personal_allowed:false,can_authorize_personal:false};
function actions(result){const calls=[];return {calls,authorize:async()=>{calls.push('authorize')},choose:async p=>{calls.push(p);return result||{data:{...base,choice_required:false,device_type:p?'PERSONAL':'SHARED'},error:null}}};}
test('removing the prompt never silently authorizes a manager device',async()=>{for(const choice of [undefined,false]){const a=actions();const p=await settleLoginDevice({...base,can_authorize_personal:true},choice,a);assert.deepEqual(a.calls,[false]);assert.equal(p.device_type,'SHARED');}});
test('an explicit manager checkbox uses the existing authorization operation',async()=>{const a=actions();await settleLoginDevice({...base,can_authorize_personal:true},true,a);assert.deepEqual(a.calls,['authorize',true]);});
test('staff checkbox cannot grant trust; already approved personal devices stay remembered',async()=>{const a=actions();await settleLoginDevice(base,true,a);assert.deepEqual(a.calls,[false]);const b=actions();await settleLoginDevice({...base,authorized:true,device_type:'PERSONAL',personal_allowed:true},undefined,b);assert.deepEqual(b.calls,[true]);});
test('existing session choice is preserved without a new blocking step',async()=>{for(const device_type of ['PERSONAL','SHARED']){const a=actions();const p={...base,device_type,choice_required:false};assert.equal(await settleLoginDevice(p,undefined,a),p);assert.deepEqual(a.calls,[]);}});
test('older open prompt keeps its policy; connectivity failures remain retryable',async()=>{const a=actions({data:null,error:{message:'FRESH_LOGIN_REQUIRED'}});assert.equal(await settleLoginDevice(base,undefined,a),base);await assert.rejects(()=>settleLoginDevice(base,undefined,actions({data:null,error:{message:'Failed to fetch'}})));});
test('Google login intent is one-use, expires, and preserves unchecked state',()=>{const values=new Map();const s={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};rememberOAuthDevice(false,s,1000);assert.equal(takeOAuthDevice(s,1001),false);assert.equal(takeOAuthDevice(s,1002),undefined);rememberOAuthDevice(true,s,1000);assert.equal(takeOAuthDevice(s,601001),undefined);});
