import test from 'node:test';
import assert from 'node:assert/strict';
import {reviewDraft,reviewNet,reviewPayload,changeReviewLine,isFreightName} from '../lib/receipt-review.ts';
const receipt={supplier_name:'豪野',receipt_date:'2026-09-05',document_number:'a',tax:0,total:4200,note:'',adjustment:0,revision:2,source_fingerprint:'same',pending:false,lines:[
 {row_key:'1',product_name:'功夫腿',quantity:10,unit:'公斤',unit_price:420,subtotal:4200,category:'食材',note:'',specification:''},
 {row_key:'2',product_name:'鵝肝',quantity:2,unit:'包',unit_price:null,subtotal:null,category:'食材',note:'',specification:''}
]};
test('normal missing price remains missing; classification alone does not guess release',()=>{const d=reviewDraft(receipt);assert.equal(reviewNet(d),null);assert.throws(()=>reviewPayload(receipt,d,true));});
test('custody release contributes zero payable, preserves quantity, and needs a selected lot to submit',()=>{let d=changeReviewLine(reviewDraft(receipt),1,'handling','CUSTODY_RELEASE');assert.equal(reviewNet(d),4200);assert.throws(()=>reviewPayload(receipt,d,true));assert.equal(reviewPayload(receipt,d,false).lines[1].unit_price,null);d=changeReviewLine(d,1,'custody_lot_id','lot');const payload=reviewPayload(receipt,d,true);assert.equal(payload.lines[1].quantity,2);assert.equal(payload.lines[1].subtotal,0);assert.equal(payload.lines[1].category,'食材');assert.equal(payload.total,4200);assert.equal(receipt.lines[1].subtotal,null);});
test('freight remains a charged invoice line exactly once',()=>{const r={...receipt,total:4415,lines:[receipt.lines[0],{...receipt.lines[1],product_name:'運費',quantity:1,unit:'筆',unit_price:215,subtotal:215,handling:'FREIGHT'}]};const d=reviewDraft(r);assert.equal(reviewNet(d),4415);assert.equal(reviewPayload(r,d,true).lines[1].subtotal,215);});
test('returning a release to normal requires its own price and clears the custody link',()=>{let d=changeReviewLine(reviewDraft(receipt),1,'handling','CUSTODY_RELEASE');d=changeReviewLine(d,1,'custody_lot_id','lot');d=changeReviewLine(d,1,'handling','NORMAL');assert.equal(d.lines[1].custody_lot_id,'');assert.equal(reviewNet(d),null);assert.throws(()=>reviewPayload(receipt,d,true));});
test('already posted release cannot change quantity, unit, date or classification on later save',()=>{const r={...receipt,lines:[receipt.lines[0],{...receipt.lines[1],handling:'CUSTODY_RELEASE',custody_lot_id:'lot',custody_event_id:'event',custody_posted:true,subtotal:0}]};const d=reviewDraft(r);assert.equal(reviewPayload(r,d,true).lines[1].custody_event_id,'event');for(const [key,value] of [['quantity','3'],['unit','盒'],['handling','NORMAL'],['custody_lot_id','other']])assert.throws(()=>reviewPayload(r,changeReviewLine(d,1,key,value),false));assert.throws(()=>reviewPayload(r,{...d,date:'2026-09-06'},false));});
test('freight suggestions use narrow names and never classify food or custody automatically',()=>{assert(isFreightName('運費(箱)'));assert(isFreightName('其他運費'));assert(!isFreightName('運費折抵'));assert(!isFreightName('鵝肝'));});
