import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {accountSummary,accountPayload,accountDate,filterReceiptAccounts,parseAccountInput,accountExportRows} from '../lib/receipt-accounting.ts';
const row=(id,extra={})=>({batch_id:id,batch_number:'RC-'+id,receipt_date:'2026-09-10',work_date:'2026-10-01',uploaded_at:'2026-10-01T00:00:00Z',supplier_name:'甲供應商',document_number:'DOC-'+id,products:'麵粉',line_count:2,line_net:100,pages:2,net:100,tax:5,total:105,source_net:100,source_tax:5,source_total:105,amount_override:null,note:'',revision:0,source_fingerprint:'source',checked_at:null,pending:false,amount_conflict:false,status:'UNCHECKED',record_state:'LIVE',can_edit:true,...extra});
const filters={from:'2026-09-01',to:'2026-09-30',supplier:'ALL',supplierNames:[],query:'',category:'ALL',scope:'ALL'};
test('one receipt counted once, never per page or ingredient; inclusive tax never added twice',()=>{const s=accountSummary([row('a'),row('a'),row('b',{tax:0,total:100})]);assert.equal(s.count,2);assert.equal(s.net.value,200);assert.equal(s.tax.value,5);assert.equal(s.total.value,205);});
test('unknown tax is not zero and incomplete or conflicting receipts stay visibly partial',()=>{const s=accountSummary([row('known'),row('unknown',{tax:null,total:null}),row('pending',{pending:true,status:'PENDING'}),row('conflict',{amount_conflict:true,status:'RECHECK'})]);assert.equal(s.tax.value,5);assert.equal(s.tax.missing,3);assert.equal(s.pending,1);assert.equal(s.net.value,200);assert.equal(s.net.missing,2);});
test('changed sources are excluded from reliable totals until rechecked',()=>{const s=accountSummary([row('changed',{status:'RECHECK',checked_at:'2026-09-11'})]);assert.equal(s.total.value,0);assert.equal(s.total.missing,1);assert.equal(s.checked,0);});
test('dates use actual arrivals; missing dates stay exceptions instead of fabricated upload dates',()=>{assert.equal(accountDate('115/09/01'),'2026-09-01');assert.equal(accountDate('2026-02-30'),'');assert.equal(accountDate('garbage'),'');const r=filterReceiptAccounts([row('a'),row('b',{receipt_date:'2026-08-01'}),row('c',{receipt_date:null})],[],filters);assert.deepEqual(r.map(v=>v.batch_id),['a','c']);});
test('search, single receipt, record flags, supplier and category filters share the display scope',()=>{const list=[row('a'),row('b',{supplier_name:'乙',record_state:'REMOVED'}),row('c',{record_state:'TEST'})];assert.equal(filterReceiptAccounts(list,[],{...filters,query:'DOC-a'}).length,1);assert.deepEqual(filterReceiptAccounts(list,[],{...filters,scope:'REMOVED'}).map(r=>r.batch_id),['b']);assert.equal(filterReceiptAccounts(list,[],{...filters,batchId:'other'}).length,0);assert.equal(filterReceiptAccounts(list,[],{...filters,supplier:'__SUPPLIER__',supplierNames:['甲 供應商']}).length,1);assert.equal(filterReceiptAccounts(list,[{batch_id:'a',category:'食材',status:'PENDING'}],{...filters,category:'食材'}).length,1);assert.equal(filterReceiptAccounts(list,[],{...filters,category:'酒水'}).length,0);});
test('financial check independent of receiving; pending, missing and inconsistent amounts cannot be checked',()=>{assert.equal(accountPayload(row('a'),null,'ok',true).checked,true);assert.throws(()=>accountPayload(row('a',{pending:true}),null,'',true));assert.throws(()=>accountPayload(row('a',{source_tax:null}),null,'',true));assert.throws(()=>accountPayload(row('a',{receipt_date:null}),null,'',true));assert.throws(()=>accountPayload(row('a'),{net:100,tax:5,total:110},'',true));assert.equal(accountPayload(row('a'),{net:100,tax:0,total:100},'',true).amount_override.tax,0);});
test('revision tokens survive; notes never create implicit amount overrides',()=>{const p=accountPayload(row('a',{revision:3}),null,'供應商確認',false);assert.equal(p.revision,3);assert.equal(p.source_fingerprint,'source');assert.equal(p.amount_override,null);assert.equal(p.checked,false);});
test('inputs reject invalid and oversized values, while blank remains unknown',()=>{assert.equal(parseAccountInput(''),null);assert.equal(parseAccountInput('0'),0);assert.equal(parseAccountInput('23.427'),23.427);for(const input of ['NaN','Infinity','1e4','1,000','1000000000','0.12345'])assert.throws(()=>parseAccountInput(input));});
test('export has numeric amounts, explicit unknown tax and notes',()=>{const out=accountExportRows([row('a',{tax:null,total:null,note:'缺稅額'})]);assert.equal(out[0]['稅額'],'待確認');assert.equal(out[0]['未稅金額'],100);assert.equal(out[0]['備註'],'缺稅額');assert.equal(out[0]['貨單號碼'],'DOC-a');});
const ui=readFileSync(new URL('../app/pilot/receipt-accounting.tsx',import.meta.url),'utf8');
test('UI retains failed drafts, reuses request tokens and uses existing authorized original viewer',()=>{assert.match(ui,/retry\.current\?\.key!==key/);assert.match(ui,/await saveReceiptAccount[\s\S]*setEdit\(null\)/);assert.match(ui,/props\.onSource\(row\.batch_id\)/);assert.match(ui,/ReceiptReviewWorkbench/);assert.match(ui,/readScopedReceiptAccounts/);assert.match(ui,/key=\{row.batch_id\}/);assert.doesNotMatch(ui,/localStorage\.setItem|enqueue-receipt-ocr/);});

test('zero-padded ROC dates belong only to their actual receipt month',()=>{
 for(const value of ['0115/09/04','民國0115年09月04日','115/09/04','2026-09-04'])assert.equal(accountDate(value),'2026-09-04');
 assert.equal(accountDate('0115/09/09'),'2026-09-09');
 for(const value of ['0115/02/29','0115/09/31','0115/13/04'])assert.equal(accountDate(value),'');
 const receipts=[row('first',{receipt_date:'0115/09/04'}),row('second',{receipt_date:'0115/09/09'})];
 assert.equal(filterReceiptAccounts(receipts,[],filters).length,2);
 assert.equal(filterReceiptAccounts(receipts,[],{...filters,from:'2026-10-01',to:'2026-10-31'}).length,0);
 assert.equal(accountExportRows(receipts)[0]['到貨日期'],'2026-09-04');
});
