import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import ts from 'typescript';
import * as helpers from '../lib/receipt-accounting.ts';
import {nextReviewId} from '../lib/receipt-review.ts';
const source=readFileSync(new URL('../app/pilot/receipt-accounting.tsx',import.meta.url),'utf8');
const ast=ts.createSourceFile('receipt-accounting.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const body=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='ReceiptAccountingBody');
const compiled=ts.transpileModule(body.getText(ast),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.React}}).outputText;
const row=(id,extra={})=>({batch_id:id,batch_number:'RC-'+id,receipt_date:'2026-09-10',work_date:'2026-09-10',supplier_name:'甲供應商',document_number:'DOC-'+id,products:'麵粉',line_count:2,line_net:100,pages:2,net:100,tax:5,total:105,source_net:100,source_tax:5,source_total:105,amount_override:null,note:'',revision:0,source_fingerprint:'hash',checked_at:null,pending:false,amount_conflict:false,reviewed:true,status:'UNCHECKED',record_state:'LIVE',can_edit:true,...extra});
function nodes(tree){if(Array.isArray(tree))return tree.flatMap(nodes);if(!tree||typeof tree!=='object')return [];return [tree,...nodes(tree.props?.children)];}
const text=node=>typeof node==='string'?node:typeof node==='number'?String(node):Array.isArray(node)?node.map(text).join(''):node?.props?text(node.props.children):'';
function harness(rows=[row('a')]){
 const state=[],refs=[],calls=[],opened=[];let si=0,ri=0,id=0,fail=false,records=rows;
 const props={storeId:'store',userId:'user',tab:'accounts',onTabChange(){},filters:{from:'2026-09-01',to:'2026-09-30',supplier:'ALL',supplierNames:[],query:'',category:'ALL',scope:'ALL'},lines:[],children:React.createElement('div',null,'既有品項明細'),disabled:false,editing:false,onEditing(){},onSource:id=>opened.push(id)};
 const scope={React,...helpers,nextReviewId,ReceiptReviewWorkbench:()=>null,ReceiptBulkReview:()=>React.createElement('div',null,'整批編輯明細'),AbortController,document:{visibilityState:'visible'},crypto:{randomUUID:()=>`request-${++id}`},receiptReadError:()=> '讀取失敗',exportRows:async(...args)=>calls.push({export:args}),useState:initial=>{const i=si++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return [state[i],v=>{state[i]=typeof v==='function'?v(state[i]):v;}];},useRef:initial=>{const i=ri++;return refs[i]||(refs[i]={current:initial});},useCallback:fn=>fn,useEffect(){},readScopedReceiptAccounts:async(_store,_signal,_from,_to,_supplier,batch)=>records.filter(r=>!batch||r.batch_id===batch),saveReceiptAccount:async(store,batch,data,request)=>{calls.push({store,batch,data,request});if(fail)throw Error('NETWORK');records=records.map(r=>r.batch_id===batch?{...r,...(data.amount_override||{}),amount_override:data.amount_override,note:data.note,status:data.checked?'CHECKED':'UNCHECKED',checked_at:data.checked?'2026-09-11':null,revision:r.revision+1}:r);return {saved:true};}};
 runInNewContext(compiled,scope);const render=()=>{si=0;ri=0;return scope.ReceiptAccountingBody(props);};render();state[0]=rows;state[1]=false;state[5]=JSON.stringify(['store','user','2026-09-01','2026-09-30','ALL']);
 return {state,props,calls,opened,render,html:()=>renderToStaticMarkup(render()),fail:v=>{fail=v;},find:predicate=>nodes(render()).find(predicate),button:label=>nodes(render()).find(n=>n.type==='button'&&text(n)===label)};
}
const settle=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
test('actual component renders one checkbox per receipt, grouped suppliers, missing tax and original access',()=>{const h=harness([row('a'),row('b',{tax:null,total:null,status:'MISSING'}),row('c',{supplier_name:'乙供應商',pending:true,status:'PENDING',tax:null,total:null})]);const html=h.html();assert.equal((html.match(/type="checkbox"/g)||[]).length,3);assert.equal((html.match(/<h3>甲供應商<\/h3>/g)||[]).length,1);assert.match(html,/稅額待確認/);assert.match(html,/待建檔/);nodes(h.find(n=>n.type==='tr'&&text(n).includes('DOC-a'))).find(n=>n.type==='button'&&text(n)==='查看').props.onClick();assert.deepEqual(h.opened,['a']);});
test('checkbox roundtrip calls the persistent API and reloads checked then unchecked state',async()=>{const h=harness();h.find(n=>n.type==='input'&&n.props.type==='checkbox').props.onChange({currentTarget:{checked:true,dataset:{accountId:'a'}}});await settle();assert.equal(h.calls[0].data.checked,true);assert.equal(h.find(n=>n.type==='input'&&n.props.type==='checkbox').props.checked,true);h.find(n=>n.type==='input'&&n.props.type==='checkbox').props.onChange({currentTarget:{checked:false,dataset:{accountId:'a'}}});await settle();assert.equal(h.calls[1].data.revision,1);assert.equal(h.find(n=>n.type==='input'&&n.props.type==='checkbox').props.checked,false);});
test('row correction opens the unified workbench even for a completed receipt',()=>{const h=harness([row('a',{status:'CHECKED'})]);h.button('核對／更正').props.onClick();assert.equal(h.state[7],'a');});
test('reading failure labels same-scope receipts stale and blocks exporting or checking',()=>{const h=harness();h.state[2]='讀取失敗';assert.match(h.html(),/DOC-a/);assert.match(h.html(),/尚未更新/);assert.equal(h.button('匯出對帳清單').props.disabled,true);assert.equal(h.find(n=>n.type==='input'&&n.props.type==='checkbox').props.disabled,true);h.props.filters.supplier='另一廠商';assert.doesNotMatch(h.html(),/DOC-a/);});
test('read-only and pending entries cannot be checked; items tab uses inline bulk editor',()=>{const h=harness([row('a',{can_edit:false}),row('b',{pending:true,status:'PENDING'})]);const boxes=nodes(h.render()).filter(n=>n.type==='input'&&n.props.type==='checkbox');assert.ok(boxes.every(n=>n.props.disabled));h.props.tab='items';assert.match(h.html(),/整批編輯明細/);assert.doesNotMatch(h.html(),/DOC-a/);});

test('unverified receipts stay out of reconciliation while previously checked receipts remain',()=>{const h=harness([row('new',{reviewed:false}),row('old',{reviewed:false,status:'CHECKED'}),row('ready')]);assert.doesNotMatch(h.html(),/DOC-new/);assert.match(h.html(),/DOC-old/);assert.match(h.html(),/DOC-ready/);});
