import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';import ts from 'typescript';import React from 'react';import * as requireRuntime from 'react/jsx-runtime';
import * as model from '../lib/transfer-batch.ts';import * as direction from '../lib/transfer-direction.ts';
const code=ts.transpileModule(readFileSync(new URL('../app/pilot/transfer-batch-form.tsx',import.meta.url),'utf8'),{fileName:'transfer-batch-form.tsx',compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const products=[{id:'squid',name:'透抽',unit:'公斤'},{id:'butter',name:'奶油',unit:'盒'},{id:'eggs',name:'雞蛋',unit:'顆'}];
function nodes(tree,predicate){const all=[];function visit(n){if(Array.isArray(n))return n.forEach(visit);if(!React.isValidElement(n))return;if(predicate(n))all.push(n);visit(n.props.children);}visit(tree);return all;}
function label(n){if(n==null||typeof n==='boolean')return '';if(Array.isArray(n))return n.map(label).join('');return React.isValidElement(n)?label(n.props.children):String(n);}
function harness({storage=new Map(),sender,confirm=true,storeId='a',userId='field'}={}){
 const hooks=[],effects=[],calls=[];let cursor=0,tree;const props={store:{id:storeId,name:storeId==='a'?'BeApe':'Gras'},userId,peers:[{id:storeId==='a'?'b':'a',name:storeId==='a'?'Gras':'BeApe'}],catalogs:[{store_id:'a',products},{store_id:'b',products:[{id:'wine',name:'酒',unit:'瓶'}]}],units:['公斤','盒','顆','包'],batchVersion:1,loading:false,refresh:async()=>{},onBack:()=>{}};
 const hooksReact={...React,useState(initial){const i=cursor++;hooks[i]??={value:typeof initial==='function'?initial():initial};return[hooks[i].value,v=>{hooks[i].value=typeof v==='function'?v(hooks[i].value):v;}];},useRef(initial){const i=cursor++;hooks[i]??={value:{current:initial}};return hooks[i].value;},useEffect(fn,deps){const i=cursor++;if(!hooks[i]||deps.some((d,k)=>d!==hooks[i].deps[k])){hooks[i]?.cleanup?.();hooks[i]={deps};effects.push(()=>hooks[i].cleanup=fn());}}};
 const scope={exports:{},console,crypto,queueMicrotask,window:{confirm:()=>confirm},require(name){if(name==='react')return hooksReact;if(name==='react/jsx-runtime')return requireRuntime;if(name==='lucide-react')return new Proxy({},{get:(_t,n)=>String(n)});if(name==='./unit-select')return{default:'UnitSelect'};if(name==='@/lib/transfer-direction')return direction;if(name==='@/lib/transfer-batch')return model;if(name==='@/lib/workspace-storage')return{workspaceStorage:()=>({getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)})};if(name==='@/lib/operation-deadline')return {operationDeadline:run=>run(new AbortController().signal)};if(name==='@/lib/app-workspace')return {appError:()=> '請確認輸入資料。',writeOperation:async(store,action,payload,id)=>{calls.push({store,action,payload:JSON.parse(JSON.stringify(payload)),id});return sender?sender(payload,id):{count:payload.items.length,items:payload.items.map((r,i)=>({...r,id:`movement-${i}`,from_store_id:payload.from_store_id,to_store_id:payload.to_store_id}))};}};if(name.endsWith('.css'))return {};throw Error(name);}};
 runInNewContext(code,scope);const render=()=>{cursor=0;tree=scope.exports.default(props);return tree;};const settle=async()=>{for(let i=0;i<15;i++){for(const e of effects.splice(0))e();await Promise.resolve();render();}};render();
 const find=(type,prop,value)=>{const found=nodes(tree,n=>n.type===type&&n.props[prop]===value);assert.equal(found.length,1,`${type} ${prop}=${value}`);return found[0];};
 const button=text=>{const found=nodes(tree,n=>n.type==='button'&&label(n)===text);assert.ok(found.length,`button ${text}`);return found[0];};
 return {storage,calls,props,settle,render,find,button,get tree(){return tree;},async act(fn,...args){await fn(...args);await settle();},dispose(){hooks.forEach(h=>h.cleanup?.());}};
}
async function choose(h){await h.settle();await h.act(h.find('input','value','beape-to-gras').props.onChange);await h.act(h.find('input','id','transfer-batch-search').props.onFocus);let checks=nodes(h.tree,n=>n.type==='input'&&n.props.type==='checkbox');await h.act(checks[0].props.onChange);await h.act(h.find('input','id','transfer-batch-search').props.onChange,{target:{value:'奶油'}});checks=nodes(h.tree,n=>n.type==='input'&&n.props.type==='checkbox');await h.act(checks[0].props.onChange);await h.act(h.button('加入已選品項（2 項）').props.onClick);}
test('actual form keeps selections across searches and submits two rows once from receiving store',async()=>{const h=harness({storeId:'b'});await choose(h);assert.equal(nodes(h.tree,n=>n.type==='input'&&/項數量/.test(n.props['aria-label']||'')).length,2);await h.act(h.find('input','aria-label','第 1 項數量').props.onChange,{target:{value:'2'}});await h.act(h.find('input','aria-label','第 2 項數量').props.onChange,{target:{value:'1'}});const units=nodes(h.tree,n=>n.type==='UnitSelect');await h.act(units[0].props.onChange,'包');const form=nodes(h.tree,n=>n.type==='form')[0];form.props.onSubmit({preventDefault(){}});form.props.onSubmit({preventDefault(){}});await h.settle();assert.equal(h.calls.length,1);assert.equal(h.calls[0].store,'b');assert.equal(h.calls[0].payload.from_store_id,'a');assert.equal(h.calls[0].payload.items[0].unit,'包');assert.equal(h.calls[0].payload.items.length,2);assert.match(label(h.tree),/已登記 2 項調撥/);});
test('actual form retains immutable pending data through timeout and reopening before retry',async()=>{const h=harness({sender:async()=>{throw Error('timeout');}});await choose(h);for(let i=1;i<=2;i++)await h.act(h.find('input','aria-label',`第 ${i} 項數量`).props.onChange,{target:{value:'1'}});await h.act(nodes(h.tree,n=>n.type==='form')[0].props.onSubmit,{preventDefault(){}});assert.equal(h.find('input','aria-label','第 1 項數量').props.disabled,true);assert.ok(h.button('確認上次送出／重試'));const original=h.calls[0];h.dispose();const reopened=harness({storage:h.storage});await reopened.settle();await reopened.act(nodes(reopened.tree,n=>n.type==='form')[0].props.onSubmit,{preventDefault(){}});assert.equal(reopened.calls[0].id,original.id);assert.deepEqual(reopened.calls[0].payload,original.payload);assert.match(label(reopened.tree),/已登記 2 項調撥/);});
test('direction changes clear rows only after confirmation; drafts are account-isolated',async()=>{const h=harness();await choose(h);await h.act(h.find('input','value','gras-to-beape').props.onChange);assert.equal(nodes(h.tree,n=>n.type==='input'&&/項數量/.test(n.props['aria-label']||'')).length,0);assert.equal(h.calls.length,0);const other=harness({storage:h.storage,userId:'other'});await other.settle();assert.equal(other.find('input','value','gras-to-beape').props.checked,false);const denied=harness({confirm:false});await choose(denied);await denied.act(denied.find('input','value','gras-to-beape').props.onChange);assert.equal(nodes(denied.tree,n=>n.type==='input'&&/項數量/.test(n.props['aria-label']||'')).length,2);});
test('search Enter never submits a partial search or resets its query',async()=>{const h=harness();await h.settle();const input=h.find('input','id','transfer-batch-search');await h.act(input.props.onCompositionStart);await h.act(input.props.onChange,{target:{value:'透抽ㄤ'}});await h.act(h.find('input','id','transfer-batch-search').props.onKeyDown,{key:'Enter',nativeEvent:{isComposing:true},preventDefault(){}});assert.equal(h.find('input','id','transfer-batch-search').props.value,'透抽ㄤ');assert.equal(h.calls.length,0);});
