import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyTransferBatch,addTransferProduct,transferBatchPayload,readTransferBatch,migrateSingleTransfer,submitTransferBatch,confirmedTransferBatch} from '../lib/transfer-batch.ts';
const directions=[{from_store_id:'a',to_store_id:'b'},{from_store_id:'b',to_store_id:'a'}];
const products=[{id:'squid',name:'透抽',unit:'公斤'},{id:'butter',name:'奶油',unit:'盒'}];
function draft(){let d={...emptyTransferBatch(),...directions[0],note:'支援活動'};for(const p of products)d=addTransferProduct(d,p,p.id);return {...d,items:d.items.map((r,i)=>({...r,quantity:String(i+1)}))};}
const response=p=>({count:p.items.length,items:p.items.map((r,i)=>({...r,id:`move-${i}`,from_store_id:p.from_store_id,to_store_id:p.to_store_id,review_status:'PENDING'}))});
test('one direction and note contain multiple independently quantified items, with explicit units',()=>{const d=draft();d.items[0].unit='包';const p=transferBatchPayload(d,products,directions);assert.equal(p.items.length,2);assert.equal(p.items[0].unit,'包');assert.equal(p.items[0].quantity,1);assert.equal(p.note,'支援活動');assert.deepEqual([p.from_store_id,p.to_store_id],['a','b']);});
test('repeated selections keep original quantity and do not duplicate rows',()=>{const d=draft();assert.equal(addTransferProduct(d,products[0],'again'),d);assert.equal(d.items[0].quantity,'1');});
test('removed or other-source products, zero/NaN quantities, blank units and duplicate rows are rejected',()=>{for(const patch of [{quantity:'0'},{quantity:'NaN'},{quantity:'-1'},{unit:''},{product_id:'foreign'},{manual:true}]){const d=draft();Object.assign(d.items[0],patch);assert.throws(()=>transferBatchPayload(d,products,directions));}const d=draft();d.items.push({...d.items[0],key:'dup'});assert.throws(()=>transferBatchPayload(d,products,directions),/重複/);assert.throws(()=>transferBatchPayload(draft(),[products[1]],directions));});
test('manual items stay in the same payload without becoming catalog products',()=>{const d=draft();d.items.push({key:'manual',manual:true,product_id:'',name:' 雞蛋 ',unit:'顆',quantity:'20'});const p=transferBatchPayload(d,products,directions);assert.deepEqual(p.items[2],{product_id:null,name:'雞蛋',quantity:20,unit:'顆',manual:true});});
test('successful submission persists request before network and confirmed receipt before clearing it',async()=>{const d=draft(),p=transferBatchPayload(d,products,directions),order=[];let state;const result=await submitTransferBatch(d,p,{recordingStoreId:'b',requestId:()=>crypto.randomUUID(),persist:v=>{state=v;order.push(v.pending?'pending':'confirmed');},send:async(payload,id)=>{assert.equal(state.pending.id,id);order.push('send');return response(payload);}});assert.deepEqual(order,['pending','send','confirmed']);assert.equal(result.completed.count,2);assert.equal(result.pending,undefined);assert.deepEqual(readTransferBatch(JSON.stringify(result)),JSON.parse(JSON.stringify(result)));});
test('ambiguous timeout survives reload and retries exactly one immutable id/payload',async()=>{const d=draft(),p=transferBatchPayload(d,products,directions);let saved,ids=[],payloads=[];await assert.rejects(submitTransferBatch(d,p,{recordingStoreId:'b',requestId:()=>crypto.randomUUID(),persist:v=>saved=JSON.stringify(v),send:async(payload,id)=>{ids.push(id);payloads.push(JSON.stringify(payload));throw Error('REQUEST_TIMEOUT');}}));const reloaded=readTransferBatch(saved);const result=await submitTransferBatch(reloaded,undefined,{recordingStoreId:'b',requestId:()=>{throw Error('must reuse id');},persist:v=>saved=JSON.stringify(v),send:async(payload,id)=>{ids.push(id);payloads.push(JSON.stringify(payload));return response(payload);}});assert.equal(ids[0],ids[1]);assert.equal(payloads[0],payloads[1]);assert.equal(result.completed.count,2);});
test('storage failure prevents dispatch; post-commit storage failure retains retry snapshot',async()=>{let calls=0;const d=draft(),p=transferBatchPayload(d,products,directions);await assert.rejects(submitTransferBatch(d,p,{recordingStoreId:'a',requestId:()=>crypto.randomUUID(),persist:()=>{throw Error('quota');},send:async()=>{calls++;}}));assert.equal(calls,0);let saved;await assert.rejects(submitTransferBatch(d,p,{recordingStoreId:'a',requestId:()=>crypto.randomUUID(),persist:v=>{if(v.completed)throw Error('quota');saved=JSON.stringify(v);},send:async p=>response(p)}));assert.ok(readTransferBatch(saved).pending);});
test('unknown/truncated/wrong-direction replies never count as saved; validation failures unlock corrections',async()=>{const d=draft(),p=transferBatchPayload(d,products,directions),pending={id:crypto.randomUUID(),payload:p};for(const bad of [null,{},response({...p,from_store_id:'b'}),{count:1,items:response(p).items.slice(0,1)}])assert.throws(()=>confirmedTransferBatch(bad,pending,'a'));let saved;await assert.rejects(submitTransferBatch(d,p,{recordingStoreId:'a',requestId:()=>crypto.randomUUID(),persist:v=>saved=v,send:async()=>{throw {code:'22023',message:'TRANSFER_ITEM_2: INVALID_QUANTITY'};}}));assert.equal(saved.pending,undefined);assert.equal(saved.items.length,2);});
test('completed drafts never send twice and pending drafts cannot gain more selections',async()=>{const d=draft(),p=transferBatchPayload(d,products,directions),done={...d,completed:response(p)};assert.equal(await submitTransferBatch(done,p,{recordingStoreId:'a',requestId:()=>{throw Error();},persist:()=>{throw Error();},send:()=>{throw Error();}}),done);const pending={...d,pending:{id:crypto.randomUUID(),payload:p}};assert.equal(addTransferProduct(pending,{id:'egg',name:'蛋',unit:'顆'},'egg'),pending);});
test('single draft and unresolved single request upgrade without losing the original retry id',async()=>{const id=crypto.randomUUID(),payload={to_store_id:'a',product_id:'squid',quantity:2};const d=migrateSingleTransfer(JSON.stringify({to_store_id:'a',product_id:'squid',name:'透抽',quantity:'2',unit:'公斤'}),JSON.stringify({id,signature:JSON.stringify(payload)}),'b');assert.equal(d.from_store_id,'b');assert.equal(d.pending.id,id);assert.equal(d.pending.legacy,true);const done=await submitTransferBatch(d,undefined,{recordingStoreId:'b',requestId:()=>{throw Error();},persist:()=>{},send:async(p,rid)=>{assert.equal(rid,id);assert.deepEqual(p,payload);return {id:'original',product_id:'squid',name:'透抽',quantity:2,unit:'公斤',from_store_id:'b',to_store_id:'a'};}});assert.equal(done.completed.items[0].id,'original');});
