'use client';
import {useState} from 'react';
import type {WasteRecord} from '@/lib/expiry-waste';
import {wasteSummary} from '@/lib/expiry-waste';
import {exportRows} from './reports-workspace';
import {displayTime} from './inventory-catalog';
type Props={rows:WasteRecord[];canAmount:boolean;filter:'today'|'month'|'choose';onFilter:(v:'today'|'month'|'choose')=>void;month:string;onMonth:(v:string)=>void;state:'LIVE'|'TEST'|'REMOVED';onState:(v:'LIVE'|'TEST'|'REMOVED')=>void;onOpen:(r:WasteRecord)=>void;onAdd:()=>void;adding:boolean};
const money=(n:number|null)=>n===null?'未計價':`NT$ ${n.toLocaleString('zh-TW',{maximumFractionDigits:2})}`;
export default function AdminWasteList(p:Props){
 const [search,setSearch]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('');
 const rows=p.rows.filter(r=>(!reason||r.reason===reason)&&[r.name,r.actor_name,r.note,r.reason].join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 const summary=wasteSummary(rows);
 async function download(){try{await exportRows(rows.map(r=>({'日期':displayTime(r.created_at),'品名':r.name,'數量':r.quantity,'單位':r.unit,...(p.canAmount?{'參考單價':r.reference_price??'未計價','參考金額':r.reference_amount??'未計價'}:{}),'原因':r.reason,'經手人':r.actor_name,'備註':r.note||'','狀態':r.review_status==='PENDING'?'待確認':'已確認'})),'xlsx',`廢棄紀錄_${p.month}`);setError('');}catch{setError('匯出未完成，請重試。');}}
 return <section className="admin-data-list"><div className="admin-data-summary">{p.canAmount&&<div><span>已計價廢棄金額</span><strong>{summary.count&&summary.unpriced===summary.count?'未計價':money(summary.amount)}</strong></div>}<div><span>廢棄紀錄</span><strong>{rows.length} 筆</strong></div>{p.canAmount&&<div><span>未計價</span><strong>{summary.unpriced} 筆</strong></div>}</div>
 <div className="admin-data-tabs"><span>廢棄明細</span></div><div className="admin-data-filters"><input type="search" aria-label="搜尋廢棄" placeholder="搜尋品名、經手人、備註" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="廢棄期間" value={p.filter} onChange={e=>p.onFilter(e.target.value as Props['filter'])}><option value="today">今天</option><option value="month">本月</option><option value="choose">選擇月份</option></select>{p.filter==='choose'&&<input type="month" aria-label="廢棄月份" value={p.month} onChange={e=>e.target.value&&p.onMonth(e.target.value)}/>}<select aria-label="廢棄原因" value={reason} onChange={e=>setReason(e.target.value)}><option value="">全部原因</option>{[...new Set(p.rows.map(r=>r.reason))].map(r=><option key={r}>{r}</option>)}</select><select aria-label="廢棄資料狀態" value={p.state} onChange={e=>p.onState(e.target.value as Props['state'])}><option value="LIVE">正式資料</option><option value="TEST">測試資料</option><option value="REMOVED">已移出</option></select></div>
 <div className="admin-data-actions"><button className="shell-primary" onClick={p.onAdd}>{p.adding?'收起補登':'新增／行政補登'}</button><button className="shell-secondary admin-export" disabled={!rows.length} onClick={()=>void download()}>匯出 Excel</button></div>{error&&<p role="alert">{error}</p>}
 <div className="admin-data-table-wrap"><table><thead><tr>{['日期','品名','數量','單位',...(p.canAmount?['參考單價','參考金額']:[]),'原因','經手人','備註','狀態','操作'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{displayTime(r.created_at)}</td><td>{r.name}</td><td>{r.quantity}</td><td>{r.unit}</td>{p.canAmount&&<><td>{money(r.reference_price)}</td><td>{money(r.reference_amount)}</td></>}<td>{r.reason}</td><td>{r.actor_name||'—'}</td><td>{r.note||'—'}</td><td>{r.review_status==='PENDING'?'待確認':'已確認'}</td><td><button className="text-button" onClick={()=>p.onOpen(r)}>{r.review_status==='PENDING'?'查看／核對':'查看'}</button></td></tr>)}{!rows.length&&<tr><td colSpan={p.canAmount?11:9}>此期間沒有符合條件的廢棄紀錄。</td></tr>}</tbody></table></div><small>共 {rows.length} 筆；保留原始廢棄紀錄。</small></section>;
}
