'use client';
import StoreArchive from './store-archive';
import StoreLifecycleConfirm,{type ManagedStore} from './store-lifecycle-confirm';
import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {deviceId} from '@/lib/login-device';
import {isDemoPath} from '@/lib/demo-client.mjs';
import {canManageStores,type AppStore} from '@/lib/app-workspace';
import {useOperation,useWorkspace} from './operation-hooks';
import type {ShellView} from './app-shell';
type Organization={id:string;name:string;business_type:string;store_mode:string;has_erp:boolean;updated_at:string};
type StoreSettings=ManagedStore;
type Device={id:string;label:string;device_type:string;authorized_at:string|null;revoked_at:string|null;last_seen_at:string};
type SettingsData={devices?:Device[];organization?:Organization;stores?:StoreSettings[];settings?:Record<string,unknown>;editable?:boolean;revision?:number};
export default function BusinessSettings({returnLabel="返回上一頁",store,userId,section,initialPage='home',onManageStore,onBack,onNavigate,onChanged,accountContent}:{store:AppStore;stores:AppStore[];initialPage?:'home'|'store-home';onManageStore:(id:string)=>Promise<void>;userId:string;section:'business'|'preferences';returnLabel?:string;onBack:()=>void;onNavigate:(view:ShellView)=>void;onChanged:()=>Promise<void>;accountContent?:ReactNode}){
 const business=section==='business';const workspace=useWorkspace<SettingsData>(store.id,business?'business':'settings');const operation=useOperation(store.id,userId);
 const[currentDevice]=useState(()=>{try{return isDemoPath(window.location.pathname)?'demo-device':deviceId();}catch{return '';}});const[deviceTypes,setDeviceTypes]=useState<Record<string,string>>({});const[page,setPage]=useState<string>(initialPage);const[notice,setNotice]=useState('');const org=workspace.data?.organization;const managedStores=workspace.data?.stores||[];const activeStores=managedStores.filter(s=>s.is_active);const inactiveStores=managedStores.filter(s=>!s.is_active);
 const [lifecycle,setLifecycle]=useState<{target:ManagedStore;action:'store.delete'|'store.deactivate'|'store.restore'}>();const[archiveTarget,setArchiveTarget]=useState<string>();
 const [draft,setDraft]=useState<Record<string,string|boolean|number>>({});const[draftRevision,setDraftRevision]=useState(0);
 const[reloading,setReloading]=useState(false);const recoverySequence=useRef(0);const recoveryIdentity=useRef('');
 const editIdentity=`${store.id}:${section}:${page}:${draft.id||''}`;
 useLayoutEffect(()=>{recoveryIdentity.current=editIdentity;},[editIdentity]);
 useEffect(()=>()=>{recoverySequence.current++;},[]);
 const open=(next:string,latest=workspace.data)=>{const latestOrg=latest?.organization;const latestStore=latest?.stores?.find(item=>item.id===store.id);const settings=latest?.settings||{};operation.setError('');setNotice('');if(next==='business'&&latestOrg)setDraft({...latestOrg});else if(next==='store'&&latestStore)setDraft({...latestStore});else setDraft({remember_device:settings.remember_device!==false,reauth_days:Number(settings.reauth_days??7),erp_receiving:settings.erp_receiving!==false,erp_waste:settings.erp_waste!==false,erp_time:String(settings.erp_time||'21:30'),paper_required:store.business_type==='CHAIN_RESTAURANT'&&(settings.paper_required!==false),count_cadence:String(settings.count_cadence||(store.business_type==='CHAIN_RESTAURANT'?'DAILY':'MONTHLY')),blind_count:true} as Record<string,string|boolean|number>);setDraftRevision(latest?.revision||0);setPage(next);};
 const reloadDraft=async()=>{
  const request=++recoverySequence.current;const identity=recoveryIdentity.current;const id=draft.id;
  setReloading(true);
  try{
   const latest=await workspace.refresh();
   if(request!==recoverySequence.current||identity!==recoveryIdentity.current||!latest)return;
   operation.setError('');
   if((page==='store'&&!latest.stores?.some(item=>item.id===id))||(page==='business'&&latest.organization?.id!==id)){
    setDraft({});setPage('home');setNotice('此筆資料已不在目前可管理的清單，已返回設定。');return;
   }
   if(page==='device')setDeviceTypes({});
   open(page,latest);setNotice('已重新載入最新設定，未儲存的修改已捨棄。');
  }finally{if(request===recoverySequence.current)setReloading(false);}
 };
 const save=async()=>{const action=page==='business'?'business.save':page==='store'?'store.save':'settings.save';const payload=action==='settings.save'?{revision:draftRevision,settings:draft}:draft;const result=await operation.run(action,payload);if(result){setNotice('設定已儲存。');setPage(business?'store-home':'home');await workspace.refresh();await onChanged();}};
 const canEdit=business?canManageStores(store):!!workspace.data?.editable;
 const checkbox=(key:string,label:string)=><label className="checkbox-row"><input type="checkbox" checked={draft[key]===true} disabled={!canEdit||reloading} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>{label}</label>;
 if(archiveTarget)return <StoreArchive storeId={archiveTarget} baseStore={store} userId={userId} onBack={()=>setArchiveTarget(undefined)}/>;
 return <><button className="shell-back" disabled={reloading} onClick={()=>page==='home'?onBack():setPage(page==='store-home'||page==='new-store'?'home':business?'store-home':'home')}>‹ {page==='home'?returnLabel:business?'返回設定':'返回個人設定'}</button><h1>{business?'門市設定':'個人設定'}</h1>{business&&page==='home'&&<p className="shell-note">管理各門市的基本資料與營運設定。</p>}{notice&&<p role="status">{notice}</p>}{(operation.error||workspace.error)&&<p className="pilot-message" role="alert">{operation.error||workspace.error}<button type="button" disabled={reloading||operation.busy} onClick={()=>void (!['home','store-home','new-store'].includes(page)?reloadDraft():workspace.refresh())}>{reloading?'正在重新載入…':!['home','store-home','new-store'].includes(page)?'重新載入設定（捨棄未存變更）':'重新讀取'}</button></p>}
 {workspace.loading&&!workspace.data?<p>正在讀取設定…</p>:<>
 {page==='home'&&business&&<>{lifecycle?<StoreLifecycleConfirm anchorId={store.id} userId={userId} target={lifecycle.target} action={lifecycle.action} onCancel={()=>setLifecycle(undefined)} onSaved={async()=>{setLifecycle(undefined);setNotice(lifecycle.action==='store.delete'?'門市已刪除。':'門市狀態已更新。');await onChanged();await workspace.refresh();}}/>:<div className="store-card-grid"><h2>營業中門市（{activeStores.length}）</h2>{activeStores.map(s=><section className="shell-card business-setting-card" key={s.id}><header><div><strong>{s.name}</strong><small>門市代碼：{s.store_code}</small></div><button className="text-button" aria-label={`管理 ${s.name}`} onClick={()=>{if(s.id===store.id)setPage('store-home');else void onManageStore(s.id);}}>管理</button><details className="store-lifecycle-menu"><summary aria-label={`${s.name} ${s.store_code} 更多操作`}>⋯</summary><button className="text-button" onClick={()=>setLifecycle({target:s,action:'store.deactivate'})}>停用門市</button></details></header></section>)}{inactiveStores.length>0&&<section className="shell-section"><h2>已停用門市（{inactiveStores.length}）</h2><div className="shell-card swipe-list">{inactiveStores.map(s=><div className="swipe-row" key={s.id}><button type="button" className="swipe-row-main" onClick={()=>setArchiveTarget(s.id)}><span><strong>{s.name}</strong><small>門市代碼：{s.store_code}{s.can_delete?'・可刪除':'・歷史資料保留'}</small></span><b>›</b></button>{s.can_delete&&<button type="button" className="swipe-row-remove" onClick={()=>setLifecycle({target:s,action:'store.delete'})}>刪除</button>}</div>)}</div><p className="shell-note">可刪除的停用門市左滑即可移除；有作業歷史的門市只保留查看與恢復。</p></section>}{store.is_active!==false&&<button className="shell-card shell-secondary full add-store-card" onClick={()=>{setDraft({name:''});setPage('new-store');}}>＋新增門市</button>}</div>}</>}

 {page==='store-home'&&business&&<><h2>{store.name}</h2><div className="shell-card shell-list"><button className="shell-list-row" onClick={()=>open('store')}><span><strong>基本資料</strong><small>{store.store_code}・{store.staff_login_mode==='EMPLOYEE_NUMBER'?'員工編號':'姓名／暱稱'}</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>open('reminders')}><span><strong>使用功能與提醒</strong><small>盤點、進貨、效期、廢棄及既有作業功能</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>open('count-policy')}><span><strong>作業設定</strong><small>盤點方式與紙本謄寫</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>onNavigate('members')}><span><strong>員工與權限</strong></span><b>›</b></button>{(store.role==='OWNER'||store.is_business_responsible)&&<button className="shell-list-row" onClick={()=>open('business')}><span><strong>商家基本資料</strong><small>{org?.name}・企業內共用</small></span><b>›</b></button>}</div></>}
 {page==='home'&&!business&&<div className="shell-card shell-list"><button className="shell-list-row" onClick={()=>open('device')}><span><strong>登入與裝置</strong><small>個人／共用裝置與重新驗證</small></span><b>›</b></button></div>}
 {page!=='home'&&page!=='store-home'&&page!=='new-store'&&<form onSubmit={e=>{e.preventDefault();void save();}}><section className="shell-card transfer-form">
 {page==='business'&&<><label>商家名稱<input disabled={reloading} value={String(draft.name||'')} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><label>餐廳類型<select disabled={reloading} value={String(draft.business_type||'')} onChange={e=>setDraft({...draft,business_type:e.target.value})}><option value="SINGLE_RESTAURANT">獨立餐廳</option><option value="CHAIN_RESTAURANT">連鎖餐飲</option></select></label><label>門市結構<select disabled={reloading} value={String(draft.store_mode||'')} onChange={e=>setDraft({...draft,store_mode:e.target.value})}><option value="SINGLE">單一門市</option><option value="MULTI">多家門市</option></select></label>{checkbox('has_erp','使用公司 ERP（只提醒與記錄完成）')}</>}
 {page==='store'&&<><label>門市名稱<input disabled={reloading} value={String(draft.name||'')} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><label>員工識別<select disabled={reloading} value={String(draft.staff_login_mode||'')} onChange={e=>setDraft({...draft,staff_login_mode:e.target.value})}><option value="NAME_OR_NICKNAME">姓名／暱稱</option><option value="EMPLOYEE_NUMBER">員工編號</option></select></label></>}
 {page==='device'&&<>{checkbox('remember_device','允許記住裝置')}<label>未使用多久重新驗證<select disabled={!canEdit||reloading} value={String(draft.reauth_days)} onChange={e=>setDraft({...draft,reauth_days:Number(e.target.value)})}><option value="0">每次</option><option value="1">1 天</option><option value="7">7 天</option><option value="30">30 天</option></select></label><p className="shell-note">新裝置登入後可在下方授權；共用裝置只記住門市。</p>{(workspace.data?.devices||[]).map(d=><section className="device-authorization" key={d.id}><strong>{d.label}{d.id===currentDevice?'（此裝置）':''}</strong><small>{d.revoked_at?'已撤銷':d.authorized_at?'已授權':'尚未授權'}・最近使用 {new Date(d.last_seen_at).toLocaleString('zh-TW')}</small><label>裝置類型<select aria-label={`${d.label}${d.id===currentDevice?'（此裝置）':''}裝置類型`} disabled={!canEdit||reloading} value={deviceTypes[d.id]||d.device_type} onChange={e=>setDeviceTypes(v=>({...v,[d.id]:e.target.value}))}><option value="PERSONAL">個人</option><option value="SHARED">店內共用</option></select></label>{canEdit&&<div className="shell-button-stack"><button type="button" className="shell-secondary" disabled={operation.busy||reloading} onClick={async()=>{if(await operation.run('device.authorize',{id:d.id,device_type:deviceTypes[d.id]||d.device_type})){setNotice('裝置授權已儲存。');await workspace.refresh();await onChanged();}}}>儲存裝置授權</button>{d.authorized_at&&!d.revoked_at&&<button type="button" className="text-button" disabled={operation.busy||reloading} onClick={async()=>{if(await operation.run('device.revoke',{id:d.id})){setNotice('裝置授權已撤銷。');await workspace.refresh();await onChanged();}}}>撤銷授權</button>}</div>}</section>)}</>}
 {page==='reminders'&&<><div className="module-chip-list">{['盤點','進貨','商品','供應商','效期','廢棄','交接','異常'].map(t=><span key={t}>{t}</span>)}</div>{store.has_erp?<>{checkbox('erp_receiving','進貨 ERP 驗收提醒')}{checkbox('erp_waste','廢棄 ERP 輸入提醒')}<label>廢棄提醒時間<input type="time" value={String(draft.erp_time)} disabled={!canEdit||reloading} onChange={e=>setDraft({...draft,erp_time:e.target.value})}/></label></>:<p>門市的效期與異常會出現在待辦，完成後停止提醒。</p>}<button type="button" className="text-button" onClick={()=>onNavigate('notifications')}>查看目前通知 ›</button></>}
 {page==='count-policy'&&<><p>員工盲盤：只顯示本次數量。</p>{store.business_type==='CHAIN_RESTAURANT'&&checkbox('paper_required','需要紙本謄寫')}<label>盤點方式<select disabled={!canEdit||reloading} value={String(draft.count_cadence)} onChange={e=>setDraft({...draft,count_cadence:e.target.value})}><option value="DAILY">每日</option><option value="MONTHLY">每月</option><option value="MANUAL">需要時開始</option></select></label>{canEdit&&<button type="button" className="text-button" onClick={()=>onNavigate('manual')}>區域與品項設定 ›</button>}</>}
 </section>{canEdit&&!(page==='reminders'&&!store.has_erp)&&<button className="shell-primary full" disabled={operation.busy||reloading}>{operation.busy?'儲存中…':'儲存設定'}</button>}{!canEdit&&<p className="shell-note">此設定由商家管理者管理。</p>}</form>}
 {page==='new-store'&&<form onSubmit={async e=>{e.preventDefault();const result=await operation.run('store.create',{name:String(draft.name||'').trim()});if(result){setPage('home');setNotice('門市已建立，已套用預設設定。');await onChanged();await workspace.refresh();}}}><section className="shell-card transfer-form"><label>門市名稱<input disabled={reloading} value={String(draft.name||'')} maxLength={160} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label></section><button className="shell-primary full" disabled={operation.busy||reloading}>{operation.busy?'建立中…':'建立門市'}</button></form>}
 </>}{page==='home'&&!business&&accountContent}</>;
}
