'use client';
import StoreArchive from './store-archive';
import StoreLifecycleConfirm,{type ManagedStore} from './store-lifecycle-confirm';
import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {deviceId} from '@/lib/login-device';
import {supabase} from '@/lib/supabase-browser';
import {isDemoPath} from '@/lib/demo-client.mjs';
import {canManageStores,type AppStore} from '@/lib/app-workspace';
import {BAIHUAYUAN_NAME,isBaihuayuanStoreName} from '@/lib/baihuayuan';
import {useOperation,useWorkspace} from './operation-hooks';
import type {ShellView} from './app-shell';
type Organization={id:string;name:string;business_type:string;store_mode:string;has_erp:boolean;updated_at:string};
type StoreSettings=ManagedStore;
type Device={id:string;label:string;device_type:string;authorized_at:string|null;revoked_at:string|null;last_seen_at:string};
type SettingsData={devices?:Device[];organization?:Organization;stores?:StoreSettings[];settings?:Record<string,unknown>;editable?:boolean;revision?:number};
export default function BusinessSettings({returnLabel="返回上一頁",store,userId,section,initialPage='home',onManageStore,onBack,onNavigate,onChanged,accountContent}:{store:AppStore;stores:AppStore[];initialPage?:'home'|'store-home';onManageStore:(id:string)=>Promise<void>;userId:string;section:'business'|'preferences';returnLabel?:string;onBack:()=>void;onNavigate:(view:ShellView)=>void;onChanged:()=>Promise<void>;accountContent?:ReactNode}){
 const business=section==='business';const workspace=useWorkspace<SettingsData>(store.id,business?'business':'settings');const operation=useOperation(store.id,userId);
 const[currentDevice]=useState(()=>{try{return isDemoPath(window.location.pathname)?'demo-device':deviceId();}catch{return '';}});const[deviceTypes,setDeviceTypes]=useState<Record<string,string>>({});const[page,setPage]=useState<string>(initialPage);const[notice,setNotice]=useState('');const org=workspace.data?.organization;const managedStores=(workspace.data?.stores||[]).filter(s=>isBaihuayuanStoreName(s.name));const activeStores=managedStores.filter(s=>s.is_active);const inactiveStores=managedStores.filter(s=>!s.is_active);
 const [lifecycle,setLifecycle]=useState<{target:ManagedStore;action:'store.delete'|'store.deactivate'|'store.restore'}>();const[archiveTarget,setArchiveTarget]=useState<string>();
 const [draft,setDraft]=useState<Record<string,string|boolean|number>>({});const[draftRevision,setDraftRevision]=useState(0);
 const[reloading,setReloading]=useState(false);const recoverySequence=useRef(0);const recoveryIdentity=useRef('');
 const editIdentity=`${store.id}:${section}:${page}:${draft.id||''}`;
 useLayoutEffect(()=>{recoveryIdentity.current=editIdentity;},[editIdentity]);
 useEffect(()=>()=>{recoverySequence.current++;},[]);
 const open=(next:string,latest=workspace.data)=>{const latestOrg=latest?.organization;const latestStore=latest?.stores?.find(item=>item.id===store.id);const settings=latest?.settings||{};operation.setError('');setNotice('');if(next==='business'&&latestOrg)setDraft({...latestOrg,name:BAIHUAYUAN_NAME,business_type:'SINGLE_RESTAURANT',store_mode:'MULTI',has_erp:false});else if(next==='store'&&latestStore)setDraft({...latestStore});else setDraft({remember_device:settings.remember_device!==false,reauth_days:Number(settings.reauth_days??7),count_cadence:String(settings.count_cadence||'MONTHLY'),blind_count:true} as Record<string,string|boolean|number>);setDraftRevision(latest?.revision||0);setPage(next);};
 const reloadDraft=async()=>{
  const request=++recoverySequence.current;const identity=recoveryIdentity.current;const id=draft.id;
  setReloading(true);
  try{
   const latest=await workspace.refresh();
   if(request!==recoverySequence.current||identity!==recoveryIdentity.current||!latest)return;
   operation.setError('');
   if((page==='store'&&!latest.stores?.some(item=>item.id===id))||(page==='business'&&latest.organization?.id!==id)){
    setDraft({});setPage('home');setNotice('此筆資料已不在目前可管理的清單，已返回設定。');return;
   }
   if(page==='device')setDeviceTypes({});
   open(page,latest);setNotice('已重新載入最新設定，未儲存的修改已捨棄。');
  }finally{if(request===recoverySequence.current)setReloading(false);}
 };
 const save=async()=>{const action=page==='business'?'business.save':page==='store'?'store.save':'settings.save';const payload=action==='business.save'?{...draft,name:BAIHUAYUAN_NAME,business_type:'SINGLE_RESTAURANT',store_mode:'MULTI',has_erp:false}:action==='settings.save'?{revision:draftRevision,settings:draft}:draft;const result=await operation.run(action,payload);if(result){setNotice('設定已儲存。');setPage(business?'store-home':'home');await workspace.refresh();await onChanged();}};
 const canEdit=business?canManageStores(store):!!workspace.data?.editable;
 const saveStoreCode=async()=>{if(page!=='store')return;const code=String(draft.store_code||'').trim();if(!/^\d{4}$/.test(code)){operation.setError('門市代號請輸入 4 位數字。');return;}const {data,error}=await supabase.rpc('update_store_login_code',{p_store_id:store.id,p_store_code:code,p_updated_at:String(draft.updated_at||'')});if(error){operation.setError(error.message.includes('STORE_CODE_ALREADY_EXISTS')?'此門市代號已被使用。':error.message.includes('STORE_CODE_4_DIGITS_REQUIRED')?'門市代號請輸入 4 位數字。':'門市代號更新失敗，請重試。');return;}if(data){setNotice('門市代號已更新。');await workspace.refresh();await onChanged();}};
 const checkbox=(key:string,label:string)=><label className="checkbox-row"><input type="checkbox" checked={draft[key]===true} disabled={!canEdit||reloading} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>{label}</label>;
 if(archiveTarget)return <StoreArchive storeId={archiveTarget} baseStore={store} userId={userId} onBack={()=>setArchiveTarget(undefined)}/>;
 return <><button className="shell-back" disabled={reloading} onClick={()=>page==='home'?onBack():setPage(page==='store-home'||page==='new-store'?'home':business?'store-home':'home')}>‹ {page==='home'?returnLabel:business?'返回設定':'返回個人設定'}</button><h1>{business?'門市設定':'個人設定'}</h1>{business&&page==='home'&&<p className="shell-note">管理各門市的基本資料與營運設定。</p>}{notice&&<p role="status">{notice}</p>}{(operation.error||workspace.error)&&<p className="pilot-message" role="alert">{operation.error||workspace.error}<button type="button" disabled={reloading||operation.busy} onClick={()=>void (!['home','store-home','new-store'].includes(page)?reloadDraft():workspace.refresh())}>{reloading?'正在重新載入…':!['home','store-home','new-store'].includes(page)?'重新載入設定（捨棄未存變更）':'重新讀取'}</button></p>}
 {workspace.loading&&!workspace.data?<p>正在讀取設定…</p>:<>
 {page==='home'&&business&&<>{lifecycle?<StoreLifecycleConfirm anchorId={store.id} userId={userId} target={lifecycle.target} action={lifecycle.action} onCancel={()=>setLifecycle(undefined)} onSaved={async()=>{setLifecycle(undefined);setNotice(lifecycle.action==='store.delete'?'門市已刪除。':'門市狀態已更新。');await onChanged();await workspace.refresh();}}/>:<div className="store-card-grid"><h2>營業中門市（{activeStores.length}）</h2>{activeStores.map(s=><section className="shell-card business-setting-card" key={s.id}><header><div><strong>{s.name}</strong><small>門市代碼：{s.store_code}</small></div><button className="text-button" aria-label={`管理 ${s.name}`} onClick={()=>{if(s.id===store.id)setPage('store-home');else void onManageStore(s.id);}}>管理</button><details className="store-lifecycle-menu"><summary aria-label={`${s.name} ${s.store_code} 更多操作`}>⋯</summary><button className="text-button" onClick={()=>setLifecycle({target:s,action:'store.deactivate'})}>停用門市</button></details></header></section>)}{inactiveStores.length>0&&<section className="shell-section"><h2>已停用門市（{inactiveStores.length}）</h2><div className="shell-card shell-list">{inactiveStores.map(s=><div className="shell-list-row" key={s.id}><button type="button" className="text-button" onClick={()=>setArchiveTarget(s.id)}><span><strong>{s.name}</strong><small>門市代號：{s.store_code}{s.can_delete?'・可刪除':'・有歷史資料'}</small></span></button>{s.can_delete?<button type="button" className="shell-secondary" onClick={()=>setLifecycle({target:s,action:'store.delete'})}>刪除</button>:<small>僅可保留／查看歷史</small>}</div>)}</div><p className="shell-note">沒有作業紀錄的停用門市可直接刪除；有歷史資料的門市會保留，避免盤點、進貨、調撥或廢棄紀錄被破壞。</p></section>}{store.is_active!==false&&<button className="shell-card shell-secondary full add-store-card" onClick={()=>{setDraft({name:''});setPage('new-store');}}>＋新增門市</button>}</div>}</>}

 {page==='store-home'&&business&&<><h2>{store.name}</h2><div className="shell-card shell-list"><button className="shell-list-row" onClick={()=>open('store')}><span><strong>基本資料</strong><small>{store.store_code}・{store.staff_login_mode==='EMPLOYEE_NUMBER'?'員工編號':'姓名／暱稱'}</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>open('reminders')}><span><strong>使用功能與提醒</strong><small>盤點、進貨、效期、廢棄及既有作業功能</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>open('count-policy')}><span><strong>作業設定</strong><small>盤點方式與紙本謄寫</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>onNavigate('members')}><span><strong>員工與權限</strong></span><b>›</b></button>{(store.role==='OWNER'||store.is_business_responsible)&&<button className="shell-list-row" onClick={()=>open('business')}><span><strong>商家基本資料</strong><small>{org?.name}・企業內共用</small></span><b>›</b></button>}</div></>}
 {page==='home'&&!business&&<div className="shell-card shell-list"><button className="shell-list-row" onClick={()=>open('device')}><span><strong>登入與裝置</strong><small>個人／共用裝置與重新驗證</small></span><b>›</b></button></div>}
 {page!=='home'&&page!=='store-home'&&page!=='new-store'&&<form onSubmit={e=>{e.preventDefault();void save();}}><section className="shell-card transfer-form">
 {page==='business'&&<><label>公司名稱<input disabled value={BAIHUAYUAN_NAME}/></label><p className="shell-note">百花猿固定使用獨立餐廳、多門市、無 ERP 的營運邏輯；BeApe／Gras 共用公司層資料。</p></>}
 {page==='store'&&<><label>門市名稱<input disabled={reloading} value={String(draft.name||'')} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><label>門市代號<input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} disabled={!canEdit||reloading} value={String(draft.store_code||'')} onChange={e=>setDraft({...draft,store_code:e.target.value.replace(/\D/g,'').slice(0,4)})} required/></label><p className="shell-note">門市代號固定 4 位數，供員工與主管現場登入使用。</p><button type="button" className="shell-secondary full" disabled={!canEdit||reloading||operation.busy||!/^\d{4}$/.test(String(draft.store_code||''))} onClick={()=>void saveStoreCode()}>儲存門市代號</button><label>員工識別<select disabled={reloading} value={String(draft.staff_login_mode||'')} onChange={e=>setDraft({...draft,staff_login_mode:e.target.value})}><option value="NAME_OR_NICKNAME">姓名／暱稱</option><option value="EMPLOYEE_NUMBER">員工編號</option></select></label></>}
 {page==='device'&&<>{checkbox('remember_device','允許記住裝置')}<label>舊版裝置驗證期限<select disabled={!canEdit||reloading} value={String(draft.reauth_days)} onChange={e=>setDraft({...draft,reauth_days:Number(e.target.value)})}><option value="0">每次</option><option value="1">1 天</option><option value="7">7 天</option><option value="30">30 天</option></select></label><p className="shell-note">主管授權後，新版登入可選擇個人裝置（未使用 30 天重新驗證）或共用裝置（閒置 15 分鐘鎖定）。選「每次」或關閉記住裝置將停用個人裝置保留；下方可撤銷任何裝置。</p>{(workspace.data?.devices||[]).map(d=><section className="device-authorization" key={d.id}><strong>{d.label}{d.id===currentDevice?'（此裝置）':''}</strong><small>{d.revoked_at?'已撤銷':d.authorized_at?'主管已授權':'依登入時選擇'}・最近使用 {new Date(d.last_seen_at).toLocaleString('zh-TW')}</small><label>裝置類型<select aria-label={`${d.label}${d.id===currentDevice?'（此裝置）':''}裝置類型`} disabled={!canEdit||reloading} value={deviceTypes[d.id]||d.device_type} onChange={e=>setDeviceTypes(v=>({...v,[d.id]:e.target.value}))}><option value="PERSONAL">個人</option><option value="SHARED">店內共用</option></select></label>{canEdit&&<div className="shell-button-stack"><button type="button" className="shell-secondary" disabled={operation.busy||reloading} onClick={async()=>{if(await operation.run('device.authorize',{id:d.id,device_type:deviceTypes[d.id]||d.device_type})){setNotice('裝置授權已儲存。');await workspace.refresh();await onChanged();}}}>儲存裝置授權</button>{!d.revoked_at&&<button type="button" className="text-button" disabled={operation.busy||reloading} onClick={async()=>{if(await operation.run('device.revoke',{id:d.id})){setNotice('裝置授權已撤銷。');await workspace.refresh();await onChanged();}}}>撤銷授權</button>}</div>}</section>)}</>}
 {page==='reminders'&&<><div className="module-chip-list">{['盤點','進貨','跨店調撥／借貸','廢棄'].map(t=><span key={t}>{t}</span>)}</div><p>百花猿目前先以四項核心營運流程上線測試；異常與提醒只在需要處理時出現。</p><button type="button" className="text-button" onClick={()=>onNavigate('notifications')}>查看目前通知 ›</button></>}
 {page==='count-policy'&&<><p>員工與主管皆使用盲盤；只顯示本次要輸入的數量。</p><label>盤點方式<select disabled={!canEdit||reloading} value={String(draft.count_cadence)} onChange={e=>setDraft({...draft,count_cadence:e.target.value})}><option value="DAILY">每日</option><option value="MONTHLY">每月</option><option value="MANUAL">需要時開始</option></select></label>{canEdit&&<button type="button" className="text-button" onClick={()=>onNavigate('manual')}>區域與品項設定 ›</button>}</>}
 </section>{canEdit&&page!=='reminders'&&<button className="shell-primary full" disabled={operation.busy||reloading}>{operation.busy?'儲存中…':'儲存設定'}</button>}{!canEdit&&<p className="shell-note">此設定由商家管理者管理。</p>}</form>}
 {page==='new-store'&&<form onSubmit={async e=>{e.preventDefault();const name=String(draft.name||'').trim();if(!isBaihuayuanStoreName(name)){setNotice('百花猿目前只建立 BeApe 或 Gras 門市。');return;}const result=await operation.run('store.create',{name});if(result){setPage('home');setNotice('門市已建立，已套用百花猿預設設定。');await onChanged();await workspace.refresh();}}}><section className="shell-card transfer-form"><label>門市名稱<select disabled={reloading} value={String(draft.name||'')} onChange={e=>setDraft({...draft,name:e.target.value})} required><option value="">選擇門市</option><option value="BeApe">BeApe</option><option value="Gras">Gras</option></select></label><p className="shell-note">建立後可在「基本資料」把系統暫時產生的代號改成自訂 4 位數門市代號。</p></section><button className="shell-primary full" disabled={operation.busy||reloading}>{operation.busy?'建立中…':'建立門市'}</button></form>}
 </>}{page==='home'&&!business&&accountContent}</>;
}
