'use client';
import {useState} from 'react';
import type {AppStore} from '@/lib/app-workspace';
import {useOperation,useOperationDraft,useWorkspace} from './operation-hooks';
import InventoryCatalog from './inventory-catalog';
import ImportHistory from './import-history';
import ProductMapping from './product-mapping';

type Product={id:string;name:string;product_code:string|null;category:string|null;base_unit:string;specification:string|null;current_supplier_id:string|null;is_active:boolean;updated_at:string;aliases:string[];safety_quantity:number|null;note:string|null;supplier_name:string|null};
type Supplier={id:string;name:string;supplier_code:string;contact_name:string|null;phone:string|null;delivery_note:string|null;is_active:boolean;updated_at:string};
type Data={editable:boolean;products?:Product[];suppliers?:Supplier[]};
type Draft={id:string;name:string;code:string;category:string;unit:string;specification:string;supplier_id:string;aliases:string;safety_quantity:string;note:string;contact_name:string;phone:string;delivery_note:string;is_active:boolean;updated_at:string};
const empty:Draft={id:'',name:'',code:'',category:'',unit:'',specification:'',supplier_id:'',aliases:'',safety_quantity:'',note:'',contact_name:'',phone:'',delivery_note:'',is_active:true,updated_at:''};
export default function CatalogWorkspace({store,userId,section,onBack,onImport,onReceiving,onReceipt}:{store:AppStore;userId:string;section:'catalog'|'suppliers';onBack:()=>void;onImport:()=>void;onReceiving:()=>void;onReceipt:(id:string)=>void}){
 const workspace=useWorkspace<Data>(store.id,section);const suppliers=useWorkspace<Data>(store.id,'suppliers');const operation=useOperation(store.id,userId);
 const[page,setPage]=useState<'home'|'list'|'edit'|'source'|'mapping'>('home');const[search,setSearch]=useState('');const[draft,setDraft,clearDraft]=useOperationDraft<Draft>(userId,store.id,`catalog:${section}`,empty);const[notice,setNotice]=useState('');
 const product=section==='catalog';const editable=!!workspace.data?.editable;
 const openProduct=(p:Product)=>{setDraft({...empty,id:p.id,name:p.name,code:/^P-[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(p.product_code||'')?'':p.product_code||'',category:p.category||'',unit:p.base_unit,specification:p.specification||'',supplier_id:p.current_supplier_id||'',aliases:p.aliases.join('、'),safety_quantity:p.safety_quantity===null?'':String(p.safety_quantity),note:p.note||'',is_active:p.is_active,updated_at:p.updated_at});setPage('edit');};
 const openSupplier=(s:Supplier)=>{setDraft({...empty,id:s.id,name:s.name,code:/^S-[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(s.supplier_code||'')?'':s.supplier_code||'',contact_name:s.contact_name||'',phone:s.phone||'',delivery_note:s.delivery_note||'',is_active:s.is_active,updated_at:s.updated_at});setPage('edit');};
 const save=async()=>{const payload={...draft,id:draft.id||null,aliases:draft.aliases.split(/[、,\n]/).map(v=>v.trim()).filter(Boolean),safety_quantity:draft.safety_quantity===''?null:Number(draft.safety_quantity)};
  const result=await operation.run(product?'product.save':'supplier.save',payload);if(result){clearDraft();setNotice('資料已儲存，原始來源與歷史紀錄保留。');setPage('list');await workspace.refresh();}
 };
 const field=(name:keyof Draft,label:string,required=false,type='text')=><label className="field">{label}<input name={name} type={type} required={required} value={String(draft[name])} disabled={!editable} onChange={e=>setDraft({...draft,[name]:e.target.value})} min={type==='number'?0:undefined} step={type==='number'?'any':undefined}/></label>;
 return <><button className="shell-back" onClick={()=>page==='home'?onBack():setPage(page==='edit'?'list':'home')}>‹ {page==='home'?'返回首頁':`返回${product?'商品與編碼':'供應商'}`}</button><h1>{page==='edit'?draft.id?'查看與修改':'新增'+(product?'商品':'供應商'):product?'商品與編碼':'供應商'}</h1>
 {(workspace.error||operation.error)&&<p role="alert" className="pilot-message">{operation.error||workspace.error}<button type="button" onClick={()=>void workspace.refresh()}>重新讀取</button></p>}{notice&&<p role="status">{notice}</p>}
 {workspace.loading&&!workspace.data?<p>正在讀取…</p>:<>
 {page==='home'&&<div className="shell-card shell-list"><button className="shell-list-row" onClick={()=>setPage('list')}><span><strong>{product?'商品主檔':'供應商清單'}</strong><small>{product?'正式名稱、別名、分類與單位':'聯絡與配送資料'}</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>setPage('mapping')}><span><strong>{product?'待對應編碼':'品項對應'}</strong><small>{product?'需要時查看貨單與商品對應':'供應商品名與正式商品'}</small></span><b>›</b></button><button className="shell-list-row" onClick={product?onImport:onReceiving}><span><strong>{product?'Excel 匯入':'到貨紀錄'}</strong><small>{product?'沿用既有匯入與來源保存':'查看進貨原圖與明細'}</small></span><b>›</b></button>{product&&<button className="shell-list-row" onClick={()=>setPage('source')}><span><strong>原始來源與歷史</strong></span><b>›</b></button>}</div>}
 {page==='mapping'&&<ProductMapping store={store} userId={userId} onReceipt={onReceipt}/>}
 {page==='source'&&<><ImportHistory storeId={store.id} refreshKey={0} expanded/><InventoryCatalog storeId={store.id} refreshKey={0} expanded canEdit={false}/></>}
 {page==='list'&&<><label className="field">搜尋<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={product?'品名、編碼或別名':'供應商名稱'}/></label>{editable&&draft.name&&<button className="text-button" onClick={()=>setPage('edit')}>繼續編輯 {draft.name}</button>}{editable&&<button className="shell-secondary full" onClick={()=>{setDraft(empty);setPage('edit');setNotice('');}}>新增{product?'商品':'供應商'}</button>}<div className="shell-card shell-list">{product?workspace.data?.products?.filter(p=>`${p.name} ${p.product_code} ${p.aliases.join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(p=><button className="shell-list-row" key={p.id} onClick={()=>openProduct(p)}><span><strong>{p.name}</strong><small>{p.base_unit}・{p.supplier_name||'未提供供應商'}{p.is_active?'':'・已停用'}</small></span><b>›</b></button>):workspace.data?.suppliers?.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())).map(s=><button className="shell-list-row" key={s.id} onClick={()=>openSupplier(s)}><span><strong>{s.name}</strong><small>{s.contact_name||'未提供聯絡人'}{s.is_active?'':'・已停用'}</small></span><b>›</b></button>)}</div>{!(product?workspace.data?.products?.length:workspace.data?.suppliers?.length)&&<p>目前沒有資料。</p>}{!editable&&<p className="shell-note">目前身分可查看資料；如需修改，請由商家授權的資料維護人員處理。</p>}</>}
 {page==='edit'&&<form onSubmit={e=>{e.preventDefault();void save();}}><section className="shell-card transfer-form">{field('name',product?'正式品名':'供應商名稱',true)}{field('code','商家編碼（選填）')}{product?<>{field('aliases','別名（以頓號分隔）')}{field('category','分類')}{field('unit','單位',true)}{field('specification','規格')}<label className="field">供應商<select disabled={!editable} value={draft.supplier_id} onChange={e=>setDraft({...draft,supplier_id:e.target.value})}><option value="">未提供</option>{suppliers.data?.suppliers?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{field('safety_quantity','安全庫存（選填）',false,'number')}{field('note','備註')}</>:<>{field('contact_name','聯絡人')}{field('phone','電話',false,'tel')}{field('delivery_note','配送資訊')}</>}{draft.id&&<label className="checkbox-row"><input type="checkbox" checked={draft.is_active} disabled={!editable} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/>使用中</label>}</section>{editable&&<button className="shell-primary full" disabled={operation.busy}>{operation.busy?'儲存中…':'儲存'}</button>}</form>}
 </>}</>;
}
