'use client';
import {useCallback,useEffect,useLayoutEffect,useRef,useState} from 'react';
import {useUiState} from './workspace-memory';
import {PRODUCT_CATEGORIES} from '@/lib/product-categories';
import type {AppStore} from '@/lib/app-workspace';
import {useOperation,useOperationDraft,useWorkspace} from './operation-hooks';
import InventoryCatalog from './inventory-catalog';
import ImportHistory from './import-history';
import ProductMapping from './product-mapping';

type Product={primary_category?:string;category_revision?:number;id:string;name:string;product_code:string|null;category:string|null;base_unit:string;specification:string|null;current_supplier_id:string|null;is_active:boolean;updated_at:string;aliases:string[];safety_quantity:number|null;note:string|null;supplier_name:string|null};
type Supplier={id:string;name:string;supplier_code:string;contact_name:string|null;phone:string|null;delivery_note:string|null;is_active:boolean;updated_at:string};
type Data={editable:boolean;lifecycle_allowed?:boolean;products?:Product[];suppliers?:Supplier[]};
type Draft={primary_category:string;category_revision:number;id:string;name:string;code:string;category:string;unit:string;specification:string;supplier_id:string;aliases:string;safety_quantity:string;note:string;contact_name:string;phone:string;delivery_note:string;is_active:boolean;updated_at:string};
const empty:Draft={primary_category:'',category_revision:0,id:'',name:'',code:'',category:'',unit:'',specification:'',supplier_id:'',aliases:'',safety_quantity:'',note:'',contact_name:'',phone:'',delivery_note:'',is_active:true,updated_at:''};
export default function CatalogWorkspace({returnLabel="返回上一頁",store,userId,section,onBack,onImport,onReceiving,onReceipt,initialProductId}:{initialProductId?:string;store:AppStore;userId:string;section:'catalog'|'suppliers';returnLabel?:string;onBack:()=>void;onImport:()=>void;onReceiving:()=>void;onReceipt:(id:string)=>void}){
 const workspace=useWorkspace<Data>(store.id,section);const suppliers=useWorkspace<Data>(store.id,'suppliers');const operation=useOperation(store.id,userId);
 const[page,setPage]=useUiState<'home'|'list'|'edit'|'source'|'mapping'>(`${section}-page`,'home');const[search,setSearch]=useUiState(`${section}-search`,'');const[draft,setDraft,clearDraft]=useOperationDraft<Draft>(userId,store.id,`catalog:${section}`,empty);const[notice,setNotice]=useState('');const[selectedIds,setSelectedIds]=useState<string[]>([]);
 const[reloading,setReloading]=useState(false);const recoverySequence=useRef(0);const recoveryIdentity=useRef('');
 const editIdentity=`${store.id}:${section}:${page}:${draft.id}`;
 useLayoutEffect(()=>{recoveryIdentity.current=editIdentity;},[editIdentity]);
 useEffect(()=>()=>{recoverySequence.current++;},[]);
 const product=section==='catalog';const editable=!!workspace.data?.editable;const canLifecycle=!!workspace.data?.lifecycle_allowed;
 const openProduct=useCallback((p:Product)=>{setDraft({...empty,id:p.id,name:p.name,code:/^P-[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(p.product_code||'')?'':p.product_code||'',category:p.category||'',primary_category:p.primary_category||'',category_revision:p.category_revision||0,unit:p.base_unit,specification:p.specification||'',supplier_id:p.current_supplier_id||'',aliases:p.aliases.join('、'),safety_quantity:p.safety_quantity===null?'':String(p.safety_quantity),note:p.note||'',is_active:p.is_active,updated_at:p.updated_at});setPage('edit');},[setDraft,setPage]);
 const openedProduct=useRef<string|undefined>(undefined);
 useEffect(()=>{if(initialProductId&&workspace.data?.products&&openedProduct.current!==initialProductId){const p=workspace.data.products.find(p=>p.id===initialProductId);if(p){openedProduct.current=initialProductId;openProduct(p);}}},[initialProductId,workspace.data,openProduct]);
 const openSupplier=(s:Supplier)=>{setDraft({...empty,id:s.id,name:s.name,code:/^S-[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(s.supplier_code||'')?'':s.supplier_code||'',contact_name:s.contact_name||'',phone:s.phone||'',delivery_note:s.delivery_note||'',is_active:s.is_active,updated_at:s.updated_at});setPage('edit');};
 const reloadDraft=async()=>{
  const request=++recoverySequence.current;const identity=recoveryIdentity.current;const id=draft.id;
  setReloading(true);
  try{
   const latest=await workspace.refresh();
   if(request!==recoverySequence.current||identity!==recoveryIdentity.current||!latest)return;
   operation.setError('');
   if(product){const row=latest.products?.find(item=>item.id===id);if(row){openProduct(row);setNotice('已重新載入最新資料，未儲存的修改已捨棄。');return;}}
   else {const row=latest.suppliers?.find(item=>item.id===id);if(row){openSupplier(row);setNotice('已重新載入最新資料，未儲存的修改已捨棄。');return;}}
   clearDraft();setPage('list');setNotice('此筆資料已不在目前清單，已返回清單。');
  }finally{if(request===recoverySequence.current)setReloading(false);}
 };
 const save=async()=>{const {is_active,...productDraft}=draft;const payload={...(product?productDraft:{...productDraft,is_active}),id:draft.id||null,aliases:draft.aliases.split(/[、,\n]/).map(v=>v.trim()).filter(Boolean),safety_quantity:draft.safety_quantity===''?null:Number(draft.safety_quantity)};
  const result=await operation.run(product?'product.save':'supplier.save',payload);if(result){clearDraft();setNotice('資料已儲存，原始來源與歷史紀錄保留。');setPage('list');await workspace.refresh();}
 };
 const lifecycle=async(mode:string,ids=selectedIds)=>{const result=await operation.run<{results:{status:string;reason:string}[]}>('product.lifecycle',{ids,mode});if(result){setSelectedIds([]);setNotice(result.results.map(r=>({DISABLED:'品項已停用；歷史與來源仍保留',RESTORED:'品項已重新啟用',DELETED:'已移除品項'}[r.status]||r.reason||r.status)).join('；'));setPage('list');await workspace.refresh();}};
 const field=(name:keyof Draft,label:string,required=false,type='text')=><label className="field">{label}<input name={name} type={type} required={required} value={String(draft[name])} disabled={!editable||reloading} onChange={e=>setDraft({...draft,[name]:e.target.value})} min={type==='number'?0:undefined} step={type==='number'?'any':undefined}/></label>;
 return <><button className="shell-back" disabled={reloading} onClick={()=>page==='home'||!!initialProductId?onBack():setPage(page==='edit'?'list':'home')}>‹ {page==='home'||!!initialProductId?returnLabel:`返回${product?'品項與編碼':'供應商'}`}</button><h1>{page==='edit'?draft.id?'查看與修改':'新增'+(product?'商品':'供應商'):product?'品項與編碼':'供應商'}</h1>
 {(workspace.error||operation.error)&&<p role="alert" className="pilot-message">{operation.error||workspace.error}<button type="button" disabled={reloading||operation.busy} onClick={()=>void (page==='edit'&&draft.id?reloadDraft():workspace.refresh())}>{reloading?'正在重新載入…':page==='edit'&&draft.id?'重新載入此筆（捨棄未存變更）':'重新讀取'}</button></p>}{notice&&<p role="status">{notice}</p>}
 {workspace.loading&&!workspace.data?<p>正在讀取…</p>:<>
 {page==='home'&&<div className="shell-card shell-list"><button className="shell-list-row" onClick={()=>setPage('list')}><span><strong>{product?'品項清單':'供應商清單'}</strong><small>{product?'正式名稱、別名、分類與單位':'聯絡與配送資料'}</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>setPage('mapping')}><span><strong>{product?'待對應編碼':'品項對應'}</strong><small>{product?'需要時查看貨單與商品對應':'供應商品名與正式商品'}</small></span><b>›</b></button><button className="shell-list-row" onClick={product?onImport:onReceiving}><span><strong>{product?'檔案匯入':'到貨紀錄'}</strong><small>{product?'沿用既有匯入與來源保存':'查看進貨原圖與明細'}</small></span><b>›</b></button>{product&&<button className="shell-list-row" onClick={()=>setPage('source')}><span><strong>原始來源與歷史</strong></span><b>›</b></button>}</div>}
 {page==='mapping'&&<ProductMapping store={store} userId={userId} onReceipt={onReceipt}/>}
 {page==='source'&&<><ImportHistory key={store.id} storeId={store.id} storeName={store.name} refreshKey={0}/><InventoryCatalog storeId={store.id} refreshKey={0} expanded canEdit={false}/></>}
 {page==='list'&&<><label className="field">搜尋<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={product?'品名、編碼或別名':'供應商名稱'}/></label>{editable&&draft.name&&<button className="text-button" onClick={()=>setPage('edit')}>繼續編輯 {draft.name}</button>}{editable&&<button className="shell-secondary full" onClick={()=>{setDraft(empty);setPage('edit');setNotice('');}}>新增{product?'品項':'供應商'}</button>}{canLifecycle&&product&&<details className="setup-panel"><summary>批次停用／重新啟用品項</summary>{workspace.data?.products?.map(p=><label className="checkbox-row" key={p.id}><input type="checkbox" checked={selectedIds.includes(p.id)} onChange={e=>setSelectedIds(e.target.checked?[...selectedIds,p.id]:selectedIds.filter(id=>id!==p.id))}/>{p.name} {p.is_active?'':'（已停用）'}</label>)}<div className="shell-button-stack"><button type="button" className="shell-secondary" disabled={!selectedIds.length||operation.busy} onClick={()=>void lifecycle("DISABLE")}>停用所選</button><button type="button" className="shell-secondary" disabled={!selectedIds.length||operation.busy} onClick={()=>void lifecycle("RESTORE")}>重新啟用所選</button></div><p>停用會暫停此品項的日常使用；同商家共用品項的狀態會一併更新，歷史紀錄保留。</p></details>}<div className="shell-card shell-list">{product?workspace.data?.products?.filter(p=>`${p.name} ${p.product_code} ${p.aliases.join(' ')}`.toLowerCase().includes(search.toLowerCase())).map(p=><button className="shell-list-row" key={p.id} onClick={()=>openProduct(p)}><span><strong>{p.name}</strong><small>{p.base_unit}・{p.supplier_name||'未提供供應商'}{p.is_active?'':'・已停用'}</small></span><b>›</b></button>):workspace.data?.suppliers?.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())).map(s=><button className="shell-list-row" key={s.id} onClick={()=>openSupplier(s)}><span><strong>{s.name}</strong><small>{s.contact_name||'未提供聯絡人'}{s.is_active?'':'・已停用'}</small></span><b>›</b></button>)}</div>{!(product?workspace.data?.products?.length:workspace.data?.suppliers?.length)&&<p>目前沒有資料。</p>}{!editable&&<p className="shell-note">目前身分可查看資料；如需修改，請由商家授權的資料維護人員處理。</p>}</>}
 {page==='edit'&&<form onSubmit={e=>{e.preventDefault();void save();}}><section className="shell-card transfer-form">{field('name',product?'正式品名':'供應商名稱',true)}{field('code','商家編碼（選填）')}{product?<>{field('aliases','別名（以頓號分隔）')}{store.business_type==='CHAIN_RESTAURANT'?field('category','分類'):<label className="field">分類<select aria-label="品項分類" disabled={!editable||reloading||operation.busy} value={draft.primary_category||''} onChange={e=>setDraft({...draft,primary_category:e.target.value})}>{!draft.id&&<option value="">依品名自動分類</option>}{PRODUCT_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label>}{field('unit','單位',true)}{field('specification','規格')}<label className="field">供應商<select disabled={!editable||reloading} value={draft.supplier_id} onChange={e=>setDraft({...draft,supplier_id:e.target.value})}><option value="">未提供</option>{suppliers.data?.suppliers?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{field('safety_quantity','安全庫存（選填）',false,'number')}{field('note','備註')}</>:<>{field('contact_name','聯絡人')}{field('phone','電話',false,'tel')}{field('delivery_note','配送資訊')}</>}{draft.id&&<p className="shell-note">狀態：{draft.is_active?'使用中':'已停用'}</p>}</section>{product&&canLifecycle&&draft.id&&<button type="button" className="shell-secondary" disabled={operation.busy||reloading} onClick={()=>void lifecycle(draft.is_active?"DISABLE":"RESTORE",[draft.id])}>{draft.is_active?"停用此品項":"重新啟用此品項"}</button>}{editable&&<button className="shell-primary full" disabled={operation.busy||reloading}>{operation.busy?'儲存中…':'儲存'}</button>}</form>}
 </>}</>;
}
