'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Plus,RefreshCw,Search,X} from 'lucide-react';
import {supabase} from '@/lib/supabase-browser';
import type {Json} from '@/lib/database.types';
import {custodyError,custodyToday,custodyWarnings,type CustodyAccount,type CustodyKind,type CustodyState} from '@/lib/custody';

type Action='create'|'batch'|'collect'|'settings';
type Form={action:Action;account_id:string;revision:number;product_id:string;party:string;unit:string;quantity:string;label:string;expires_on:string;reference:string;minimum:string;warning_days:string;followup:string;note:string;handler:string;occurred_on:string;lot_id:string;dirty:boolean;request_id:string};
const followups:Record<string,string>={pending:'待聯絡',contacted:'已聯絡',ordered:'已下訂',complete:'補購完成'};
const number=(n:number)=>n.toLocaleString('zh-TW',{maximumFractionDigits:6});
export default function CustodyWorkspace({storeId,kind,registerGuard}:{storeId:string;kind:CustodyKind;registerGuard:(guard:(()=>Promise<boolean>)|null)=>void}) {
 const [data,setData]=useState<CustodyState|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState('');
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('active'),[month,setMonth]=useState(''),[expanded,setExpanded]=useState<string|null>(null),[form,setForm]=useState<Form|null>(null);
 const formRef=useRef<Form|null>(null),working=useRef(false),sequence=useRef(0),submitted=useRef<{action:Action;data:Json}|null>(null);
 const supplier=kind==='supplier',title=supplier?'寄庫':'保留貨',verb=supplier?'領貨':'取貨';
 const askLeave=useCallback(async()=>!working.current&&(!formRef.current?.dirty||window.confirm('內容尚未儲存，確定離開？')),[]);
 useEffect(()=>{registerGuard(askLeave);const unload=(e:BeforeUnloadEvent)=>{if(formRef.current?.dirty||working.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);return()=>{registerGuard(null);window.removeEventListener('beforeunload',unload);};},[askLeave,registerGuard]);
 const fetchState=useCallback(async(action='read',payload:Json={})=>{const result=await supabase.rpc('baihuayuan_custody',{p_store_id:storeId,p_kind:kind,p_action:action,p_data:payload});if(result.error)throw result.error;return result.data as unknown as CustodyState;},[storeId,kind]);
 const read=useCallback(async(quiet=false)=>{
  if(working.current||quiet&&(formRef.current||document.visibilityState!=='visible'))return;
  const token=++sequence.current;
  try{const next=await fetchState();if(token!==sequence.current||quiet&&formRef.current)return;setData(next);setError('');}
  catch(e){if(token===sequence.current)setError(custodyError(e));}finally{if(token===sequence.current)setLoading(false);}
 },[fetchState]);
 useEffect(()=>{const ref=sequence;const initial=setTimeout(()=>void read(),0),timer=setInterval(()=>void read(true),5000);const refresh=()=>void read(true);window.addEventListener('focus',refresh);window.addEventListener('online',refresh);document.addEventListener('visibilitychange',refresh);return()=>{ref.current++;clearTimeout(initial);clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);document.removeEventListener('visibilitychange',refresh);};},[read]);
 const visible=data?.store_id===storeId&&data.kind===kind?data:null;
 const accounts=visible?.accounts||[];
 function open(action:Action,account?:CustodyAccount){sequence.current++;setUncertain(false);submitted.current=null;const next:Form={action,account_id:account?.id||'',revision:account?.revision||0,product_id:account?.product_id||'',party:account?.party||'',unit:account?.unit||'',quantity:'',label:'',expires_on:'',reference:'',minimum:String(account?.minimum??0),warning_days:String(account?.warning_days??30),followup:account?.followup||'pending',note:action==='settings'?account?.note||'':'',handler:'',occurred_on:custodyToday(),lot_id:account?.lots.find(l=>l.remaining>0&&(!l.expires_on||l.expires_on>=custodyToday()))?.id||'',dirty:false,request_id:crypto.randomUUID()};formRef.current=next;setForm(next);setError('');setLoading(false);}
 function change(patch:Partial<Form>){if(!formRef.current||working.current||uncertain)return;submitted.current=null;const next={...formRef.current,...patch,dirty:true,request_id:crypto.randomUUID()};formRef.current=next;setForm(next);}
 async function close(){if(await askLeave()){formRef.current=null;setForm(null);submitted.current=null;setUncertain(false);setError('');void read();}}
 async function reload(){if(!formRef.current||working.current)return;const current=formRef.current;const token=++sequence.current;setLoading(true);try{const next=await fetchState();if(token!==sequence.current)return;setData(next);if(submitted.current&&next.accounts.some(a=>a.events.some(e=>e.id===current.request_id))){formRef.current=null;setForm(null);submitted.current=null;setUncertain(false);setError('');return;}if(uncertain){setError('尚未確認上次儲存結果，請按「確認儲存」重試同一筆操作，避免重複登記。');return;}const account=next.accounts.find(a=>a.id===current.account_id);if(account){change({revision:account.revision});setError('已讀取最新餘量，保留您的輸入；請核對後再儲存。');}else if(current.action==='create'){setError('已讀取最新資料，請先確認是否已建立相同紀錄。');}else setError('找不到這筆紀錄，請關閉後重新選擇。');}catch(e){setError(custodyError(e));}finally{if(token===sequence.current)setLoading(false);}}
 async function save(e:React.FormEvent){e.preventDefault();const f=formRef.current;if(!f||working.current||loading)return;working.current=true;sequence.current++;setBusy(true);setError('');
  const payload=submitted.current||{action:f.action,data:{request_id:f.request_id,account_id:f.account_id||undefined,revision:f.revision,product_id:f.product_id||undefined,party:f.party,unit:f.unit,quantity:f.quantity||undefined,label:f.label,expires_on:f.expires_on||undefined,reference:f.reference,minimum:f.minimum,warning_days:f.warning_days,followup:f.followup,note:f.note,handler:f.handler||undefined,occurred_on:f.occurred_on,lot_id:f.lot_id||undefined}};
  submitted.current=payload;
  try{setData(await fetchState(payload.action,payload.data));formRef.current=null;setForm(null);submitted.current=null;setUncertain(false);}
  catch(err){const code=err&&typeof err==='object'&&'code' in err?String(err.code):'';const ambiguous=!/^[0-9A-Z]{5}$/.test(code);setUncertain(ambiguous);if(!ambiguous)submitted.current=null;setError(ambiguous?'連線中斷，儲存結果尚未確認。請重新讀取或按確認儲存重試同一筆操作。':custodyError(err));}finally{working.current=false;setBusy(false);}
 }
 const filtered=accounts.filter(a=>`${a.name} ${a.party}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())&&(filter==='all'||filter==='active'&&a.remaining>0||filter==='complete'&&a.remaining===0||filter==='attention'&&custodyWarnings(a).length>0));
 const account=form?accounts.find(a=>a.id===form.account_id):undefined;
 const lot=account?.lots.find(l=>l.id===form?.lot_id);
 return <div className="custody-workspace" role="tabpanel" id={`im-panel-${kind}`} aria-label={title}>
  <div className="im-filters"><label className="im-search"><Search size={18}/><input aria-label={`搜尋${title}品項或對象`} placeholder={supplier?'搜尋品項、供應商':'搜尋品項、保留對象'} value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label={`${title}狀態`} value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">{supplier?'尚有寄庫':'待取貨'}</option><option value="all">全部紀錄</option><option value="attention">需要注意</option><option value="complete">已取完</option></select><button className="im-primary" disabled={loading||busy||!visible} onClick={()=>open('create')}><Plus size={17}/>新增{title}</button><button className="cu-outline" aria-label={`重新整理${title}`} disabled={busy||!!form} onClick={()=>void read()}><RefreshCw size={18}/></button></div>
  <p className="cu-caption">{supplier?'供應商保管的已購入貨品，領回後才計入門市現貨。':'已進貨、暫存門市等待指定對象取走；未取部分仍照實盤點。'}</p>
  {error&&!form&&<p className="im-error" role="alert">{error}<button onClick={()=>void read()}>重新載入</button></p>}
  {loading&&!visible?<p className="im-empty" role="status">正在讀取{title}…</p>:!visible?<p className="im-empty">目前無法讀取，請重新載入。</p>:!filtered.length?<div className="im-empty"><h2>{accounts.length?'沒有符合條件的紀錄':`尚未建立${title}`}</h2><p>{accounts.length?'試著切換狀態或調整搜尋。':`從「新增${title}」開始登記品項與數量。`}</p></div>:<div className="cu-list">{filtered.map(a=><article className="cu-account" key={a.id}>
   <header><div><span className={`cu-tag ${supplier?'supplier':'reserved'}`}>{title}</span><h2>{a.name}</h2><p>{supplier?'供應商':'保留對象'}：{a.party}</p></div><div className="cu-balance"><span>{supplier?'寄庫餘量':'尚未取貨'}</span><strong>{number(a.remaining)} <small>{a.unit}</small></strong><span>原始 {number(a.original)}・已{supplier?'領':'取'} {number(a.original-a.remaining)}</span></div></header>
   {custodyWarnings(a).map(w=><p className="cu-alert" key={w}>{w}</p>)}
   {supplier&&<div className="cu-meta"><span>安全水位 {number(a.minimum)} {a.unit}</span><span>到期前 {a.warning_days} 日提醒</span><span>補購：{followups[a.followup]}</span></div>}
   {a.note&&<p className="cu-caption">{a.note}</p>}
   <div className="im-table-wrap"><table><thead><tr><th>批次</th><th>原始數量</th><th>剩餘數量</th><th>效期</th><th>原採購／單據</th></tr></thead><tbody>{a.lots.filter(l=>l.remaining>0||expanded===a.id||a.remaining===0).map(l=><tr key={l.id}><td>{l.label}</td><td>{number(l.quantity)} {a.unit}</td><td><strong>{number(l.remaining)} {a.unit}</strong></td><td>{l.expires_on||'未設定'}</td><td>{l.reference||'—'}</td></tr>)}</tbody></table></div>
   <footer><button className="cu-outline" aria-expanded={expanded===a.id} onClick={()=>setExpanded(expanded===a.id?null:a.id)}>{expanded===a.id?'收起紀錄':`${verb}紀錄`}</button><div><button className="cu-outline" onClick={()=>open('settings',a)}>{supplier?'提醒與備註':'編輯備註'}</button><button className="cu-outline" onClick={()=>open('batch',a)}>新增批次</button><button className="im-primary" disabled={a.remaining===0} onClick={()=>open('collect',a)}>登記{verb}</button></div></footer>
   {expanded===a.id&&<div className="cu-history"><label>紀錄月份 <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{month&&<button className="cu-outline" onClick={()=>setMonth('')}>全部月份</button>}<p className="cu-caption">月份只篩選紀錄，餘量跨月持續保留。</p><ul>{a.events.filter(e=>!month||e.occurred_on.startsWith(month)).map(e=><li key={e.id}><strong>{e.occurred_on}　{e.action==='collect'?verb:e.action==='settings'?'更新設定':e.action==='create'?'建立紀錄':'新增批次'}{e.quantity!==null&&` ${number(e.quantity)} ${a.unit}`}</strong><span>經手：{e.handler}・登記：{e.actor}</span>{e.lot_id&&<span>批次：{a.lots.find(l=>l.id===e.lot_id)?.label||'—'}</span>}{e.note&&<span>{e.note}</span>}<small>登記時間 {new Date(e.created_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false})}</small></li>)}</ul>{!a.events.some(e=>!month||e.occurred_on.startsWith(month))&&<p>這個月份沒有紀錄。</p>}</div>}
  </article>)}</div>}
  {form&&<div className="im-modal-backdrop"><form className="im-modal cu-form" role="dialog" aria-modal="true" aria-labelledby="cu-form-title" onSubmit={e=>void save(e)} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();void close();}if(e.key==='Tab'){const fields=e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)');const first=fields[0],last=fields[fields.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
   <header><h2 id="cu-form-title">{form.action==='create'?`新增${title}`:form.action==='batch'?'新增批次':form.action==='collect'?`登記${verb}`:'提醒與備註'}</h2><button type="button" disabled={busy} aria-label="關閉" onClick={()=>void close()}><X/></button></header>
   <fieldset disabled={busy||uncertain}><legend className="cu-sr">{title}資料</legend>
    {form.action==='create'?<><label>品項<select autoFocus required value={form.product_id} onChange={e=>{const product=visible?.products.find(p=>p.id===e.target.value);change({product_id:e.target.value,unit:product?.unit||'',party:supplier?product?.supplier||'':form.party});}}><option value="">選擇門市品項</option>{visible?.products.map(p=><option key={p.id} value={p.id}>{p.name}（{p.unit}）</option>)}</select></label><div className="cu-fields"><label>{supplier?'供應商':'保留對象'}<input required maxLength={120} value={form.party} onChange={e=>change({party:e.target.value})}/></label><label>單位<input required maxLength={30} value={form.unit} onChange={e=>change({unit:e.target.value})}/></label></div></>:<h3>{account?.name} · {account?.party}</h3>}
    {(form.action==='create'||form.action==='batch')&&<><label>批次名稱<input autoFocus={form.action==='batch'} required maxLength={120} placeholder="例如：9 月購入" value={form.label} onChange={e=>change({label:e.target.value})}/></label><div className="cu-fields"><label>數量（{form.unit||'請選單位'}）<input required type="number" min="0.000001" max="999999999" step="any" value={form.quantity} onChange={e=>change({quantity:e.target.value})}/></label><label>效期{!supplier&&'（選填）'}<input required={supplier} type="date" min="2000-01-01" max="2200-12-31" value={form.expires_on} onChange={e=>change({expires_on:e.target.value})}/></label></div><label>原採購／單據編號（選填）<input maxLength={200} value={form.reference} onChange={e=>change({reference:e.target.value})}/></label><p className="cu-caption">{supplier?'登記已購入、目前仍在供應商的數量。':'登記已在門市的待取數量，不會再次增加現貨。'}</p></>}
    {form.action==='collect'&&<><label>領取批次<select autoFocus required value={form.lot_id} onChange={e=>change({lot_id:e.target.value})}><option value="">選擇批次</option>{account?.lots.filter(l=>l.remaining>0).map(l=><option key={l.id} value={l.id} disabled={!!l.expires_on&&l.expires_on<custodyToday()}>{l.label}・剩餘 {number(l.remaining)} {form.unit}{l.expires_on?`・${l.expires_on}`:''}</option>)}</select></label><p className="cu-caption">依效期排序，建議優先領取較早到期批次。{supplier?'領到目前所選門市。':'取走後扣除門市現貨及未取數量。'}</p><label>本次{verb}數量（{form.unit}）<input required type="number" min="0.000001" max={lot?.remaining??0} step="any" value={form.quantity} onChange={e=>change({quantity:e.target.value})}/></label></>}
    {supplier&&(form.action==='create'||form.action==='settings')&&<><div className="cu-fields"><label>安全水位（{form.unit||'單位'}）<input type="number" required min="0" max="999999999" step="any" value={form.minimum} onChange={e=>change({minimum:e.target.value})}/></label><label>到期前幾日提醒<input type="number" required min="1" max="365" value={form.warning_days} onChange={e=>change({warning_days:e.target.value})}/></label></div>{form.action==='settings'&&<label>補購進度<select value={form.followup} onChange={e=>change({followup:e.target.value})}>{Object.entries(followups).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}</>}
    {form.action!=='settings'&&<div className="cu-fields"><label>{form.action==='collect'?verb:'登記'}日期<input type="date" required min="2000-01-01" max={custodyToday()} value={form.occurred_on} onChange={e=>change({occurred_on:e.target.value})}/></label><label>經手人<input required maxLength={120} value={form.handler} onChange={e=>change({handler:e.target.value})}/></label></div>}
    <label>備註（選填）<textarea maxLength={2000} value={form.note} onChange={e=>change({note:e.target.value})}/></label>
   </fieldset>{error&&<p role="alert" className="im-error">{error}</p>}<footer><button type="button" disabled={busy||loading} onClick={()=>void reload()}>重新讀取最新資料</button><button type="submit" className="im-primary" disabled={busy||loading||form.action!=='create'&&!account}>{busy?'儲存中…':'確認儲存'}</button></footer>
  </form></div>}
 </div>;
}
