'use client';
import {useEffect,useRef,useState} from 'react';
import {ingredientSourceLabel,ingredientPurchase,ingredientSaveData,formatPurchaseSpecification,usesPackageSpecification} from '@/lib/ingredient-catalog';
import {baselineName,baselineGroups,baselineSources,baselinePurchaseDate,emptyPriceSheet,isIngredientStopped,priceCandidate,priceSearch,priceEdit,candidatePurchase,supplierOptions,type PriceSheetData,type PriceIngredient,type SupplyState,type PriceSheetEdit} from '@/lib/ingredient-price-sheet';
import './ingredient-price-sheet.css';
type Props={cloudDraft?:{read:()=>Promise<{token:string;edits:Record<string,PriceSheetEdit>}|null>;save:(edits:Record<string,PriceSheetEdit>,expected:string|null,token:string)=>Promise<{token:string}>};data:PriceSheetData;loaded:boolean;failed:boolean;canExport:boolean;draftKey:string;save:(action:string,data:Record<string,unknown>,requestId:string)=>Promise<void>;registerLeave?:(handler:(()=>Promise<boolean>)|null)=>void};
const money=(v:number|null|undefined)=>v==null?'待補':`$${v.toLocaleString('zh-TW',{maximumFractionDigits:6})}`;
const date=(v?:string)=>v?new Date(v).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}):'—';
const units=['待補單位','g','公斤','台斤','ml','L','包','盒','瓶','罐','箱','顆','片','卷','份','隻','條','塊'];
const reasons=['價格偏高','品質不佳','規格不符','交貨不穩','停止供貨','菜單停用','其他'];
export default function IngredientPriceSheet({data=emptyPriceSheet,loaded,failed,canExport,draftKey,save,registerLeave,cloudDraft}:Props){
 const [tab,setTab]=useState('purchase'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<string[]>([]);
 const [edits,setEdits]=useState<Record<string,PriceSheetEdit>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [alias,setAlias]=useState<string|null>(null),[sources,setSources]=useState<string|null>(null),[priceHistory,setPriceHistory]=useState<string|null>(null),[history,setHistory]=useState<{id:string;key?:string}|null>(null);
 const [decision,setDecision]=useState<{row:PriceIngredient;key:string;restore:boolean;reason:string;disposition:string;note:string;revision:number;requestId:string}|null>(null);
 const [expanded,setExpanded]=useState<string[]>([]);
 const [aliasTarget,setAliasTarget]=useState<Record<string,string>>({});
 const [recovery,setRecovery]=useState<Record<string,PriceSheetEdit>|null>(null);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const timer=setTimeout(()=>{try{const value=JSON.parse(localStorage.getItem(draftKey)||'null');if(value&&Object.keys(value).length)setRecovery(value);}catch{/* No cloud values are replaced by malformed drafts. */}},0);return()=>clearTimeout(timer);},[draftKey]);
 const editRef=useRef(edits);
 const cloudToken=useRef<string|null>(null),cloudReady=useRef(false);
 useEffect(()=>{if(!cloudDraft)return;let active=true;void cloudDraft.read().then(value=>{if(!active)return;cloudToken.current=value?.token||null;cloudReady.current=true;if(value&&Object.keys(value.edits).length){if(!Object.keys(editRef.current).length)setRecovery(local=>local||value.edits);setMessage('系統有已保存草稿，可恢復後接續。');}}).catch(()=>{if(active)setMessage('系統草稿讀取失敗，本機修改仍保留，請重新同步後重試。');});return()=>{active=false;};},[cloudDraft]);
 async function persistCloud(next:Record<string,PriceSheetEdit>){if(!cloudDraft)return;if(!cloudReady.current)throw Error('系統草稿尚未讀取，請重新同步。');const saved=await cloudDraft.save(next,cloudToken.current,crypto.randomUUID());cloudToken.current=saved.token;}
 async function discardEdits(){if(!window.confirm('捨棄尚未儲存的修改及已保存草稿？'))return;setBusy(true);setError('');try{await persistCloud({});setRecovery(null);updateEdits({});}catch{setError('草稿清除失敗，修改仍保留，請重試。');}finally{setBusy(false);}}
 async function keepCloud(){setBusy(true);setError('');try{await persistCloud(edits);setMessage('草稿已保存至系統，同帳號換裝置可接續；尚未更新正式價格。');}catch(e){setError(String(e&&typeof e==='object'&&'message' in e?e.message:e).includes('DRAFT_CHANGED')?'其他裝置已更新草稿，本頁輸入保留，請重新同步後核對。':'草稿保存失敗，輸入保留，請重試。');}finally{setBusy(false);}}

 useEffect(()=>{const keep=()=>{try{localStorage.setItem(draftKey,JSON.stringify(editRef.current));return true;}catch{setError('無法暫存，請先儲存修改。');return false;}};registerLeave?.(async()=>busy?false:keep());const warn=(e:BeforeUnloadEvent)=>{if(Object.keys(editRef.current).length){keep();e.preventDefault();}};window.addEventListener('beforeunload',warn);return()=>{registerLeave?.(null);window.removeEventListener('beforeunload',warn);};},[draftKey,registerLeave,busy]);
 function updateEdits(next:Record<string,PriceSheetEdit>){setEdits(next);editRef.current=next;try{localStorage.setItem(draftKey,JSON.stringify(next));}catch{setError('無法暫存，請先儲存修改。');}}
 function edit(row?:PriceIngredient){const key=row?.id||`new:${crypto.randomUUID()}`;updateEdits({...edits,[key]:{row,draft:priceEdit(row),requestId:crypto.randomUUID()}});}
 function change(key:string,field:string,value:string){const current=edits[key];updateEdits({...edits,[key]:{...current,requestId:crypto.randomUUID(),draft:{...current.draft,[field]:value,...(field==='unit'&&!usesPackageSpecification(value)?{specification:'',content:'',contentUnit:''}:{}),...(['price','unit','content','contentUnit','specification'].includes(field)?{reference:''}:{})}}});}
 const states=data.supply_states||[],events=data.supply_events||[];
 const active=data.ingredients.filter(r=>!isIngredientStopped(r,states));
 const missing=active.filter(r=>r.cost_price===null||r.review_status!=='confirmed');const pending=active.filter(r=>priceCandidate(r,states));
 const groups=baselineGroups(active);
 const purchaseGroups=groups.filter(g=>g.purchase),historyGroups=groups.filter(g=>g.history),reviewGroups=groups.filter(g=>g.rows.length>1||(!g.purchase&&!g.history));
 const filteredGroups=(tab==='purchase'?purchaseGroups:tab==='historical'?historyGroups:tab==='review'?reviewGroups:groups).map(g=>({...g,rows:g.rows.filter(r=>tab==='pending'?pending.includes(r):tab==='missing'?missing.includes(r):tab==='draft'?!!edits[r.id]:true)})).filter(g=>g.rows.length&&g.rows.some(r=>priceSearch(r,search)));
 const removed=states.filter(s=>s.stopped);const rows=filteredGroups.flatMap(g=>g.rows);
 const removedRows=removed.filter(s=>{const r=data.ingredients.find(r=>r.id===s.ingredient_id);return r&&(priceSearch(r,search)||`${s.reason} ${s.note} ${s.supplier_name}`.includes(search));});
 const count=tab==='removed'?removedRows.length:filteredGroups.length, pages=Math.max(1,Math.ceil(count/50)),p=Math.min(page,pages-1);
 const pageGroups=filteredGroups.slice(p*50,p*50+50);
 const visible=pageGroups.flatMap(g=>expanded.includes(g.key)||search.trim()||g.rows.some(r=>edits[r.id])?g.rows:[g.rows[0]]);
 const rowGroups=new Map(pageGroups.flatMap(g=>g.rows.map(r=>[r.id,g] as const)));
 const canWrite=data.can_price&&loaded&&!failed&&!busy;
 async function run(action:string,payload:Record<string,unknown>,requestId=crypto.randomUUID()){setBusy(true);setError('');setMessage('');try{await save(action,payload,requestId);return true;}catch(e){setError(e instanceof Error?e.message:'尚未完成，請重試。');return false;}finally{setBusy(false);}}
 async function saveEdits(){setBusy(true);setError('');const remaining={...edits};let done=0;try{for(const [key,e] of Object.entries(edits)){const payload={...ingredientSaveData(e.draft,e.row),supplier_id:e.draft.supplier_id||null};await save('save',payload,e.requestId);delete remaining[key];updateEdits(remaining);done++;}if(cloudDraft&&cloudReady.current)await persistCloud(remaining);setMessage(`已儲存 ${done} 項，原有交易及鎖定食譜保留。`);}catch(e){setError(`已儲存 ${done} 項；其餘輸入保留。${e instanceof Error?e.message:''}`);}finally{setBusy(false);}}
 function stop(row:PriceIngredient,state?:SupplyState){setDecision({row,key:state?.supplier_key||'*',restore:!!state?.stopped,reason:state?.reason||'價格偏高',disposition:state?.disposition||'可重新詢價',note:'',revision:state?.revision||0,requestId:crypto.randomUUID()});}
 async function submitDecision(){if(!decision)return;const current=states.find(s=>s.ingredient_id===decision.row.id&&s.supplier_key===decision.key);if(decision.restore&&!decision.note.trim()){setError('請簡短記錄恢復採購的原因。');return;}if(await run(decision.restore?'restore':'stop',{id:decision.row.id,revision:decision.row.revision,supplier_key:decision.key,supply_revision:current?.revision||0,reason:decision.reason,disposition:decision.disposition,note:decision.note},decision.requestId)){setDecision(null);setMessage('已保存紀錄；歷次停用與恢復原因均保留。');}}
 async function confirm(row:PriceIngredient,keep=false){const q=priceCandidate(row,states);if(!q)return;const newPrice=candidatePurchase(row,q);if(!keep&&!window.confirm(`${row.name}：改用 ${money(newPrice.amount)}／${newPrice.unit}？新作業立即生效，既有交易及鎖定食譜不變。`))return;await run(keep?'keep':'confirm',{id:row.id,revision:row.revision,reference_id:q.id,expected_price:q.price,effective_date:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}),change_reason:keep?'保留標準進價':'確認貨單新價'});}
 async function exportRows(){try{const x=await import('xlsx');const values=tab==='removed'?removedRows.map(s=>({食材:data.ingredients.find(r=>r.id===s.ingredient_id)?.name,供應商:s.supplier_name,停用原因:s.reason,處理方式:s.disposition,備註:s.note,日期:date(s.updated_at)})):rows.filter(r=>!selected.length||selected.includes(r.id)).map(r=>{const v=priceEdit(r);return {識別碼:r.id,歸組名稱:baselineName(r.name),來源:ingredientSourceLabel(r),來源日期:r.effective_date||'',最近請購:baselinePurchaseDate(r),食材:r.name,別名:r.aliases.map(a=>a.name).join('、'),供應商:r.supplier_name||'',單位:v.unit,價格:v.price,規格:v.specification??formatPurchaseSpecification(v.content,v.contentUnit)};});const book=x.utils.book_new();x.utils.book_append_sheet(book,x.utils.json_to_sheet(values),'食材價格');x.writeFile(book,'食材價格表.xlsx');}catch{setError('匯出失敗，請重試。');}}
 async function importFiles(files:FileList|null){if(!files)return;try{const x=await import('xlsx'),next={...edits};for(const file of Array.from(files)){const book=x.read(await file.arrayBuffer());const items=x.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[book.SheetNames[0]],{defval:''});for(const item of items){const name=String(item['食材']||item['食材名稱']||'').trim();if(!name)continue;const id=String(item['識別碼']||'');const row=id?data.ingredients.find(r=>r.id===id):data.ingredients.find(r=>r.name===name&&priceEdit(r).unit===String(item['單位']||''));if(id&&!row)throw Error('檔案含其他門市或不存在的識別碼。');if(row&&isIngredientStopped(row,states))throw Error(`${name}已移除，請先查看停用紀錄，匯入不會自動恢復。`);const key=row?.id||`import:${name}:${String(item['單位']||'')}`;if(next[key])continue;const supplier=String(item['供應商']||'').trim();const sp=data.suppliers.find(s=>s.name===supplier);if(supplier&&!sp)throw Error(`供應商「${supplier}」尚未建立，請先至供應商管理建立。`);const draft={...priceEdit(row),name,unit:String(item['單位']||row?.unit||'待補單位'),price:String(item['價格']??''),reference:'',supplier_id:sp?.id||'',...(item['規格']!==undefined?{specification:String(item['規格'])}:{}),content:String(item['內容量']||''),contentUnit:String(item['內容單位']||'g')};ingredientSaveData(draft,row);next[key]={row,draft,requestId:crypto.randomUUID()};}}updateEdits(next);setTab('all');setMessage('已匯入編輯列，檢查後按儲存才會寫入。');}catch(e){setError(e instanceof Error?e.message:'無法讀取檔案。');}if(input.current)input.current.value='';}
 function editCells(key:string,e:PriceSheetEdit){return <tr key={key} className="price-edit-row"><td>編輯</td><td><input aria-label="食材名稱" value={e.draft.name} onChange={v=>change(key,'name',v.target.value)}/></td><td title={e.row?.aliases.map(a=>a.name).join('、')}>{e.row?.aliases[0]?.name||'—'}</td><td><select aria-label="供應商" value={e.draft.supplier_id} onChange={v=>change(key,'supplier_id',v.target.value)}><option value="">待補／沿用來源</option>{data.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}{states.some(t=>t.ingredient_id===e.row?.id&&t.supplier_key===`id:${s.id}`&&t.stopped)?' ⚠ 已停用':''}</option>)}</select></td><td><select aria-label="進貨單位" value={e.draft.unit} onChange={v=>change(key,'unit',v.target.value)}>{[...new Set([e.draft.unit,...units])].map(u=><option key={u}>{u}</option>)}</select></td><td><input aria-label="規格" disabled={!usesPackageSpecification(e.draft.unit)} placeholder={usesPackageSpecification(e.draft.unit)?'例如：2公斤（可後補）':'—'} value={e.draft.specification??formatPurchaseSpecification(e.draft.content,e.draft.contentUnit)} onChange={v=>change(key,'specification',v.target.value)}/></td><td><input aria-label="確認價格" type="number" min="0" step="any" placeholder="可後補" value={e.draft.price} onChange={v=>change(key,'price',v.target.value)}/></td><td>—</td><td>—</td><td><input aria-label="生效日期" type="date" max={new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'})} value={e.draft.effective_date||''} onChange={v=>change(key,'effective_date',v.target.value)}/></td><td><select aria-label="調價原因" value={e.draft.change_reason||'供應商調價'} onChange={v=>change(key,'change_reason',v.target.value)}>{['供應商調價','蔬菜／季節價格變動','更換供應商','包裝規格變更','修正原資料','確認標準進價','其他'].map(r=><option key={r}>{r}</option>)}</select></td><td><button onClick={()=>{const next={...edits};delete next[key];updateEdits(next);}}>取消</button></td></tr>;}
 return <section className="ingredient-price-sheet" aria-label="食材價格表"><header><h1>食材價格表</h1><p>先看請購食材，依請購日期由新到舊排列；同名同單位紀錄集中，歷史食譜另存參考。</p></header>
 <div className="price-sheet-toolbar"><input aria-label="搜尋食材、別名、供應商" placeholder="搜尋食材、別名、供應商" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/>
 <div>{tab!=='removed'&&data.can_price&&<><button disabled={!canWrite} onClick={()=>{const next={...edits};for(const r of visible)if(!next[r.id])next[r.id]={row:r,draft:priceEdit(r),requestId:crypto.randomUUID()};updateEdits(next);}}>編輯本頁全部</button><span className="price-toolbar-spacer"/><button disabled={!canWrite} onClick={()=>edit()}>＋ 新增</button><button disabled={!canWrite} onClick={()=>input.current?.click()}>匯入</button><input ref={input} hidden type="file" multiple accept=".xlsx,.xls,.csv" onChange={e=>void importFiles(e.target.files)}/></>}{canExport&&<button disabled={!loaded||failed||busy} onClick={()=>void exportRows()}>匯出</button>}</div></div>
 <nav className="price-sheet-tabs">{[['purchase','請購食材',purchaseGroups.length],['historical','歷史參考',historyGroups.length],['review','待整理',reviewGroups.length],['all','全部',groups.length],['draft','草稿',Object.keys(edits).length],['pending','待確認價差',pending.length],['missing','待補價格',missing.length],['removed','已移除',removed.length]].map(([key,label,n])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(String(key));setPage(0);setSelected([]);}}>{label} <small>{n}</small></button>)}</nav>
 <p className="baseline-summary">{tab==='historical'?'僅有歷史食譜來源，不代表已停用。':tab==='review'?'同名紀錄與尚無請購依據的品項集中核對；不同單位、品牌與規格保持分開。':'請購資料優先顯示；日期未記載的排後面，匯入時間不當作採購日期。'} 同名紀錄可原列展開；價格尚未重新套用。</p>
 {recovery&&<div role="status">有尚未儲存的修改。<button disabled={!canWrite} onClick={()=>{updateEdits(recovery);setRecovery(null);}}>恢復草稿</button><button onClick={()=>void discardEdits()}>捨棄</button></div>}
 {error&&<p role="alert" className="price-sheet-error">{error}</p>}{message&&<p role="status">{message}</p>}
 {!loaded?<p>{failed?'讀取失敗，請重新同步。':'讀取食材價格…'}</p>:<div className="price-sheet-scroll"><table><thead>{tab==='removed'?<tr><th>食材</th><th>供應商／範圍</th><th>最後確認價</th><th>停用原因</th><th>處理方式</th><th>備註</th><th>日期</th><th>操作</th></tr>:<tr><th>選取</th><th>食材名稱</th><th>別名</th><th>供應商</th><th>進貨單位</th><th>規格</th><th>進價</th><th>待確認新價</th><th>價差</th><th>生效日期</th><th>調價原因</th><th>操作</th></tr>}</thead><tbody>
 {tab==='removed'?removedRows.slice(p*50,p*50+50).map(s=>{const row=data.ingredients.find(r=>r.id===s.ingredient_id)!;const ev=events.find(e=>e.ingredient_id===row.id&&e.supplier_key===s.supplier_key&&e.action==='stop');const v=ingredientPurchase(ev?.snapshot||row);return <tr key={`${row.id}:${s.supplier_key}`}><td title={row.name}>{row.name}</td><td title={s.supplier_name}>{s.supplier_name}</td><td>{money(v?.amount??ev?.snapshot.cost_price)}／{v?.unit||row.unit}</td><td>{s.reason}</td><td>{s.disposition}</td><td title={s.note}>{s.note||'—'}</td><td>{date(s.updated_at)}</td><td><button onClick={()=>setHistory({id:row.id,key:s.supplier_key})}>查看紀錄</button>{data.can_price&&<button disabled={!canWrite} onClick={()=>stop(row,s)}>恢復</button>}</td></tr>;}):<>
 {Object.entries(edits).filter(([,e])=>!e.row).map(([key,e])=>editCells(key,e))}
 {visible.map(row=>{if(edits[row.id])return editCells(row.id,edits[row.id]);const group=rowGroups.get(row.id)!;const first=group.rows[0].id===row.id;const aliases=[...new Set(row.aliases.map(a=>a.name).filter(n=>n!==row.name))];const value=priceEdit(row),q=priceCandidate(row,states),qValue=q?candidatePurchase(row,q):null;const diff=q&&row.cost_price!==null&&row.cost_price>0?(q.price!-row.cost_price)/row.cost_price*100:null;const suppliers=supplierOptions(row);const hasHistory=events.some(e=>e.ingredient_id===row.id);return <tr key={row.id} className={q?'price-has-change':''}><td><input type="checkbox" aria-label={`選取 ${row.name}`} checked={selected.includes(row.id)} onChange={e=>setSelected(e.target.checked?[...selected,row.id]:selected.filter(id=>id!==row.id))}/></td><td title={row.name}><strong>{baselineName(row.name)}</strong><small className="baseline-provenance">{ingredientSourceLabel(row)} · {row.effective_date||'日期未記載'}</small>{first&&group.rows.length>1&&<button aria-expanded={expanded.includes(group.key)} onClick={()=>setExpanded(expanded.includes(group.key)?expanded.filter(k=>k!==group.key):[...expanded,group.key])}>{expanded.includes(group.key)?'收起':'展開'}同名紀錄 {group.rows.length} 筆</button>}{!first&&<small className="baseline-provenance">同名原始紀錄</small>}</td><td><span title={aliases[0]}>{aliases[0]||'—'}</span>{row.aliases.length>0&&<button className="alias-count" onClick={()=>setAlias(row.id)}>整理別名</button>}</td><td className="price-supplier" title={suppliers.map(s=>s.name).join('、')}><button onClick={()=>setHistory({id:row.id})}>{row.supplier_name||suppliers[0]?.name||'待補'}{suppliers.length>1?` ＋${suppliers.length-1}`:''}{hasHistory?' ⚑':''}</button></td><td>{value.unit}</td><td>{formatPurchaseSpecification(value.content,value.contentUnit)||'—'}</td><td className="price-number">{value.price===''?'待補':money(Number(value.price))}</td><td className="price-number" title={q?.supplier_name}>{qValue?`${money(qValue.amount)}／${qValue.unit}`:'—'}</td><td>{diff===null?'—':`${diff>0?'↑':'↓'} ${Math.abs(diff).toFixed(1)}%`}</td><td>{data.price_history?.find(h=>h.ingredient_id===row.id)?.effective_date||row.effective_date||'既有基準'}</td><td title={data.price_history?.find(h=>h.ingredient_id===row.id)?.reason}>{data.price_history?.find(h=>h.ingredient_id===row.id)?.reason||'—'}</td><td><button onClick={()=>setPriceHistory(row.id)}>調價紀錄</button><button onClick={()=>setSources(row.id)}>來源</button>{data.can_price&&<><button disabled={!canWrite} onClick={()=>edit(row)}>編輯</button>{q&&<button disabled={!canWrite} onClick={()=>void confirm(row)}>確認新價</button>}<button disabled={!canWrite} onClick={()=>stop(row)}>停用</button></>}</td></tr>;})}</>}
 </tbody></table>{count===0&&!Object.keys(edits).length&&<p className="price-empty">此分頁沒有符合的資料。</p>}</div>}
 <footer className="price-sheet-pagination"><span>{count} 組 · {tab==='removed'?removedRows.length:rows.length} 筆原始紀錄 · 每頁 50 組</span><button disabled={p===0} onClick={()=>setPage(p-1)}>上一頁</button><span>{p+1}／{pages}</span><button disabled={p+1>=pages} onClick={()=>setPage(p+1)}>下一頁</button></footer>
 {Object.keys(edits).length>0&&<div className="price-sheet-save"><span>編輯中 {Object.keys(edits).length} 項 · 缺價可先留白儲存</span><button disabled={busy} onClick={()=>void discardEdits()}>取消編輯</button><>{cloudDraft&&<button disabled={!canWrite} onClick={()=>void keepCloud()}>保存草稿</button>}</><button disabled={!canWrite} onClick={()=>void saveEdits()}>{busy?'儲存中…':'儲存修改'}</button></div>}
 {priceHistory&&<div className="price-sheet-dialog" role="dialog" aria-modal="true" aria-label="調價紀錄"><div><button className="close" onClick={()=>setPriceHistory(null)}>關閉</button><h2>{data.ingredients.find(r=>r.id===priceHistory)?.name} · 調價紀錄</h2>{(data.price_history||[]).filter(h=>h.ingredient_id===priceHistory).map(h=>{const v=ingredientPurchase(h.snapshot);return <article key={h.id}><strong>{h.effective_date} · {money(v?.amount??h.snapshot.cost_price)}／{v?.unit||h.snapshot.unit}</strong><p>{h.reason} · {h.actor_name}</p></article>;})}<p>已儲存的歷史交易與鎖定食譜不會自動改價。</p></div></div>}
 {alias&&<div className="price-sheet-dialog" role="dialog" aria-modal="true" aria-label="全部別名"><div><button className="close" onClick={()=>setAlias(null)}>關閉</button><h2>全部別名</h2>{data.ingredients.find(r=>r.id===alias)?.aliases.map(a=><p key={a.id}>{a.name}{data.can_price&&<><select aria-label={`調整 ${a.name} 歸屬`} value={aliasTarget[a.id]||''} onChange={e=>setAliasTarget({...aliasTarget,[a.id]:e.target.value})}><option value="">選擇其他食材</option>{data.ingredients.filter(r=>r.id!==alias&&r.unit===a.unit&&!isIngredientStopped(r,states)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button disabled={!canWrite||!aliasTarget[a.id]} onClick={async()=>{const from=data.ingredients.find(r=>r.id===alias)!,to=data.ingredients.find(r=>r.id===aliasTarget[a.id])!;if(await run('alias',{id:from.id,revision:from.revision,alias_id:a.id,target_id:to.id,target_revision:to.revision}))setAlias(null);}}>確認歸屬</button></>}</p>)}<p>搜尋可比對全部別名，表格維持相同列高。</p></div></div>}
 {sources&&(()=>{const row=data.ingredients.find(r=>r.id===sources)!;return <div className="price-sheet-dialog" role="dialog" aria-modal="true" aria-label="價格來源"><div><button className="close" onClick={()=>setSources(null)}>關閉</button><h2>{row.name} · 價格來源</h2>{error&&<p role="alert">{error}</p>}<table><thead><tr><th>來源</th><th>供應商</th><th>日期</th><th>價格</th></tr></thead><tbody>{baselineSources(row).map(q=><tr key={q.id}><td>{q.source}</td><td>{q.supplier_name||'未記載'}</td><td>{q.effective_date||'未記載'}</td><td>{money(q.price)}／{q.unit}</td></tr>)}</tbody></table>{priceCandidate(row,states)&&data.can_price&&<div className="price-dialog-actions"><button disabled={!canWrite} onClick={()=>void confirm(row,true)}>保留目前價格</button><button disabled={!canWrite} onClick={()=>void confirm(row)}>確認新價</button></div>}</div></div>;})()}
 {history&&(()=>{const row=data.ingredients.find(r=>r.id===history.id)!;const related=events.filter(e=>e.ingredient_id===row.id&&(!history.key||e.supplier_key===history.key));return <div className="price-sheet-dialog" role="dialog" aria-modal="true" aria-label="供應商採購紀錄"><div><button className="close" onClick={()=>setHistory(null)}>關閉</button><h2>{row.name} · 供應商採購紀錄</h2>{supplierOptions(row).map(sp=>{const state=states.find(s=>s.ingredient_id===row.id&&s.supplier_key===sp.key);return <p key={sp.key}>{sp.name}　{state?.stopped?`已停用：${state.reason}／${state.disposition}`:'使用中'} {data.can_price&&<button disabled={!canWrite} onClick={()=>{setHistory(null);if(state?.stopped)stop(row,state);else{stop(row);setDecision({row,key:sp.key,restore:false,reason:'價格偏高',disposition:'可重新詢價',note:'',revision:state?.revision||0,requestId:crypto.randomUUID()});}}}>{state?.stopped?'重新評估／恢復':'停用此供應商供貨'}</button>}</p>;})}{related.length===0?<p>尚無停用紀錄。</p>:related.map(ev=><article key={ev.id}><strong>{date(ev.created_at)} · {ev.actor_name||'使用者'} · {ev.supplier_name} · {ev.action==='stop'?'停用':'恢復使用'}</strong><p>{ev.reason} · {ev.disposition}</p><p>{ev.note||'未補充備註'}</p></article>)}<p>只停用指定供應商的此項供貨，不影響其他食材與供應商。</p></div></div>;})()}
 {decision&&<div className="price-sheet-dialog" role="dialog" aria-modal="true" aria-label="停用與恢復紀錄"><div><button className="close" disabled={busy} onClick={()=>setDecision(null)}>關閉</button><h2>{decision.restore?'恢復使用':'停用並保留紀錄'} · {decision.row.name}</h2><label>處理範圍<select disabled={decision.restore||busy} value={decision.key} onChange={e=>setDecision({...decision,key:e.target.value,requestId:crypto.randomUUID()})}><option value="*">整項食材暫停使用</option>{supplierOptions(decision.row).map(s=><option key={s.key} value={s.key}>僅停用 {s.name} 的此項供貨</option>)}{!supplierOptions(decision.row).some(s=>s.key===decision.key)&&decision.key!=='*'&&<option value={decision.key}>{states.find(s=>s.ingredient_id===decision.row.id&&s.supplier_key===decision.key)?.supplier_name}</option>}</select></label>
 {!decision.restore?<><label>停用原因<select value={decision.reason} onChange={e=>setDecision({...decision,reason:e.target.value,requestId:crypto.randomUUID()})}>{reasons.map(r=><option key={r}>{r}</option>)}</select></label><label>日後採購建議<select value={decision.disposition} onChange={e=>setDecision({...decision,disposition:e.target.value,requestId:crypto.randomUUID()})}>{['不建議再採購','可重新詢價','暫停使用'].map(r=><option key={r}>{r}</option>)}</select></label></>:<p className="price-sheet-error">先前原因：{decision.reason} · {decision.disposition}。恢復後仍保留此紀錄。</p>}
 <label>{decision.restore?'恢復原因':'補充實際情況（可後補）'}<textarea maxLength={3000} value={decision.note} onChange={e=>setDecision({...decision,note:e.target.value,requestId:crypto.randomUUID()})} placeholder={decision.restore?'例如：已重新試用，品質確認穩定':'例如：連續兩批品質不穩，已改向其他廠商採購'}/></label><p>原有進貨、庫存、調撥、廢棄與食譜紀錄保留。</p>{error&&<p role="alert" className="price-sheet-error">{error}</p>}<button disabled={!canWrite} onClick={()=>void submitDecision()}>{busy?'儲存中…':decision.restore?'確認恢復並留紀錄':'確認停用並留紀錄'}</button></div></div>}
 </section>;
}
