'use client';
import {Fragment,useEffect,useRef,useState} from 'react';
import {ingredientSourceLabel,ingredientPurchase,ingredientSaveData,formatPurchaseSpecification,usesPackageSpecification} from '@/lib/ingredient-catalog';
import {baselineCategory,baselinePriceDate,priceCategories,baselineName,baselineGroups,baselineSources,baselinePurchaseDate,emptyPriceSheet,isIngredientStopped,priceCandidate,priceSearch,priceEdit,candidatePurchase,supplierOptions,type PriceSheetData,type PriceIngredient,type SupplyState,type PriceSheetEdit} from '@/lib/ingredient-price-sheet';
import './ingredient-price-sheet.css';
type Props={cloudDraft?:{read:()=>Promise<{token:string;edits:Record<string,PriceSheetEdit>}|null>;save:(edits:Record<string,PriceSheetEdit>,expected:string|null,token:string)=>Promise<{token:string}>};data:PriceSheetData;loaded:boolean;failed:boolean;canExport:boolean;draftKey:string;save:(action:string,data:Record<string,unknown>,requestId:string)=>Promise<void>;registerLeave?:(handler:(()=>Promise<boolean>)|null)=>void};
const money=(v:number|null|undefined)=>v==null?'':`NT$ ${v.toLocaleString('zh-TW',{maximumFractionDigits:6})}`;
const date=(v?:string|null)=>v&&!Number.isNaN(Date.parse(v))?new Date(v).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}).replaceAll('-','/') :'';
const units=['待補單位','g','公斤','台斤','ml','L','包','盒','瓶','罐','箱','顆','片','卷','份','隻','條','塊'];
const reasons=['價格偏高','品質不佳','規格不符','交貨不穩','停止供貨','菜單停用','其他'];
export default function IngredientPriceSheet({data=emptyPriceSheet,loaded,failed,canExport,draftKey,save,registerLeave,cloudDraft}:Props){
 const [tab,setTab]=useState('common'),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const [category,setCategory]=useState(''),[supplier,setSupplier]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const [edits,setEdits]=useState<Record<string,PriceSheetEdit>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [decision,setDecision]=useState<{row:PriceIngredient;key:string;restore:boolean;reason:string;disposition:string;note:string;revision:number;requestId:string}|null>(null);
 const [more,setMore]=useState<string|null>(null);
 const [aliasTarget,setAliasTarget]=useState<Record<string,string>>({});
 const [recovery,setRecovery]=useState<Record<string,PriceSheetEdit>|null>(null);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const timer=setTimeout(()=>{try{const value=JSON.parse(localStorage.getItem(draftKey)||'null');if(value&&Object.keys(value).length)setRecovery(value);}catch{/* No cloud values are replaced by malformed drafts. */}},0);return()=>clearTimeout(timer);},[draftKey]);
 const editRef=useRef(edits);
 const cloudToken=useRef<string|null>(null),cloudReady=useRef(false);
 useEffect(()=>{if(!cloudDraft)return;let active=true;void cloudDraft.read().then(value=>{if(!active)return;cloudToken.current=value?.token||null;cloudReady.current=true;if(value&&Object.keys(value.edits).length){if(!Object.keys(editRef.current).length)setRecovery(local=>local||value.edits);setMessage('系統有已保存草稿，可恢復後接續。');}}).catch(()=>{if(active)setMessage('系統草稿讀取失敗，本機修改仍保留，請重新同步後重試。');});return()=>{active=false;};},[cloudDraft]);
 async function persistCloud(next:Record<string,PriceSheetEdit>){if(!cloudDraft)return;if(!cloudReady.current)throw Error('系統草稿尚未讀取，請重新同步。');const saved=await cloudDraft.save(next,cloudToken.current,crypto.randomUUID());cloudToken.current=saved.token;}
 async function discardEdits(){if(!window.confirm('捨棄尚未儲存的修改及已保存草稿？'))return;setBusy(true);setError('');try{await persistCloud({});setRecovery(null);updateEdits({});}catch{setError('草稿清除失敗，修改仍保留，請重試。');}finally{setBusy(false);}}
 async function keepCloud(){setBusy(true);setError('');try{await persistCloud(edits);setMessage('草稿已保存至系統，同帳號換裝置可接續；尚未更新正式價格。');}catch(e){setError(String(e&&typeof e==='object'&&'message' in e?e.message:e).includes('DRAFT_CHANGED')?'其他裝置已更新草稿，本頁輸入保留，請重新同步後核對。':'草稿保存失敗，輸入保留，請重試。');}finally{setBusy(false);}}

 useEffect(()=>{const keep=()=>{try{localStorage.setItem(draftKey,JSON.stringify(editRef.current));return true;}catch{setError('無法暫存，請先儲存修改。');return false;}};registerLeave?.(async()=>busy?false:keep());const warn=(e:BeforeUnloadEvent)=>{if(Object.keys(editRef.current).length){keep();e.preventDefault();}};window.addEventListener('beforeunload',warn);return()=>{registerLeave?.(null);window.removeEventListener('beforeunload',warn);};},[draftKey,registerLeave,busy]);
 function updateEdits(next:Record<string,PriceSheetEdit>){setEdits(next);editRef.current=next;try{localStorage.setItem(draftKey,JSON.stringify(next));}catch{setError('無法暫存，請先儲存修改。');}}
 function edit(row?:PriceIngredient){if(!row){setTab('all');setPage(0);setCategory('');setSupplier('');setSearch('');}const key=row?.id||`new:${crypto.randomUUID()}`;updateEdits({...edits,[key]:{row,draft:priceEdit(row),requestId:crypto.randomUUID()}});}
 function change(key:string,field:string,value:string){const current=edits[key];updateEdits({...edits,[key]:{...current,requestId:crypto.randomUUID(),draft:{...current.draft,[field]:value,...(field==='unit'&&!usesPackageSpecification(value)?{specification:'',content:'',contentUnit:''}:{}),...(['price','unit','content','contentUnit','specification'].includes(field)?{reference:''}:{})}}});}
 const states=data.supply_states||[],events=data.supply_events||[];
 const active=data.ingredients.filter(r=>!isIngredientStopped(r,states));
 const groups=baselineGroups(active);
 const matches=(r:PriceIngredient)=>priceSearch(r,search)&&(!category||baselineCategory(r)===category)&&(!supplier||r.supplier_name===supplier);
 const filteredGroups=groups.filter(g=>(tab==='all'||tab==='removed'||(tab==='history'?g.history:!g.history))&&g.rows.some(matches)).map(g=>supplier?{...g,rows:[...g.rows].sort((a,b)=>Number(b.supplier_name===supplier)-Number(a.supplier_name===supplier))}:g);
 const removed=states.filter(s=>s.stopped);
 const removedRows=removed.filter(s=>{const r=data.ingredients.find(r=>r.id===s.ingredient_id);return r&&(!category||baselineCategory(r)===category)&&(!supplier||s.supplier_name===supplier)&&(priceSearch(r,search)||`${s.reason} ${s.note} ${s.supplier_name}`.includes(search));});
 const selectedGroups=filteredGroups.filter(g=>selected.includes(g.rows[0].id));
 const count=tab==='removed'?removedRows.length:filteredGroups.length, pages=Math.max(1,Math.ceil(count/50)),p=Math.min(page,pages-1);
 const pageGroups=filteredGroups.slice(p*50,p*50+50);
 const visible=pageGroups.map(g=>g.rows[0]);
 const rowGroups=new Map(pageGroups.flatMap(g=>g.rows.map(r=>[r.id,g] as const)));
 const canWrite=data.can_price&&loaded&&!failed&&!busy;
 async function run(action:string,payload:Record<string,unknown>,requestId=crypto.randomUUID()){setBusy(true);setError('');setMessage('');try{await save(action,payload,requestId);return true;}catch(e){setError(e instanceof Error?e.message:'尚未完成，請重試。');return false;}finally{setBusy(false);}}
 async function saveEdits(){setBusy(true);setError('');const remaining={...edits};let done=0;try{for(const [key,e] of Object.entries(edits)){if(e.row&&JSON.stringify(e.draft)===JSON.stringify(priceEdit(e.row))){delete remaining[key];updateEdits(remaining);continue;}const payload={...ingredientSaveData(e.draft,e.row),supplier_id:e.draft.supplier_id||null,category:e.draft.category||'待分類'};await save('save',payload,e.requestId);delete remaining[key];updateEdits(remaining);done++;}if(cloudDraft&&cloudReady.current)await persistCloud(remaining);setMessage(`已儲存 ${done} 項，原有交易及鎖定食譜保留。`);}catch(e){setError(`已儲存 ${done} 項；其餘輸入保留。${e instanceof Error?e.message:''}`);}finally{setBusy(false);}}
 function stop(row:PriceIngredient,state?:SupplyState){setDecision({row,key:state?.supplier_key||'*',restore:!!state?.stopped,reason:state?.reason||'價格偏高',disposition:state?.disposition||'可重新詢價',note:'',revision:state?.revision||0,requestId:crypto.randomUUID()});}
 async function submitDecision(){if(!decision)return;const current=states.find(s=>s.ingredient_id===decision.row.id&&s.supplier_key===decision.key);if(decision.restore&&!decision.note.trim()){setError('請簡短記錄恢復採購的原因。');return;}if(await run(decision.restore?'restore':'stop',{id:decision.row.id,revision:decision.row.revision,supplier_key:decision.key,supply_revision:current?.revision||0,reason:decision.reason,disposition:decision.disposition,note:decision.note},decision.requestId)){setDecision(null);setMessage('已保存紀錄；歷次停用與恢復原因均保留。');}}
 async function confirm(row:PriceIngredient,keep=false){const q=priceCandidate(row,states);if(!q)return;const newPrice=candidatePurchase(row,q);if(!keep&&!window.confirm(`${row.name}：改用 ${money(newPrice.amount)}／${newPrice.unit}？新作業立即生效，既有交易及鎖定食譜不變。`))return;await run(keep?'keep':'confirm',{id:row.id,revision:row.revision,reference_id:q.id,expected_price:q.price,effective_date:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}),change_reason:keep?'保留標準進價':'確認貨單新價'});}
 async function exportRows(){try{const x=await import('xlsx');const values=tab==='removed'?removedRows.map(s=>({食材:data.ingredients.find(r=>r.id===s.ingredient_id)?.name,供應商:s.supplier_name,停用原因:s.reason,處理方式:s.disposition,備註:s.note,日期:date(s.updated_at)})):filteredGroups.filter(g=>!selectedGroups.length||selected.includes(g.rows[0].id)).flatMap(g=>g.rows).map(r=>{const v=priceEdit(r);return {識別碼:r.id,歸組名稱:baselineName(r.name),來源:ingredientSourceLabel(r),價格日期:baselinePriceDate(r),分類:baselineCategory(r),最近請購:baselinePurchaseDate(r),食材:r.name,別名:r.aliases.map(a=>a.name).join('、'),供應商:r.supplier_name||'',單位:v.unit,價格:v.price,規格:v.specification??formatPurchaseSpecification(v.content,v.contentUnit)};});const book=x.utils.book_new();x.utils.book_append_sheet(book,x.utils.json_to_sheet(values),'食材價格');x.writeFile(book,'食材價格表.xlsx');}catch{setError('匯出失敗，請重試。');}}
 async function importFiles(files:FileList|null){if(!files)return;try{const x=await import('xlsx'),next={...edits};for(const file of Array.from(files)){const book=x.read(await file.arrayBuffer());const items=x.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[book.SheetNames[0]],{defval:''});for(const item of items){const name=String(item['食材']||item['食材名稱']||'').trim();if(!name)continue;const id=String(item['識別碼']||'');const row=id?data.ingredients.find(r=>r.id===id):data.ingredients.find(r=>r.name===name&&priceEdit(r).unit===String(item['單位']||''));if(id&&!row)throw Error('檔案含其他門市或不存在的識別碼。');if(row&&isIngredientStopped(row,states))throw Error(`${name}已移除，請先查看停用紀錄，匯入不會自動恢復。`);const key=row?.id||`import:${name}:${String(item['單位']||'')}`;if(next[key])continue;const supplier=String(item['供應商']||'').trim();const sp=data.suppliers.find(s=>s.name===supplier);if(supplier&&!sp)throw Error(`供應商「${supplier}」尚未建立，請先至供應商管理建立。`);const importedCategory=String(item['分類']||baselineCategory(row));if(!priceCategories.includes(importedCategory))throw Error(`「${name}」分類請使用食材、耗材、調料、酒水或待分類。`);const draft={...priceEdit(row),name,category:importedCategory,unit:String(item['單位']||row?.unit||'待補單位'),price:String(item['價格']??''),reference:'',supplier_id:sp?.id||'',...(item['規格']!==undefined?{specification:String(item['規格'])}:{}),content:String(item['內容量']||''),contentUnit:String(item['內容單位']||'g')};ingredientSaveData(draft,row);next[key]={row,draft,requestId:crypto.randomUUID()};}}updateEdits(next);setTab('all');setCategory('');setSupplier('');setSearch('');setSelected([]);setPage(0);setMessage('已匯入編輯列，檢查後按儲存才會寫入。');}catch(e){setError(e instanceof Error?e.message:'無法讀取檔案。');}if(input.current)input.current.value='';}
 function editCells(key:string,e:PriceSheetEdit){return <Fragment key={key}><tr className="price-edit-row">
 <td/><td><input aria-label="食材名稱" value={e.draft.name} disabled={busy} onChange={v=>change(key,'name',v.target.value)}/></td>
 <td><select aria-label="食材分類" value={e.draft.category||'待分類'} disabled={busy} onChange={v=>change(key,'category',v.target.value)}>{priceCategories.map(c=><option key={c}>{c}</option>)}</select></td>
 <td><select aria-label="供應商" value={e.draft.supplier_id} disabled={busy} onChange={v=>change(key,'supplier_id',v.target.value)}><option value="">{e.row?.supplier_name||'請選擇'}</option>{data.suppliers.map(sp=><option key={sp.id} value={sp.id}>{sp.name}</option>)}</select></td>
 <td><div className="ingredient-unit-edit"><input aria-label="確認價格" type="number" min="0" step="any" placeholder="可後補" value={e.draft.price} disabled={busy} onChange={v=>change(key,'price',v.target.value)}/><span>／</span><select aria-label="進貨單位" value={e.draft.unit} disabled={busy} onChange={v=>change(key,'unit',v.target.value)}>{[...new Set([e.draft.unit,...units])].map(u=><option key={u}>{u}</option>)}</select></div><input className="ingredient-spec-input" aria-label="規格" disabled={busy||!usesPackageSpecification(e.draft.unit)} placeholder={usesPackageSpecification(e.draft.unit)?'例如：450克（可後補）':''} value={e.draft.specification??formatPurchaseSpecification(e.draft.content,e.draft.contentUnit)} onChange={v=>change(key,'specification',v.target.value)}/></td>
 <td><input aria-label="生效日期" type="date" max={new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'})} value={e.draft.effective_date||''} disabled={busy} onChange={v=>change(key,'effective_date',v.target.value)}/></td>
 <td><button disabled={busy} onClick={()=>{const next={...edits};delete next[key];updateEdits(next);}}>取消</button><button disabled={busy} aria-expanded={more===key} onClick={()=>setMore(more===key?null:key)}>{more===key?'收起':'更多'}</button></td></tr>
 {more===key&&<tr className="ingredient-inline-details"><td colSpan={7}><div className="ingredient-detail-grid"><label>調價原因<select aria-label="調價原因" disabled={busy} value={e.draft.change_reason||'供應商調價'} onChange={v=>change(key,'change_reason',v.target.value)}>{['供應商調價','蔬菜／季節價格變動','更換供應商','包裝規格變更','修正原資料','確認標準進價','其他'].map(reason=><option key={reason}>{reason}</option>)}</select></label></div></td></tr>}</Fragment>;}
 function details(row:PriceIngredient){const group=rowGroups.get(row.id);const members=group?.rows||[row];const refs=[...new Map(members.flatMap(r=>baselineSources(r)).map(r=>[r.id,r])).values()];const aliases=[...new Set(members.flatMap(r=>r.aliases.map(a=>a.name)).filter(n=>n!==baselineName(row.name)))];const value=priceEdit(row);const related=events.filter(e=>members.some(m=>m.id===e.ingredient_id));return <tr className="ingredient-inline-details"><td colSpan={7}><div className="ingredient-detail-grid"><p>正式品名：{baselineName(row.name)}</p><p>其他名稱：{aliases.join('、')}</p><p>包裝規格：{formatPurchaseSpecification(value.content,value.contentUnit)||value.unit}</p></div>{data.can_price&&<div className="ingredient-detail-edit"><button disabled={!canWrite} onClick={()=>{edit(row);setMore(row.id);}}>編輯資料</button></div>}
 {priceCandidate(row,states)&&<p className="ingredient-change-note">有新進價可核對。{data.can_price&&<><button disabled={!canWrite} onClick={()=>void confirm(row)}>核對新價</button><button disabled={!canWrite} onClick={()=>void confirm(row,true)}>保留目前價格</button></>}</p>}
 <details><summary>查看價格紀錄</summary><p>價格來源：{ingredientSourceLabel(row)}</p><table><thead><tr><th>來源</th><th>供應商</th><th>日期</th><th>原價</th></tr></thead><tbody>{refs.map(q=><tr key={q.id}><td>{q.source}</td><td>{q.supplier_name||'未記載'}</td><td>{q.effective_date||'未記載'}</td><td>{q.price===null?'':`${money(candidatePurchase(row,q).amount)}／${candidatePurchase(row,q).unit}`}</td></tr>)}</tbody></table>{(data.price_history||[]).filter(h=>members.some(m=>m.id===h.ingredient_id)).map(h=>{const v=ingredientPurchase(h.snapshot);return <p key={h.id}>{h.effective_date} · {money(v?.amount??h.snapshot.cost_price)}／{v?.unit||h.snapshot.unit} · {h.reason}</p>;})}{!refs.length&&!(data.price_history||[]).some(h=>members.some(m=>m.id===h.ingredient_id))&&<p>尚無歷史進價紀錄。</p>}</details>
 {members.length>1&&<details><summary>同名原始紀錄（{members.length}）</summary>{members.map(m=><p key={m.id}>{m.name} · {money(ingredientPurchase(m)?.amount??m.cost_price)}／{ingredientPurchase(m)?.unit||m.unit} {data.can_price&&<button disabled={!canWrite} onClick={()=>{edit(m);setMore(m.id);}}>編輯此紀錄</button>}</p>)}</details>}
 {data.can_price&&members.some(m=>m.aliases.length)&&<details><summary>整理別名</summary>{members.flatMap(m=>m.aliases.map(a=><label className="ingredient-alias-edit" key={a.id}>{a.name}<select aria-label={`調整 ${a.name} 歸屬`} value={aliasTarget[a.id]||''} onChange={e=>setAliasTarget({...aliasTarget,[a.id]:e.target.value})}><option value="">選擇其他食材</option>{data.ingredients.filter(r=>r.id!==m.id&&r.unit===a.unit&&!isIngredientStopped(r,states)).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button disabled={!canWrite||!aliasTarget[a.id]} onClick={async()=>{const to=data.ingredients.find(r=>r.id===aliasTarget[a.id])!;if(await run('alias',{id:m.id,revision:m.revision,alias_id:a.id,target_id:to.id,target_revision:to.revision}))setMore(null);}}>確認歸屬</button></label>))}</details>}
 <details><summary>供應商與停用紀錄</summary>{supplierOptions(row).map(sp=>{const st=states.find(t=>t.ingredient_id===row.id&&t.supplier_key===sp.key);return <p key={sp.key}>{sp.name} · {st?.stopped?`已停用：${st.reason}`:'使用中'}{data.can_price&&<button disabled={!canWrite} onClick={()=>{if(st?.stopped)stop(row,st);else setDecision({row,key:sp.key,restore:false,reason:'價格偏高',disposition:'可重新詢價',note:'',revision:st?.revision||0,requestId:crypto.randomUUID()});}}>{st?.stopped?'恢復供貨':'停用供貨'}</button>}</p>;})}{related.map(ev=><p key={ev.id}>{date(ev.created_at)} · {ev.actor_name||'使用者'} · {ev.action==='stop'?'停用':'恢復'} · {ev.reason} · {ev.note}</p>)}{!related.length&&<p>尚無停用紀錄。</p>}</details>
 {data.can_price&&<div className="ingredient-detail-bottom"><button disabled={!canWrite} onClick={()=>stop(row)}>停用此品項</button></div>}</td></tr>;}
 function switchTab(value:string){setTab(value);setPage(0);setSelected([]);setMore(null);}
 return <section className="ingredient-price-sheet ingredient-baseline" aria-label="食材基準表"><header><h1>食材基準表</h1></header>
 <nav className="price-sheet-tabs" aria-label="食材範圍">{[['common','常用食材'],['history','歷史食材'],['all','全部']].map(([value,label])=><button key={value} disabled={busy} aria-pressed={tab===value} onClick={()=>switchTab(value)}>{label}</button>)}</nav>
 <div className="price-baseline-toolbar"><div className="price-baseline-filters">
 <select aria-label="篩選分類" value={category} disabled={busy} onChange={e=>{setCategory(e.target.value);setPage(0);setSelected([]);}}><option value="">全部分類</option>{priceCategories.map(c=><option key={c}>{c}</option>)}</select>
 <select aria-label="篩選供應商" value={supplier} disabled={busy} onChange={e=>{setSupplier(e.target.value);setPage(0);setSelected([]);}}><option value="">全部供應商</option>{[...new Set(data.ingredients.map(r=>r.supplier_name).filter(Boolean))].sort().map(name=><option key={name}>{name}</option>)}</select>
 <input type="search" aria-label="搜尋食材、別名、供應商" placeholder="搜尋品名、別名…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);setSelected([]);}}/>
 </div><div className="price-baseline-actions">{tab!=='removed'&&data.can_price&&<><button disabled={!canWrite} onClick={()=>{const next={...edits};for(const r of (selectedGroups.length?selectedGroups:filteredGroups).map(g=>g.rows[0]))if(!next[r.id])next[r.id]={row:r,draft:priceEdit(r),requestId:crypto.randomUUID()};updateEdits(next);}}>{selectedGroups.length?'編輯所選':'編輯全部'}</button><button className="price-add" disabled={!canWrite} onClick={()=>edit()}>新增食材</button><button disabled={!canWrite} onClick={()=>input.current?.click()}>匯入</button><input ref={input} hidden type="file" multiple accept=".xlsx,.xls,.csv" onChange={e=>void importFiles(e.target.files)}/></>}{canExport&&<button disabled={!loaded||failed||busy||tab!=='removed'&&!filteredGroups.length} onClick={()=>void exportRows()}>匯出</button>}<details className="price-baseline-more"><summary>更多 ⌄</summary><button disabled={busy} onClick={()=>switchTab(tab==='removed'?'common':'removed')}>{tab==='removed'?'返回食材表':'已停用紀錄'}</button></details></div></div>
 {tab==='removed'&&<p>已停用紀錄 <button onClick={()=>switchTab('common')}>返回食材表</button></p>}
 {recovery&&<div role="status">有尚未儲存的修改。<button disabled={!canWrite} onClick={()=>{updateEdits(recovery);setRecovery(null);setTab('all');setCategory('');setSupplier('');setSearch('');setPage(0);}}>恢復草稿</button><button onClick={()=>void discardEdits()}>捨棄</button></div>}
 {error&&<p role="alert" className="price-sheet-error">{error}</p>}{message&&<p role="status">{message}</p>}
 {!loaded?<p>{failed?'讀取失敗，請重新同步。':'讀取食材價格…'}</p>:<div className="price-sheet-scroll"><table className={tab==='removed'?'price-removed-table':'price-baseline-table'}><thead>{tab==='removed'?<tr><th>食材名稱</th><th>供應商／範圍</th><th>停用原因</th><th>操作</th></tr>:<tr><th><input type="checkbox" aria-label="選取本頁食材" checked={visible.length>0&&visible.every(r=>selected.includes(r.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(r=>r.id)])]:selected.filter(id=>!visible.some(r=>r.id===id)))}/></th><th>食材名稱</th><th>分類</th><th>供應商</th><th>參考進價</th><th>價格日期</th><th>操作</th></tr>}</thead><tbody>
 {tab==='removed'?removedRows.slice(p*50,p*50+50).map(st=>{const row=data.ingredients.find(r=>r.id===st.ingredient_id)!;return <tr key={`${row.id}:${st.supplier_key}`}><td>{baselineName(row.name)}</td><td>{st.supplier_name||'整項食材'}</td><td>{st.reason}<small>{st.note}</small></td><td>{data.can_price&&<button disabled={!canWrite} onClick={()=>stop(row,st)}>恢復</button>}</td></tr>;}):<>
 {Object.entries(edits).filter(([,e])=>!e.row||(!groups.some(g=>g.rows[0].id===e.row?.id)&&pageGroups.some(g=>g.rows.some(r=>r.id===e.row?.id)))).map(([key,e])=>editCells(key,e))}
 {visible.map(row=>{if(edits[row.id])return editCells(row.id,edits[row.id]);const v=priceEdit(row),spec=formatPurchaseSpecification(v.content,v.contentUnit);return <Fragment key={row.id}><tr className="ingredient-baseline-row">
 <td><input type="checkbox" aria-label={`選取 ${baselineName(row.name)}`} checked={selected.includes(row.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,row.id]:old.filter(id=>id!==row.id))}/></td>
 <td><strong className="ingredient-primary-name" title={baselineName(row.name)}>{baselineName(row.name)}</strong></td><td>{baselineCategory(row)==='待分類'?'':baselineCategory(row)}</td><td>{row.supplier_name||''}</td>
 <td className="price-number">{v.price===''?'':`${money(Number(v.price))}／${v.unit}`}<small className="price-package">{spec?`${spec}／${v.unit}`:''}</small></td>
 <td>{date(baselinePriceDate(row))}</td><td><button aria-expanded={more===row.id} onClick={()=>setMore(more===row.id?null:row.id)}>{more===row.id?'收起':'更多'} {more===row.id?'⌃':'⌄'}</button></td></tr>{more===row.id&&details(row)}</Fragment>;})}</>}
 </tbody></table>{count===0&&!Object.keys(edits).length&&<p className="price-empty">沒有符合的食材。可切換「全部」或調整篩選條件。</p>}</div>}
 <p className="price-baseline-note">常用食材優先顯示，過去食譜資料可至「歷史食材」查看。</p>

 {loaded&&<footer className="price-sheet-pagination"><span>{count} 項 · 每頁 50 項</span><button disabled={p===0} onClick={()=>setPage(p-1)}>上一頁</button><span>{p+1}／{pages}</span><button disabled={p+1>=pages} onClick={()=>setPage(p+1)}>下一頁</button></footer>}
 {Object.keys(edits).length>0&&<div className="price-sheet-save"><span>編輯中 {Object.keys(edits).length} 項 · 缺價可先儲存</span><button disabled={busy} onClick={()=>void discardEdits()}>取消編輯</button>{cloudDraft&&<button disabled={!canWrite} onClick={()=>void keepCloud()}>保存草稿</button>}<button disabled={!canWrite} onClick={()=>void saveEdits()}>{busy?'儲存中…':'儲存修改'}</button></div>}
 {decision&&<div className="price-sheet-dialog" role="dialog" aria-modal="true" aria-label="停用與恢復紀錄"><div><button className="close" disabled={busy} onClick={()=>setDecision(null)}>關閉</button><h2>{decision.restore?'恢復使用':'停用並保留紀錄'} · {decision.row.name}</h2><label>處理範圍<select disabled={decision.restore||busy} value={decision.key} onChange={e=>setDecision({...decision,key:e.target.value,requestId:crypto.randomUUID()})}><option value="*">整項食材暫停使用</option>{supplierOptions(decision.row).map(s=><option key={s.key} value={s.key}>僅停用 {s.name} 的此項供貨</option>)}{!supplierOptions(decision.row).some(s=>s.key===decision.key)&&decision.key!=='*'&&<option value={decision.key}>{states.find(s=>s.ingredient_id===decision.row.id&&s.supplier_key===decision.key)?.supplier_name}</option>}</select></label>
 {!decision.restore?<><label>停用原因<select value={decision.reason} onChange={e=>setDecision({...decision,reason:e.target.value,requestId:crypto.randomUUID()})}>{reasons.map(r=><option key={r}>{r}</option>)}</select></label><label>日後採購建議<select value={decision.disposition} onChange={e=>setDecision({...decision,disposition:e.target.value,requestId:crypto.randomUUID()})}>{['不建議再採購','可重新詢價','暫停使用'].map(r=><option key={r}>{r}</option>)}</select></label></>:<p className="price-sheet-error">先前原因：{decision.reason} · {decision.disposition}。恢復後仍保留此紀錄。</p>}
 <label>{decision.restore?'恢復原因':'補充實際情況（可後補）'}<textarea maxLength={3000} value={decision.note} onChange={e=>setDecision({...decision,note:e.target.value,requestId:crypto.randomUUID()})} placeholder={decision.restore?'例如：已重新試用，品質確認穩定':'例如：連續兩批品質不穩，已改向其他廠商採購'}/></label><p>原有進貨、庫存、調撥、廢棄與食譜紀錄保留。</p>{error&&<p role="alert" className="price-sheet-error">{error}</p>}<button disabled={!canWrite} onClick={()=>void submitDecision()}>{busy?'儲存中…':decision.restore?'確認恢復並留紀錄':'確認停用並留紀錄'}</button></div></div>}
 </section>;
}
