'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Search,X,ChevronDown} from 'lucide-react';
import {ingredientDraft,ingredientMatches,ingredientPending,ingredientSaveData,type IngredientCatalog,type IngredientMaster,type IngredientDraft,type IngredientSource,type IngredientAlias} from '@/lib/ingredient-catalog';

type Props={catalog:IngredientCatalog;loaded:boolean;failed:boolean;onSave:(action:string,data:Record<string,unknown>)=>Promise<boolean>;onSources:(id:string)=>Promise<IngredientSource[]>;registerLeave?:(handler:(()=>Promise<boolean>)|null)=>void};
const money=(n:number)=>n.toLocaleString('zh-TW',{maximumFractionDigits:6});
const safeLink=(url?:string)=>url&&/^https?:\/\//i.test(url)?url:undefined;
export default function IngredientCatalogView({catalog,loaded,failed,onSave,onSources,registerLeave}:Props){
 const [search,setSearch]=useState(''),[pending,setPending]=useState(false),[page,setPage]=useState(0);
 const [editing,setEditing]=useState<{row?:IngredientMaster;draft:IngredientDraft}|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const [sources,setSources]=useState<IngredientSource[]|null>(null),[sourceError,setSourceError]=useState(''),[sourceBusy,setSourceBusy]=useState(false);
 const [moving,setMoving]=useState<{alias:IngredientAlias;mode:'move'|'new';target:string;name:string}|null>(null),[targetTerm,setTargetTerm]=useState('');
 const sourceRequest=useRef(0),nameInput=useRef<HTMLInputElement>(null),opener=useRef<HTMLElement|null>(null);
 const dirty=!!editing&&JSON.stringify(editing.draft)!==JSON.stringify(ingredientDraft(editing.row));
 useEffect(()=>{registerLeave?.(async()=>{if(busy||dirty||moving){setError('請先儲存修改，或按「取消」再離開。');return false;}return true;});const warn=(e:BeforeUnloadEvent)=>{if(dirty||busy)e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>{registerLeave?.(null);window.removeEventListener('beforeunload',warn);};},[busy,dirty,moving,registerLeave]);
 function close(){if(busy)return;sourceRequest.current++;setEditing(null);setMoving(null);setError('');opener.current?.focus();}
 const editingKey=editing?(editing.row?.id||'new'):null;
 useEffect(()=>{if(editingKey)nameInput.current?.focus();},[editingKey]); // Focus only when opening another ingredient.
 function open(row?:IngredientMaster){if(busy)return;if(dirty||moving){setError('請先儲存修改，或按「取消」再切換食材。');return;}opener.current=document.activeElement as HTMLElement;sourceRequest.current++;setEditing({row,draft:ingredientDraft(row)});setSources(null);setSourceBusy(false);setSourceError('');setMoving(null);setError('');setSaved('');}
 function change(patch:Partial<IngredientDraft>){setEditing(current=>current?{...current,draft:{...current.draft,...patch}}:current);setError('');}
 async function submit(){if(!editing||busy)return;let data;try{data=ingredientSaveData(editing.draft,editing.row);}catch(e){setError((e as Error).message);return;}setBusy(true);setError('');try{if(await onSave('ingredient.save',data)){setEditing(null);setMoving(null);setSaved(`${data.name}已儲存，食譜將使用此成本價。`);opener.current?.focus();}}catch(e){setError(e instanceof Error?e.message:'尚未儲存成功，輸入內容已保留。');}finally{setBusy(false);}}
 async function loadSources(){if(!editing?.row||sources||sourceBusy)return;const token=++sourceRequest.current;setSourceBusy(true);setSourceError('');try{const data=await onSources(editing.row.id);if(token===sourceRequest.current)setSources(data);}catch{if(token===sourceRequest.current)setSourceError('來源暫時無法讀取，請重試。');}finally{if(token===sourceRequest.current)setSourceBusy(false);}}
 function move(alias:IngredientAlias,mode:'move'|'new'){if(dirty){setError('請先儲存名稱或價格修改，再調整別名歸屬。');return;}setMoving({alias,mode,target:'',name:alias.name});setTargetTerm('');setError('');}
 async function saveMove(){if(!editing?.row||!moving||busy)return;const target=catalog.ingredients.find(i=>i.id===moving.target);if(moving.mode==='move'&&!target){setError('請選擇要歸入的食材。');return;}if(moving.mode==='new'&&!moving.name.trim()){setError('請填新食材名稱。');return;}setBusy(true);setError('');try{if(await onSave('ingredient.alias',{id:editing.row.id,revision:editing.row.revision,alias_id:moving.alias.id,...(moving.mode==='move'?{target_id:target!.id,target_revision:target!.revision}:{name:moving.name.trim()})})){setEditing(null);setMoving(null);setSaved('別名歸屬已更新；原表與報價紀錄保留。');}}catch(e){setError(e instanceof Error?e.message:'歸屬尚未更新，請重試。');}finally{setBusy(false);}}
 const rows=catalog.ingredients.filter(r=>ingredientMatches(r,search)&&(!pending||ingredientPending(r)));
 const pageCount=Math.max(1,Math.ceil(rows.length/50)),currentPage=Math.min(page,pageCount-1),visible=rows.slice(currentPage*50,currentPage*50+50);
 const targets=moving?catalog.ingredients.filter(r=>r.id!==editing?.row?.id&&r.unit===moving.alias.unit&&ingredientMatches(r,targetTerm)):[];
 return <section className={`ingredient-catalog ${editing?'catalog-editing':''}`} aria-label="基礎食材">
 <div className="catalog-main">
  <header className="catalog-heading"><div><h1>基礎食材</h1><p>由三份表格整理，選用價格直接帶入食譜成本。</p></div>{catalog.can_price&&<button className="recipe-secondary" disabled={!loaded||busy} onClick={()=>open()}><Plus size={17}/>新增食材</button>}</header>
  <label className="recipe-search catalog-search"><Search size={18}/><input aria-label="搜尋食材或別名" placeholder="搜尋食材或別名" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label>
  <nav className="catalog-tabs" aria-label="基礎食材分類"><button aria-pressed={!pending} onClick={()=>{setPending(false);setPage(0);}}>全部食材</button><button aria-pressed={pending} onClick={()=>{setPending(true);setPage(0);}}>待確認 <small>{catalog.ingredients.filter(ingredientPending).length||''}</small></button></nav>
  {saved&&<p className="price-register-saved" role="status">{saved}</p>}
  {!editing&&error&&<p className="recipe-alert" role="alert">{error}</p>}
  {!loaded?<p role="status">{failed?'食材資料暫時無法讀取，請按上方「重新同步」。':'讀取基礎食材…'}</p>:<>
  <div className="catalog-table-wrap"><table className="catalog-table"><thead><tr><th>食材名稱</th><th>計價單位</th><th>成本單價</th><th>操作</th></tr></thead><tbody>{visible.map(row=>{
   const aliases=[...new Set(row.aliases.map(a=>a.name).filter(n=>n!==row.name))];
   return <tr key={row.id} className={editing?.row?.id===row.id?'catalog-selected':''}><th scope="row"><strong>{row.name}</strong>{aliases.length>0&&<small>別名：{aliases.slice(0,3).join('、')}{aliases.length>3?` 等 ${aliases.length} 個`:''}</small>}{ingredientPending(row)&&<span className="catalog-pending">{row.cost_price===null?'待補價格':'待確認'}</span>}</th><td>{row.unit}</td><td>{row.cost_price===null?<span className="recipe-pending">待補</span>:`NT$ ${money(row.cost_price)}`}</td><td><button className="recipe-secondary" onClick={()=>open(row)}>{catalog.can_price?ingredientPending(row)?'確認':'編輯':'查看'}</button></td></tr>;
  })}</tbody></table></div>{!rows.length&&<p className="recipe-muted">{catalog.ingredients.length?'沒有符合的食材，試試其他名稱或別名。':'尚無基礎食材，請新增食材。'}</p>}
  <div className="catalog-bottom"><small>{rows.length} 項基礎食材</small>{pageCount>1&&<nav className="price-register-pagination" aria-label="基礎食材分頁"><button className="recipe-secondary" disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>上一頁</button><span>{currentPage+1}／{pageCount}</span><button className="recipe-secondary" disabled={currentPage+1===pageCount} onClick={()=>setPage(currentPage+1)}>下一頁</button></nav>}</div></>}
  <p className="recipe-muted">同食材集中管理，原表名稱與價格來源保留。</p>
 </div>
 {editing&&<aside className="catalog-panel" aria-label="編輯食材">
  <header><h2>{editing.row?'編輯食材':'新增食材'}</h2><button className="catalog-close" aria-label="關閉編輯食材" disabled={busy} onClick={close}><X size={22}/></button></header>
  <form onSubmit={e=>{e.preventDefault();void submit();}}>
   <fieldset disabled={busy||!catalog.can_price} className="catalog-fields"><label>食材名稱<input ref={nameInput} aria-label="食材名稱" maxLength={200} value={editing.draft.name} onChange={e=>change({name:e.target.value})}/></label><div className="catalog-two-fields"><label>計價單位<select aria-label="計價單位" value={editing.draft.unit} onChange={e=>change({unit:e.target.value,reference:''})}>{[...new Set([editing.draft.unit,'g','ml','顆','片','卷','包','盒','瓶','罐','份','隻','條','塊'])].map(u=><option key={u}>{u}</option>)}</select></label><label>成本單價<input aria-label="成本單價" type="number" inputMode="decimal" min="0" step="any" placeholder="尚未確認可留白" value={editing.draft.price} onChange={e=>change({price:e.target.value,reference:''})}/></label></div></fieldset>
   {editing.row&&editing.draft.unit!==editing.row.unit&&<p className="recipe-muted">原單位的食譜會保留待換算提示，請確認新的單位與單價。</p>}
   {editing.row&&<section className="catalog-aliases"><h3>已歸入的別名</h3><p>系統先整理別名，判錯可在此修正。</p>{editing.row.aliases.length?<ul>{editing.row.aliases.map(alias=><li key={alias.id}><div><span>{alias.name}</span>{alias.specification&&<small>{alias.specification}</small>}{alias.corrected&&<small>已人工調整</small>}</div>{catalog.can_price&&<details className="catalog-alias-menu"><summary>調整歸屬 <ChevronDown size={14}/></summary><div><button type="button" disabled={busy} onClick={()=>move(alias,'move')}>改歸其他食材</button><button type="button" disabled={busy} onClick={()=>move(alias,'new')}>另建食材</button></div></details>}</li>)}</ul>:<small>尚無其他別名。</small>}
   {moving&&<div className="catalog-move"><strong>{moving.mode==='new'?'另建食材':'改歸其他食材'}：{moving.alias.name}</strong>{moving.mode==='new'?<label>新食材名稱<input aria-label="新食材名稱" value={moving.name} onChange={e=>setMoving({...moving,name:e.target.value})}/></label>:<><label>搜尋目標食材<input aria-label="搜尋目標食材" value={targetTerm} onChange={e=>setTargetTerm(e.target.value)} placeholder="輸入名稱或別名"/></label><label>歸入食材<select aria-label="歸入食材" value={moving.target} onChange={e=>setMoving({...moving,target:e.target.value})}><option value="">選擇食材（同為 {moving.alias.unit}）</option>{targets.map(t=><option key={t.id} value={t.id}>{t.name} · {t.cost_price===null?'待補':`$${money(t.cost_price)}`}</option>)}</select></label><small>只列出相同計價單位，避免重量與容量混用。</small></>}<div><button type="button" className="recipe-secondary" disabled={busy} onClick={()=>setMoving(null)}>取消調整</button><button type="button" className="shell-primary" disabled={busy} onClick={()=>void saveMove()}>確認歸屬</button></div></div>}
   </section>}
   {editing.row&&<details className="catalog-sources" onToggle={e=>{if(e.currentTarget.open)void loadSources();}}><summary>查看原表與價格來源</summary>{sourceBusy&&<p role="status">讀取來源…</p>}{sourceError&&<p role="alert">{sourceError}<button type="button" onClick={()=>void loadSources()}>重試</button></p>}{sources?.map(source=><article key={source.id}><strong>{source.name}</strong><p>{source.price===null?'待補價格':`NT$ ${money(source.price)}／${source.unit}`} · {source.effective_date||'原表未記載日期'}</p><small>{source.source_ref?.supplier_name||source.source}{source.review_status==='pending'?' · 原報價待確認':''}</small>{source.purchase&&<small>原表：{source.purchase.amount} 元／{source.purchase.quantity} {source.purchase.unit}</small>}{source.source_ref?.review_note&&<small>{source.source_ref.review_note}</small>}<div>{safeLink(source.source_ref?.url)&&<a href={safeLink(source.source_ref?.url)} target="_blank" rel="noreferrer">查看原表 ↗</a>}{catalog.can_price&&source.price!==null&&<button type="button" className="text-button" disabled={busy||!!moving} onClick={()=>change({price:String(source.price),unit:source.unit,reference:source.id})}>{editing.draft.reference===source.id?'已選用':source.review_status==='pending'?'採用並確認此價':'採用此價'}</button>}</div></article>)}</details>}
   {error&&<p className="recipe-alert" role="alert">{error}</p>}
   <footer className="catalog-footer"><button type="button" className="recipe-secondary" disabled={busy} onClick={close}>取消</button>{catalog.can_price&&<button type="submit" className="shell-primary" disabled={busy||!!moving}>{busy?'儲存中…':'儲存修改'}</button>}</footer>
  </form>
 </aside>}
 </section>;
}
