'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase-browser';
import {parseInventoryWorkbook,readInventoryWorkbook} from '@/lib/inventory-import';
import {readInventoryPdf} from '@/lib/inventory-pdf-browser';
import {appError} from '@/lib/app-workspace';
import {restoreReviewRows,restoreReviewEdits,emptyReviewRow,importStatusLabels,normalizeReview,reviewIssues,reviewPayload,workbookReview,type ReviewRow,type ReviewStatus,type ImportSource} from '@/lib/inventory-review';
import {workspaceStorage} from '@/lib/workspace-storage';
import type {Json} from '@/lib/database.types';
export default function InventoryImportFlow({userId,storeId,organizationId,disabled,onImported}:{userId:string;storeId:string;organizationId:string;disabled:boolean;onImported:()=>Promise<void>}) {
 const[rows,setRows]=useState<ReviewRow[]>([]);const[source,setSource]=useState<ImportSource>();const[files,setFiles]=useState<ImportSource[]>([]);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState('');const[model,setModel]=useState('');const[onlyPending,setOnlyPending]=useState(false);
 async function loadFiles(){const result=await supabase.from('inventory_import_files').select('id,original_filename,file_sha256,storage_path,sheet_names').eq('store_id',storeId).order('created_at',{ascending:false}).limit(30);if(result.data)setFiles(result.data.map(f=>({...f,sheet_names:Array.isArray(f.sheet_names)?f.sheet_names.map(String):[]})));}
 // eslint-disable-next-line react-hooks/set-state-in-effect,react-hooks/exhaustive-deps
 useEffect(()=>{void loadFiles();},[storeId]);
 const saves=useRef<Promise<void>>(Promise.resolve());const editTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const pendingEdits=useRef<{file:ImportSource;rows:ReviewRow[]}|null>(null);
 const draftKey=(f:ImportSource)=>`inventory-review:${userId}:${storeId}:${f.file_sha256}`;
 function readDraft(f:ImportSource):Record<string,Partial<ReviewRow>>{try{const value=JSON.parse(workspaceStorage(userId).getItem(draftKey(f))||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch{return {};}}
 function clearDraft(f:ImportSource,review:ReviewRow[]){const draft=readDraft(f);for(const row of review)if(JSON.stringify(draft[row.sourceId])===JSON.stringify(row)||['ADDED','EXISTING','SKIPPED'].includes(row.status))delete draft[row.sourceId];try{workspaceStorage(userId).setItem(draftKey(f),JSON.stringify(draft));}catch{}}
 async function saveReview(file:ImportSource,review:ReviewRow[]){const saved=saves.current.catch(()=>{}).then(async()=>{await writeReview(file,review);clearDraft(file,review);});saves.current=saved.catch(()=>{});return saved;}
 async function flushEdits(){if(editTimer.current)clearTimeout(editTimer.current);const pending=pendingEdits.current;pendingEdits.current=null;if(pending)await saveReview(pending.file,pending.rows);await saves.current;}
 // Edits survive an immediate reload locally; writes are serialized to preserve order.
 useEffect(()=>()=>{if(editTimer.current)clearTimeout(editTimer.current);},[]);
 async function writeReview(file:ImportSource,review:ReviewRow[]){const result=await supabase.rpc('save_inventory_import_review',{p_store_id:storeId,p_file:file as unknown as Json,p_rows:review.map(r=>({source_id:r.sourceId,sheet_name:r.sheetName,source_row:r.sourceRow,raw_values:r.rawValues,merged_ranges:r.mergedRanges,normalized_values:normalizeReview(r),status:r.status,reason:r.reason})) as unknown as Json});if(result.error)throw result.error;}
 async function readFile(file:File){if(disabled||busy)return;setBusy(true);setNotice('正在保存原檔與辨識欄位…');setRows([]);setModel('');
 try{await flushEdits();if(!/\.(xlsx?|csv|pdf)$/i.test(file.name))throw Error('請選擇 Excel、CSV 或 PDF。');if(file.size>15*1024*1024)throw Error('檔案最多 15 MB，請分成較小檔案。');const bytes=await file.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');const meta:ImportSource={original_filename:file.name,file_sha256:hash,storage_path:`${organizationId}/${storeId}/${hash}/${file.name.normalize('NFKC').replace(/[^A-Za-z0-9._-]+/g,'-')||'inventory'}`,sheet_names:[]};const previous=files.find(f=>f.file_sha256===hash);if(previous){await resume(previous);return;}setSource(meta);
 const uploaded=await supabase.storage.from('inventory-imports').upload(meta.storage_path,bytes,{contentType:/\.pdf$/i.test(file.name)?'application/pdf':file.type||'application/octet-stream',upsert:false});if(uploaded.error&&!/duplicate|already exists|resource exists/i.test(uploaded.error.message))throw uploaded.error;await saveReview(meta,[]);
 await recognize(bytes,meta);await loadFiles();
 }catch(error){setNotice(error instanceof Error?error.message:appError(error));await loadFiles();}finally{setBusy(false);}}
 async function recognize(bytes:ArrayBuffer,meta:ImportSource){
 let review:ReviewRow[];
 if(/\.pdf$/i.test(meta.original_filename)){
  const parsed=await readInventoryPdf(bytes);
  if(parsed){meta.sheet_names=parsed.sheets.map(s=>s.sheetName);review=workbookReview(parsed);setModel('PDF 文字層');}
  else{setNotice('掃描 PDF 辨識中，原檔已保存…');const result=await supabase.functions.invoke('process-inventory-pdf',{body:{storeId,storagePath:meta.storage_path}});if(result.error||!result.data?.rows){let message=result.data?.message;if(!message&&result.error?.context instanceof Response){const body=await result.error.context.json().catch(()=>null);message=body?.message;}throw Error(message||'掃描 PDF 辨識未完成，原始檔已保留，請重試。');}
  review=result.data.rows.map((r:{page:number;row:number;name?:string;unit?:string;quantity:number|null;specification?:string;supplier?:string;zone?:string;raw?:string;uncertain?:boolean;skip_reason?:string})=>({...emptyReviewRow(`第 ${r.page} 頁`,r.row),name:r.name||'',unit:r.unit||'',openingQuantity:r.quantity,quantityText:r.quantity===null||r.quantity===undefined?'':String(r.quantity),specification:r.specification||'',supplierName:r.supplier||'',zoneName:r.zone||'未分類',rawValues:{原文:r.raw||''},status:r.skip_reason?'SKIPPED':'PENDING',reason:r.skip_reason||(r.uncertain?'辨識不確定，請核對原文':'請確認後建立')}));meta.sheet_names=[...new Set(review.map(r=>r.sheetName))];setModel(`${result.data.model}・${(result.data.durationMs/1000).toFixed(1)} 秒`);}
 }else{const parsed=parseInventoryWorkbook(readInventoryWorkbook(bytes,meta.original_filename));meta.sheet_names=parsed.sheets.map(s=>s.sheetName);review=workbookReview(parsed);}
 setSource({...meta});setRows(review);await saveReview(meta,review);setNotice('請確認品名、單位與數量；確認後才建立品項。');
 }
 async function resume(file:ImportSource){setBusy(true);setNotice('正在讀取來源與待處理列…');setRows([]);setModel('');try{await flushEdits();setSource(file);const all=[];for(let offset=0;;offset+=1000){const r=await supabase.from('inventory_import_rows').select('*').eq('store_id',storeId).eq('import_file_id',file.id!).order('sheet_name').order('source_row').order('id').range(offset,offset+999);if(r.error)throw r.error;all.push(...r.data);if(r.data.length<1000)break;}
 if(!all.length){const original=await supabase.storage.from('inventory-imports').download(file.storage_path);if(original.error)throw original.error;await recognize(await original.data.arrayBuffer(),file);return;}
 const saved=restoreReviewRows(all,file.sheet_names);const drafts=readDraft(file);const restored=restoreReviewEdits(saved,drafts);setRows(restored);const changed=restored.filter(r=>r!==saved.find(s=>s.sourceId===r.sourceId));if(changed.length)await saveReview(file,changed);setNotice('已讀取原有結果與修正；只會重試未建立的列。');}catch(e){setNotice(e instanceof Error?e.message:appError(e));}finally{setBusy(false);}}
 async function commit(){if(!source||busy||disabled)return;setBusy(true);let next=rows.map(r=>({...r}));try{await flushEdits();const candidates=next.filter(r=>['PENDING','FAILED'].includes(r.status));for(const r of candidates){r.reason=reviewIssues(r);if(r.reason)r.status='PENDING';}await saveReview(source,next);
 const valid=candidates.filter(r=>!reviewIssues(r));for(let start=0;start<valid.length;start+=500){const chunk=valid.slice(start,start+500);const response=await supabase.rpc('import_pilot_inventory',{p_store_id:storeId,p_rows:{file:source,rows:chunk.map(reviewPayload)} as unknown as Json});if(response.error)throw response.error;
 const results=response.data as unknown as {source_id:string;status:ReviewStatus;reason:string}[];next=next.map(row=>{const saved=results.find(r=>r.source_id===row.sourceId);return saved?{...row,status:saved.status,reason:saved.reason}:row;});setRows([...next]);}
 clearDraft(source,next);setNotice(`成功 ${next.filter(r=>r.status==='ADDED').length}、既有 ${next.filter(r=>r.status==='EXISTING').length}、待確認 ${next.filter(r=>r.status==='PENDING').length}、失敗 ${next.filter(r=>r.status==='FAILED').length}、略過 ${next.filter(r=>r.status==='SKIPPED').length}。匯入建立品項與期初，不等於完成當日盤點。`);if(next.some(r=>['ADDED','EXISTING'].includes(r.status)))await onImported();await loadFiles();
 }catch(e){setNotice(appError(e));}finally{setRows([...next]);setBusy(false);}}
 async function skip(id:string){if(!source||busy)return;const next=rows.map(r=>r.sourceId===id?{...r,status:'SKIPPED' as ReviewStatus,reason:'使用者確認非品項，略過'}:r);setBusy(true);try{await flushEdits();await saveReview(source,next);setRows(next);setNotice('略過原因已保存。');}catch(e){setNotice(appError(e));}finally{setBusy(false);}}
 const edit=(id:string,patch:Partial<ReviewRow>)=>{if(!source)return;const next:ReviewRow[]=rows.map(r=>r.sourceId===id?{...r,...patch,status:'PENDING'}:r);setRows(next);const row=next.find(r=>r.sourceId===id)!;const draft=readDraft(source);draft[id]=row;try{workspaceStorage(userId).setItem(draftKey(source),JSON.stringify(draft));}catch{setNotice('裝置暫存空間不足，請等待修正儲存後再離開。');}const changed=[...(pendingEdits.current?.rows.filter(r=>r.sourceId!==id)||[]),row];pendingEdits.current={file:source,rows:changed};if(editTimer.current)clearTimeout(editTimer.current);editTimer.current=setTimeout(()=>{void flushEdits().then(()=>setNotice('修正已保存，確認後才建立品項。')).catch(()=>setNotice('修正尚未儲存到伺服器；請保留本頁並重試。'));},350);};
 return <><section className="shell-card upload-shell"><h2>Excel／CSV／PDF</h2><p>{disabled?'本次盤點進行中，完成後可再次匯入。':'空白數量保留「未提供」，沒有區域放「未分類」。'}</p><label className="import-button">{busy?'處理中…':'選擇檔案'}<input type="file" accept=".xlsx,.xls,.csv,.pdf" disabled={disabled||busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void readFile(f);}}/></label></section>
 {files.length>0&&<details className="setup-panel"><summary>繼續處理既有匯入</summary>{files.map(f=><button className="shell-list-row" key={f.id} disabled={busy} onClick={()=>void resume(f)}>{f.original_filename} ›</button>)}</details>}
 {notice&&<p className="pilot-message" role="status">{notice}</p>}{model&&<p className="shell-note">辨識方式：{model}</p>}
 {rows.length>0&&<section className="shell-section"><h2>確認品項</h2><p>{Object.entries(importStatusLabels).map(([key,label])=>`${label} ${rows.filter(r=>r.status===key).length}`).join('・')}</p><label className="checkbox-row"><input type="checkbox" checked={onlyPending} onChange={e=>setOnlyPending(e.target.checked)}/>只看待確認／失敗</label>
 {rows.filter(r=>!onlyPending||['PENDING','FAILED'].includes(r.status)).map(r=><article className="shell-card import-review-row" key={r.sourceId}><strong>{r.sheetName} 第 {r.sourceRow} 列・{importStatusLabels[r.status]}</strong><small>{r.reason}</small>{['PENDING','FAILED'].includes(r.status)?<><label className="field">品名<input disabled={busy} value={r.name} onChange={e=>edit(r.sourceId,{name:e.target.value})}/></label><div className="import-review-fields"><label className="field">單位<input disabled={busy} value={r.unit} maxLength={30} onChange={e=>edit(r.sourceId,{unit:e.target.value})}/></label><label className="field">期初數量（可留白）<input disabled={busy} inputMode="decimal" placeholder="未提供" value={r.quantityText} onChange={e=>edit(r.sourceId,{quantityText:e.target.value})}/></label></div><details><summary>來源原文／其他資料</summary><p className="source-raw">{Object.entries(r.rawValues).map(([k,v])=>`${k}：${v}`).join('；')}</p><label className="field">區域<input disabled={busy} value={r.zoneName} onChange={e=>edit(r.sourceId,{zoneName:e.target.value})}/></label><label className="field">規格<input disabled={busy} value={r.specification} onChange={e=>edit(r.sourceId,{specification:e.target.value})}/></label><label className="field">廠商<input disabled={busy} value={r.supplierName} onChange={e=>edit(r.sourceId,{supplierName:e.target.value})}/></label></details><button type="button" className="text-button" disabled={busy} onClick={()=>void skip(r.sourceId)}>略過此列</button></>:<p>{r.name} {r.quantityText||'未提供'} {r.unit}</p>}</article>)}
 <button className="shell-primary full" disabled={busy||disabled||!rows.some(r=>['PENDING','FAILED'].includes(r.status))} onClick={()=>void commit()}>{busy?'儲存中…':'確認建立／重試未完成列'}</button></section>}</>;
}
