'use client';
import {useState} from 'react';
import {supabase} from '@/lib/supabase-browser';
import {canManageBusiness,roleLabel,type AppRole,type AppStore} from '@/lib/app-workspace';
import {useOperation,useWorkspace} from './operation-hooks';
import StaffSettings from './staff-settings';
import {displayTime} from './inventory-catalog';
type Member={extra_permissions:string[];can_manage_business:boolean;zone_ids:string[];user_id:string;display_name:string;login_identifier:string;role:AppRole|'ADMIN';is_active:boolean;is_owner:boolean;uses_pin:boolean;email:string|null;updated_at:string;pending_count:number};
type Delegation={id:string;user_id:string;display_name:string;starts_at:string;ends_at:string;revoked_at:string|null};
export default function MembersWorkspace({store,userId,section,onBack,onChanged}:{store:AppStore;userId:string;section:'members'|'permissions';onBack:()=>void;onChanged:()=>Promise<void>}){
 const workspace=useWorkspace<{members:Member[];zones:{id:string;name:string}[];candidates:{user_id:string;display_name:string;role:AppRole;login_identifier:string}[];invitations:{id:string;email:string;display_name:string;role:AppRole;mail_state:string;mail_error:string;expires_at:string}[];delegations:Delegation[]}>(store.id,section);const operation=useOperation(store.id,userId);
 const[page,setPage]=useState('home');const[current,setCurrent]=useState<Member>();const[notice,setNotice]=useState('');const[activation,setActivation]=useState('');const[resetting,setResetting]=useState(false);
 const[handoffTo,setHandoffTo]=useState('');const[keepAdmin,setKeepAdmin]=useState(false);const[assign,setAssign]=useState({user_id:'',login_identifier:'',role:'STAFF'});
 const[delegate,setDelegate]=useState({user_id:'',starts_at:'',ends_at:''});const owner=canManageBusiness(store);
 const members=workspace.data?.members||[];const canEdit=(m:Member)=>m.user_id!==userId&&!m.is_owner&&(owner||(m.role==='STAFF'&&!m.can_manage_business));
 const save=async()=>{if(!current)return;const result=await operation.run('member.save',current);if(result){setNotice('成員資料已更新。');setPage('list');await workspace.refresh();await onChanged();}};
 const reset=async()=>{if(!current||resetting)return;setResetting(true);setActivation('');try{const{data,error}=await supabase.functions.invoke('manage-staff',{body:{action:'reset_pin',staffId:current.user_id,storeId:store.id}});if(error||!data?.activationCode)throw Error();setActivation(data.activationCode);setNotice('請將新的啟用碼交給本人，重新設定 PIN。');}catch{operation.setError('PIN 重設未完成，請重試。');}finally{setResetting(false);}};
 const label=(role:Member['role'])=>roleLabel(role==='ADMIN'?'SUPERVISOR':role,store.business_type);
 return <><button className="shell-back" onClick={()=>page==='home'?onBack():setPage('home')}>‹ {page==='home'?'返回我的':`返回${section==='members'?'成員與權限':'角色與權限'}`}</button><h1>{section==='members'?'成員與權限':'角色與權限'}</h1>{notice&&<p role="status">{notice}</p>}{(workspace.error||operation.error)&&<p className="pilot-message" role="alert">{operation.error||workspace.error}<button onClick={()=>void workspace.refresh()}>重新讀取</button></p>}
 {page==='home'&&<div className="shell-card shell-list"><button className="shell-list-row" onClick={()=>setPage('list')}><span><strong>{section==='members'?'成員清單':'角色權限'}</strong><small>新增、停用與調整門市角色</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>setPage('delegations')}><span><strong>代理主管</strong><small>設定代理期間與必要權限</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>setPage(section==='members'?'handoff':'scope')}><span><strong>{section==='members'?'離職交接':'管理範圍'}</strong><small>保留歷史與授權範圍</small></span><b>›</b></button></div>}
 {page==='list'&&<><button className="shell-secondary full" onClick={()=>setPage('new')}>新增成員</button><div className="shell-card shell-list">{members.map(m=><button className="shell-list-row" key={m.user_id} onClick={()=>{setCurrent(m);setActivation('');setNotice('');setPage('edit');}}><span><strong>{m.display_name}</strong><small>{m.uses_pin?m.login_identifier:m.email||m.login_identifier}・{label(m.role)}</small></span><b>{m.is_active?'使用中':'已停用'}</b></button>)}</div>{workspace.data?.invitations.map(i=><article className="shell-card settings-card" key={i.id}><strong>{i.display_name}・{label(i.role)}</strong><p>{i.email}</p><p>等待本人確認加入・{i.mail_state==='SENT'?'邀請信已寄出':i.mail_state==='FAILED'?'寄送失敗，請重新寄送':'邀請寄送中'}</p><div className="shell-button-stack"><button className="shell-secondary" disabled={resetting} onClick={async()=>{setResetting(true);try{const r=await supabase.functions.invoke('manage-staff',{body:{action:'invite_management',storeId:store.id,email:i.email,displayName:i.display_name,role:i.role}});if(r.error)throw r.error;setNotice(r.data.pending?'請稍後再寄；本人仍可登入並確認加入。':'邀請信已重新寄出。');await workspace.refresh();}catch{operation.setError('邀請信未能寄出，請稍後重試。');}finally{setResetting(false);}}}>重新寄送</button><button type="button" className="text-button" disabled={operation.busy} onClick={async()=>{if(await operation.run('invite.cancel',{id:i.id}))await workspace.refresh();}}>撤銷邀請</button></div></article>)}</>}
 {page==='new'&&<StaffSettings stores={[store]} canManageStores={owner} businessType={store.business_type} createOnly onWorkspaceChanged={async()=>{await workspace.refresh();await onChanged();}}/>}
 {page==='edit'&&current&&<form onSubmit={e=>{e.preventDefault();void save();}}><section className="shell-card transfer-form"><label>姓名<input disabled={!canEdit(current)} value={current.display_name} onChange={e=>setCurrent({...current,display_name:e.target.value})} required/></label><label>{current.uses_pin?'登入識別':'門市識別（Email 登入帳號不變）'}<input disabled={!canEdit(current)} value={current.login_identifier} onChange={e=>setCurrent({...current,login_identifier:e.target.value})} required/></label>{!current.uses_pin&&<p>Email 登入：{current.email||'未提供'}</p>}<label>工作身分<select disabled={!owner||!canEdit(current)} value={current.role==='ADMIN'?'SUPERVISOR':current.role} onChange={e=>setCurrent({...current,role:e.target.value as AppRole})}>{(['STAFF','SUPERVISOR','LOGISTICS','OWNER'] as const).map(r=><option value={r} key={r}>{roleLabel(r,store.business_type)}</option>)}</select></label>{!!workspace.data?.zones.length&&<fieldset><legend>負責儲放區（選填）</legend>{workspace.data.zones.map(z=><label className="checkbox-row" key={z.id}><input type="checkbox" disabled={!canEdit(current)} checked={current.zone_ids.includes(z.id)} onChange={e=>setCurrent({...current,zone_ids:e.target.checked?[...current.zone_ids,z.id]:current.zone_ids.filter(id=>id!==z.id)})}/>{z.name}</label>)}</fieldset>}{owner&&<fieldset><legend>額外功能權限</legend>{[['REPORTS_VIEW','報表查看'],['DATA_EXPORT','資料匯出']].map(([key,title])=><label className="checkbox-row" key={key}><input type="checkbox" disabled={!canEdit(current)} checked={current.extra_permissions.includes(key)} onChange={e=>setCurrent({...current,extra_permissions:e.target.checked?[...current.extra_permissions,key]:current.extra_permissions.filter(v=>v!==key)})}/>{title}</label>)}<p className="shell-note">工作身分的基本功能保留；這裡只增加本店的功能。</p><label className="checkbox-row"><input type="checkbox" disabled={!canEdit(current)} checked={current.can_manage_business} onChange={e=>setCurrent({...current,can_manage_business:e.target.checked})}/>商家管理：設定商家、邀請與授權成員</label><p className="shell-note">商家管理依已授權門市範圍生效，不更換工作身分。</p></fieldset>}<label className="checkbox-row"><input type="checkbox" disabled={!canEdit(current)} checked={current.is_active} onChange={e=>setCurrent({...current,is_active:e.target.checked})}/>此門市使用中</label></section>{canEdit(current)&&<div className="shell-button-stack"><button className="shell-primary" disabled={operation.busy}>{operation.busy?'儲存中…':'儲存變更'}</button>{current.is_active&&current.uses_pin&&<button type="button" className="shell-secondary" disabled={resetting||operation.busy} onClick={()=>void reset()}>重設 PIN</button>}</div>}{activation&&<article className="shell-card settings-card"><h3>重新設定 PIN</h3><p>{current.display_name}・{store.store_code}・{current.login_identifier}</p><code className="break-word">{activation}</code><p>本人於員工快速登入使用此啟用碼重新設定 PIN，7 天內有效。</p></article>}</form>}
 {page==='delegations'&&<><div className="shell-card shell-list">{workspace.data?.delegations.map(d=><div key={d.id} className="shell-list-row"><span><strong>{d.display_name}</strong><small>{displayTime(d.starts_at)} 至 {displayTime(d.ends_at)}</small><small>{d.revoked_at?'已撤銷':new Date(d.ends_at)<new Date()?'已到期':'有效期間內可代理主管'}</small></span>{owner&&!d.revoked_at&&new Date(d.ends_at)>new Date()&&<button type="button" className="text-button" disabled={operation.busy} onClick={async()=>{const r=await operation.run('delegation.revoke',{id:d.id,user_id:d.user_id});if(r)await workspace.refresh();}}>撤銷</button>}</div>)}</div>{owner&&<form onSubmit={async e=>{e.preventDefault();const r=await operation.run('delegation.create',{...delegate,starts_at:new Date(delegate.starts_at).toISOString(),ends_at:new Date(delegate.ends_at).toISOString()});if(r){setDelegate({user_id:'',starts_at:'',ends_at:''});await workspace.refresh();}}}><section className="shell-card transfer-form"><label>代理成員<select value={delegate.user_id} onChange={e=>setDelegate({...delegate,user_id:e.target.value})} required><option value="">選擇成員</option>{members.filter(m=>m.role==='STAFF'&&m.is_active).map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></label><label>開始時間<input type="datetime-local" value={delegate.starts_at} onChange={e=>setDelegate({...delegate,starts_at:e.target.value})} required/></label><label>結束時間<input type="datetime-local" value={delegate.ends_at} onChange={e=>setDelegate({...delegate,ends_at:e.target.value})} required/></label></section><button className="shell-primary full" disabled={operation.busy}>儲存代理設定</button></form>}</>}
 {page==='scope'&&<>{owner&&!!workspace.data?.candidates?.length&&<form onSubmit={async e=>{e.preventDefault();const r=await operation.run('member.assign',assign);if(r){setAssign({user_id:'',login_identifier:'',role:'STAFF'});await workspace.refresh();}}}><section className="shell-card transfer-form"><label>授權既有成員<select value={assign.user_id} onChange={e=>{const m=workspace.data?.candidates.find(m=>m.user_id===e.target.value);setAssign({user_id:e.target.value,login_identifier:m?.login_identifier||'',role:m?.role||'STAFF'});}} required><option value="">選擇成員</option>{workspace.data.candidates.map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></label><label>本店登入識別<input value={assign.login_identifier} onChange={e=>setAssign({...assign,login_identifier:e.target.value})} required maxLength={64}/></label><p>工作身分：{label(assign.role as AppRole)}。增加門市不更換原身分。</p></section><button className="shell-primary full" disabled={operation.busy}>儲存授權</button></form>}<p>目前門市：{store.name}。上方門市選單只列出您有權限使用的門市。</p><div className="shell-card shell-list">{members.map(m=><button className="shell-list-row" key={m.user_id} onClick={()=>{setCurrent(m);setPage('edit');}}><span><strong>{m.display_name}</strong><small>{label(m.role)}・{store.name}</small></span><b>›</b></button>)}</div></>}
 {page==='handoff'&&<>{store.is_business_responsible&&<form onSubmit={async e=>{e.preventDefault();const r=await operation.run('business.transfer',{user_id:handoffTo,keep_admin:keepAdmin});if(r){setNotice('商家管理責任已交接，雙方工作身分與歷史資料保留。');setHandoffTo('');await workspace.refresh();await onChanged();}}}><section className="shell-card transfer-form"><h2>商家管理責任交接</h2><p>接手者取得此商家所有門市的管理範圍；工作身分保持不變。此動作與下方離職交接分開。</p><label>接手管理者<select value={handoffTo} onChange={e=>setHandoffTo(e.target.value)} required><option value="">選擇已加入的管理成員</option>{members.filter(m=>m.is_active&&m.user_id!==userId&&!m.uses_pin&&m.role!=='STAFF').map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}・{label(m.role)}</option>)}</select></label><label className="checkbox-row"><input type="checkbox" checked={keepAdmin} onChange={e=>setKeepAdmin(e.target.checked)}/>保留我的商家管理權限</label><p className="shell-note">未勾選時撤回我的商家管理權；原帳號、門市工作權限及歷史紀錄保留。</p><button className="shell-primary full" disabled={operation.busy}>交接商家管理責任</button></section></form>}<p>先將未完成事項交接，再停用成員；既有工作紀錄會保留經手人與時間。</p><div className="shell-card shell-list">{members.filter(canEdit).map(m=><button className="shell-list-row" key={m.user_id} onClick={()=>{setCurrent(m);setHandoffTo('');setPage('offboard');}}><span><strong>{m.display_name}</strong><small>{label(m.role)}・待接續 {m.pending_count} 筆</small></span><b>›</b></button>)}</div></>}
 {page==='offboard'&&current&&<form onSubmit={async e=>{e.preventDefault();const r=await operation.run('member.offboard',{user_id:current.user_id,updated_at:current.updated_at,handoff_to:handoffTo||null});if(r){setNotice('此門市權限已停用，交接與歷史資料已保留。');setPage('list');await workspace.refresh();}}}><section className="shell-card transfer-form"><h2>{current.display_name}</h2><p>此門市有 {current.pending_count} 筆待接續事項。共同盤點與進貨進度保留供現有同仁接手。</p><label>接手成員<select value={handoffTo} onChange={e=>setHandoffTo(e.target.value)} required={current.pending_count>0}><option value="">選擇接手人</option>{members.filter(m=>m.is_active&&m.user_id!==current.user_id).map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></label></section><button className="shell-primary full" disabled={operation.busy}>完成交接並停用</button></form>}
 </>;
}
