'use client';
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {exportRows} from './reports-workspace';
import {sheetFingerprint,sheetImports,sheetNumber,type SheetColumn,type SheetRow,type SheetValues} from '@/lib/operations-sheet';
import './operations-sheet.css';
export type SheetProps={title:string;scope:string;rows:SheetRow[];columns:SheetColumn[];defaults:SheetValues;loading:boolean;error:string;month:string;onMonth:(month:string)=>void;onRefresh:()=>Promise<void>;onSave:(row:SheetRow)=>Promise<void>;onRemove:(rows:SheetRow[],restore:boolean)=>Promise<void>;registerLeave?:(guard:(()=>Promise<boolean>)|null)=>void;summary?:ReactNode;special?:ReactNode;readOnly?:boolean;canExport?:boolean;deleteNote?:string;onSubmit?:(rows:SheetRow[])=>Promise<void>;onSource?:(row:SheetRow)=>void};
export default function OperationsSheet(p:SheetProps){
 const [query,setQuery]=useState(''),[state,setState]=useState('LIVE'),[editing,setEditing]=useState(false),[drafts,setDrafts]=useState<Record<string,SheetRow>>({}),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const registerLeave=p.registerLeave;
 const lock=useRef(false),input=useRef<HTMLInputElement>(null),composition=useRef(false),draftRef=useRef(drafts);useEffect(()=>{draftRef.current=drafts;},[drafts]);
 const dirty=Object.values(drafts).filter(r=>r.fresh||!p.rows.some(o=>o.id===r.id&&sheetFingerprint(o.values,p.columns)===sheetFingerprint(r.values,p.columns)));
 const guard=useCallback(async()=>!lock.current&&(!Object.keys(draftRef.current).length||window.confirm('尚有未儲存的編輯，確定離開？')) ,[]);
 useEffect(()=>{registerLeave?.(guard);const before=(e:BeforeUnloadEvent)=>{if(lock.current||Object.keys(draftRef.current).length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>{registerLeave?.(null);window.removeEventListener('beforeunload',before);};},[registerLeave,guard]);
 const base=[...Object.values(drafts).filter(r=>r.fresh),...p.rows.map(r=>drafts[r.id]||r)];
 const visible=base.filter(r=>(r.state||'LIVE')===state&&Object.values(r.values).join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 const chosen=visible.filter(r=>selected.includes(r.id)&&!r.locked);
 function change(row:SheetRow,key:string,value:string){setDrafts(old=>({...old,[row.id]:{...row,values:{...row.values,[key]:value,...(['quantity','price'].includes(key)?{amount:(key==='quantity'?value:row.values.quantity)&&(key==='price'?value:row.values.price)?String(Number(key==='quantity'?value:row.values.quantity)*Number(key==='price'?value:row.values.price)):''}:{})},requestId:row.requestId||crypto.randomUUID()}}));}
 function add(){const id=crypto.randomUUID();setState('LIVE');setQuery('');setEditing(true);setDrafts(old=>({...old,[id]:{id,values:{...p.defaults},fresh:true,state:'LIVE',requestId:id}}));}
 function cancel(){if(dirty.length&&!window.confirm('取消尚未儲存的修改？'))return;setDrafts({});setEditing(false);setError('');setNotice('');}
 async function save(){if(lock.current||composition.current||p.readOnly||p.loading||p.error)return;lock.current=true;setBusy(true);setError('');let saved=0;
  try{for(const row of dirty){for(const col of p.columns){if(col.required&&!row.values[col.key]?.trim())throw Error(`「${col.label}」尚未填寫。`);if(col.type==='number')sheetNumber(row.values[col.key]||'');}await p.onSave(row);saved++;setDrafts(old=>{const next={...old};delete next[row.id];return next;});}setEditing(false);setNotice(`已儲存 ${saved} 筆。`);await p.onRefresh();}
  catch(e){if(saved)await p.onRefresh();setError(`${e instanceof Error?e.message:'儲存未確認，請重試。'} 已完成 ${saved} 筆，其餘輸入保留；重試不會重複建立已成功資料。`);}
  finally{lock.current=false;setBusy(false);}
 }
 async function remove(){if(lock.current||p.readOnly||p.loading||p.error||!chosen.length)return;const restore=state==='REMOVED';if(!window.confirm(restore?`還原 ${chosen.length} 筆？`:`將 ${chosen.length} 筆移至已移除？${p.deleteNote||'歷史紀錄會保留。'}`))return;lock.current=true;setBusy(true);setError('');try{const saved=chosen.filter(r=>!r.fresh);if(saved.length)await p.onRemove(saved,restore);setDrafts(old=>Object.fromEntries(Object.entries(old).filter(([id])=>!chosen.some(r=>r.id===id))));setSelected([]);await p.onRefresh();}catch(e){setError(e instanceof Error?e.message:'操作未完成，請重試。');}finally{lock.current=false;setBusy(false);}}
 async function submit(){if(lock.current||p.readOnly||p.loading||p.error||dirty.length||!chosen.length||!p.onSubmit)return;lock.current=true;setBusy(true);setError('');try{await p.onSubmit(chosen);setSelected([]);setNotice('已送交財務。');await p.onRefresh();}catch(e){setError(e instanceof Error?e.message:'送交未完成，請重試。');await p.onRefresh();}finally{lock.current=false;setBusy(false);}}
 async function importFiles(files:FileList|null){if(!files?.length||lock.current)return;lock.current=true;setBusy(true);setError('');try{const XLSX=await import('xlsx');const records:Record<string,unknown>[]=[];for(const file of Array.from(files)){if(!/\.(xlsx?|csv)$/i.test(file.name))throw Error('請使用 Excel 或 CSV。');const book=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});for(const name of book.SheetNames)records.push(...XLSX.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[name],{defval:'',raw:false}));}if(records.length>2000)throw Error('每次最多匯入 2,000 列。');const result=sheetImports(records,p.columns,base,p.defaults,()=>crypto.randomUUID());setDrafts(old=>({...old,...Object.fromEntries(result.rows.map(r=>[r.id,r]))}));setQuery('');setState('LIVE');setEditing(true);setNotice(`匯入預覽 ${result.rows.length} 筆，略過 ${result.skipped} 筆重複資料；確認表格後按「儲存變更」才會建檔。`);}catch(e){setError(e instanceof Error?e.message:'檔案讀取失敗。');}finally{lock.current=false;setBusy(false);if(input.current)input.current.value='';}}
 async function download(template=false){try{const rows=template?[Object.fromEntries(p.columns.filter(c=>!c.readonly).map(c=>[c.label,'']))]:(chosen.length?chosen:visible).filter(r=>!r.fresh).map(r=>({'資料編號':r.id,...Object.fromEntries(p.columns.map(c=>[c.label,r.values[c.key]??'']))}));await exportRows(rows,'xlsx',`${p.title}_${template?'匯入範本':p.month}`);}catch{setError('匯出失敗，請重試。');}}
 return <section className="operations-sheet" data-module={p.scope}><header><h1>{p.title}</h1><button className="sheet-button" disabled={busy||dirty.length>0} onClick={()=>void p.onRefresh()}>重新讀取</button></header>{p.summary&&<div className="sheet-summary">{p.summary}</div>}
 <div className="sheet-filters"><input aria-label="搜尋明細" type="search" placeholder="搜尋品名、供應商、備註…" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="明細月份" type="month" value={p.month} disabled={busy||dirty.length>0} onChange={e=>{if(e.target.value)p.onMonth(e.target.value);}}/><select aria-label="資料狀態" value={state} disabled={busy||dirty.length>0} onChange={e=>setState(e.target.value)}><option value="LIVE">正式資料</option><option value="TEST">測試資料</option><option value="REMOVED">已移除</option></select><span>{visible.length} 筆</span></div>
 <div className="sheet-actions"><button className="sheet-button primary" disabled={busy||p.readOnly||p.loading} onClick={add}>新增</button>{editing?<><button className="sheet-button primary" disabled={busy||p.readOnly||p.loading||!dirty.length} onClick={()=>void save()}>{busy?'儲存中…':'儲存變更'}</button><button className="sheet-button" disabled={busy} onClick={cancel}>取消編輯</button></>:<button className="sheet-button" disabled={busy||p.readOnly||p.loading||state==='REMOVED'} onClick={()=>setEditing(true)}>編輯全部</button>}<button className="sheet-button" disabled={busy||p.readOnly||!chosen.length||dirty.some(r=>!r.fresh)} onClick={()=>void remove()}>{state==='REMOVED'?'還原':'刪除'}（{chosen.length}）</button>{p.onSubmit&&<button className="sheet-button" disabled={busy||p.readOnly||p.loading||dirty.length>0||!chosen.length||state!=='LIVE'} onClick={()=>void submit()}>送交財務</button>}<span className="sheet-spacer"/><button className="sheet-button" disabled={busy||p.readOnly||p.loading} onClick={()=>input.current?.click()}>匯入</button><input ref={input} type="file" accept=".xlsx,.xls,.csv" multiple hidden onChange={e=>void importFiles(e.target.files)}/><button className="sheet-button" disabled={busy||p.canExport===false} onClick={()=>void download()}>匯出</button><button className="sheet-button" disabled={busy||p.readOnly} onClick={()=>void download(true)}>下載匯入範本</button>{p.special}</div>
 {(error||p.error)&&<p className="sheet-error" role="alert">{error||p.error}</p>}{notice&&<p className="sheet-notice" role="status">{notice}</p>}
 <div className="sheet-scroll"><table><thead><tr><th><input type="checkbox" aria-label="選取全部明細" checked={visible.some(r=>!r.locked)&&visible.filter(r=>!r.locked).every(r=>selected.includes(r.id))} onChange={e=>setSelected(e.target.checked?visible.filter(r=>!r.locked).map(r=>r.id):[])}/></th>{p.columns.map(c=><th key={c.key}>{c.label}</th>)}{p.onSource&&<th>原始資料</th>}</tr></thead><tbody>{visible.map(row=><tr key={row.id} className={row.fresh?'sheet-new':''}><td><input type="checkbox" aria-label={`選取 ${row.values.name||row.id}`} disabled={row.locked||busy} checked={selected.includes(row.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,row.id]:old.filter(id=>id!==row.id))}/></td>{p.columns.map(col=><td key={col.key}>{editing&&!p.readOnly&&!p.loading&&!col.readonly&&(!col.editable||col.editable(row))&&!row.locked&&state!=='REMOVED'?<><input aria-label={`${row.values.name||'新增'} ${col.label}`} list={col.options?`${p.scope}-${col.key}`:undefined} type={col.type||'text'} step={col.type==='number'?'any':undefined} value={row.values[col.key]||''} disabled={busy} onCompositionStart={()=>composition.current=true} onCompositionEnd={()=>composition.current=false} onChange={e=>change(row,col.key,e.target.value)}/></>:row.values[col.key]||(['price','amount'].includes(col.key)?'未計價':'—')}</td>)}{p.onSource&&<td>{!row.fresh&&<button className="sheet-link" onClick={()=>p.onSource?.(row)}>查看</button>}</td>}</tr>)}{!visible.length&&<tr><td colSpan={p.columns.length+1+(p.onSource?1:0)}>{p.loading?'讀取中…':p.error?'讀取未完成，請重試。':'目前沒有符合條件的資料。可新增或匯入。'}</td></tr>}</tbody></table></div>{p.columns.filter(c=>c.options).map(c=><datalist key={c.key} id={`${p.scope}-${c.key}`}>{c.options?.map(v=><option key={v} value={v}/>)}</datalist>)}<footer>已選取 {chosen.length} 筆{dirty.length?`・${dirty.length} 筆尚未儲存`:''}</footer></section>;
}
