'use client';
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {exportRows} from './reports-workspace';
import {sheetFingerprint,sheetImports,sheetNumber,changeSheetValues,type SheetColumn,type SheetRow,type SheetValues} from '@/lib/operations-sheet';
import {workspaceStorage} from '@/lib/workspace-storage';
import {sheetDraftKey,readSheetDraft,writeSheetDraft,draftStorageMessage,type SheetDraft} from '@/lib/operations-sheet-draft';
import './operations-sheet.css';
export type SheetProps={cloudDraft?:{read:()=>Promise<SheetDraft|null>;save:(rows:SheetRow[],expected:string|null,token:string)=>Promise<SheetDraft>};userId:string;title:string;scope:string;rows:SheetRow[];columns:SheetColumn[];defaults:SheetValues;loading:boolean;error:string;month:string;onMonth:(month:string)=>void;onRefresh:()=>Promise<void>;onSave:(row:SheetRow)=>Promise<void>;onRemove:(rows:SheetRow[],restore:boolean)=>Promise<void>;registerLeave?:(guard:(()=>Promise<boolean>)|null)=>void;summary?:ReactNode;special?:ReactNode;readOnly?:boolean;canExport?:boolean;deleteNote?:string;onSubmit?:(rows:SheetRow[])=>Promise<void>;onPrice?:(rows:SheetRow[])=>Promise<SheetRow[]>;onSource?:(row:SheetRow)=>void};
export default function OperationsSheet(p:SheetProps){
 const [onlyMissing,setOnlyMissing]=useState(false),[draftView,setDraftView]=useState(false);
 const [query,setQuery]=useState(''),[state,setState]=useState('LIVE'),[editing,setEditing]=useState(false),[drafts,setDrafts]=useState<Record<string,SheetRow>>({}),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const registerLeave=p.registerLeave;
 const [recovery,setRecovery]=useState<SheetDraft|null>(null),[draftLoaded,setDraftLoaded]=useState(''),[draftStatus,setDraftStatus]=useState('');
 const draftKey=sheetDraftKey(p.userId,p.scope,p.month),draftToken=useRef<string|null>(null);
 const lock=useRef(false),input=useRef<HTMLInputElement>(null),composition=useRef(false),draftRef=useRef<SheetRow[]>([]);
 const dirty=Object.values(drafts).filter(r=>r.fresh||!p.rows.some(o=>o.id===r.id&&sheetFingerprint(o.values,p.columns)===sheetFingerprint(r.values,p.columns)));
 useEffect(()=>{draftRef.current=dirty;});
 const cloudToken=useRef<string|null>(null),cloudReady=useRef(false);
 const [cloudStatus,setCloudStatus]=useState('');
 const cloud=p.cloudDraft;
 useEffect(()=>{if(!cloud)return;let active=true;void cloud.read().then(saved=>{if(!active)return;cloudToken.current=saved?.token||null;cloudReady.current=true;if(saved?.rows.length){if(!draftRef.current.length)setRecovery(local=>local?.rows.length?local:saved);setCloudStatus('系統有已保存草稿，可恢復後繼續；若本機另有修改，優先保留本機版本。');}}).catch(()=>{if(active)setCloudStatus('系統草稿讀取失敗，請重新讀取頁面後再保存草稿；本機輸入仍保留。');});return()=>{active=false;};},[cloud]);
 async function saveCloud(rows:SheetRow[]){if(!cloud)return;if(!cloudReady.current)throw Error('系統草稿尚未讀取，請先重新讀取頁面。');const saved=await cloud.save(rows,cloudToken.current,crypto.randomUUID());cloudToken.current=saved.token;setCloudStatus(rows.length?'草稿已保存至系統，同帳號可換裝置接續；未計入正式金額。':'系統草稿已清除。');}
 async function keepDraft(){if(lock.current||!dirty.length)return;lock.current=true;setBusy(true);setError('');try{await saveCloud(dirty);}catch(e){setError(String(e&&typeof e==='object'&&'message' in e?e.message:e).includes('DRAFT_CHANGED')?'其他裝置已修改草稿，本頁輸入保留，請重新讀取後核對。':e instanceof Error?e.message:'草稿保存失敗，輸入保留。');}finally{lock.current=false;setBusy(false);}}


 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const saved=readSheetDraft(workspaceStorage(p.userId),draftKey);draftToken.current=saved?.token||null;setRecovery(saved?.rows.length?saved:null);}catch(e){setDraftStatus(draftStorageMessage(e));}setDraftLoaded(draftKey);});return()=>{active=false;};},[p.userId,draftKey]);
 useEffect(()=>{if(draftLoaded!==draftKey||recovery)return;let status='';try{const saved=writeSheetDraft(workspaceStorage(p.userId),draftKey,draftRef.current,draftToken.current);draftToken.current=saved?.token||null;status=saved?'草稿已暫存於此裝置，尚未正式儲存。':'';}catch(e){status=draftStorageMessage(e);}let active=true;queueMicrotask(()=>{if(active)setDraftStatus(status);});return()=>{active=false;};},[drafts,p.rows,p.userId,draftKey,draftLoaded,recovery]);
 const guard=useCallback(async()=>!lock.current&&(!draftRef.current.length||window.confirm('尚有未正式儲存的編輯，確定離開？請先確認草稿暫存狀態。')) ,[]);
 useEffect(()=>{registerLeave?.(guard);const before=(e:BeforeUnloadEvent)=>{if(lock.current||draftRef.current.length){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>{registerLeave?.(null);window.removeEventListener('beforeunload',before);};},[registerLeave,guard]);
 const currentIds=new Set(p.rows.map(r=>r.id));
 const base=[...Object.values(drafts).filter(r=>r.fresh||!currentIds.has(r.id)).map(r=>r.fresh?r:{...r,locked:true}),...p.rows.map(r=>drafts[r.id]?{...drafts[r.id],locked:r.locked,state:r.state}:r)];
 const visible=base.filter(r=>(!draftView||dirty.some(d=>d.id===r.id))&&(!onlyMissing||!r.values.price)&&(r.state||'LIVE')===state&&Object.values(r.values).join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 const chosen=visible.filter(r=>selected.includes(r.id)&&!r.locked);
 const awaitingDraft=draftLoaded!==draftKey||!!recovery;
 const blocked=!!(p.readOnly||p.loading||p.error||awaitingDraft);
 function recover(){if(!recovery)return;setDrafts(Object.fromEntries(recovery.rows.map(r=>[r.id,r])));setRecovery(null);setEditing(true);setQuery('');setState('LIVE');setNotice('已恢復草稿，確認內容後再按「儲存變更」。');}
 async function discardRecovery(){if(!window.confirm('捨棄這份尚未儲存的草稿？'))return;try{if(cloud)await saveCloud([]);writeSheetDraft(workspaceStorage(p.userId),draftKey,[],draftToken.current);draftToken.current=null;setRecovery(null);setDraftStatus('');}catch(e){setDraftStatus(draftStorageMessage(e));}}
 async function refresh(){if(lock.current||p.loading)return;lock.current=true;setBusy(true);setError('');try{await p.onRefresh();}catch(e){setError(e instanceof Error?e.message:'讀取失敗，輸入仍保留，請重試。');}finally{lock.current=false;setBusy(false);}}
 function change(row:SheetRow,key:string,value:string){setDrafts(old=>({...old,[row.id]:{...row,meta:['name','unit','date','from','price','purchase_price','price_unit','content_quantity','content_unit'].includes(key)?{...row.meta as object,costQuote:undefined}:row.meta,values:changeSheetValues(row.values,key,value),requestId:crypto.randomUUID()}}));}

 async function autoPrice(row:SheetRow){if(!p.onPrice||lock.current||blocked||row.values.price!==''||row.values.purchase_price||!row.values.name||!row.values.unit)return;const snapshot=JSON.stringify(row.values);try{const [priced]=await p.onPrice([row]);setDrafts(old=>{const current=old[row.id];return current&&JSON.stringify(current.values)===snapshot?{...old,[row.id]:priced}:old;});}catch{setNotice('進價暫時無法帶入，輸入保留，可按「帶入進價」重試。');}}
 function add(){const id=crypto.randomUUID();setState('LIVE');setQuery('');setEditing(true);setDrafts(old=>({...old,[id]:{id,values:{...p.defaults},fresh:true,state:'LIVE',requestId:id}}));}
 async function cancel(){if(dirty.length&&!window.confirm('取消尚未儲存的修改？'))return;if(cloud)try{await saveCloud([]);}catch{setError('系統草稿尚未清除，輸入保留，請重試。');return;}setDrafts({});setEditing(false);setError('');setNotice('');}
 async function save(){if(lock.current||composition.current||blocked)return;lock.current=true;setBusy(true);setError('');let saved=0;const remaining=[...dirty];
  try{for(const row of dirty){const original=p.rows.find(r=>r.id===row.id);if(!row.fresh&&(!original||original.locked||original.state==='REMOVED'))throw Error(`「${row.values.name||'此筆資料'}」目前已移除、鎖定或不在此月份，草稿保留，請核對資料狀態。`);for(const col of p.columns){if(col.required&&!row.values[col.key]?.trim())throw Error(`「${col.label}」尚未填寫。`);if(col.type==='number')sheetNumber(row.values[col.key]||'');}await p.onSave(row);saved++;remaining.shift();setDrafts(old=>{const next={...old};delete next[row.id];return next;});}setEditing(false);setNotice(`已儲存 ${saved} 筆。`);if(cloud&&cloudReady.current)try{await saveCloud(remaining);}catch{setCloudStatus('正式資料已儲存，但系統草稿清理失敗；請勿在其他裝置重複提交，重新核對草稿。');}await p.onRefresh();}
  catch(e){if(saved){if(cloud&&cloudReady.current)try{await saveCloud(remaining);}catch{setCloudStatus('部分資料已儲存，系統草稿未同步，請核對後重試。');}try{await p.onRefresh();}catch{/* Keep the original save error and all remaining inputs. */}}setError(`${e instanceof Error?e.message:'儲存未確認，請重試。'} 已完成 ${saved} 筆，其餘輸入保留；重試不會重複建立已成功資料。`);}
  finally{lock.current=false;setBusy(false);}
 }
 async function remove(){if(lock.current||p.readOnly||p.loading||p.error||!chosen.length)return;const restore=state==='REMOVED';if(!window.confirm(restore?`還原 ${chosen.length} 筆？`:`將 ${chosen.length} 筆移至已移除？${p.deleteNote||'歷史紀錄會保留。'}`))return;lock.current=true;setBusy(true);setError('');try{const saved=chosen.filter(r=>!r.fresh);if(saved.length)await p.onRemove(saved,restore);setDrafts(old=>Object.fromEntries(Object.entries(old).filter(([id])=>!chosen.some(r=>r.id===id))));setSelected([]);await p.onRefresh();}catch(e){setError(e instanceof Error?e.message:'操作未完成，請重試。');}finally{lock.current=false;setBusy(false);}}
 async function submit(){if(lock.current||p.readOnly||p.loading||p.error||dirty.length||!chosen.length||!p.onSubmit)return;lock.current=true;setBusy(true);setError('');try{await p.onSubmit(chosen);setSelected([]);setNotice('已送交財務。');await p.onRefresh();}catch(e){setError(e instanceof Error?e.message:'送交未完成，請重試。');await p.onRefresh();}finally{lock.current=false;setBusy(false);}}
 async function importFiles(files:FileList|null){if(!files?.length||lock.current||blocked)return;lock.current=true;setBusy(true);setError('');try{const XLSX=await import('xlsx');const records:Record<string,unknown>[]=[];for(const file of Array.from(files)){if(!/\.(xlsx?|csv)$/i.test(file.name))throw Error('請使用 Excel 或 CSV。');const book=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false});for(const name of book.SheetNames)records.push(...XLSX.utils.sheet_to_json<Record<string,unknown>>(book.Sheets[name],{defval:'',raw:false}));}if(records.length>2000)throw Error('每次最多匯入 2,000 列。');const result=sheetImports(records,p.columns,base,p.defaults,()=>crypto.randomUUID());setDrafts(old=>({...old,...Object.fromEntries(result.rows.map(r=>[r.id,r]))}));setQuery('');setState('LIVE');setEditing(true);setNotice(`匯入預覽 ${result.rows.length} 筆，略過 ${result.skipped} 筆重複資料；確認表格後按「儲存變更」才會建檔。`);}catch(e){setError(e instanceof Error?e.message:'檔案讀取失敗。');}finally{lock.current=false;setBusy(false);if(input.current)input.current.value='';}}
 async function price(){if(lock.current||blocked||!p.onPrice)return;const targets=(chosen.length?chosen:visible.filter(r=>!r.values.price)).filter(r=>!r.locked&&r.state!=='REMOVED');if(!targets.length){setNotice('目前清單沒有未帶價資料；勾選指定列可重新套價。');return;}if(targets.some(r=>r.values.price)&&!window.confirm('以參考進價替換勾選列的單價？先顯示在原列，按儲存變更才正式更新。'))return;lock.current=true;setBusy(true);setError('');try{const priced=await p.onPrice(targets);setDrafts(old=>({...old,...Object.fromEntries(priced.map(r=>[r.id,r]))}));setEditing(true);const missing=priced.filter(r=>!r.values.price).length;setNotice(`已查找 ${priced.length} 筆，${missing} 筆仍缺價格或換算；請核對原列，按儲存變更才正式更新。`);}catch(e){setError(e instanceof Error?e.message:'價格查找失敗，原輸入保留。');}finally{lock.current=false;setBusy(false);}}
 async function download(template=false){if(lock.current||p.loading||p.error||p.canExport===false&&!template)return;try{if(!template&&(dirty.length||recovery)&&!window.confirm('有尚未儲存的修改。此次只匯出已儲存版本，不包含草稿修改與新增列，是否繼續？'))return;const persistedVisible=p.rows.filter(r=>(!onlyMissing||!r.values.price)&&(r.state||'LIVE')===state&&Object.values(r.values).join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));const persisted=chosen.length?p.rows.filter(r=>chosen.some(c=>c.id===r.id)):persistedVisible;if(!template&&!persisted.length){setError('目前沒有可匯出的已儲存資料；新增列請先儲存。');return;}const rows=template?[Object.fromEntries(p.columns.filter(c=>!c.readonly).map(c=>[c.label,'']))]:persisted.map(r=>({'資料編號':r.id,...Object.fromEntries(p.columns.map(c=>[c.label,r.values[c.key]??'']))}));await exportRows(rows,'xlsx',`${p.title}_${template?'匯入範本':p.month}`);}catch{setError('匯出失敗，請重試。');}}
 return <section className="operations-sheet" data-module={p.scope}><header><h1>{p.title}</h1><button className="sheet-button" disabled={busy||p.loading} onClick={()=>void refresh()}>{dirty.length?'保留輸入並重試讀取':'重新讀取'}</button></header>{p.summary&&<div className="sheet-summary">{p.summary}</div>}
 <div className="sheet-filters"><input aria-label="搜尋明細" type="search" placeholder="搜尋品名、供應商、備註…" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="明細月份" type="month" value={p.month} disabled={busy||dirty.length>0||awaitingDraft} onChange={e=>{if(e.target.value)p.onMonth(e.target.value);}}/><div className="sheet-state-tabs" aria-label="資料狀態"><button aria-pressed={!draftView&&state==='LIVE'} disabled={busy} onClick={()=>{setDraftView(false);setState('LIVE');}}>正式資料</button><button aria-pressed={draftView} disabled={busy} onClick={()=>{setDraftView(true);setState('LIVE');}}>草稿（{dirty.length||recovery?.rows.length||0}）</button></div><details className="sheet-more"><summary>更多</summary><button disabled={busy||dirty.length>0||awaitingDraft} onClick={()=>{setState('REMOVED');setDraftView(false);}}>已移除紀錄</button><button disabled={busy||dirty.length>0||awaitingDraft} onClick={()=>{setState('TEST');setDraftView(false);}}>測試資料</button></details>{state!=='LIVE'&&<strong>{state==='REMOVED'?'已移除紀錄':'測試資料'}</strong>}<span>{visible.length} 筆</span>{p.onPrice&&<label><input type="checkbox" checked={onlyMissing} onChange={e=>setOnlyMissing(e.target.checked)}/>只看未帶價</label>}</div>
 <div className="sheet-actions"><button className="sheet-button" disabled={busy||blocked||state==='REMOVED'||editing} onClick={()=>setEditing(true)}>編輯全部</button>{p.onPrice&&<button className="sheet-button" disabled={busy||blocked||state!=='LIVE'} onClick={()=>void price()}>帶入進價</button>}{p.onSubmit&&<button className="sheet-button" disabled={busy||blocked||dirty.length>0||!chosen.length||state!=='LIVE'} onClick={()=>void submit()}>送交財務</button>}<span className="sheet-spacer"/><button className="sheet-button primary" disabled={busy||blocked} onClick={add}>新增</button><button className="sheet-button" disabled={busy||blocked} onClick={()=>input.current?.click()}>匯入</button><input ref={input} type="file" accept=".xlsx,.xls,.csv" multiple hidden onChange={e=>void importFiles(e.target.files)}/><button className="sheet-button" disabled={busy||p.loading||!!p.error||p.canExport===false} onClick={()=>void download()}>匯出</button><button className="sheet-button" disabled={busy||p.readOnly} onClick={()=>void download(true)}>下載匯入範本</button>{p.special}</div>
 {chosen.length>0&&<div className="sheet-selection"><span>已勾選 {chosen.length} 筆</span><button className="sheet-button" disabled={busy||blocked||dirty.some(r=>!r.fresh)} onClick={()=>void remove()}>{state==='REMOVED'?'還原已選項目':'移除已選項目'}</button></div>}

 {recovery&&<div className="sheet-recovery" role="status"><span>發現上次未儲存的 {recovery.rows.length} 筆草稿（此裝置）。</span><button className="sheet-button primary" disabled={busy||p.loading} onClick={recover}>恢復草稿</button><button className="sheet-button" disabled={busy} onClick={discardRecovery}>捨棄草稿</button></div>}
 {cloudStatus&&<p className="sheet-draft-status" role="status">{cloudStatus}</p>}{draftStatus&&<p className="sheet-draft-status" role="status">{draftStatus}</p>}
 {(error||p.error)&&<p className="sheet-error" role="alert">{error||p.error}</p>}{notice&&<p className="sheet-notice" role="status">{notice}</p>}
 <div className="sheet-scroll"><table><thead><tr><th><input type="checkbox" aria-label="選取全部明細" checked={visible.some(r=>!r.locked)&&visible.filter(r=>!r.locked).every(r=>selected.includes(r.id))} onChange={e=>setSelected(e.target.checked?visible.filter(r=>!r.locked).map(r=>r.id):[])}/></th>{p.columns.map(c=><th key={c.key}>{c.label}</th>)}{p.onSource&&<th>原始資料</th>}</tr></thead><tbody>{visible.map(row=><tr key={row.id} className={row.fresh?'sheet-new':''}><td><input type="checkbox" aria-label={`選取 ${row.values.name||row.id}`} disabled={row.locked||busy} checked={selected.includes(row.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,row.id]:old.filter(id=>id!==row.id))}/></td>{p.columns.map(col=><td key={col.key}>{editing&&!p.readOnly&&!col.readonly&&(!col.editable||col.editable(row))&&!row.locked&&state!=='REMOVED'?<>{col.select?<select aria-label={`${row.values.name||'新增'} ${col.label}`} value={row.values[col.key]||''} disabled={busy||p.loading} onBlur={()=>void autoPrice(row)} onChange={e=>change(row,col.key,e.target.value)}><option value="">請選擇</option>{[...new Set([...(col.options||[]),...(row.values[col.key]?[row.values[col.key]]:[])])].map(v=><option key={v} value={v}>{v}</option>)}</select>:<input aria-label={`${row.values.name||'新增'} ${col.label}`} list={col.options?`${p.scope}-${col.key}`:undefined} type={col.type||'text'} step={col.type==='number'?'any':undefined} value={row.values[col.key]||''} disabled={busy||p.loading} onCompositionStart={()=>composition.current=true} onCompositionEnd={()=>composition.current=false} onBlur={()=>void autoPrice(row)} onChange={e=>change(row,col.key,e.target.value)}/>}</>:row.values[col.key]||(['price','amount'].includes(col.key)?'未計價':'—')}</td>)}{p.onSource&&<td>{!row.fresh&&<button className="sheet-link" onClick={()=>p.onSource?.(row)}>查看</button>}</td>}</tr>)}{!visible.length&&<tr><td colSpan={p.columns.length+1+(p.onSource?1:0)}>{p.loading?'讀取中…':p.error?'讀取未完成，請重試。':'目前沒有符合條件的資料。可新增或匯入。'}</td></tr>}</tbody></table></div>{p.columns.filter(c=>c.options).map(c=><datalist key={c.key} id={`${p.scope}-${c.key}`}>{c.options?.map(v=><option key={v} value={v}/>)}</datalist>)}<footer>已選取 {chosen.length} 筆{dirty.length?`・${dirty.length} 筆尚未儲存`:''}</footer>{editing&&<div className="sheet-save-bar"><span>已修改 {dirty.length} 筆 · 缺價格可先儲存</span><span className="sheet-spacer"/><button className="sheet-button" disabled={busy} onClick={cancel}>取消編輯</button><>{cloud&&<button className="sheet-button" disabled={busy||blocked||!dirty.length} onClick={()=>void keepDraft()}>保存草稿</button>}</><button className="sheet-button primary" disabled={busy||blocked||!dirty.length} onClick={()=>void save()}>{busy?'處理中…':'儲存變更'}</button></div>}</section>;
}
