'use client';
import {useLayoutEffect,useRef,useState} from 'react';
import {useOperation} from './operation-hooks';
import {ChevronRight,Pencil,X} from 'lucide-react';
export type BasicProduct={id:string;name:string;count_unit:string;specification:string|null;updated_at?:string;unit_price?:number|null};
export default function ProductBasicEditor({storeId,userId,product,onSaved,disabled=false,onEditingChange,includePrice=false,modal=false,beforeEdit,onSaveAttempt,canEditBasic=true,onChangeArea}:{storeId:string;userId:string;product:BasicProduct;onSaved:(product:BasicProduct)=>void|Promise<void>;disabled?:boolean;includePrice?:boolean;modal?:boolean;onEditingChange?:(editing:boolean)=>void;beforeEdit?:()=>Promise<boolean>;onSaveAttempt?:()=>void;canEditBasic?:boolean;onChangeArea?:()=>Promise<boolean>}){
 const[editing,setEditing]=useState(false);const[draft,setDraft]=useState(product);const[notice,setNotice]=useState('');const operation=useOperation(storeId,userId);const element=useRef<HTMLDivElement>(null);const position=useRef<number|null>(null);const wasEditing=useRef(false);
 const[editView,setEditView]=useState<'actions'|'basic'>('basic');const[choosingArea,setChoosingArea]=useState(false);
 useLayoutEffect(()=>{if(!editing&&position.current!==null){element.current?.closest('.shell-content')?.scrollTo({top:position.current});position.current=null;}},[editing]);
 useLayoutEffect(()=>{if(!modal)return;if(editing)element.current?.querySelector<HTMLElement>('[role="dialog"] input,[role="dialog"] .count-edit-choice')?.focus();else if(wasEditing.current)element.current?.querySelector<HTMLButtonElement>('button')?.focus();wasEditing.current=editing;},[editing,editView,modal]);
 const close=()=>{setEditing(false);onEditingChange?.(false);};
 const form=<form className="product-basic-form" onSubmit={async e=>{e.preventDefault();if(!canEditBasic)return;onSaveAttempt?.();const result=await operation.run<BasicProduct>(includePrice?'count.catalog-edit':'product.edit-basic',{id:product.id,name:draft.name,unit:draft.count_unit,specification:draft.specification,updated_at:draft.updated_at,...(includePrice&&draft.unit_price!==undefined?{unit_price:draft.unit_price}:{})});if(result){await onSaved(result);setNotice('已儲存');close();}}}>
 <label>品名<input value={draft.name} maxLength={160} disabled={operation.busy} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><label>單位<input value={draft.count_unit} maxLength={30} disabled={operation.busy} onChange={e=>setDraft({...draft,count_unit:e.target.value,...(includePrice?{unit_price:null}:{})})} required/></label><label>規格（選填）<input value={draft.specification||''} disabled={operation.busy} onChange={e=>setDraft({...draft,specification:e.target.value})}/></label>{includePrice?<label>每 {draft.count_unit||"單位"} 單價（元，可留白）<input type="number" min="0" step="any" value={draft.unit_price??''} placeholder="待補單價" disabled={operation.busy} onChange={e=>setDraft({...draft,unit_price:e.target.value===''?null:Number(e.target.value)})}/></label>:<small>本次數量不變；新單位從下次盤點使用。</small>}
 {operation.error&&<p role="alert">{operation.error}</p>}<div className="shell-button-stack"><button type="button" className="shell-secondary" disabled={operation.busy} onClick={close}>取消</button><button className="shell-primary" disabled={operation.busy}>{operation.busy?'儲存中…':'儲存'}</button></div></form>;
 const editorContent=editView==='actions'&&onChangeArea?<div className="count-edit-choices"><p>{product.name}</p>{canEditBasic&&<button type="button" className="count-edit-choice" disabled={choosingArea} onClick={()=>setEditView('basic')}>修改品項資料<ChevronRight size={18}/></button>}<button type="button" className="count-edit-choice" disabled={choosingArea} onClick={async()=>{setChoosingArea(true);try{if(await onChangeArea())close();else setNotice('數量或備註尚未儲存，請關閉後重試儲存。');}finally{setChoosingArea(false);}}}>{choosingArea?'儲存中…':'更改儲物區'}<ChevronRight size={18}/></button>{notice&&<p role="status">{notice}</p>}</div>:canEditBasic?form:null;
 if(!canEditBasic&&!onChangeArea)return null;
 return <div ref={element} className="product-inline-editor">{!editing&&<button type="button" className="text-button" disabled={disabled} aria-label={`${modal?'修改':'編輯'} ${product.name}`} onClick={async()=>{if(beforeEdit&&!await beforeEdit())return;position.current=element.current?.closest('.shell-content')?.scrollTop??null;setDraft(product);operation.setError('');setNotice('');setEditView(onChangeArea?'actions':'basic');setEditing(true);onEditingChange?.(true);}}>{modal&&<Pencil size={17}/>} {modal?'修改':'編輯'}</button>}{notice&&!modal&&<small role="status">{notice}</small>}{editing&&(modal?<div className="modal-backdrop"><section className="shell-card count-product-dialog" role="dialog" aria-modal="true" aria-labelledby={`edit-product-${product.id}`} onKeyDown={event=>{if(event.key==='Escape'&&!operation.busy&&!choosingArea)close();if(event.key==='Tab'){const focusable=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('input:not(:disabled),button:not(:disabled)'));const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}}><header><h2 id={`edit-product-${product.id}`}>{editView==='actions'?'修改':'修改品項'}</h2><button className="text-button" type="button" aria-label="取消修改品項" disabled={operation.busy||choosingArea} onClick={close}><X size={21}/></button></header>{editorContent}</section></div>:editorContent)}</div>;
}
