"use client";
import {useEffect,useRef,useState} from 'react';
import {fieldNames,numericFields,type ReceiptField} from '@/lib/receipt-workflow';
import {supabase} from '@/lib/supabase-browser';
import {useOperation} from './operation-hooks';
import {receiptError} from '@/lib/receipt-workflow';
type Product={id:string;name:string;base_unit:string|null;specification:string|null};
export default function ReceiptCardEditor({storeId,userId,batchId,runId,row,fields,mapping,chain,onClose}:{storeId:string;userId:string;organizationId:string;batchId:string;runId:string;row:string;fields:ReceiptField[];mapping?:{product_id:string;name:string;unit:string};chain:boolean;onClose:(saved:boolean)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const[snapshot]=useState(()=>fields.filter(f=>f.row_key===row));const[values,setValues]=useState(()=>Object.fromEntries(snapshot.map(f=>[f.id,f.value===null?'':String(f.value??'')])));const[products,setProducts]=useState<Product[]>([]);const[productId,setProductId]=useState(mapping?.product_id||'');const[mode,setMode]=useState('KEEP');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const operation=useOperation(storeId,userId);
 useEffect(()=>{const element=dialog.current!;const scroller=element.closest('.shell-content');const top=scroller?.scrollTop||0;element.showModal();return()=>{element.close();requestAnimationFrame(()=>scroller?.scrollTo({top}));};},[]);
 async function loadProducts(){setLoading(true);setError('');try{const r=await supabase.rpc('app_workspace',{p_store_id:storeId,p_section:'product-options',p_filter:{}});if(r.error)throw r.error;const data=r.data as unknown as {products?:Product[]};if(!Array.isArray(data?.products))throw Error('PRODUCT_OPTIONS_UNAVAILABLE');setProducts(data.products);}catch(e){setError(receiptError(e));}finally{setLoading(false);}}
 async function save(){setError('');try{const changes=snapshot.map(f=>{const v=values[f.id].trim();const value=v===''?null:numericFields.has(f.field_name)?Number(v):v;if(typeof value==='number'&&!Number.isFinite(value))throw Error('NUMBER_REQUIRED');return {id:f.id,old:f.value??null,value};});const result=await operation.run('receipt.edit-card',{batch_id:batchId,run_id:runId,row_key:row,fields:changes,previous_product_id:mapping?.product_id||null,mapping_mode:mode,product_id:productId||null});if(result)onClose(true);}catch(e){setError(receiptError(e));}}
 const input=(f:ReceiptField)=><label className="field" key={f.id}>{f.field_name==='product'?'品名':fieldNames[f.field_name]}<input type={numericFields.has(f.field_name)?'number':f.field_name==='receipt_date'?'date':'text'} step="any" value={values[f.id]} disabled={operation.busy} onChange={e=>{setValues({...values,[f.id]:e.target.value});if(['product','unit','specification'].includes(f.field_name)){setMode('NONE');setProductId('');}}}/></label>;
 const primary=row==='document'?['supplier_name','receipt_date','document_number']:['product','quantity','unit'];
 return <dialog ref={dialog} className="context-expiry-dialog" aria-label={row==='document'?'修改貨單':'修改品項'} onCancel={e=>{e.preventDefault();if(!operation.busy)onClose(false);}}><h2>{row==='document'?'修改貨單':'修改品項'}</h2><form onSubmit={e=>{e.preventDefault();void save();}}>{snapshot.filter(f=>primary.includes(f.field_name)).map(input)}{row!=='document'&&<details onToggle={e=>{if(e.currentTarget.open&&!products.length)void loadProducts();}}><summary>商品對應・{mode==='NONE'?'尚未確認':mode==='CREATE'?'建立新商品':products.find(p=>p.id===productId)?.name||mapping?.name||'尚未對應'}</summary><label className="field">對應商品<select value={mode==='CREATE'?'__new':productId} disabled={operation.busy||loading} onChange={e=>{setMode(e.target.value==='__new'?'CREATE':e.target.value?'SELECT':'NONE');setProductId(e.target.value==='__new'?'':e.target.value);}}><option value="">未確認，先保留原始資料</option>{mapping&&!products.some(p=>p.id===mapping.product_id)&&<option value={mapping.product_id} disabled>{mapping.name}（原紀錄）</option>}{products.map(p=><option key={p.id} value={p.id}>{p.name}・{p.base_unit} {p.specification}</option>)}{!chain&&<option value="__new">依本次品名與單位建立商品</option>}</select></label><p className="shell-note">單位換算未確認時保留待整理，不計入庫存。</p>{error&&<button type="button" className="text-button" onClick={()=>void loadProducts()}>重新讀取商品</button>}</details>}{snapshot.some(f=>!primary.includes(f.field_name))&&<details><summary>規格、價格與其他明細</summary>{snapshot.filter(f=>!primary.includes(f.field_name)).map(input)}</details>}{(error||operation.error)&&<p role="alert">{error||operation.error}</p>}<div className="context-expiry-actions"><button type="button" className="shell-secondary" disabled={operation.busy} onClick={()=>onClose(false)}>取消</button><button type="submit" className="shell-primary" disabled={operation.busy}>{operation.busy?'儲存中…':'完成修改'}</button></div></form></dialog>;
}
