'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ClipboardList,CheckCircle2,MessageSquare,Plus} from 'lucide-react';
import type {AppStore} from '@/lib/app-workspace';
import {useOperation,useOperationDraft,useWorkspace} from './operation-hooks';
import {displayTime} from './inventory-catalog';

export type RecordSection='incidents'|'handover'|'bulletins'|'company-tasks';
export type OperationalRecord={id:string;kind:'incident'|'handover'|'bulletin'|'company_task';title:string;body:string;category:string|null;status:'OPEN'|'IN_PROGRESS'|'COMPLETE';created_by:string;actor_name:string;created_at:string;responsible_id:string|null;responsible_name:string|null;due_at:string|null;expires_at:string|null;completed_at:string|null;revision:number;read_at:string|null;audience:string[];readers:{display_name:string;read_at:string}[];events:{id:string;action:string;note:string;actor_name:string;created_at:string}[]};
const sectionNames={incidents:'異常回報',handover:'交接',bulletins:'公佈欄','company-tasks':'公司流程待辦'};
export default function RecordsWorkspace({store,userId,section,onBack,initialId,pendingWork,returnLabel='返回首頁'}:{store:AppStore;userId:string;section:RecordSection;onBack:()=>void;initialId?:string;pendingWork?:ReactNode;returnLabel?:string}){
 const workspace=useWorkspace<{records:OperationalRecord[]}>(store.id,section);const operation=useOperation(store.id,userId);
 const[nav,setNav]=useOperationDraft(userId,store.id,`record-navigation:${section}`,{page:(section==='bulletins'&&store.role==='STAFF'?'open':'home') as 'home'|'new'|'open'|'history'|'detail'|'pending',selected:''});const page=initialId?'detail':nav.page;const setPage=(page:typeof nav.page)=>setNav(v=>({...v,page}));const selected=initialId||nav.selected;const setSelected=(selected:string)=>setNav(v=>({...v,selected}));
 const [draft,setDraft,clearDraft]=useOperationDraft(userId,store.id,section,{title:'',body:'',category:'其他',expires_at:'',audience:['STAFF','SUPERVISOR','LOGISTICS','OWNER']});
 const [note,setNote]=useState('');const current=workspace.data?.records.find(r=>r.id===selected);
 const[now,setNow]=useState(()=>Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const readTried=useRef<string|undefined>(undefined);
 const all=workspace.data?.records||[];const isExpired=(r:OperationalRecord)=>!!r.expires_at&&new Date(r.expires_at).getTime()<now;
 const active=all.filter(r=>r.status!=='COMPLETE'&&(section!=='bulletins'||!isExpired(r)));const history=all.filter(r=>r.status==='COMPLETE'||(section==='bulletins'&&isExpired(r)));
 const canCreate=section==='incidents'||section==='handover'||store.role!=='STAFF';
 const change=(next:typeof page)=>{operation.setError('');setPage(next);};
 const open=async(record:OperationalRecord)=>{setSelected(record.id);setNote('');change('detail');if(section==='bulletins'&&!record.read_at){await operation.run('record.read',{id:record.id});await workspace.refresh();}};
 const submit=async()=>{if(section==='bulletins'&&!draft.audience.length){operation.setError('請至少選擇一個公告對象。');return;}const result=await operation.run<OperationalRecord>('record.create',{...draft,expires_at:draft.expires_at?new Date(draft.expires_at).toISOString():null,kind:section==='incidents'?'incident':section==='handover'?'handover':section==='bulletins'?'bulletin':'company_task'});if(result){clearDraft();setSelected(result.id);change('detail');await workspace.refresh();}};
 useEffect(()=>{if(initialId&&current&&section==='bulletins'&&!current.read_at&&!operation.busy&&readTried.current!==current.id){readTried.current=current.id;void operation.run('record.read',{id:current.id}).then(()=>workspace.refresh());}},[initialId,current,section,operation,workspace]);
 const action=async(name:'record.take'|'record.complete')=>{if(!current)return;const result=await operation.run(name,{id:current.id,revision:current.revision,note});if(result){setNote('');await workspace.refresh();}};
 return <><button className="shell-back" type="button" onClick={()=>(page==='detail'&&initialId)||page==='home'||(section==='bulletins'&&store.role==='STAFF'&&page==='open')?onBack():change('home')}>‹ <span>{(page==='detail'&&initialId)||page==='home'?returnLabel:`返回${sectionNames[section]}`}</span></button><div className="workspace-heading"><h1>{page==='new'?section==='bulletins'?'新增公告':section==='incidents'?'新增異常':section==='handover'?'本班交接':'新增公司流程':sectionNames[section]}</h1></div>
 {(workspace.error||operation.error)&&<p className="pilot-message" role="alert">{operation.error||workspace.error}</p>}{workspace.error&&<button className="shell-secondary" onClick={()=>void workspace.refresh()}>重新讀取</button>}
 {workspace.loading&&!workspace.data?<p role="status">正在讀取…</p>:<>
 {page==='home'&&<div className="shell-card shell-list">{canCreate&&<button className="shell-list-row" onClick={()=>change(section==='handover'?'pending':'new')}><Plus/><span><strong>{section==='incidents'?'新增異常':section==='handover'?'本班待交接':section==='bulletins'?'新增公告':'公司流程設定'}</strong><small>{section==='incidents'?'庫存、收貨、效期、設備或其他':'留下需要接續的事項'}</small></span><b>›</b></button>}<button className="shell-list-row" onClick={()=>change('open')}><ClipboardList/><span><strong>{section==='handover'?'接手確認':section==='bulletins'?'目前公告':'處理中'}</strong><small>{active.length} 筆</small></span><b>›</b></button><button className="shell-list-row" onClick={()=>change('history')}><CheckCircle2/><span><strong>{section==='handover'?'歷史交接':section==='bulletins'?'公告紀錄':'已完成'}</strong><small>{history.length} 筆</small></span><b>›</b></button></div>}
 {page==='pending'&&section==='handover'&&<><h2>本班待交接</h2>{pendingWork}<button className="shell-secondary full" onClick={()=>change('new')}>補充交接事項</button></>}
 {page==='new'&&canCreate&&<form onSubmit={e=>{e.preventDefault();void submit();}}><section className="shell-card transfer-form">{section==='incidents'&&<label><span>異常類型</span><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{['庫存','收貨','效期','設備','其他'].map(s=><option key={s}>{s}</option>)}</select></label>}<label><span>{section==='bulletins'?'公告標題':'事項'}</span><input value={draft.title} maxLength={160} onChange={e=>setDraft({...draft,title:e.target.value})} required/></label><label><span>說明</span><textarea value={draft.body} maxLength={5000} onChange={e=>setDraft({...draft,body:e.target.value})}/></label>{section==='bulletins'&&<><label><span>顯示至（選填）</span><input type="datetime-local" value={draft.expires_at} onChange={e=>setDraft({...draft,expires_at:e.target.value})}/></label><fieldset><legend>公告對象</legend>{[['STAFF','員工'],['SUPERVISOR',store.business_type==='CHAIN_RESTAURANT'?'店長':'主管'],['LOGISTICS',store.business_type==='CHAIN_RESTAURANT'?'區主管':'行政／後勤'],['OWNER','老闆']].map(([role,label])=><label key={role} className="checkbox-row"><input type="checkbox" checked={draft.audience.includes(role)} onChange={e=>setDraft({...draft,audience:e.target.checked?[...draft.audience,role]:draft.audience.filter(v=>v!==role)})}/>{label}</label>)}</fieldset></>}</section><p className="shell-note">門市、經手人與時間會自動保存。</p><button className="shell-primary full" disabled={operation.busy}>{operation.busy?'儲存中…':section==='bulletins'?'發布公告':'儲存紀錄'}</button></form>}
 {(page==='open'||page==='history')&&<><div className="shell-card shell-list">{(page==='open'?active:history).map(r=><button className="shell-list-row" key={r.id} onClick={()=>void open(r)}><MessageSquare/><span><strong>{r.title}</strong><small>{r.actor_name}・{displayTime(r.created_at)}{section==='bulletins'?r.read_at?'・已讀':'・未讀':r.responsible_name?`・${r.responsible_name} 接手`:''}</small></span><b>›</b></button>)}</div>{!(page==='open'?active:history).length&&<p>{page==='open'?'目前沒有待處理事項。':'目前沒有完成紀錄。'}</p>}</>}
 {page==='detail'&&current&&<><section className="shell-card result-list"><div><span>{current.category||'事項'}</span><strong>{current.title}</strong></div><div><span>內容</span><strong className="preserve-lines">{current.body||'未提供'}</strong></div><div><span>建立</span><strong>{current.actor_name}・{displayTime(current.created_at)}</strong></div>{current.responsible_name&&<div><span>接手人</span><strong>{current.responsible_name}</strong></div>}<div><span>狀態</span><strong>{current.status==='COMPLETE'?'已完成':section==='bulletins'?current.read_at?'已讀':'未讀':current.status==='IN_PROGRESS'?'處理中':'待接手'}</strong></div>{current.completed_at&&<div><span>完成時間</span><strong>{displayTime(current.completed_at)}</strong></div>}</section>{current.status!=='COMPLETE'&&section!=='bulletins'&&<><label className="field">處理說明（選填）<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="shell-button-stack"><button className="shell-secondary" disabled={operation.busy||current.responsible_id===userId} onClick={()=>void action('record.take')}>{section==='handover'?'確認接手':'由我處理'}</button>{(store.role!=='STAFF'||current.kind!=='incident'||(current.responsible_id||current.created_by)===userId)&&<button className="shell-primary" disabled={operation.busy} onClick={()=>void action('record.complete')}>{section==='company-tasks'?'已完成公司流程':'完成處理'}</button>}</div></>}{section==='bulletins'&&store.role!=='STAFF'&&current.status!=='COMPLETE'&&<button className="shell-secondary" disabled={operation.busy} onClick={()=>void action('record.complete')}>結束公告</button>}{section==='bulletins'&&store.role!=='STAFF'&&<section className="shell-section"><h2>已讀紀錄</h2>{current.readers?.map(r=><p key={r.display_name+r.read_at}>{r.display_name}・{displayTime(r.read_at)}</p>)}</section>}<section className="shell-section"><h2>處理紀錄</h2><div className="shell-card timeline-list">{current.events.map(e=><article key={e.id}><i/><div><strong>{e.action==='CREATE'?'建立':e.action==='record.take'?'確認接手':e.action==='record.complete'?'完成處理':'修改'}・{e.actor_name}</strong><small>{displayTime(e.created_at)}</small>{e.note&&<p>{e.note}</p>}</div></article>)}</div></section></>}
 </>}</>;
}

export function RecordsActivity({storeId,mode,onOpen}:{storeId:string;mode:'activity'|'tasks'|'notifications';onOpen:(section:RecordSection,id:string)=>void}){
 const {data,error,refresh}=useWorkspace<{records:OperationalRecord[]}>(storeId,mode);
 if(error)return <p role="alert">{error}<button onClick={()=>void refresh()}>重試</button></p>;
 const records=(data?.records||[]).filter(r=>mode==='activity'||(r.status!=='COMPLETE'&&(!r.expires_at||new Date(r.expires_at)>new Date())&&(r.kind!=='bulletin'||!r.read_at)));
 return <section className="shell-section"><h2>{mode==='activity'?'交接與異常紀錄':mode==='tasks'?'待接續事項':'工作通知'}</h2><div className="shell-card shell-list">{records.map(r=><button key={r.id} className="shell-list-row" onClick={()=>onOpen(r.kind==='incident'?'incidents':r.kind==='handover'?'handover':r.kind==='bulletin'?'bulletins':'company-tasks',r.id)}><span><strong>{r.title}</strong><small>{r.status==='COMPLETE'?'已完成':r.responsible_name?`${r.responsible_name} 處理中`:'待處理'}・{displayTime(r.created_at)}</small></span><b>›</b></button>)}</div>{data&&!records.length&&<p className="shell-note">目前沒有事項。</p>}</section>;
}
