'use client';
import {useState} from 'react';
import {receiptPriceSummary} from '@/lib/receipt-price-summary';
import {localMonth,monthRange,type AppStore} from '@/lib/app-workspace';
import {useOperationDraft,useWorkspace} from './operation-hooks';
import {displayTime} from './inventory-catalog';
import type {ShellView} from './app-shell';
type Report={counts:{id:string;started_at:string;completed_at:string;status:string}[];receipts:{id:string;receipt_date:string|null;source_batch_id:string;document_number:string;supplier_name:string;total_inc_tax:number|null}[];lines:{id:string;receipt_id:string;product_id:string|null;name:string;quantity:number|null;unit:string|null;unit_price:number|null;amount:number|null;receipt_date:string|null;supplier_name:string;inventory_status:string;source_batch_id:string}[]};
type Audit={events:{id:string;action:string;actor_name:string;entity_type:string;entity_id:string;old_value:unknown;new_value:unknown;created_at:string}[]};
const formatAmount=(value:number|null)=>value===null?'未提供':`NT$ ${Number(value).toLocaleString()}`;
export async function exportRows(rows:Record<string,unknown>[],format:'xlsx'|'csv',fileName:string){
 const XLSX=await import('xlsx');const records=rows.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,value===null||value===undefined?'未提供':typeof value==='object'?JSON.stringify(value):value])));
 const sheet=XLSX.utils.json_to_sheet(records.length?records:[{紀錄:'此期間沒有資料'}]);
 if(format==='xlsx'){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'紀錄');XLSX.writeFile(book,`${fileName}.xlsx`);}
 else {const safe=records.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,typeof value==='string'&&/^[=+\-@\t\r]/.test(value)?`'${value}`:value])));const csv=XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(safe.length?safe:[{紀錄:'此期間沒有資料'}]));const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${fileName}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
}
export default function ReportsWorkspace({store,userId,section,onBack,onCount,onReceipt,onNavigate}:{store:AppStore;userId:string;section:'reports'|'exports'|'costs'|'audit';onBack:()=>void;onCount:(id:string)=>void;onReceipt:(id:string)=>void;onNavigate:(view:ShellView)=>void}){
 const[state,setState]=useOperationDraft(userId,store.id,`report:${section}`,{month:localMonth(),page:'home',search:''});const{month,page,search}=state;const setMonth=(month:string)=>setState(v=>({...v,month}));const setPage=(page:string)=>setState(v=>({...v,page}));const[formatOpen,setFormatOpen]=useState(false);const[exporting,setExporting]=useState(false);const[exportError,setExportError]=useState('');
 const workspace=useWorkspace<Report&Partial<Audit>>(store.id,section==='audit'?'audit':'reports',monthRange(month));
 const data=workspace.data;const lines=(data?.lines||[]).filter(l=>`${l.name} ${l.supplier_name||''}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));const receipts=(data?.receipts||[]).filter(r=>!search||lines.some(l=>l.receipt_id===r.id));const total=receipts.length&&receipts.every(r=>r.total_inc_tax!==null)?receipts.reduce((n,r)=>n+Number(r.total_inc_tax),0):null;const title=section==='reports'?'報表中心':section==='exports'?'資料匯出':section==='costs'?'成本分析':'Audit Log';
 const pages=section==='exports'?[['counts','盤點回填版','保持來源位置，新品另表'],['audit','完整稽核明細','來源、操作者、時間與事件'],['summary','營運摘要','只包含已確認資料']]:section==='costs'?[['receipts','食材成本','依已確認收貨查看'],['prices','價格變化','各品項與單位分開比較'],['waste','廢棄影響','只呈現可追溯資料']]:section==='audit'?[['counts','盤點事件','原始實盤與追加更正'],['receipts','進貨證據鏈','原圖、OCR、修正與發布'],['events','權限異動','角色、代理與停用紀錄']]:[['summary','營運摘要','門市與期間'],['counts','盤點報表','完整成果與完成時間'],['receipts','進貨報表','供應商與品項']];
 const rows:Record<string,unknown>[]=page==='summary'?[{門市:store.name,月份:month,已確認盤點:data?.counts?.length||0,已確認收貨:receipts.length,進貨總額:total}]:page==='events'?(data?.events||[]).map(e=>({時間:e.created_at,操作者:e.actor_name,事件:e.action,資料:e.entity_type,識別:e.entity_id,修改前:e.old_value,修改後:e.new_value})):page==='counts'?(data?.counts||[]).map(c=>({門市:store.name,盤點識別:c.id,開始:c.started_at,完成:c.completed_at,狀態:'已完成'})):lines.map(l=>({門市:store.name,日期:l.receipt_date,供應商:l.supplier_name,品名:l.name,數量:l.quantity,單位:l.unit,單價:l.unit_price,金額:l.amount,狀態:inventoryState(l.inventory_status),貨單:l.receipt_id}));
 const prices=receiptPriceSummary(lines);
 const download=async(format:'xlsx'|'csv')=>{setExporting(true);setExportError('');try{await exportRows(rows,format,`序-${store.name}-${month}-${page}`);setFormatOpen(false);}catch{setExportError('匯出未完成，請重試。');}finally{setExporting(false);}};
 const go=(next:string)=>{if(next==='waste'){onNavigate('waste');return;}if(next==='audit'){onNavigate('audit');return;}if(section==='audit'&&next==='counts'){onNavigate('count');return;}if(section==='audit'&&next==='receipts'){onNavigate('receiving');return;}setPage(next);setExportError('');};
 return <><button className="shell-back" onClick={()=>page==='home'?onBack():setPage('home')}>‹ {page==='home'?'返回首頁':`返回${title}`}</button><h1>{title}</h1>
 {workspace.error&&<p className="pilot-message" role="alert">{workspace.error}<button onClick={()=>void workspace.refresh()}>重新讀取</button></p>}
 {page==='home'?<div className="shell-card shell-list">{pages.map(([next,label,copy])=><button className="shell-list-row" key={next} onClick={()=>go(next)}><span><strong>{label}</strong><small>{copy}</small></span><b>›</b></button>)}</div>:<>
 <label className="field">月份<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label>
 {page!=='events'&&page!=='counts'&&<label className="field">搜尋品項／供應商<input type="search" value={search} onChange={e=>setState(v=>({...v,search:e.target.value}))}/></label>}
 {workspace.loading?<p role="status">正在讀取報表…</p>:<>
 {page==='summary'&&<section className="shell-card result-list"><div><span>門市</span><strong>{store.name}</strong></div><div><span>已確認盤點</span><strong>{data?.counts?.length||0} 次</strong></div><div><span>已確認收貨</span><strong>{receipts.length} 張</strong></div><div><span>進貨總額</span><strong>{formatAmount(total)}</strong></div></section>}
 {page==='counts'&&<section className="shell-card shell-list">{data?.counts?.map(c=><button className="shell-list-row" key={c.id} onClick={()=>onCount(c.id)}><span><strong>{displayTime(c.completed_at)}</strong><small>已確認盤點・查看完整明細與回填檔案</small></span><b>›</b></button>)}</section>}
 {(page==='receipts'||page==='summary')&&<section className="shell-section"><h2>進貨明細</h2><div className="shell-card shell-list">{receipts.map(r=><button className="shell-list-row" key={r.id} onClick={()=>onReceipt(r.source_batch_id)}><span><strong>{r.supplier_name||'未提供供應商'}</strong><small>{r.receipt_date||'未提供日期'}・{r.document_number||'未提供單號'}・{formatAmount(r.total_inc_tax)}</small></span><b>›</b></button>)}</div></section>}
 {page==='prices'&&<section className="shell-card shell-list">{prices.map((l,i)=><button className="shell-list-row" key={i} onClick={()=>onReceipt(l.source)}><span><strong>{l.name}／{l.unit||'未提供單位'}</strong><small>最近 {l.latestDate||'未提供日期'}・{formatAmount(l.latest)}</small><small>本期加權均價 {l.weightedAverage===null?'未提供':formatAmount(Math.round(l.weightedAverage*100)/100)}・{l.supplier}</small></span><b>›</b></button>)}</section>}
 {page==='events'&&<div className="shell-card timeline-list">{data?.events?.map(e=><article key={e.id}><i/><div><strong>{eventLabel(e.action)}・{e.actor_name}</strong><small>{displayTime(e.created_at)}</small><details><summary>查看明細</summary><pre className="audit-json">{JSON.stringify({修改前:e.old_value,修改後:e.new_value},null,2)}</pre></details></div></article>)}</div>}
 {!rows.length&&<p className="shell-note">此期間沒有符合的已確認資料。</p>}
 {page==='counts'?<p className="shell-note">選擇一筆盤點，查看明細並匯出原表回填檔案。</p>:<div className="report-actions"><div className="export-menu"><button className="shell-primary" disabled={exporting||!!workspace.error} aria-expanded={formatOpen} onClick={()=>setFormatOpen(v=>!v)}>匯出檔案</button>{formatOpen&&<div className="shell-button-stack"><button className="shell-secondary" disabled={exporting} onClick={()=>void download('xlsx')}>Excel</button><button className="shell-secondary" disabled={exporting} onClick={()=>void download('csv')}>CSV</button></div>}</div><button className="shell-secondary" onClick={()=>window.print()}>列印／另存 PDF</button></div>}{exportError&&<p className="pilot-message" role="alert">{exportError}</p>}
 </>}</>}
 </>;
}
function eventLabel(action:string){const labels:Record<string,string>={'member.save':'成員權限更新','member.assign':'門市授權','delegation.create':'設定代理','delegation.revoke':'撤銷代理','settings.save':'更新作業設定','business.save':'商家資料更新','store.save':'門市資料更新','product.save':'商品資料更新','supplier.save':'供應商資料更新'};return labels[action]||action;}

function inventoryState(value:string){return ({POSTED:"已計入庫存",MAPPING_PENDING:"商品待對應",UNIT_PENDING:"單位待確認",QUANTITY_PENDING:"數量待確認",REVIEW_PENDING:"辨識資料未確認"} as Record<string,string>)[value]||"未確認";}
