'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Bell,CalendarClock,Trash2,Truck,ClipboardList,Users,Settings,Package,ChartNoAxesCombined,ArrowLeftRight,Ellipsis,MessagesSquare,ShieldCheck,Building2,Download,FileClock,TriangleAlert,Warehouse} from 'lucide-react';
import {useWorkFeed} from './work-feed';
import {localMonth} from '@/lib/app-workspace';
import {useUiState} from './workspace-memory';
import {supabase} from '@/lib/supabase-browser';
import {hasCrossStore,canManageBusiness,canViewReports,canExportData,type AppStore} from '@/lib/app-workspace';
import type {ShellView} from './app-shell';
import {displayTime} from './inventory-catalog';
export type Dashboard={reminder_priorities?:Record<string,string[]>;expiry_upcoming?:number;thaw_due?:number;count:{id:string;status:string;completed_at:string|null;paper_required:boolean;paper_completed_at:string|null}|null;count_items:number;count_completed:number;receipt_pending:number;receipt_issues:number;expiry_urgent:number;incidents:number;handover:number;erp_pending:number;receipt_erp_pending:number;month_receipt_amount:number|null;month_waste_amount:number|null;bulletins:{id:string;title:string;actor_name:string;created_at:string}[];shortages:{id:string;name:string;updated_at:string;remaining?:number;unit?:string;available?:number;total?:number}[]};
const icons:Partial<Record<ShellView,typeof Bell>>={count:ClipboardList,receiving:Truck,'receiving-issue':TriangleAlert,expiry:CalendarClock,waste:Trash2,handover:MessagesSquare,other:Ellipsis,bulletins:Bell,members:Users,catalog:Package,suppliers:Truck,reports:ChartNoAxesCombined,costs:ChartNoAxesCombined,preferences:Settings,permissions:ShieldCheck,business:Building2,exports:Download,audit:FileClock,incidents:TriangleAlert,transfers:ArrowLeftRight,stock:Warehouse};
export const viewTitles:Partial<Record<ShellView,string>>={stock:'分區與解凍',home:'首頁',activity:'作業紀錄',tasks:'待辦',notifications:'通知',settings:'我的',count:'盤點',receiving:'進貨','receiving-issue':'進貨異常回報',expiry:'效期提醒',waste:'廢棄',handover:'交接',other:'其他作業',bulletins:'公佈欄',members:'員工與權限',catalog:'品項與編碼',suppliers:'供應商',reports:'報表中心',costs:'成本分析',preferences:'個人設定',permissions:'員工與權限',business:'門市設定',exports:'資料匯出',audit:'操作稽核',incidents:'異常回報',transfers:'借貸','company-tasks':'公司流程待辦'};
export function useDashboard(store:AppStore,stores:AppStore[]=[store]){
 const[data,setData]=useState<Record<string,Dashboard>>({});const[error,setError]=useState('');const[reload,setReload]=useState(0);
 const ids=stores.map(s=>s.id).sort().join(',');
 useEffect(()=>{let alive=true;async function run(){
  if((store.settings.count_cadence|| (store.business_type==='CHAIN_RESTAURANT'?'DAILY':'MONTHLY'))==='DAILY'&&['STAFF','SUPERVISOR'].includes(store.role)){const result=await supabase.rpc('ensure_pilot_daily_count',{p_store_id:store.id});if(result.error){if(alive)setError('每日盤點未能載入，請稍後重試。');return;}}
  const entries=await Promise.all(ids.split(',').map(async id=>{const{data,error}=await supabase.rpc('get_app_dashboard',{p_store_id:id});if(error)throw error;return[id,data as Dashboard] as const;}));
  if(alive){setData(Object.fromEntries(entries));setError('');}
 }void run().catch(()=>{if(alive)setError('無法讀取營運資料，請重新載入。');});
 const focus=()=>void run().catch(()=>{if(alive)setError('無法讀取營運資料，請重新載入。');});window.addEventListener('focus',focus);const timer=setInterval(focus,30000);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',focus);};},[ids,store.id,store.role,store.business_type,store.settings.count_cadence,reload]);
 return{data,error,refresh:()=>setReload(v=>v+1)};
}
export default function RoleHome({store,stores,onNavigate,onStore,versionPanel}:{store:AppStore;stores:AppStore[];onNavigate:(v:ShellView)=>void;onStore:(id:string)=>void;versionPanel:ReactNode}){
 const work=useWorkFeed(store,localMonth());
 const management=store.role==='LOGISTICS'||store.role==='OWNER';const chain=store.business_type==='CHAIN_RESTAURANT';
 const{data,error,refresh}=useDashboard(store,management&&chain?stores:[store]);const d=data[store.id];
 const title=store.role==='OWNER'?'營運總覽':store.role==='LOGISTICS'?chain?'跨店營運':'營運總覽':store.role==='SUPERVISOR'?'今日營運重點':'歡迎回來';
 const subtitle=store.role==='OWNER'?'管理商家，掌握全局':store.role==='LOGISTICS'?chain?'查看各門市進度、異常與公司流程':'核對資料，掌握營運成果':store.role==='SUPERVISOR'?chain?'處理門市異常，確認營運順暢':'依負責門市與儲物區處理營運事項':'先完成今天的工作';
 const totals=(key:'receipt_pending'|'receipt_issues'|'expiry_urgent'|'incidents'|'erp_pending'|'receipt_erp_pending'|'count_completed')=>d?.[key]??0;
 const amount=(key:'month_receipt_amount'|'month_waste_amount')=>{const value=d?.[key];return value!==null&&value!==undefined?`NT$ ${Number(value).toLocaleString()}`:'未提供';};
 const tile=(view:ShellView,label?:string)=>{if(['business','permissions','audit'].includes(view)&&!canManageBusiness(store))return null;if(view==='members'&&store.role!=='SUPERVISOR'&&!canManageBusiness(store))return null;const Icon=icons[view]||ClipboardList;return <button type="button" key={view} className="shell-icon-tile" onClick={()=>onNavigate(view)}><span><Icon className="ui-icon"/></span><strong>{label||viewTitles[view]}</strong></button>;};
 const row=(view:ShellView,label:string,count?:number,copy?:string)=><button type="button" className="shell-list-row" onClick={()=>onNavigate(view)}><span><strong>{label}</strong>{copy&&<small>{copy}</small>}</span>{count!==undefined&&<b>{count} 項</b>}<b>›</b></button>;
 return <><div className="role-home-title"><div><span>{new Date().toLocaleDateString('zh-TW')}</span><h1>{title}</h1><p>{subtitle}</p></div></div>{error&&<p role="alert" className="pilot-message">{error}<button className="text-button" onClick={refresh}>重新載入</button></p>}{work.error&&<p role="alert">待辦{work.error}<button className="text-button" onClick={work.refresh}>重試</button></p>}{!d&&!error?<p role="status">正在讀取門市資料…</p>:d&&<>
 {store.role==='SUPERVISOR'&&<section className="shell-section"><div className="shell-section-head"><h2>今日重點</h2><button className="text-button" onClick={()=>onNavigate('tasks')}>查看全部</button></div>{d.receipt_issues+d.expiry_urgent+(!chain?d.incidents:0)>0?<div className="shell-card shell-list">{d.receipt_issues>0&&row('receiving-issue','進貨異常回報',d.receipt_issues,'理貨後有問題才回報')}{d.expiry_urgent>0&&row('expiry','即期風險',d.expiry_urgent)}{!chain&&d.incidents>0&&row('incidents','待確認異常',d.incidents)}</div>:<div className="shell-card completion-card"><strong>今天沒有待處理異常</strong><p>有異常時才會顯示在這裡。</p></div>}</section>}
 {management&&<section className="shell-section"><h2>{store.role==='OWNER'?'營運摘要／重大異常':chain?'本店營運重點':'今日待核對'}</h2><div className="shell-card shell-list">{row('receiving',chain?'門市進貨待完成':'收貨待核對',totals('receipt_pending'))}{store.has_erp?row('company-tasks','進貨 ERP 待完成',totals('receipt_erp_pending')):row('catalog','編碼待確認',undefined,'依商家需求選用')}{row('expiry',chain?'本店效期異常':'即期風險',totals('expiry_urgent'))}{row('incidents','門市異常待處理',totals('incidents'))}{row('reports','盤點紀錄',totals('count_completed'))}</div></section>}
 {!management&&<section className="shell-section"><h2>每日作業</h2><div className="shell-tile-grid">{tile('count')}{tile('receiving')}{store.role==='STAFF'&&tile('receiving-issue')}{tile('waste')}{tile('expiry')}{store.role==='STAFF'?tile('handover'):tile('stock','本店庫存')}{store.role==='SUPERVISOR'&&hasCrossStore(store)&&tile('transfers','借貸／調撥')}</div></section>}
 {!management&&store.has_erp&&<section className="shell-section"><h2>公司流程待辦</h2><div className="shell-card shell-list">{row('company-tasks','ERP 待完成',d.receipt_erp_pending,'可稍後統一處理')}</div></section>}
 {management&&chain&&<section className="shell-section"><h2>全部門市・門市狀態</h2><div className="shell-card shell-list">{stores.map(s=><button className="shell-list-row" key={s.id} onClick={()=>onStore(s.id)}><span><strong>{s.name}（{s.store_code}）</strong><small>{data[s.id]?`${data[s.id].incidents+data[s.id].receipt_pending+data[s.id].expiry_urgent} 項待處理`:'正在讀取'}</small></span><b>›</b></button>)}</div></section>}
 {management&&(!chain||store.role==='OWNER')&&<section className="shell-section"><h2>營運成果</h2><div className="shell-card result-list"><div><span>本月進貨總額</span><strong>{amount('month_receipt_amount')}</strong></div><div><span>本月食材成本</span><strong>未提供</strong></div>{store.role==='OWNER'&&<div><span>本月毛利率</span><strong>未提供</strong></div>}<div><span>本月盤點次數</span><strong>{totals('count_completed')} 次</strong></div><div><span>本月廢棄參考金額</span><strong>{amount('month_waste_amount')}</strong></div></div></section>}
 {store.role==='STAFF'&&<section className="shell-section"><h2>商家留言板</h2><div className="shell-card shell-list">{d.bulletins.length?d.bulletins.map(b=><button className="shell-list-row" key={b.id} onClick={()=>onNavigate('bulletins')}><span><strong>{b.title}</strong><small>{b.actor_name}・{displayTime(b.created_at)}</small></span><b>›</b></button>):row('bulletins','目前沒有新公告')}</div></section>}
 </>}{versionPanel}</>;
}
export function OtherWorkspace({store,onNavigate,onBack}:{store:AppStore;onNavigate:(view:ShellView)=>void;onBack:()=>void}){
 const views:ShellView[]=store.role==='STAFF'?['incidents','handover','bulletins']:store.role==='SUPERVISOR'?['incidents','handover','bulletins']:store.role==='LOGISTICS'?['count','receiving','expiry','waste','incidents','handover','reports','bulletins','preferences']:['count','receiving','expiry','waste','catalog','suppliers','costs','reports','incidents','handover','bulletins','preferences'];
 if(store.role!=='STAFF'){views.push('stock');if(hasCrossStore(store))views.push('transfers');if(store.has_erp)views.push('company-tasks');}
 if(canManageBusiness(store)){for(const v of ['members','business','audit'] as ShellView[])if(!views.includes(v))views.push(v);}if(canViewReports(store)&&!views.includes('reports'))views.push('reports');if(canExportData(store)&&!views.includes('exports'))views.push('exports');
 return <><button className="shell-back" onClick={onBack}>‹ 返回首頁</button><h1>其他作業</h1><div className="shell-card shell-list">{views.map(v=>{const Icon=icons[v]||ClipboardList;return <button className="shell-list-row" key={v} onClick={()=>onNavigate(v)}><Icon/><span><strong>{viewTitles[v]}</strong></span><b>›</b></button>;})}</div></>;
}
export function ShortagesWorkspace({store,onNavigate,onBack,onProduct}:{store:AppStore;onNavigate:(view:ShellView)=>void;onBack:()=>void;onProduct?:(id:string)=>void}){
 const{data,error,refresh}=useDashboard(store);const[search,setSearch]=useUiState('shortage-search','');const rows=data[store.id]?.shortages;const visible=rows?.filter(r=>r.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 return <><button className="shell-back" onClick={onBack}>‹ 返回首頁</button><h1>缺貨品項</h1><label className="field">搜尋品項<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>{error&&<p role="alert">{error}<button onClick={refresh}>重新載入</button></p>}<div className="shell-card shell-list">{visible?.map(r=><div key={r.id}><button className="shell-list-row" onClick={()=>onNavigate(hasCrossStore(store)?'transfers':'receiving')}><span><strong>{r.name}</strong><small>尚缺 {r.remaining??'未提供'} {r.unit}・可用 {r.available??'未提供'} {r.unit}</small><small>安全庫存設定 {r.remaining!==undefined&&r.available!==undefined?Number(r.remaining)+Number(r.available):'未提供'} {r.unit}</small></span><b>›</b></button>{onProduct&&<button className="text-button" onClick={()=>onProduct(r.id)}>調整安全庫存</button>}</div>)}</div>{rows&&!visible?.length&&<p>{rows.length?'沒有符合搜尋的品項。':'目前沒有已確認的缺貨提醒。'}</p>}</>;
}
