'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Bell,CalendarClock,Trash2,Truck,ClipboardList,Users,Settings,Package,ChartNoAxesCombined,ArrowLeftRight,Ellipsis,MessagesSquare,ShieldCheck,Building2,Download,FileClock,TriangleAlert} from 'lucide-react';
import {supabase} from '@/lib/supabase-browser';
import {hasCrossStore,type AppStore} from '@/lib/app-workspace';
import type {ShellView} from './app-shell';
import {displayTime} from './inventory-catalog';
export type Dashboard={count:{id:string;status:string;completed_at:string|null;paper_required:boolean;paper_completed_at:string|null}|null;count_items:number;count_completed:number;receipt_pending:number;receipt_issues:number;expiry_urgent:number;incidents:number;handover:number;erp_pending:number;month_receipt_amount:number|null;month_waste_amount:number|null;bulletins:{id:string;title:string;actor_name:string;created_at:string}[];shortages:{id:string;name:string;updated_at:string}[]};
const icons:Partial<Record<ShellView,typeof Bell>>={count:ClipboardList,receiving:Truck,expiry:CalendarClock,waste:Trash2,handover:MessagesSquare,other:Ellipsis,bulletins:Bell,members:Users,catalog:Package,suppliers:Truck,reports:ChartNoAxesCombined,costs:ChartNoAxesCombined,preferences:Settings,permissions:ShieldCheck,business:Building2,exports:Download,audit:FileClock,incidents:TriangleAlert,transfers:ArrowLeftRight};
export const viewTitles:Partial<Record<ShellView,string>>={home:'首頁',activity:'作業紀錄',tasks:'待辦',notifications:'通知',settings:'我的',count:'盤點',receiving:'進貨',expiry:'效期提醒',waste:'廢棄',handover:'交接',other:'其他作業',bulletins:'公佈欄',members:'成員與權限',catalog:'商品與編碼',suppliers:'供應商',reports:'報表中心',costs:'成本分析',preferences:'設定',permissions:'角色與權限',business:'商家與門市設定',exports:'資料匯出',audit:'Audit Log',incidents:'異常回報',transfers:'借貸','company-tasks':'公司流程待辦'};
export function useDashboard(store:AppStore,stores:AppStore[]=[store]){
 const[data,setData]=useState<Record<string,Dashboard>>({});const[error,setError]=useState('');const[reload,setReload]=useState(0);
 const ids=stores.map(s=>s.id).sort().join(',');
 useEffect(()=>{let alive=true;async function run(){
  if((store.settings.count_cadence|| (store.business_type==='CHAIN_RESTAURANT'?'DAILY':'MONTHLY'))==='DAILY'&&['STAFF','SUPERVISOR'].includes(store.role)){const result=await supabase.rpc('ensure_pilot_daily_count',{p_store_id:store.id});if(result.error){if(alive)setError('每日盤點未能載入，請稍後重試。');return;}}
  const entries=await Promise.all(ids.split(',').map(async id=>{const{data,error}=await supabase.rpc('get_app_dashboard',{p_store_id:id});if(error)throw error;return[id,data as Dashboard] as const;}));
  if(alive){setData(Object.fromEntries(entries));setError('');}
 }void run().catch(()=>{if(alive)setError('無法讀取營運資料，請重新載入。');});
 const focus=()=>void run().catch(()=>{if(alive)setError('無法讀取營運資料，請重新載入。');});window.addEventListener('focus',focus);const timer=setInterval(focus,30000);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',focus);};},[ids,store.id,store.role,store.business_type,store.settings.count_cadence,reload]);
 return{data,error,refresh:()=>setReload(v=>v+1)};
}
export default function RoleHome({store,stores,onNavigate,onStore,versionPanel}:{store:AppStore;stores:AppStore[];onNavigate:(v:ShellView)=>void;onStore:(id:string)=>void;versionPanel:ReactNode}){
 const management=store.role==='LOGISTICS'||store.role==='OWNER';const chain=store.business_type==='CHAIN_RESTAURANT';
 const{data,error,refresh}=useDashboard(store,management?stores:[store]);const d=data[store.id];
 const title=store.role==='OWNER'?'營運總覽':store.role==='LOGISTICS'?chain?'跨店營運':'後勤工作台':store.role==='SUPERVISOR'?'今日營運重點':'歡迎回來';
 const subtitle=store.role==='OWNER'?'管理商家，掌握全局':store.role==='LOGISTICS'?chain?'查看各門市進度、異常與公司流程':'核對資料，掌握營運成果':store.role==='SUPERVISOR'?chain?'處理門市異常，確認營運順暢':'依負責門市與儲物區處理營運事項':'先完成今天的工作';
 const totals=(key:'receipt_pending'|'receipt_issues'|'expiry_urgent'|'incidents'|'erp_pending'|'count_completed')=>Object.values(data).reduce((n,d)=>n+d[key],0);
 const amount=(key:'month_receipt_amount'|'month_waste_amount')=>{const known=Object.values(data).map(d=>d[key]).filter((v):v is number=>v!==null);return known.length?`NT$ ${known.reduce((n,v)=>n+Number(v),0).toLocaleString()}`:'未提供';};
 const countLabel=d?.count&&['DRAFT','IN_PROGRESS'].includes(d.count.status)?'繼續盤點':d?.count&&['CLOSED','REVIEWING'].includes(d.count.status)?'查看盤點結果':d?.count_items?'開始盤點':'盤點';
 const tile=(view:ShellView,label?:string)=>{const Icon=icons[view]||ClipboardList;return <button type="button" key={view} className="shell-icon-tile" onClick={()=>onNavigate(view)}><span><Icon className="ui-icon"/></span><strong>{label||viewTitles[view]}</strong></button>;};
 const row=(view:ShellView,label:string,count?:number,copy?:string)=><button type="button" className="shell-list-row" onClick={()=>onNavigate(view)}><span><strong>{label}</strong>{copy&&<small>{copy}</small>}</span>{count!==undefined&&<b>{count} 項</b>}<b>›</b></button>;
 return <><div className="role-home-title"><div><span>{new Date().toLocaleDateString('zh-TW')}</span><h1>{title}</h1><p>{subtitle}</p></div></div>{error&&<p role="alert" className="pilot-message">{error}<button className="text-button" onClick={refresh}>重新載入</button></p>}{!d&&!error?<p role="status">正在讀取門市資料…</p>:d&&<>
 {store.role==='STAFF'&&<section className="shell-section"><h2>今天先看</h2><div className="home-metrics home-action-metrics">{[['缺貨品項',d.shortages.length,'shortages'],['效期提醒',d.expiry_urgent,'expiry'],['待處理',d.incidents+d.handover+d.erp_pending,'tasks']].map(([label,value,view])=><button key={label} className="shell-metric" onClick={()=>onNavigate(view as ShellView)}><strong>{value}</strong><span>{label}</span><i aria-hidden="true">›</i></button>)}</div></section>}
 {store.role==='SUPERVISOR'&&<section className="shell-section"><div className="shell-section-head"><h2>今日重點</h2><button className="text-button" onClick={()=>onNavigate('tasks')}>查看全部</button></div><div className="shell-card shell-list">{chain&&row('count',countLabel,undefined,'店長可接手門市進度')}{row('receiving','進貨異常',d.receipt_issues,'缺貨、少到、多到與品質異常')}{row('expiry','即期風險',d.expiry_urgent)}{!chain&&row('incidents','待確認異常',d.incidents)}</div></section>}
 {management&&<section className="shell-section"><h2>{store.role==='OWNER'?'營運摘要／重大異常':chain?'今日跨店重點':'今日待核對'}</h2><div className="shell-card shell-list">{row('receiving',chain?'門市進貨待完成':'收貨待核對',totals('receipt_pending'))}{store.has_erp?row('company-tasks','公司流程待完成',totals('erp_pending')):row('catalog','編碼待確認',undefined,'依商家需求選用')}{row('expiry',chain?'跨店效期異常':'即期風險',totals('expiry_urgent'))}{row('incidents','門市異常待處理',totals('incidents'))}{row('reports','盤點紀錄',totals('count_completed'))}</div></section>}
 {!management&&<section className="shell-section"><h2>每日作業</h2><div className="shell-tile-grid">{tile('count',countLabel)}{tile('receiving')}{tile('waste')}{tile('expiry')}{tile(store.role==='STAFF'?'handover':'bulletins')}{tile('other')}</div></section>}
 {!management&&store.has_erp&&<section className="shell-section"><h2>公司流程待辦</h2><div className="shell-card shell-list">{row('company-tasks','ERP 待完成',d.erp_pending,'可稍後統一處理')}</div></section>}
 {management&&chain&&<section className="shell-section"><h2>門市狀態</h2><div className="shell-card shell-list">{stores.map(s=><button className="shell-list-row" key={s.id} onClick={()=>onStore(s.id)}><span><strong>{s.name}</strong><small>{data[s.id]?`${data[s.id].incidents+data[s.id].receipt_pending+data[s.id].expiry_urgent} 項待處理`:'正在讀取'}</small></span><b>›</b></button>)}</div></section>}
 {management&&(!chain||store.role==='OWNER')&&<section className="shell-section"><h2>營運成果</h2><div className="shell-card result-list"><div><span>本月進貨總額</span><strong>{amount('month_receipt_amount')}</strong></div><div><span>本月食材成本</span><strong>未提供</strong></div>{store.role==='OWNER'&&<div><span>本月毛利率</span><strong>未提供</strong></div>}<div><span>本月盤點次數</span><strong>{totals('count_completed')} 次</strong></div><div><span>本月廢棄參考金額</span><strong>{amount('month_waste_amount')}</strong></div></div></section>}
 {management&&<section className="shell-section"><h2>{store.role==='OWNER'?'管理設定':chain?'跨店管理':'管理功能'}</h2><div className="shell-tile-grid management-grid">{(store.role==='OWNER'?['members','business','permissions','exports','audit','other']:chain?['bulletins',...(store.has_erp?['company-tasks']:[]),'reports','preferences','other']:['catalog','suppliers','costs','reports','bulletins','preferences']).map(v=>tile(v as ShellView))}</div></section>}
 {store.role==='STAFF'&&<section className="shell-section"><h2>商家留言板</h2><div className="shell-card shell-list">{d.bulletins.length?d.bulletins.map(b=><button className="shell-list-row" key={b.id} onClick={()=>onNavigate('bulletins')}><span><strong>{b.title}</strong><small>{b.actor_name}・{displayTime(b.created_at)}</small></span><b>›</b></button>):row('bulletins','目前沒有新公告')}</div></section>}
 </>}{versionPanel}</>;
}
export function OtherWorkspace({store,onNavigate,onBack}:{store:AppStore;onNavigate:(view:ShellView)=>void;onBack:()=>void}){
 const views:ShellView[]=store.role==='STAFF'?['incidents','handover','bulletins']:store.role==='SUPERVISOR'?['incidents','handover','members','catalog','suppliers','reports','preferences']:store.role==='LOGISTICS'?['count','receiving','expiry','waste','incidents','handover','reports','bulletins','preferences']:['count','receiving','expiry','waste','catalog','suppliers','costs','reports','incidents','handover','bulletins','preferences'];
 if(hasCrossStore(store))views.push('transfers');if(store.has_erp)views.push('company-tasks');
 return <><button className="shell-back" onClick={onBack}>‹ 返回首頁</button><h1>其他作業</h1><div className="shell-card shell-list">{views.map(v=>{const Icon=icons[v]||ClipboardList;return <button className="shell-list-row" key={v} onClick={()=>onNavigate(v)}><Icon/><span><strong>{viewTitles[v]}</strong></span><b>›</b></button>;})}</div></>;
}
export function ShortagesWorkspace({store,onNavigate,onBack}:{store:AppStore;onNavigate:(view:ShellView)=>void;onBack:()=>void}){
 const{data,error,refresh}=useDashboard(store);const rows=data[store.id]?.shortages;
 return <><button className="shell-back" onClick={onBack}>‹ 返回首頁</button><h1>缺貨品項</h1>{error&&<p role="alert">{error}<button onClick={refresh}>重新載入</button></p>}<div className="shell-card shell-list">{rows?.map(r=><button key={r.id} className="shell-list-row" onClick={()=>onNavigate(hasCrossStore(store)?'transfers':'receiving')}><span><strong>{r.name}</strong><small>最近一次已確認盤點低於已設定的備料需求</small></span><b>›</b></button>)}</div>{rows&&!rows.length&&<p>目前沒有已確認的缺貨提醒。</p>}</>;
}
