'use client';
import {useEffect,useState} from 'react';
import {useWorkspace,useOperation} from './operation-hooks';
import {stockStateLabels,movementPlan} from '@/lib/stock-rules.mjs';
type Position={id:string;product_id:string;zone_id:string;zone_name:string;unit:string;quantity:number;state:string;ready_at:string|null;revision:number};
type Product={id:string;name:string;unit:string;thaw_enabled:boolean;thaw_minutes:number|null;stock:{total:number|null;available:number|null}};
type Data={products:Product[];zones:{id:string;name:string}[];positions:Position[]};
export default function StockWorkspace({storeId,userId,canManage,canOperate=true,initialPositionId,onBack}:{initialPositionId?:string;storeId:string;userId:string;canManage:boolean;canOperate?:boolean;onBack:()=>void}){
 const [now,setNow]=useState(()=>Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 const w=useWorkspace<Data>(storeId,'stock');const op=useOperation(storeId,userId);const[selected,setSelected]=useState('');const[position,setPosition]=useState(initialPositionId||'');const[qty,setQty]=useState('');const[zone,setZone]=useState('');const[state,setState]=useState('READY');const[minutes,setMinutes]=useState('');const[notice,setNotice]=useState('');
 const selectedId=selected||w.data?.positions.find(p=>p.id===initialPositionId)?.product_id||'';const p=w.data?.products.find(p=>p.id===selectedId);const pos=w.data?.positions.find(p=>p.id===position);const positions=w.data?.positions.filter(x=>x.product_id===selectedId)||[];
 const open=async(id:string)=>{setSelected(id);setPosition('');const p=w.data?.products.find(p=>p.id===id);setMinutes(String(p?.thaw_minutes||''));if(await op.run('stock.open',{product_id:id}))await w.refresh();};
 const move=async()=>{if(!pos||!p)return;try{movementPlan(pos,qty,state,p.thaw_minutes);const r=await op.run('stock.move',{product_id:p.id,position_id:pos.id,revision:pos.revision,quantity:Number(qty),zone_id:zone||pos.zone_id,state});if(r){setPosition('');setQty('');setNotice('分區數量與狀態已儲存，總量不變。');await w.refresh();}}catch(e){op.setError(e instanceof Error&&e.message==='THAW_DURATION_REQUIRED'?'請先由主管設定解凍所需時間。':'請確認數量未超過來源庫存。');}};
 return <><button className="shell-back" onClick={onBack}>‹ 返回原作業</button><h1>分區與解凍</h1>{(w.error||op.error)&&<p role="alert">{op.error||w.error}</p>}{notice&&<p role="status">{notice}</p>}
 <label className="field">品項<select value={selectedId} onChange={e=>void open(e.target.value)}><option value="">選擇品項</option>{w.data?.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 {p&&<><p>總庫存：{p.stock.total??'未提供'} {p.unit}・目前可用：{p.stock.available??'未提供'} {p.unit}</p>{canManage&&<details className="setup-panel"><summary>此品項解凍設定（選用）</summary><label className="field">解凍所需分鐘<input type="number" min="1" max="43200" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><button className="shell-secondary" disabled={op.busy} onClick={async()=>{if(await op.run('stock.settings',{product_id:p.id,thaw_enabled:true,thaw_minutes:Number(minutes)})){setNotice('已保存本店解凍時間。');await w.refresh();}}}>儲存解凍設定</button>{p.thaw_enabled&&<button className="text-button" onClick={async()=>{if(await op.run('stock.settings',{product_id:p.id,thaw_enabled:false,thaw_minutes:p.thaw_minutes}))await w.refresh();}}>停用解凍管理</button>}</details>}
 <div className="shell-card shell-list">{positions.map(row=><button type="button" className="shell-list-row" key={row.id} disabled={!canOperate} onClick={()=>{setPosition(row.id);setZone(row.zone_id);setState(row.state==='UNCONFIRMED'?'READY':row.state);setQty('');}}><span><strong>{row.zone_name}・{row.quantity} {row.unit}</strong><small>{(stockStateLabels as Record<string,string>)[row.state]||'狀態待確認'}{row.ready_at?`・預計 ${new Date(row.ready_at).toLocaleString('zh-TW')}`:''}</small>{row.state==='THAWING'&&row.ready_at&&Date.parse(row.ready_at)<=now&&<small>預計時間已到，請現場確認後再標記可用。</small>}</span><b>›</b></button>)}</div>{!positions.length&&<p>尚無已確認庫存；請先完成盤點或記錄實際收貨。</p>}
 {pos&&canOperate&&<form className="shell-card transfer-form" onSubmit={e=>{e.preventDefault();void move();}}><h2>{pos.zone_name} → 移動／確認狀態</h2><label className="field">數量（{pos.unit}）<input type="number" min="0.000001" max={pos.quantity} step="any" value={qty} onChange={e=>setQty(e.target.value)} required/></label><label className="field">目的區域<select value={zone||pos.zone_id} onChange={e=>setZone(e.target.value)} required>{w.data?.zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label>{p.thaw_enabled&&<label className="field">狀態<select value={state} onChange={e=>setState(e.target.value)}>{Object.entries(stockStateLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}<button className="shell-primary" disabled={op.busy}>{op.busy?'儲存中…':'確認儲存'}</button><button className="text-button" type="button" onClick={()=>setPosition('')}>取消</button></form>}</>}
 </>;
}

export function ThawNotice({storeId,onOpen}:{storeId:string;onOpen:()=>void}){const w=useWorkspace<Data>(storeId,'stock');const[now,setNow]=useState(()=>Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);const pending=w.data?.positions.filter(p=>p.state==='UNCONFIRMED'||(p.state==='THAWING'&&p.ready_at&&Date.parse(p.ready_at)<=now))||[];return pending.length?<button className="shell-secondary full" onClick={onOpen}>分區與解凍待確認・{pending.length} 筆</button>:null;}
