'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Search,Plus,ArrowUpRight,Phone} from 'lucide-react';
import {supabase} from '@/lib/supabase-browser';
import {receiptRead,receiptReadRows,receiptReadError} from '@/lib/receipt-read';
import {supplierForLine,supplierMatches,supplierPriceItems,safeSupplierLink,type SupplierProfile,type SupplierProduct,type SupplierReceiptLine,type SupplierPriceItem} from '@/lib/supplier-prices';
import type {AppStore} from '@/lib/app-workspace';
import {useOperation,useOperationDraft} from './operation-hooks';
import {useUiState} from './workspace-memory';

type Draft={kind:'supplier'|'product';id:string;name:string;code:string;updated_at:string;is_active:boolean;contact_name:string;phone:string;delivery_note:string;order_method:string;order_url:string;cutoff_time:string;order_note:string;aliases:string;unit:string;specification:string;supplier_id:string};
const empty:Draft={kind:'supplier',id:'',name:'',code:'',updated_at:'',is_active:true,contact_name:'',phone:'',delivery_note:'',order_method:'',order_url:'',cutoff_time:'',order_note:'',aliases:'',unit:'',specification:'',supplier_id:''};
const money=(value:number|null)=>value===null?'—':`NT$ ${value.toLocaleString('zh-TW',{maximumFractionDigits:4})}`;
function delta(item:SupplierPriceItem){if(item.ambiguous)return '同單多種價格';if(item.latest===null)return item.pending?'待核對':'尚無進價';if(item.previous===null)return '首次紀錄';if(!item.change)return '無異動';return `${item.change>0?'↑':'↓'} ${Math.abs(item.change).toLocaleString()}${item.percent===null?'':`（${Math.abs(item.percent)}%）`}`;}
export default function SupplierWorkspace({store,userId,onBack,onReceipt,onReceiving,onProduct}:{store:AppStore;userId:string;onBack:()=>void;onReceipt:(id:string)=>void;onReceiving:(names:string[])=>void;onProduct:(id:string)=>void}){
 const[profiles,setProfiles]=useState<SupplierProfile[]>([]),[products,setProducts]=useState<SupplierProduct[]>([]),[lines,setLines]=useState<SupplierReceiptLine[]>([]);
 const[editable,setEditable]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[priceError,setPriceError]=useState(''),[notice,setNotice]=useState('');
 const[selected,setSelected]=useUiState('supplier-selected',''),[tab,setTab]=useUiState<'prices'|'contact'>('supplier-tab','prices'),[search,setSearch]=useUiState('supplier-search',''),[itemSearch,setItemSearch]=useState(''),[filter,setFilter]=useState('ALL');
 const[historyKey,setHistoryKey]=useState<string|null>(null),[editor,setEditor]=useState(false);
 const[draft,setDraft,clearDraft]=useOperationDraft(userId,store.id,'supplier-profile',empty);const operation=useOperation(store.id,userId);
 const flight=useRef<AbortController|null>(null),generation=useRef(0),editing=useRef(false);
 useEffect(()=>{editing.current=editor||operation.busy;},[editor,operation.busy]);
 const refresh=useCallback(async(background=false)=>{
  if(background&&(flight.current||editing.current||document.visibilityState!=='visible'))return;
  flight.current?.abort();const controller=new AbortController();flight.current=controller;const seq=++generation.current;const current=()=>seq===generation.current&&!controller.signal.aborted;setLoading(true);
  const read=(section:'suppliers'|'catalog')=>receiptRead(signal=>supabase.rpc('app_workspace',{p_store_id:store.id,p_section:section,p_filter:{}}).abortSignal(signal),controller.signal);
  const metadata=Promise.all([read('suppliers'),read('catalog')]).then(([s,p])=>{if(s.error||p.error)throw s.error||p.error;const data=s.data as unknown as {suppliers:SupplierProfile[];editable:boolean},catalog=p.data as unknown as {products:SupplierProduct[]};if(!Array.isArray(data?.suppliers)||!Array.isArray(catalog?.products))throw Error('INVALID_RESPONSE');if(current()){setProfiles(data.suppliers);setProducts(catalog.products);setEditable(data.editable);setError('');}return data.suppliers;}).catch(e=>{if(current()){setError(receiptReadError(e));setEditable(false);}return undefined;});
  const prices=Promise.all([receiptRead(signal=>supabase.rpc('get_pilot_receipt_ledger',{p_store_id:store.id}).abortSignal(signal),controller.signal),receiptRead(signal=>supabase.rpc('get_baihuayuan_record_flags',{p_store_id:store.id,p_entity_type:'RECEIPT_BATCH'}).abortSignal(signal),controller.signal)]).then(([r,f])=>{const rows=receiptReadRows<SupplierReceiptLine>(r),flags=receiptReadRows<{entity_id:string;state:string}>(f);const hidden=new Set(flags.filter(x=>x.state!=='LIVE').map(x=>x.entity_id));if(current()){setLines(rows.filter(row=>!hidden.has(row.batch_id)));setPriceError('');}}).catch(e=>{if(current()){setLines([]);setPriceError('進價資料未能讀取。'+receiptReadError(e));}});
  const [result]=await Promise.all([metadata,prices]);if(current()){setLoading(false);flight.current=null;}controller.abort();return result;
 },[store.id]);
 useEffect(()=>{const counter=generation,activeFlight=flight;const run=()=>void refresh(true);void refresh();window.addEventListener('focus',run);window.addEventListener('online',run);return()=>{counter.current++;activeFlight.current?.abort();window.removeEventListener('focus',run);window.removeEventListener('online',run);};},[refresh]);
 const itemsBySupplier=useMemo(()=>new Map(profiles.map(s=>[s.id,supplierPriceItems(s,products,lines,profiles)])),[profiles,products,lines]);
 const supplier=profiles.find(s=>s.id===selected),items=itemsBySupplier.get(selected)||[],history=items.find(item=>item.key===historyKey);
 const unresolved=useMemo(()=>[...new Set(lines.filter(row=>!supplierForLine(profiles,row)).map(row=>row.supplier_name))],[lines,profiles]);
 const overview=profiles.filter(s=>{const items=itemsBySupplier.get(s.id)||[];return (filter!=='ACTIVE'||s.is_active)&&(filter!=='UP'||items.some(i=>(i.change||0)>0))&&`${s.name} ${(s.aliases||[]).join(' ')} ${items.map(i=>i.name).join(' ')}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase());});
 const newSupplier=(name='')=>{operation.setError('');setDraft({...empty,name});setEditor(true);};
 const editSupplier=(s:SupplierProfile)=>{operation.setError('');setDraft({...empty,id:s.id,name:s.name,code:s.supplier_code||'',updated_at:s.updated_at,is_active:s.is_active,contact_name:s.contact_name||'',phone:s.phone||'',delivery_note:s.delivery_note||'',order_method:s.order_method||'',order_url:s.order_url||'',cutoff_time:s.cutoff_time||'',order_note:s.order_note||'',aliases:(s.aliases||[]).join('、')});setEditor(true);};
 const save=async()=>{
  if(!editable||operation.busy)return;
  if(draft.kind==='supplier'&&!draft.id&&profiles.some(s=>supplierMatches(s,draft.name))){operation.setError('已有相同名稱或別名的供應商，請取消後開啟既有資料。');return;}
  if(draft.order_url&&!safeSupplierLink(draft.order_url)){operation.setError('請填寫完整的 http 或 https 訂貨網址。');return;}
  const payload=draft.kind==='supplier'?{...draft,id:draft.id||null,aliases:draft.aliases.split(/[、,\n]/).map(x=>x.trim()).filter(Boolean)}:{name:draft.name,unit:draft.unit,specification:draft.specification,supplier_id:draft.supplier_id,code:'',aliases:[],safety_quantity:null,note:''};
  const result=await operation.run<{id:string}>(draft.kind==='supplier'?'supplier.save':'product.save',payload);
  if(result){if(draft.kind==='supplier')setSelected(result.id);setEditor(false);clearDraft();setNotice('已儲存。進價仍以核對後的原始貨單為準。');await refresh();}
 };
 const closeEditor=()=>{if(operation.busy)return;if(window.confirm('放棄這次尚未儲存的修改？')){setEditor(false);clearDraft();operation.setError('');}};
 const reloadEditor=async()=>{if(!window.confirm('重新載入會捨棄本次修改，確定繼續？'))return;const rows=await refresh();const row=rows?.find(s=>s.id===draft.id);if(row)editSupplier(row);};
 const contactAction=(s:SupplierProfile)=>{const link=safeSupplierLink(s.order_url);if(link)return <a className="supplier-contact-link" href={link} target="_blank" rel="noopener noreferrer">{s.order_method||'訂貨網站'} <ArrowUpRight size={14}/></a>;if(s.phone&&(!s.order_method||/電話/.test(s.order_method)))return <a className="supplier-contact-link" href={`tel:${s.phone.replace(/[^+\d*#,;]/g,'')}`}><Phone size={14}/>{s.order_method||'電話聯絡'}</a>;return <button type="button" className="text-button" onClick={()=>{setSelected(s.id);setTab('contact');}}>{s.order_method||'尚未設定'}</button>;};
 const field=(name:keyof Draft,label:string,required=false,type='text',maxLength=160)=><label><span>{label}</span><input aria-label={label} type={type} required={required} maxLength={maxLength} value={String(draft[name])} disabled={operation.busy} onChange={e=>{operation.setError('');setDraft({...draft,[name]:e.target.value});}}/></label>;
 return <div className="supplier-workspace">
  <button type="button" className="shell-back" onClick={()=>supplier?setSelected(''):onBack()}>‹ {supplier?'返回供應商':'返回首頁'}</button>
  <div className="supplier-heading"><div><h1>{supplier?.name||'供應商'}</h1>{!supplier&&<p>管理供應品項、進價與聯絡方式。</p>}</div><div className="supplier-heading-actions">{supplier?<>{editable&&<button type="button" className="shell-secondary" onClick={()=>editSupplier(supplier)}>編輯供應商</button>}<button type="button" className="text-button" onClick={()=>onReceiving([supplier.name,...(supplier.aliases||[])])}>查看此供應商進貨明細 ↗</button></>:editable&&<button type="button" className="shell-primary" onClick={()=>newSupplier()}><Plus size={17}/>新增供應商</button>}</div></div>
  {notice&&<p className="shell-note" role="status">{notice}</p>}{error&&<p className="shell-note" role="alert">{error}</p>}{priceError&&<p className="shell-note" role="alert">{priceError}</p>}
  <div className="supplier-read"><span role="status">{loading?'正在讀取供應商與進價…':''}</span><button type="button" className="text-button" disabled={loading||operation.busy} onClick={()=>void refresh()}>重新讀取</button></div>
  {!editor&&draft.name&&editable&&<button type="button" className="text-button" onClick={()=>setEditor(true)}>繼續未儲存的修改：{draft.name}</button>}
  {!supplier?<>
   <div className="supplier-toolbar"><label className="supplier-search"><Search size={18}/><input aria-label="搜尋供應商、品項" placeholder="搜尋供應商、品項…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="供應商篩選" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">全部供應商</option><option value="ACTIVE">使用中</option><option value="UP">有漲價品項</option></select></div>
   <div className="supplier-table-wrap"><table className="supplier-table"><thead><tr><th>供應商</th><th>供應品項</th><th>進價異動</th><th>聯絡與叫貨</th><th>操作</th></tr></thead><tbody>{overview.map(s=>{const items=itemsBySupplier.get(s.id)||[],up=items.filter(i=>(i.change||0)>0).length,down=items.filter(i=>(i.change||0)<0).length,pending=items.some(i=>i.pending||i.ambiguous),available=items.some(i=>i.previous!==null&&i.latest!==null);return <tr key={s.id}><td><strong>{s.name}</strong>{!s.is_active&&<small>已停用</small>}</td><td>{priceError||loading?'—':`${items.length} 項`}</td><td>{priceError?'無法讀取':loading?'讀取中':<div className="supplier-badges">{!!up&&<span className="supplier-change up">{up} 項漲價</span>}{!!down&&<span className="supplier-change down">{down} 項降價</span>}{pending&&<span className="supplier-change pending">待核對</span>}{!up&&!down&&!pending&&(available?'無異動':'尚無比較資料')}</div>}</td><td>{contactAction(s)}</td><td><button type="button" className="text-button" onClick={()=>{setSelected(s.id);setTab('prices');setItemSearch('');}}>查看 →</button></td></tr>;})}</tbody></table></div>
   {!loading&&!error&&!overview.length&&<p className="shell-note">目前沒有符合條件的供應商。</p>}
   {!!unresolved.length&&!priceError&&<details className="supplier-unmatched"><summary>{unresolved.length} 個貨單供應商名稱尚待整理</summary><p>確認是否為既有供應商；可在「編輯供應商」補上貨單別名，或建立新供應商。</p>{unresolved.map(name=><div key={name}><strong>{name}</strong><button className="text-button" onClick={()=>onReceiving([name])}>查看原始貨單</button>{editable&&name!=='未提供'&&<button className="text-button" onClick={()=>newSupplier(name)}>新增供應商</button>}</div>)}</details>}
  </>:<>
   <div className="supplier-tabs" role="tablist" aria-label="供應商資料"><button type="button" role="tab" aria-selected={tab==='prices'} onClick={()=>setTab('prices')}>品項與進價</button><button type="button" role="tab" aria-selected={tab==='contact'} onClick={()=>setTab('contact')}>聯絡與叫貨資料</button></div>
   {tab==='prices'?<section role="tabpanel" aria-label="品項與進價"><div className="supplier-toolbar"><label className="supplier-search"><Search size={18}/><input aria-label="搜尋品項" placeholder="搜尋品項…" value={itemSearch} onChange={e=>setItemSearch(e.target.value)}/></label>{editable&&<button type="button" className="shell-primary" onClick={()=>{operation.setError('');setDraft({...empty,kind:'product',supplier_id:supplier.id});setEditor(true);}}><Plus size={17}/>新增品項</button>}</div>
   <div className="supplier-table-wrap"><table className="supplier-table"><thead><tr><th>品名／規格</th><th>單位</th><th>上次未稅單價</th><th>最新未稅單價</th><th>漲跌</th><th>操作</th></tr></thead><tbody>{items.filter(i=>`${i.name} ${i.specification}`.toLocaleLowerCase().includes(itemSearch.toLocaleLowerCase())).map(item=><tr key={item.key}><td><strong>{item.name}</strong><small>{item.specification}</small>{!!item.pending&&<small>{item.pending} 筆待核對</small>}</td><td>{item.unit}</td><td>{money(item.previous)}</td><td>{money(item.latest)}</td><td><span className={`supplier-change ${(item.change||0)>0?'up':(item.change||0)<0?'down':''}`}>{delta(item)}</span></td><td><button type="button" className="text-button" onClick={()=>setHistoryKey(item.key)}>查看紀錄</button></td></tr>)}</tbody></table></div>{!loading&&!items.length&&!priceError&&<p className="shell-note">尚無供應品項，可新增品項或從進貨貨單建立。</p>}<p className="supplier-footnote">辨識有誤？從「查看紀錄」開啟原始貨單修正，核對後更新進價。</p></section>:<section role="tabpanel" aria-label="聯絡與叫貨資料" className="supplier-contact-panel"><div className="supplier-contact-heading"><h2>聯絡與叫貨資料</h2>{editable&&<button type="button" className="shell-secondary" onClick={()=>editSupplier(supplier)}>編輯聯絡資料</button>}</div><dl>{[['聯絡人',supplier.contact_name],['電話',supplier.phone],['叫貨方式',supplier.order_method],['收單時間',supplier.cutoff_time],['配送日／配送資訊',supplier.delivery_note],['備註',supplier.order_note]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'尚未設定'}</dd></div>)}<div><dt>訂貨連結</dt><dd>{safeSupplierLink(supplier.order_url)?<a href={safeSupplierLink(supplier.order_url)!} target="_blank" rel="noopener noreferrer">開啟訂貨連結 ↗</a>:'尚未設定'}</dd></div></dl></section>}
  </>}
  <p className="supplier-footnote">進價比較以同品項、同規格、同單位的前後兩張已核對貨單為準。測試與已移出資料不計入。</p>
  {history&&<div className="supplier-modal-backdrop"><section className="supplier-modal" role="dialog" aria-modal="true" aria-label="進價紀錄"><div className="supplier-contact-heading"><div><h2>{history.name}</h2><p>{history.specification}・{history.unit}</p></div><button type="button" className="text-button" onClick={()=>setHistoryKey(null)}>關閉</button></div>{editable&&history.productId&&<button type="button" className="text-button" onClick={()=>onProduct(history.productId!)}>編輯品項資料</button>}{!history.history.length&&<p className="shell-note">尚無進價紀錄；完成進貨核對後會顯示於此。</p>}<div className="supplier-table-wrap"><table className="supplier-table"><thead><tr><th>進貨日期</th><th>未稅單價</th><th>核對狀態</th><th>原始貨單</th></tr></thead><tbody>{history.history.map(row=><tr key={row.batch_id+':'+row.row_key}><td>{row.receipt_date||'日期待確認'}</td><td>{money(row.unit_price)}</td><td>{row.status==='COMPLETE'?'已核對':'待核對'}</td><td><button type="button" className="text-button" onClick={()=>onReceipt(row.batch_id)}>{row.status==='COMPLETE'?'查看原單':'開啟核對／修正'}</button></td></tr>)}</tbody></table></div></section></div>}
  {editor&&<div className="supplier-modal-backdrop"><section className="supplier-modal" role="dialog" aria-modal="true" aria-label={draft.kind==='product'?'新增品項':draft.id?'編輯供應商':'新增供應商'}><form onSubmit={e=>{e.preventDefault();void save();}}><div className="supplier-contact-heading"><h2>{draft.kind==='product'?'新增品項':draft.id?'編輯供應商':'新增供應商'}</h2><button type="button" className="text-button" disabled={operation.busy} onClick={closeEditor}>取消</button></div><div className="supplier-form">{field('name',draft.kind==='supplier'?'供應商名稱':'品名',true)}{draft.kind==='supplier'?<>{field('contact_name','聯絡人')}{field('phone','電話',false,'tel')}{field('order_method','叫貨方式（例如 LINE、電話、網站）',false,'text',80)}{field('order_url','LINE／訂貨網址',false,'url',2000)}{field('cutoff_time','收單時間')}{field('delivery_note','配送日／配送資訊',false,'text',2000)}<label className="supplier-form-wide"><span>備註</span><textarea aria-label="備註" maxLength={4000} disabled={operation.busy} value={draft.order_note} onChange={e=>setDraft({...draft,order_note:e.target.value})}/></label><label className="supplier-form-wide"><span>貨單上的其他名稱（以頓號分隔）</span><textarea aria-label="貨單上的其他名稱（以頓號分隔）" disabled={operation.busy} value={draft.aliases} onChange={e=>setDraft({...draft,aliases:e.target.value})}/></label></>:<>{field('unit','單位',true,'text',30)}{field('specification','規格')}<p className="supplier-form-wide">新增供應品項資料；進價會從核對後的進貨貨單取得。</p></>}</div>{operation.error&&<p role="alert" className="shell-note">{operation.error}{draft.id&&<button type="button" className="text-button" disabled={loading||operation.busy} onClick={()=>void reloadEditor()}>重新載入此筆（捨棄修改）</button>}</p>}<div className="supplier-form-actions"><button type="submit" className="shell-primary" disabled={operation.busy||!editable}>{operation.busy?'儲存中…':operation.error?'重試儲存':'儲存'}</button></div></form></section></div>}
 </div>;
}
