'use client';
import {useState} from 'react';
import {Search,ArrowLeftRight,ClipboardList,CheckCircle2} from 'lucide-react';
import {appError,groupedQuantities,localMonth,monthRange,readWorkspace,type AppStore} from '@/lib/app-workspace';
import {useOperation,useOperationDraft,useWorkspace} from './operation-hooks';
import {displayTime} from './inventory-catalog';

type Movement = {id:string;from_store_id:string;to_store_id:string;from_name:string;to_name:string;kind:'LOAN'|'TRANSFER';name:string;quantity:number;unit:string;returned_quantity:number;expected_return_on:string|null;status:string;revision:number;actor_name:string;created_at:string;closed_at:string|null;reference_price:number|null;events:{id:string;action:string;name:string;quantity:number;unit:string;actor_name:string;created_at:string}[]};
type Workspace = {records:Movement[];stores:{id:string;name:string}[];products:{id:string;name:string;unit:string}[];has_erp:boolean};
type Page='home'|'search'|'new'|'open'|'history'|'monthly'|'detail'|'return'|'exchange'|'complete';
const statusName:Record<string,string>={OPEN:'待歸還',RETURNED:'已歸還',EXCHANGED:'換貨結清',COMPLETE:'調撥完成'};
export default function TransfersWorkspace({store,userId,onBack,returnLabel="返回首頁"}:{store:AppStore;userId:string;onBack:()=>void;returnLabel?:string}){
 const[page,setPage]=useState<Page>('home');const[detailOrigin,setDetailOrigin]=useState<Page>('open');const[completedEntry,setCompletedEntry]=useState<{name:string;quantity:string;unit:string}>();const[month,setMonth]=useState(localMonth);const workspace=useWorkspace<Workspace>(store.id,'transfers',monthRange(month));
 const operation=useOperation(store.id,userId);const[selected,setSelected]=useState<string>();const[complete,setComplete]=useState<Movement>();const[completionAction,setCompletionAction]=useState('create');
 const[search,setSearch]=useState('');const[searching,setSearching]=useState(false);const[results,setResults]=useState<{id:string;name:string;updated_at:string|null}[]>();const[searchError,setSearchError]=useState('');
 const[draft,setDraft,clearDraft]=useOperationDraft(userId,store.id,'movement',{mode:'loan',other_store_id:'',product_id:'',name:'',quantity:'',unit:'',expected_return_on:''});
 const[settlement,setSettlement,clearSettlement]=useOperationDraft(userId,store.id,`settlement:${selected||'none'}:${page==='exchange'?'exchange':'return'}`,{quantity:'',name:'',unit:''});
 const data=workspace.data;const current=data?.records.find(r=>r.id===selected);const field=store.role==='STAFF'||store.role==='SUPERVISOR';
 const pending=(data?.records||[]).filter(r=>r.status==='OPEN');const history=(data?.records||[]).filter(r=>localMonthOf(r.created_at)===month);const moves=history.filter(r=>r.kind==='TRANSFER');
 const change=(next:Page)=>{operation.setError('');setPage(next);};
 const open=(row:Movement)=>{setDetailOrigin(page);setSelected(row.id);change('detail');};
 const title:Record<Page,string>={home:'借貸',search:'搜尋庫存',new:'新增紀錄',open:'待處理',history:'借貸紀錄',monthly:'本月調撥',detail:current?.kind==='TRANSFER'?'調撥':current?.to_store_id===store.id?'借入':'借出',return:current?.to_store_id===store.id?'記錄已歸還':'記錄收到歸還',exchange:'記錄換回品項',complete:completionAction==='return'?'歸還已記錄':complete?.status==='EXCHANGED'?'換貨已結清':complete?.kind==='TRANSFER'?'調撥已記錄':'借貸已記錄'};
 const back=()=>{if(page==='home')onBack();else if(page==='return'||page==='exchange')change('detail');else if(page==='detail')change(detailOrigin);else change('home');};
 const save=async()=>{const result=await operation.run<Movement>('movement.create',{...draft,quantity:Number(draft.quantity)});if(result){setCompletionAction('create');setCompletedEntry({name:draft.name,quantity:draft.quantity,unit:draft.unit});clearDraft();setComplete(result);change('complete');await workspace.refresh();}};
 const settle=async()=>{if(!current)return;const result=await operation.run<Movement>(page==='exchange'?'movement.exchange':'movement.return',{id:current.id,revision:current.revision,quantity:Number(settlement.quantity),...(page==='exchange'?{name:settlement.name,unit:settlement.unit}:{})});if(result){setCompletionAction(page);setCompletedEntry({name:page==='exchange'?settlement.name:current.name,quantity:settlement.quantity,unit:page==='exchange'?settlement.unit:current.unit});clearSettlement();setComplete(result);change('complete');await workspace.refresh();}};
 const units=[...new Set([...(data?.products.map(p=>p.unit)||[]),'包','公斤','盒','瓶','罐','個','片','塊','袋','箱'])];
 const rowCard=(row:Movement)=><button key={row.id} type="button" className="shell-list-row" onClick={()=>open(row)}><span><strong>{row.name} {row.quantity} {row.unit}</strong><small>{row.from_name} → {row.to_name}・{statusName[row.status]}</small>{row.status==='OPEN'&&<small>待還 {Number(row.quantity)-Number(row.returned_quantity)} {row.unit}{row.expected_return_on?`・預計 ${row.expected_return_on}`:''}</small>}</span><b>›</b></button>;
 return <><button type="button" className="shell-back" onClick={back}>‹ <span>{page==='home'?returnLabel:page==='return'||page==='exchange'?'返回借貸明細':'返回借貸'}</span></button>
 <div className="workspace-heading">{page!=='complete'&&<h1>{title[page]}</h1>}</div>
 {(workspace.error||operation.error)&&<p className="pilot-message" role="alert">{operation.error||workspace.error}</p>}
 {workspace.error&&<button className="shell-secondary" onClick={()=>void workspace.refresh()}>重新讀取</button>}
 {workspace.loading&&!data?<p role="status">正在讀取借貸紀錄…</p>:<>
 {page==='home'&&<><button type="button" className="transfer-search-entry" onClick={()=>change('search')}><span><Search/></span><div><strong>搜尋庫存</strong><small>查看可能有貨的門市</small></div><b>›</b></button><div className="transfer-entry-grid">{field&&<Entry label="新增紀錄" copy="借入、借出或調撥" onClick={()=>change('new')}/>}<Entry label="待處理" copy={`尚未歸還 ${pending.length} 筆`} onClick={()=>change('open')}/><Entry label="借貸紀錄" copy={`本月 ${history.length} 筆`} onClick={()=>change('history')}/>{!field&&<Entry label="本月調撥" copy="品項、數量與門市" onClick={()=>change('monthly')}/>}</div></>}
 {page==='search'&&<><form className="transfer-search-form" onSubmit={async e=>{e.preventDefault();setSearching(true);setSearchError('');try{const next=await readWorkspace<{stores:NonNullable<typeof results>}>(store.id,'transfer-search',{search});setResults(next.stores);}catch(error){setSearchError(appError(error));}finally{setSearching(false);}}}><label><Search/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} aria-label="搜尋品項" placeholder="輸入品項名稱" required/><button type="submit" disabled={searching}>{searching?'搜尋中…':'搜尋'}</button></label></form>{searchError&&<p className="pilot-message" role="alert">{searchError}</p>}<div className="transfer-recommendations">{results?.map((s,i)=><article className="shell-card transfer-recommendation" key={s.id}><header><span>{i+1}</span><div><strong>{s.name}</strong><small>{s.updated_at?`${displayTime(s.updated_at)} 更新`:'尚無已完成盤點時間'}</small></div></header></article>)}</div>{results?.length===0&&<p>目前沒有符合的門市品項紀錄。</p>}<p className="shell-note">庫存可能因現場使用而變動，實際品項與數量請聯絡門市確認。</p></>}
 {page==='new'&&field&&<form onSubmit={e=>{e.preventDefault();void save();}}><section className="shell-card transfer-form"><label><span>異動方式</span><select aria-label="異動方式" value={draft.mode} onChange={e=>setDraft({...draft,mode:e.target.value})}><option value="loan">借入</option><option value="loan_out">借出</option><option value="move">調撥</option></select></label><label><span>門市</span><select aria-label="門市" value={draft.other_store_id} onChange={e=>setDraft({...draft,other_store_id:e.target.value})} required><option value="">選擇門市</option>{data?.stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label><span>品項</span><input list="movement-products" value={draft.name} maxLength={160} onChange={e=>{const p=data?.products.find(p=>p.name===e.target.value);setDraft({...draft,name:e.target.value,product_id:p?.id||'',unit:p?.unit||draft.unit});}} required/></label><datalist id="movement-products">{data?.products.map(p=><option key={p.id} value={p.name}/>)}</datalist><label><span>數量</span><div className="transfer-quantity"><input aria-label="數量" type="number" min="0.000001" max="999999999" step="any" value={draft.quantity} onChange={e=>setDraft({...draft,quantity:e.target.value})} required/><select aria-label="單位" value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})} required><option value="">單位</option>{units.map(u=><option key={u}>{u}</option>)}</select></div></label>{draft.mode!=='move'&&<label><span>預計歸還日（選填）</span><input type="date" value={draft.expected_return_on} onChange={e=>setDraft({...draft,expected_return_on:e.target.value})}/></label>}</section><button type="submit" className="shell-primary full" disabled={operation.busy}>{operation.busy?'儲存中…':`完成${draft.mode==='loan'?'借入':draft.mode==='loan_out'?'借出':'調撥'}紀錄`}</button></form>}
 {page==='open'&&<>{['借入','借出'].map((label,index)=><section className="shell-section" key={label}><h2>{label}</h2><div className="shell-card shell-list">{pending.filter(r=>index===0?r.to_store_id===store.id:r.from_store_id===store.id).map(rowCard)}</div></section>)}{!pending.length&&<p>目前沒有尚未歸還的紀錄。</p>}</>}
 {(page==='history'||page==='monthly')&&<><label className="field">月份<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label>{page==='history'&&<button className="text-button" onClick={()=>change('monthly')}>查看本月調撥 ›</button>}<div className="shell-card shell-list">{(page==='monthly'?moves:history).map(rowCard)}</div>{page==='monthly'&&<section className="shell-section"><h2>品項彙整</h2><div className="shell-card result-list">{groupedQuantities(moves).map(r=><div key={JSON.stringify([r.name,r.unit])}><span>{r.name}</span><strong>{r.quantity} {r.unit}</strong></div>)}</div></section>}{!(page==='monthly'?moves:history).length&&<p>本月沒有紀錄。</p>}</>}
 {page==='detail'&&current&&<><section className="shell-card result-list transfer-loan-summary"><Info label={current.to_store_id===store.id?'借出門市':'借入門市'} value={current.to_store_id===store.id?current.from_name:current.to_name}/><Info label="品項" value={current.name}/><Info label={current.kind==='TRANSFER'?'調撥數量':'借貸數量'} value={`${current.quantity} ${current.unit}`}/>{current.kind==='LOAN'&&<><Info label="剩餘數量" value={`${Number(current.quantity)-Number(current.returned_quantity)} ${current.unit}`}/><Info label="預計歸還" value={current.expected_return_on||'未設定'}/></>}<Info label="經手人" value={`${current.actor_name||'已保存人員'}・${displayTime(current.created_at)}`}/><Info label="狀態" value={statusName[current.status]}/>{!data?.has_erp&&store.role!=='STAFF'&&<Info label="參考單價" value={current.reference_price===null?'未提供':`${current.reference_price}／${current.unit}`}/>}</section>{current.status==='OPEN'&&field&&<div className="shell-button-stack"><button className="shell-primary" onClick={()=>{change('return');}}>{current.to_store_id===store.id?'登記歸還':'登記收到歸還'}</button><button className="shell-secondary" onClick={()=>{change('exchange');}}>改以其他品項換貨</button></div>}<section className="shell-section"><h2>紀錄</h2><div className="shell-card timeline-list">{current.events.map(e=><article key={e.id}><i/><div><strong>{e.action==='RETURN'?'歸還':e.action==='EXCHANGE'?'換貨結清':'建立'}・{e.name} {e.quantity} {e.unit}</strong><small>{e.actor_name}・{displayTime(e.created_at)}</small></div></article>)}</div></section></>}
 {(page==='return'||page==='exchange')&&current&&field&&<form onSubmit={e=>{e.preventDefault();void settle();}}><section className="shell-card transfer-form"><label><span>{page==='exchange'?'換回品項':'歸還品項'}</span><input value={page==='return'?current.name:settlement.name} readOnly={page==='return'} onChange={e=>setSettlement({...settlement,name:e.target.value})} required/></label><label><span>本次數量</span><div className="transfer-quantity"><input type="number" min="0.000001" step="any" max={page==='return'?Number(current.quantity)-Number(current.returned_quantity):999999999} value={settlement.quantity} onChange={e=>setSettlement({...settlement,quantity:e.target.value})} required/><select aria-label="單位" disabled={page==='return'} value={page==='return'?current.unit:settlement.unit} onChange={e=>setSettlement({...settlement,unit:e.target.value})} required><option value="">單位</option>{[...new Set([...units,current.unit])].map(u=><option key={u}>{u}</option>)}</select></div></label></section><button className="shell-primary full" disabled={operation.busy}>{operation.busy?'儲存中…':page==='exchange'?'完成換貨結清':'完成歸還紀錄'}</button><p className="shell-note">{page==='exchange'?'實際收到後記錄，完成後原借貸結清。':'請依實際歸還數量記錄；未還完的部分會保留待辦。'}</p></form>}
 {page==='complete'&&complete&&<><section className="completion-state"><span><CheckCircle2/></span><h1>{title.complete}</h1><p>{completedEntry?.name} {completedEntry?.quantity} {completedEntry?.unit}</p></section><section className="shell-card completion-card"><strong>{statusName[complete.status]}</strong>{complete.status==='OPEN'&&<p>尚待歸還 {Number(complete.quantity)-Number(complete.returned_quantity)} {complete.unit}</p>}</section><button className="shell-primary full" onClick={()=>change('home')}>返回借貸</button></>}
 </>}</>;
}
function localMonthOf(value:string){const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>;}
function Entry({label,copy,onClick}:{label:string;copy:string;onClick:()=>void}){return <button className="shell-card transfer-status-card" onClick={onClick}><span>{label==='新增紀錄'?<ArrowLeftRight/>:<ClipboardList/>}</span><div><strong>{label}</strong><small>{copy}</small></div><b>›</b></button>;}
