'use client';
import {stockStateLabels} from '@/lib/stock-rules.mjs';
import UnitSelect from './unit-select';
import {useState} from 'react';
import {useUiState} from './workspace-memory';
import {remainingLoan,movementDirection,localRecordMonth} from '@/lib/workflow-rules';
import {Search,ArrowLeftRight,ClipboardList,CheckCircle2} from 'lucide-react';
import {appError,groupedQuantities,localMonth,monthRange,readWorkspace,type AppStore} from '@/lib/app-workspace';
import {useOperation,useOperationDraft,useWorkspace} from './operation-hooks';
import {displayTime} from './inventory-catalog';
import {isBaihuayuanMovement,isBaihuayuanStoreName} from '@/lib/baihuayuan';

export type Movement = {id:string;from_store_id:string;to_store_id:string;from_name:string;to_name:string;kind:'LOAN'|'TRANSFER';product_id?:string|null;name:string;quantity:number;unit:string;returned_quantity:number;expected_return_on:string|null;status:string;revision:number;actor_name:string;created_at:string;closed_at:string|null;reference_price:number|null;supplier_id?:string|null;supplier_name?:string|null;transfer_amount?:number|null;note?:string;review_status?:'PENDING'|'CONFIRMED';reviewer_name?:string|null;reviewed_at?:string|null;available_snapshot?:number|null;stock_warning?:boolean;events:{id:string;action:string;name:string;quantity:number;unit:string;actor_name:string;created_at:string}[]};
type ProductSupplier={id:string;name:string;unit_price:number|null;receipt_date:string|null};
type Workspace = {units?:string[];records:Movement[];stores:{id:string;name:string}[];products:{id:string;name:string;unit:string;average_cost?:number|null;current_supplier_id?:string|null;current_supplier_name?:string|null;suppliers?:ProductSupplier[]}[];has_erp:boolean};
type Page='home'|'search'|'new'|'transfer'|'open'|'history'|'monthly'|'detail'|'return'|'exchange'|'complete';
const statusName:Record<string,string>={OPEN:'待歸還',RETURNED:'已歸還',EXCHANGED:'換貨結清',COMPLETE:'調撥完成'};
export default function TransfersWorkspace({store,userId,onBack,archive=false,returnLabel="返回首頁",initialId,initialMonth,initialPage}:{initialPage?:'home';initialId?:string;initialMonth?:string;store:AppStore;userId:string;archive?:boolean;onBack:()=>void;returnLabel?:string}){
 const[landing,setLanding]=useUiState<Page>('transfers-landing','home');const[page,setLocalPage]=useState<Page>(initialId?'detail':initialPage||landing);const setPage=(next:Page)=>{setLocalPage(next);if(['home','open','history','monthly','search'].includes(next))setLanding(next);};const[detailOrigin,setDetailOrigin]=useState<Page>('open');const[completedEntry,setCompletedEntry]=useState<{name:string;quantity:string;unit:string}>();const[month,setMonth]=useUiState(`transfers-month:${initialId||'home'}`,initialMonth||localMonth());const workspace=useWorkspace<Workspace>(store.id,archive?'archived-transfers':'transfers',monthRange(month));
 const operation=useOperation(store.id,userId);const[selected,setSelected]=useUiState<string|undefined>('transfers-selected',initialId);const[complete,setComplete]=useState<Movement>();const[completionAction,setCompletionAction]=useState('create');
 const[search,setSearch]=useUiState('transfers-search','');const[searching,setSearching]=useState(false);const[results,setResults]=useState<{id:string;name:string;updated_at:string|null;products?:{id:string;name:string;unit:string;stock:{total:number|null;available:number|null};states:{state:string;quantity:number;unit:string;ready_at:string|null}[]}[]}[]>();const[searchError,setSearchError]=useState('');
 const[draft,setDraft,clearDraft]=useOperationDraft(userId,store.id,'movement',{mode:'loan',other_store_id:'',product_id:'',name:'',quantity:'',unit:'',expected_return_on:''});
 const[transferDraft,setTransferDraft,clearTransferDraft]=useOperationDraft(userId,store.id,'transfer-guided',{to_store_id:'',product_id:'',name:'',supplier_id:'',quantity:'',note:''});
 const[settlement,setSettlement,clearSettlement]=useOperationDraft(userId,store.id,`settlement:${selected||'none'}:${page==='exchange'?'exchange':'return'}`,{quantity:'',name:'',unit:''});
 const[reviewDraft,setReviewDraft]=useState({quantity:'',unit_price:'',supplier_id:''});
 const data=workspace.data;const peerStores=(data?.stores||[]).filter(s=>isBaihuayuanStoreName(s.name));const records=(data?.records||[]).filter(r=>isBaihuayuanMovement(r.from_name,r.to_name));const current=records.find(r=>r.id===(initialId||selected));const field=['STAFF','SUPERVISOR','LOGISTICS','OWNER'].includes(store.role);const canReview=store.role==='LOGISTICS'||store.role==='OWNER'||store.can_manage_business===true;
 const pending=records.filter(r=>r.status==='OPEN');const pendingTransferReviews=records.filter(r=>r.kind==='TRANSFER'&&r.review_status==='PENDING');const history=records.filter(r=>localRecordMonth(r.created_at)===month);const moves=history.filter(r=>r.kind==='TRANSFER');const loans=history.filter(r=>r.kind==='LOAN');
 const change=(next:Page)=>{operation.setError('');setPage(next);};
 const open=(row:Movement)=>{setDetailOrigin(page);setSelected(row.id);setReviewDraft({quantity:String(row.quantity),unit_price:row.reference_price===null||row.reference_price===undefined?'':String(row.reference_price),supplier_id:row.supplier_id||''});change('detail');};
 const title:Record<Page,string>={home:'借貸與調撥',search:'搜尋庫存',new:'新增借貸',transfer:'調撥',open:'待處理',history:'借貸紀錄',monthly:'本月調撥',detail:current?.kind==='TRANSFER'?'調撥':current?.to_store_id===store.id?'借入':'借出',return:current?.to_store_id===store.id?'記錄已歸還':'記錄收到歸還',exchange:'記錄換回品項',complete:completionAction==='return'?'歸還已記錄':complete?.status==='EXCHANGED'?'換貨已結清':complete?.kind==='TRANSFER'?'調撥已記錄':'借貸已記錄'};
 const back=()=>{if((page==='detail'||page==='complete')&&initialId){onBack();return;}if(page==='home')onBack();else if(page==='return'||page==='exchange')change('detail');else if(page==='detail')change(detailOrigin);else change('home');};
 const save=async()=>{const result=await operation.run<Movement>('movement.create',{...draft,quantity:Number(draft.quantity)});if(result){setCompletionAction('create');setCompletedEntry({name:draft.name,quantity:draft.quantity,unit:draft.unit});clearDraft();setComplete(result);change('complete');await workspace.refresh();}};
 const saveTransfer=async()=>{const product=data?.products.find(p=>p.id===transferDraft.product_id);if(!product)return;const result=await operation.run<Movement>('movement.transfer-create',{to_store_id:transferDraft.to_store_id,product_id:transferDraft.product_id,quantity:Number(transferDraft.quantity),note:transferDraft.note});if(result){setCompletionAction('create');setCompletedEntry({name:product.name,quantity:transferDraft.quantity,unit:product.unit});clearTransferDraft();setComplete(result);change('complete');await workspace.refresh();}};
 const settle=async()=>{if(!current)return;const result=await operation.run<Movement>(page==='exchange'?'movement.exchange':'movement.return',{id:current.id,revision:current.revision,quantity:Number(settlement.quantity),...(page==='exchange'?{name:settlement.name,unit:settlement.unit}:{})});if(result){setCompletionAction(page);setCompletedEntry({name:page==='exchange'?settlement.name:current.name,quantity:settlement.quantity,unit:page==='exchange'?settlement.unit:current.unit});clearSettlement();setComplete(result);change('complete');await workspace.refresh();}};
 const confirmTransfer=async()=>{if(!current||current.kind!=='TRANSFER')return;const price=Number(reviewDraft.unit_price);const quantity=Number(reviewDraft.quantity);if(!Number.isFinite(price)||price<0||!Number.isFinite(quantity)||quantity<=0){operation.setError('請確認調撥數量與單價。');return;}const result=await operation.run<Movement>('movement.transfer-confirm',{id:current.id,revision:current.revision,quantity,unit_price:price,supplier_id:reviewDraft.supplier_id||null});if(result){setComplete(result);setCompletionAction('confirm');setCompletedEntry({name:result.name,quantity:String(result.quantity),unit:result.unit});change('complete');await workspace.refresh();}};
 const units=[...new Set([...(data?.units||[]),...(data?.products.map(p=>p.unit)||[]),'包','公斤','盒','瓶','罐','個','片','塊','袋','箱'])];
 const rowCard=(row:Movement)=><button key={row.id} type="button" className="shell-list-row" onClick={()=>open(row)}><span><strong>{row.name} {row.quantity} {row.unit}</strong><small>{movementDirection(row.kind,row.from_store_id,store.id)}・{row.from_store_id===store.id?row.to_name:row.from_name}・{row.kind==='TRANSFER'&&row.review_status==='PENDING'?'待行政確認':statusName[row.status]}</small>{row.stock_warning&&<small>⚠ 系統庫存與現場調撥數量不一致，待行政核對</small>}{row.status==='OPEN'&&<small>待還 {Number(row.quantity)-Number(row.returned_quantity)} {row.unit}{row.expected_return_on?`・預計 ${row.expected_return_on}`:''}</small>}</span><b>›</b></button>;
 return <><button type="button" className="shell-back" onClick={back}>‹ <span>{page==='home'||(page==='detail'||page==='complete')&&initialId?returnLabel:page==='return'||page==='exchange'?'返回借貸明細':'返回借貸'}</span></button>
 <div className="workspace-heading">{page!=='complete'&&<h1>{page==='detail'&&current?.kind==='TRANSFER'?'調撥明細':title[page]}</h1>}</div>
 {(workspace.error||operation.error)&&<p className="pilot-message" role="alert">{operation.error||workspace.error}</p>}
 {workspace.error&&<button className="shell-secondary" onClick={()=>void workspace.refresh()}>重新讀取</button>}
 {workspace.loading&&!data?<p role="status">正在讀取借貸紀錄…</p>:<>
 {page==='home'&&<>{field&&!archive&&<button type="button" className="transfer-search-entry" onClick={()=>change('search')}><span><Search/></span><div><strong>搜尋庫存</strong><small>庫存只供參考，不阻擋現場登記</small></div><b>›</b></button>}{canReview&&pendingTransferReviews.length>0&&<section className="shell-section"><div className="shell-section-head"><h2>待行政確認</h2><span>{pendingTransferReviews.length} 筆</span></div><div className="shell-card shell-list">{pendingTransferReviews.map(rowCard)}</div></section>}<div className="transfer-entry-grid">{field&&!archive&&<><Entry label="調撥" copy="現場先記錄，行政後續確認金額" onClick={()=>change('transfer')}/><Entry label="新增借貸" copy="借入或借出" onClick={()=>change('new')}/></>}<Entry label="待處理" copy={`尚未歸還 ${pending.length} 筆`} onClick={()=>change('open')}/><Entry label="借貸紀錄" copy={`本月 ${loans.length} 筆`} onClick={()=>change('history')}/></div></>}
 {page==='search'&&<><form className="transfer-search-form" onSubmit={async e=>{e.preventDefault();setSearching(true);setSearchError('');try{const next=await readWorkspace<{stores:NonNullable<typeof results>}>(store.id,'transfer-search',{search});setResults(next.stores.filter(s=>isBaihuayuanStoreName(s.name)&&s.products?.length));}catch(error){setSearchError(appError(error));}finally{setSearching(false);}}}><label><Search/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} aria-label="搜尋品項" placeholder="輸入品項名稱" required/><button type="submit" disabled={searching}>{searching?'搜尋中…':'搜尋'}</button></label></form>{searchError&&<p className="pilot-message" role="alert">{searchError}</p>}<div className="transfer-recommendations">{results?.map((s,i)=><article className="shell-card transfer-recommendation" key={s.id}><header><span>{i+1}</span><div><strong>{s.name}</strong><small>{s.updated_at?`${displayTime(s.updated_at)} 更新`:'尚無已完成盤點時間'}</small></div></header>{s.products?.map((p,index)=><div className="transfer-stock" key={`${p.name}:${p.unit}:${index}`}><strong>{p.name}</strong><p>總庫存 {p.stock.total??'未提供'} {p.unit}・目前可用 {p.stock.available??'未提供'} {p.unit}</p>{p.states.filter(x=>x.state!=='READY').map((x,i)=><small key={i}>{(stockStateLabels as Record<string,string>)[x.state]||'狀態待確認'} {x.quantity} {x.unit}{x.ready_at?`・預計 ${displayTime(x.ready_at)}`:''}</small>)}{field&&!archive&&<button type="button" className="shell-secondary" onClick={()=>{setDraft({...draft,mode:"loan",other_store_id:s.id,product_id:p.id,name:p.name,quantity:"",unit:p.unit,expected_return_on:""});change("new");}}>登記借入</button>}</div>)}</article>)}</div>{results?.length===0&&<p>目前沒有符合的門市品項紀錄。</p>}<p className="shell-note">庫存可能因現場使用而變動，實際品項與數量請聯絡門市確認。</p></>}
 {page==='new'&&field&&<form onSubmit={e=>{e.preventDefault();void save();}}><section className="shell-card transfer-form"><label><span>異動方式</span><select aria-label="異動方式" value={draft.mode} onChange={e=>setDraft({...draft,mode:e.target.value})}><option value="loan">借入</option><option value="loan_out">借出</option></select></label><label><span>門市</span><select aria-label="門市" value={draft.other_store_id} onChange={e=>setDraft({...draft,other_store_id:e.target.value})} required><option value="">選擇門市</option>{peerStores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label><span>品項</span><input list="movement-products" value={draft.name} maxLength={160} onChange={e=>{const p=data?.products.find(p=>p.name===e.target.value);setDraft({...draft,name:e.target.value,product_id:p?.id||'',unit:p?.unit||draft.unit});}} required/></label><datalist id="movement-products">{data?.products.map(p=><option key={p.id} value={p.name}/>)}</datalist><label><span>數量</span><div className="transfer-quantity"><input aria-label="數量" type="number" min="0.000001" max="999999999" step="any" value={draft.quantity} onChange={e=>setDraft({...draft,quantity:e.target.value})} required/><UnitSelect value={draft.unit} onChange={unit=>setDraft({...draft,unit})} units={units}/></div></label><label><span>預計歸還日（選填）</span><input type="date" value={draft.expected_return_on} onChange={e=>setDraft({...draft,expected_return_on:e.target.value})}/></label></section><p className="shell-note">依實際已收貨或已交付數量記錄；不同單位未設定換算時分開保存。</p><button type="submit" className="shell-primary full" disabled={operation.busy}>{operation.busy?'儲存中…':`完成${draft.mode==='loan'?'借入':'借出'}紀錄`}</button></form>}
 {page==='transfer'&&field&&!archive&&(()=>{
  const product=data?.products.find(p=>p.id===transferDraft.product_id);
  return <form onSubmit={e=>{e.preventDefault();void saveTransfer();}}>
   <section className="shell-card transfer-form">
    <div className="shell-section-head"><h2>現場調撥登記</h2></div>
    <label><span>轉入門市</span><select value={transferDraft.to_store_id} onChange={e=>setTransferDraft({...transferDraft,to_store_id:e.target.value})} required><option value="">選擇門市</option>{peerStores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>
    <label><span>品項</span><input list="transfer-products" value={transferDraft.name} placeholder="輸入品項名稱" onChange={e=>{const p=data?.products.find(p=>p.name===e.target.value);setTransferDraft({...transferDraft,name:e.target.value,product_id:p?.id||''});}} required/></label>
    <datalist id="transfer-products">{data?.products.map(p=><option key={p.id} value={p.name}/>)}</datalist>
    {product&&<label><span>數量</span><div className="transfer-quantity"><input type="number" min="0.000001" step="any" value={transferDraft.quantity} onChange={e=>setTransferDraft({...transferDraft,quantity:e.target.value})} required/><b>{product.unit}</b></div></label>}
    <label><span>備註（選填）</span><input value={transferDraft.note} maxLength={200} placeholder="例如：支援活動、臨時調貨" onChange={e=>setTransferDraft({...transferDraft,note:e.target.value})}/></label>
   </section>
   <p className="shell-note">現場只記錄實際發生的調撥，不因系統庫存不足阻擋。行政／後勤之後再核對數量、單價與金額。</p>
   <button type="submit" className="shell-primary full" disabled={operation.busy||!product||!transferDraft.to_store_id||!transferDraft.quantity}>{operation.busy?'儲存中…':'完成現場登記'}</button>
  </form>;
 })()}
 {page==='open'&&<>{['借入','借出'].map((label,index)=><section className="shell-section" key={label}><h2>{label}</h2><div className="shell-card shell-list">{pending.filter(r=>index===0?r.to_store_id===store.id:r.from_store_id===store.id).map(rowCard)}</div></section>)}{!pending.length&&<p>目前沒有尚未歸還的紀錄。</p>}</>}
 {(page==='history'||page==='monthly')&&<><label className="field">月份<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><div className="compact-tabs" role="tablist" aria-label="紀錄分類"><button type="button" role="tab" aria-selected={page==='history'} onClick={()=>change('history')}>借貸</button><button type="button" role="tab" aria-selected={page==='monthly'} onClick={()=>change('monthly')}>調撥</button></div><div className="shell-card shell-list">{(page==='monthly'?moves:loans).map(rowCard)}</div>{page==='monthly'&&<><section className="shell-section"><h2>品項彙整</h2><div className="shell-card result-list">{groupedQuantities(moves).map(r=><div key={JSON.stringify([r.name,r.unit])}><span>{r.name}</span><strong>{r.quantity} {r.unit}</strong></div>)}</div></section><section className="shell-card completion-card"><strong>本月調撥金額</strong><p>{moves.some(r=>r.transfer_amount!==null&&r.transfer_amount!==undefined)?'NT$ '+moves.reduce((sum,r)=>sum+Number(r.transfer_amount||0),0).toLocaleString():'尚無可計算金額'}</p></section></>}{!(page==='monthly'?moves:loans).length&&<p>本月沒有紀錄。</p>}</>}
 {page==='detail'&&current&&<><section className="shell-card result-list transfer-loan-summary"><Info label={current.kind==='TRANSFER'?(current.to_store_id===store.id?'調出門市':'調入門市'):(current.to_store_id===store.id?'借出門市':'借入門市')} value={current.to_store_id===store.id?current.from_name:current.to_name}/><Info label="品項" value={current.name}/><Info label={current.kind==='TRANSFER'?'調撥數量':'借貸數量'} value={`${current.quantity} ${current.unit}`}/>{current.kind==='LOAN'&&<><Info label="剩餘數量" value={`${remainingLoan(current.quantity,current.returned_quantity)} ${current.unit}`}/><Info label="預計歸還" value={current.expected_return_on||'未設定'}/></>}{current.kind==='TRANSFER'&&<><Info label="確認狀態" value={current.review_status==='PENDING'?'待行政確認':'已確認'}/>{current.stock_warning&&<Info label="庫存提示" value={`系統可用 ${current.available_snapshot??0} ${current.unit}，現場登記 ${current.quantity} ${current.unit}`}/>}<Info label="單價" value={current.review_status==='PENDING'?'待行政確認':current.reference_price===null?'未提供':'NT$ '+Number(current.reference_price).toLocaleString()+'／'+current.unit}/><Info label="調撥金額" value={current.review_status==='PENDING'?'待行政確認':current.transfer_amount===null||current.transfer_amount===undefined?'未提供':'NT$ '+Number(current.transfer_amount).toLocaleString()}/>{current.reviewer_name&&<Info label="行政確認" value={`${current.reviewer_name}・${displayTime(current.reviewed_at||null)}`}/>}</>}<Info label="經手人" value={`${current.actor_name||'已保存人員'}・${displayTime(current.created_at)}`}/><Info label="狀態" value={current.kind==='TRANSFER'&&current.review_status==='PENDING'?'現場已登記':statusName[current.status]}/></section>
 {current.kind==='TRANSFER'&&current.review_status==='PENDING'&&canReview&&(()=>{const product=data?.products.find(p=>p.id===current.product_id);const suppliers=product?.suppliers||[];return <form onSubmit={e=>{e.preventDefault();void confirmTransfer();}}><section className="shell-card transfer-form"><h2>行政確認調撥</h2><p className="shell-note">核對實際數量與成本；庫存差異只提醒，不阻擋確認。</p><label><span>確認數量</span><div className="transfer-quantity"><input type="number" min="0.000001" step="any" value={reviewDraft.quantity} onChange={e=>setReviewDraft({...reviewDraft,quantity:e.target.value})} required/><b>{current.unit}</b></div></label><label><span>供應商（選填）</span><select value={reviewDraft.supplier_id} onChange={e=>{const supplier=suppliers.find(s=>s.id===e.target.value);setReviewDraft({...reviewDraft,supplier_id:e.target.value,unit_price:supplier?.unit_price===null||supplier?.unit_price===undefined?reviewDraft.unit_price:String(supplier.unit_price)});}}><option value="">不指定</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label><span>確認單價</span><input type="number" min="0" step="any" value={reviewDraft.unit_price} placeholder={current.reference_price===null?'輸入未稅單價':String(current.reference_price)} onChange={e=>setReviewDraft({...reviewDraft,unit_price:e.target.value})} required/></label><div className="shell-card" style={{padding:12,background:'#f6f8f7'}}><span>調撥金額</span><strong style={{display:'block',fontSize:22}}>{reviewDraft.unit_price&&reviewDraft.quantity?'NT$ '+(Number(reviewDraft.unit_price)*Number(reviewDraft.quantity)).toLocaleString():'待輸入單價'}</strong></div><button className="shell-primary full" disabled={operation.busy}>{operation.busy?'確認中…':'確認調撥'}</button></section></form>;})()}
 {current.status==='OPEN'&&field&&<div className="shell-button-stack"><button className="shell-primary" onClick={()=>{change('return');}}>{current.to_store_id===store.id?'登記歸還':'登記收到歸還'}</button><button className="shell-secondary" onClick={()=>{change('exchange');}}>改以其他品項換貨</button></div>}<section className="shell-section"><h2>紀錄</h2><div className="shell-card timeline-list">{current.events.map(e=><article key={e.id}><i/><div><strong>{e.action==='RETURN'?'歸還':e.action==='EXCHANGE'?'換貨結清':e.action==='CONFIRM'?'行政確認':'建立'}・{e.name} {e.quantity} {e.unit}</strong><small>{e.actor_name}・{displayTime(e.created_at)}</small></div></article>)}</div></section></>}
 {(page==='return'||page==='exchange')&&current&&field&&<form onSubmit={e=>{e.preventDefault();void settle();}}><section className="shell-card transfer-form"><label><span>{page==='exchange'?'換回品項':'歸還品項'}</span><input value={page==='return'?current.name:settlement.name} readOnly={page==='return'} onChange={e=>setSettlement({...settlement,name:e.target.value})} required/></label><label><span>本次數量</span><div className="transfer-quantity"><input type="number" min="0.000001" step="any" max={page==='return'?remainingLoan(current.quantity,current.returned_quantity):999999999} value={settlement.quantity} onChange={e=>setSettlement({...settlement,quantity:e.target.value})} required/><UnitSelect disabled={page==='return'} value={page==='return'?current.unit:settlement.unit} onChange={unit=>setSettlement({...settlement,unit})} units={[...units,current.unit]}/></div></label></section><button className="shell-primary full" disabled={operation.busy}>{operation.busy?'儲存中…':page==='exchange'?'完成換貨結清':'完成歸還紀錄'}</button><p className="shell-note">{page==='exchange'?'實際收到後記錄，完成後原借貸結清。':'請依實際歸還數量記錄；未還完的部分會保留待辦。'}</p></form>}
 {page==='complete'&&complete&&<><section className="completion-state"><span><CheckCircle2/></span><h1>{completionAction==='confirm'?'調撥已確認':complete.kind==='TRANSFER'&&complete.review_status==='PENDING'?'現場調撥已登記':title.complete}</h1><p>{completedEntry?.name} {completedEntry?.quantity} {completedEntry?.unit}</p></section><section className="shell-card completion-card"><strong>{complete.kind==='TRANSFER'&&complete.review_status==='PENDING'?'待行政確認':statusName[complete.status]}</strong>{complete.status==='OPEN'&&<p>尚待歸還 {remainingLoan(complete.quantity,complete.returned_quantity)} {complete.unit}</p>}{complete.kind==='TRANSFER'&&<p>{complete.from_name} → {complete.to_name}<br/>{complete.review_status==='PENDING'?'現場紀錄已保存，行政將後續核對數量與金額。':complete.transfer_amount!==null&&complete.transfer_amount!==undefined?'NT$ '+Number(complete.transfer_amount).toLocaleString():'已完成確認'}</p>}</section><button className="shell-primary full" onClick={()=>initialId?onBack():change('home')}>{initialId?returnLabel:"返回調撥／借貸"}</button></>}
 </>}</>;
}
function Info({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>;}
function Entry({label,copy,onClick}:{label:string;copy:string;onClick:()=>void}){return <button className="shell-card transfer-status-card" onClick={onClick}><span>{label==='新增紀錄'?<ArrowLeftRight/>:<ClipboardList/>}</span><div><strong>{label}</strong><small>{copy}</small></div><b>›</b></button>;}
