'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import OperationsSheet from './operations-sheet';
import {supabase} from '@/lib/supabase-browser';
import {readScopedReceiptAccounts,saveReceiptReview} from '@/lib/receipt-accounting-api';
import {reviewDraft,reviewPayload,type ReviewAccount} from '@/lib/receipt-review';
import {canExportData,monthRange,readWorkspace,writeOperation,type AppStore} from '@/lib/app-workspace';
import {inventoryPurchases,monthlyDisplayRows,inventoryFieldNotes,type InventoryMonth,type InventoryRow} from '@/lib/inventory-monthly';
import {inventoryAccountLines,inventoryMonthEnd} from '@/lib/inventory-cost';
import {type CatalogItem} from './inventory-catalog';
import {type Movement} from './transfers-workspace';
import {wasteReasons,type ExpiryWorkspaceData,type WasteRecord} from '@/lib/expiry-waste';
import {PRODUCT_CATEGORIES} from '@/lib/product-categories';
import {sheetNumber,sheetMerge,type SheetKind,type SheetColumn,type SheetRow} from '@/lib/operations-sheet';
type Props={kind:SheetKind;store:AppStore;registerLeave?:(guard:(()=>Promise<boolean>)|null)=>void;onSpecial:(name:string,id?:string)=>void};
type TransferData={records:(Movement&{occurred_at?:string})[];products:{id:string;name:string;unit:string}[]};
type InventoryMeta={row?:InventoryRow;catalog?:CatalogItem};
const text=(v:unknown)=>v==null?'':String(v);
const day=(v:string)=>v?new Date(v).toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'}):'';
const monthNow=()=>day(new Date().toISOString()).slice(0,7);
async function rpc(name:string,args:Record<string,unknown>){const r=await (supabase.rpc as unknown as (n:string,a:Record<string,unknown>)=>Promise<{data:unknown;error:{message:string}|null}>)(name,args);if(r.error)throw Error(r.error.message);return r.data;}
function friendly(error:unknown){const m=error instanceof Error?error.message:String(error);if(/REVISION_CONFLICT|CHANGED/.test(m))return '資料已更新或這次要求已保存；輸入保留，請核對後重新讀取，避免覆蓋他人修改。';if(/PRODUCT_MATCH_REQUIRED/.test(m))return '品名與單位尚未對應唯一食材，請使用表格下拉建議的品名與單位。';if(/PRODUCT_REMOVED_OR_DISABLED/.test(m))return '品項已移除或停用，請先在已移除清單還原，或由品項管理重新啟用。';if(/COUNT_IN_PROGRESS/.test(m))return '此品項已有進行中的盤點數量，需完成盤點後再移除；原數量與歷史會保留。';if(/QUANTITY_LOCKED|UNIT_LOCKED|DIRECTION_LOCKED/.test(m))return '這筆已影響庫存或效期紀錄，數量、單位或方向須保留；仍可修改價格與備註。';return m;}
export default function UnifiedOperationsWorkspace({kind,store,registerLeave,onSpecial}:Props){
 const [month,setMonth]=useState(monthNow),[rows,setRows]=useState<SheetRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[products,setProducts]=useState<string[]>([]),[inventory,setInventory]=useState<InventoryMonth>(),[canAmount,setCanAmount]=useState(true);
 const accounts=useRef(new Map<string,ReviewAccount>()),generation=useRef(0);
 const load=useCallback(async()=>{const seq=++generation.current;setLoading(true);setError('');try{let next:SheetRow[]=[];let names:string[]=[];const range=monthRange(month);
  if(kind==='receipt'){const list=await readScopedReceiptAccounts(store.id,new AbortController().signal,month+'-01',inventoryMonthEnd(month),'ALL');if(seq!==generation.current)return;accounts.current=new Map(list.map(a=>[a.batch_id,a]));next=list.flatMap(a=>a.lines.map(l=>({id:`${a.batch_id}:${l.row_key}`,state:a.record_state,locked:!a.can_edit,values:{date:reviewDraft(a).date,supplier:a.supplier_name,name:l.product_name,category:l.category,unit:l.unit,quantity:text(l.quantity),price:text(l.unit_price),amount:text(l.subtotal),note:l.note,handling:l.handling||'NORMAL'},meta:{batch:a.batch_id,key:l.row_key}})));}
  else if(kind==='inventory'){const data=await rpc('baihuayuan_inventory_month',{p_store_id:store.id,p_month:month+'-01',p_action:'read',p_data:{}}) as InventoryMonth;const catalog=await rpc('get_pilot_inventory_catalog',{p_store_id:store.id}) as CatalogItem[];const receipt=await readScopedReceiptAccounts(store.id,new AbortController().signal,'',inventoryMonthEnd(month),'ALL');data.rows=inventoryPurchases(data.rows,inventoryAccountLines(receipt),[],data.month);if(seq!==generation.current)return;setInventory(data);const current=monthlyDisplayRows(data.rows);next=current.map(r=>({id:r.row_key,state:!data.historical&&!data.closed&&catalog.find(c=>c.product_id===r.product_id)?.is_removed?'REMOVED':'LIVE',locked:data.closed||data.historical,values:{name:r.name,supplier:r.supplier,category:r.category,unit:r.unit,opening:text(r.previous_quantity),purchases:text(r.purchase_quantity),quantity:text(r.current_quantity),price:text(r.unit_price),amount:text(r.amount),note:r.review_note,field_note:inventoryFieldNotes(r),zone:r.zones.map(z=>z.zone).join('、')},meta:{row:r,catalog:catalog.find(c=>c.product_id===r.product_id)}}));const used=new Set(current.map(r=>r.product_id));if(!data.historical&&!data.closed)next.push(...catalog.filter((c,i)=>!used.has(c.product_id)&&catalog.findIndex(x=>x.product_id===c.product_id)===i).map(c=>({id:`catalog:${c.product_id}`,state:c.is_removed?'REMOVED':'LIVE',locked:c.product_is_active===false||data.closed||data.historical,values:{name:c.name,supplier:c.supplier||'',category:'',unit:c.unit,opening:'',purchases:'',quantity:'',price:text(c.unit_price),amount:'',note:'尚未列入此月份盤點',zone:c.zone},meta:{catalog:c}})));names=catalog.map(c=>c.name);}
  else {const flags=await rpc('get_baihuayuan_record_flags',{p_store_id:store.id,p_entity_type:kind==='transfer'?'TRANSFER':'WASTE'}) as {entity_id:string;state:string}[];const state=(id:string)=>flags.find(f=>f.entity_id===id)?.state||'LIVE';
   if(kind==='transfer'){const data=await readWorkspace<TransferData>(store.id,'transfers',range);names=data.products.map(p=>p.name);next=data.records.filter(r=>r.kind==='TRANSFER'&&day(r.occurred_at||r.created_at).slice(0,7)===month).map(r=>({id:r.id,state:state(r.id),values:{date:day(r.occurred_at||r.created_at),from:r.from_name,to:r.to_name,name:r.name,quantity:text(r.quantity),unit:r.unit,price:text(r.reference_price),amount:text(r.transfer_amount),actor:r.actor_name||'',note:r.note||'',status:r.review_status==='PENDING'?'待確認':'已確認'},meta:r}));}
   else{const data=await rpc('get_pilot_expiry_waste',{p_store_id:store.id,p_from:range.from,p_until:range.to}) as ExpiryWorkspaceData;if(seq!==generation.current)return;setCanAmount(data.can_view_amount===true&&data.permissions.audit);names=data.products.map(p=>p.name);next=data.waste.map(r=>({id:r.id,state:state(r.id),values:{date:r.work_date||day(r.created_at),name:r.name,quantity:text(r.review?.confirmed_quantity??r.quantity),unit:r.unit,price:text(r.reference_price),amount:text(r.reference_amount),reason:r.reason,actor:r.actor_name,note:r.note||'',status:r.review_status==='PENDING'?'待確認':'已確認'},meta:r}));}
  }if(seq===generation.current){setRows(next.map(r=>({...r,meta:{...(r.meta as Record<string,unknown>),originalValues:{...r.values}}})));setProducts([...new Set(names)]);}
 }catch(e){if(seq===generation.current)setError(friendly(e));}finally{if(seq===generation.current)setLoading(false);}},[kind,store.id,month]);
 useEffect(()=>{const counter=generation;const timer=setTimeout(()=>void load(),0);return()=>{clearTimeout(timer);counter.current++;};},[load]);
 const col=(key:string,label:string,extra:Partial<SheetColumn>={}):SheetColumn=>({key,label,...extra});
 const existing=(r:SheetRow)=>!r.fresh;
 const columns:SheetColumn[]=kind==='receipt'?[col('date','日期',{type:'date',required:true}),col('supplier','供應商',{required:true}),col('name','品名',{required:true}),col('category','分類',{options:[...PRODUCT_CATEGORIES]}),col('quantity','數量',{type:'number'}),col('unit','單位',{required:true}),col('price','未稅單價',{type:'number'}),col('amount','未稅金額',{readonly:true}),col('note','備註')]:kind==='inventory'?[col('name','品名',{required:true}),col('supplier','供應商',{readonly:true}),col('category','分類',{readonly:true}),col('unit','單位',{required:true,editable:r=>r.fresh||!(r.meta as InventoryMeta)?.row}),col('opening','期初',{readonly:true}),col('purchases','進貨',{readonly:true}),col('quantity','期末',{type:'number',editable:r=>(r.meta as InventoryMeta)?.row?.current_quantity!=null&&!!inventory?.source_id}),col('price','成本單價',{type:'number'}),col('amount','期末金額',{readonly:true}),col('zone','儲物區',{editable:r=>!!r.fresh}),col('field_note','現場備註',{readonly:true}),col('note','核對備註',{editable:r=>(r.meta as InventoryMeta)?.row?.current_quantity!=null&&!!inventory?.source_id})]:[col('date','日期',{type:'date',required:true}),...(kind==='transfer'?[col('from','調出門市',{options:['BeApe','Gras'],required:true,editable:r=>!existing(r)}),col('to','調入門市',{options:['BeApe','Gras'],required:true,editable:r=>!existing(r)})]:[]),col('name','品名',{options:products,required:true}),col('quantity','數量',{type:'number',required:true,editable:r=>kind!=='transfer'||r.fresh||(r.meta as Movement)?.review_status==='PENDING'}),col('unit','單位',{required:true,editable:r=>!!r.fresh}),...(canAmount?[col('price','單價',{type:'number'}),col('amount','金額',{readonly:true})]:[]),...(kind==='waste'?[col('reason','原因',{options:wasteReasons,required:true})]:[]),col('actor','經手人'),col('note','備註'),col('status','狀態',{readonly:true})];
 const defaults={date:month===monthNow()?day(new Date().toISOString()):month+'-01',name:'',unit:'',quantity:'',price:'',note:'',zone:'未分類',reason:wasteReasons[0],from:store.name,to:store.name==='BeApe'?'Gras':'BeApe',supplier:'',category:'食材'};
 async function save(row:SheetRow){try{const v=row.values,request=row.requestId||crypto.randomUUID();
  if(kind==='receipt'&&!row.fresh){const meta=row.meta as {batch:string;key:string};const a=accounts.current.get(meta.batch);if(!a)throw Error('原貨單讀取未完成。');const draft=reviewDraft(a);const original=(row.meta as {originalValues:Record<string,string>}).originalValues;const latest=a.lines.find(l=>l.row_key===meta.key);if(!latest)throw Error('REVISION_CONFLICT');const merged=sheetMerge(original,v,{supplier:a.supplier_name,date:reviewDraft(a).date,name:latest.product_name,category:latest.category,quantity:text(latest.quantity),unit:latest.unit,price:text(latest.unit_price),note:latest.note},['supplier','date','name','category','quantity','unit','price','note']);draft.supplier=merged.supplier;draft.date=merged.date;draft.lines=draft.lines.map(l=>l.row_key===meta.key?{...l,product_name:merged.name,category:merged.category,quantity:merged.quantity,unit:merged.unit,unit_price:merged.price,subtotal:merged.quantity!==text(latest.quantity)||merged.price!==text(latest.unit_price)?merged.quantity&&merged.price?text(Number(merged.quantity)*Number(merged.price)):'':l.subtotal,note:merged.note}:l);const saved=await saveReceiptReview(store.id,a.batch_id,{...reviewPayload(a,draft,false),reviewed:false},request);accounts.current.set(a.batch_id,saved);}
  else if(kind==='inventory'){const meta=row.meta as InventoryMeta|undefined;if(row.fresh){if(v.quantity?.trim())throw Error('新增品項先建立名稱、單位與單價；期末數量由該月份盤點帶入。');await rpc('save_baihuayuan_sheet_row',{p_store_id:store.id,p_kind:'inventory',p_id:null,p_value:v,p_expected:{},p_request_id:request});}
   else if(meta?.row&&meta.row.current_quantity!=null&&inventory?.source_id){const r=meta.row;await rpc('save_baihuayuan_inventory_inline_v2',{p_store_id:store.id,p_month:month+'-01',p_session_id:inventory?.source_id,p_row_key:r.row_key,p_source_signature:r.source_signature,p_expected_source_quantity:r.source_quantity??r.current_quantity,p_name:v.name,p_quantity:sheetNumber(v.quantity),p_unit_price:sheetNumber(v.price),p_note:v.note||'行政表格修正'});}
   else if(meta?.catalog){const c=meta.catalog;await writeOperation(store.id,'count.catalog-edit',{id:c.product_id,name:v.name,unit:v.unit,specification:c.specification,updated_at:c.updated_at,unit_price:sheetNumber(v.price)},request);}else throw Error('此筆尚無可修改的本月盤點來源，請先確認月份。');
  }else{const old=row.meta as Movement|WasteRecord|undefined;const expected=kind==='transfer'?{revision:(old as Movement)?.revision}:old?{name:old.name,quantity:old.quantity,unit:old.unit,price:(old as WasteRecord).reference_price,note:(old as WasteRecord).note||'',reason:(old as WasteRecord).reason,actor:(old as WasteRecord).actor_name,date:(old as WasteRecord).work_date}:{};await rpc('save_baihuayuan_sheet_row',{p_store_id:store.id,p_kind:kind,p_id:row.fresh?null:row.id,p_value:v,p_expected:expected,p_request_id:request});}
 }catch(e){throw Error(friendly(e));}}
 async function submit(selected:SheetRow[]){for(const id of new Set(selected.map(r=>(r.meta as {batch:string}).batch))){const account=accounts.current.get(id);if(!account?.can_edit)throw Error('貨單已更新，請重新讀取。');if(account.reviewed)continue;const saved=await saveReceiptReview(store.id,id,{...reviewPayload(account,reviewDraft(account),false),checked:account.status==='CHECKED',reviewed:true},crypto.randomUUID());accounts.current.set(id,saved);}}
 async function remove(selected:SheetRow[],restore:boolean){try{if(kind==='inventory'){const ids=[...new Set(selected.map(r=>{const meta=r.meta as InventoryMeta;return meta.row?.product_id||meta.catalog?.product_id;}))];await writeOperation(store.id,'count.catalog-lifecycle',{ids,mode:restore?'RESTORE':'REMOVE'},crypto.randomUUID());}else{const ids=[...new Set(selected.map(r=>kind==='receipt'?(r.meta as {batch:string}).batch:r.id))];for(const id of ids)await rpc('set_baihuayuan_record_state',{p_store_id:store.id,p_entity_type:kind==='receipt'?'RECEIPT_BATCH':kind==='transfer'?'TRANSFER':'WASTE',p_entity_id:id,p_state:restore?'LIVE':'REMOVED',p_reason:restore?null:'行政表格移除'});}}catch(e){throw Error(friendly(e));}}
 const title={receipt:'進貨管理',inventory:'庫存管理',transfer:'調撥管理',waste:'廢棄紀錄'}[kind];const priced=rows.filter(r=>r.state==='LIVE'&&r.values.amount!=='');const total=priced.reduce((n,r)=>n+Number(r.values.amount||0),0);
 return <OperationsSheet key={`${kind}:${store.id}:${month}`} title={title} scope={`${kind}-${store.id}`} rows={rows} columns={columns} defaults={defaults} loading={loading} error={error} month={month} onMonth={setMonth} onRefresh={load} onSave={save} onRemove={remove} onSubmit={kind==='receipt'?submit:undefined} registerLeave={registerLeave} readOnly={!!error||kind==='inventory'&&(inventory?.closed||inventory?.historical)} canExport={canExportData(store)} deleteNote={kind==='receipt'?'同張貨單的全部明細一併移除，原貨單與歷史保留。':kind==='inventory'?'僅移除本店品項，歷史盤點保留。':undefined} summary={<><span>明細<strong>{rows.filter(r=>r.state==='LIVE').length} 筆</strong></span>{canAmount&&<span>已計價金額<strong>{priced.length?'NT$ '+total.toLocaleString('zh-TW',{maximumFractionDigits:2}):'未計價'}</strong></span>}</>} special={<>{kind==='receipt'&&<><button className="sheet-button" onClick={()=>onSpecial('photos')}>貨單照片</button><button className="sheet-button" onClick={()=>onSpecial('finance')}>財務對帳</button></>}{kind==='inventory'&&<><button className="sheet-button" onClick={()=>onSpecial('spot')}>抽盤</button><button className="sheet-button" onClick={()=>onSpecial('inventory')}>寄庫／保留貨／確認月份</button></>}</>} onSource={kind==='receipt'?row=>onSpecial('source',(row.meta as {batch:string}).batch):undefined}/>;
}
