'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase-browser';
import {appError,hasCrossStore,localMonth,monthRange,readWorkspace,type AppStore} from '@/lib/app-workspace';
import {taipeiDate,monthRange as dateRange,type ExpiryWorkspaceData} from '@/lib/expiry-waste';
import {movementDirection,remainingLoan,visibleWork,countProgress,type WorkEntry} from '@/lib/workflow-rules';
import {useUiState} from './workspace-memory';
import {displayTime} from './inventory-catalog';
import type {OperationalRecord} from './records-workspace';
import type {Movement} from './transfers-workspace';
import {arrivalLabel,pendingDeliveryIssues,pendingReceiptErp} from '@/lib/receipt-delivery';
import type {Batch} from './receiving-workspace';
export const workCategories:Record<string,string>={all:'全部',count:'盤點',receipt:'收貨',expiry:'效期',waste:'廢棄',loan:'借貸',transfer:'調撥',incident:'異常',handover:'交接',bulletin:'公告',company_task:'公司流程',stock:'解凍確認'};
export function useWorkFeed(store:AppStore,month:string){
 const[snapshot,setSnapshot]=useState<{scope:string;rows:WorkEntry[];progress?:ReturnType<typeof countProgress>}>();const[error,setError]=useState('');const[reload,setReload]=useState(0);const scope=`${store.id}:${month}:${store.role}`;
 useEffect(()=>{let alive=true;let sequence=0;const run=async()=>{const request=++sequence;try{const range=dateRange(month);const [records,moves,receipts,expiry,counts,stock]=await Promise.all([
 readWorkspace<{records:OperationalRecord[]}>(store.id,'activity'),hasCrossStore(store)?readWorkspace<{records:Movement[]}>(store.id,'transfers',monthRange(month)):Promise.resolve({records:[]}),
 supabase.rpc('get_pilot_receipts',{p_store_id:store.id}),supabase.rpc('get_pilot_expiry_waste',{p_store_id:store.id,p_from:range[0],p_until:range[1]}),supabase.from('inventory_count_sessions').select('id,status,started_at,completed_at,paper_required,paper_completed_at,paper_reviewed_at,snapshot').eq('store_id',store.id).order('started_at',{ascending:false}),readWorkspace<{products:{id:string;name:string}[];positions:{id:string;product_id:string;name?:string;product_name?:string;state:string;quantity:number;unit:string;ready_at:string;updated_at:string;zone_name:string}[]}>(store.id,'stock')]);
 for(const r of [receipts,expiry,counts])if(r.error)throw r.error;
 const rows:WorkEntry[]=[];const add=(category:string,id:string,title:string,copy:string,at:string,pending:boolean,target:string,page?:string,detail?:string)=>rows.push({key:`${category}:${id}`,category,id,title,copy,at,pending,target,page,detail});
 for(const r of records.records)add(r.kind,r.id,r.title,`${r.status==='COMPLETE'?'已完成':r.responsible_name?`${r.responsible_name} 處理中`:'待接續'}・${r.actor_name}`,r.created_at,r.status!=='COMPLETE'&&(!r.expires_at||Date.parse(r.expires_at)>Date.now())&&(r.kind!=='bulletin'||!r.read_at),({incident:'incidents',handover:'handover',bulletin:'bulletins',company_task:'company-tasks'})[r.kind]);
 for(const r of moves.records)add(r.kind==='LOAN'?'loan':'transfer',r.id,`${movementDirection(r.kind,r.from_store_id,store.id)}・${r.name} ${r.quantity} ${r.unit}`,`${r.from_store_id===store.id?r.to_name:r.from_name}・${r.status==='OPEN'?`待還 ${remainingLoan(r.quantity,r.returned_quantity)} ${r.unit}`:r.kind==='TRANSFER'?'已完成':'已結清'}`,r.created_at,r.status==='OPEN','transfers');
 for(const b of (receipts.data||[]) as unknown as Batch[]){const confirmed=b.status==='COMPLETED'||!!b.review_saved;const erp=pendingReceiptErp(b);add('receipt',b.id,b.supplier||b.batch_number,`${arrivalLabel(b.delivery)}・${pendingDeliveryIssues(b.delivery)?`異常 ${pendingDeliveryIssues(b.delivery)}・`:''}${confirmed?'已確認收貨':b.ocr_status==='SUCCEEDED'?'待核對':b.job_status==='FAILED'?'辨識需重試':'處理中'}${erp?'・ERP 待完成':''}`,b.uploaded_at,!confirmed||erp||pendingDeliveryIssues(b.delivery)>0,'receiving','status');}
 const ew=expiry.data as unknown as ExpiryWorkspaceData;
 for(const i of ew.items)add('expiry',i.id,i.name,`${i.expires_on} 到期・${i.zone_name}`,i.created_at,true,'expiry',i.category==='urgent'?'urgent':i.category==='upcoming'?'upcoming':'special');
 for(const w of ew.waste)add('waste',w.id,`${w.name} ${w.quantity} ${w.unit}`,`${w.reason}・${w.actor_name}`,w.created_at,false,'waste','waste-detail');
 for(const u of ew.used)add('expiry',u.id,u.name,`已使用完・${u.zone_name}・${u.actor_name}`,u.created_at,false,'expiry','history',`${u.expires_on} 到期・已使用完`);
 for(const i of ew.issues)add('incident',i.id,`${i.snapshot.name}・${i.type==='LABEL'?'標示異常':'其他狀況'}`,`${i.snapshot.zone_name}・${i.actor_name}`,i.created_at,false,'expiry','history',i.note);
 if(ew.erp_pending.length)add('company_task','waste-erp','廢棄 ERP 待完成',`${ew.erp_pending.length} 筆`,ew.erp_pending[0].created_at,true,'waste','erp');
 for(const c of counts.data||[])add('count',c.id,'盤點',c.status==='CLOSED'?'已完成':c.status==='REVIEWING'?'已送出・待確認':'進行中',c.completed_at||c.started_at,['DRAFT','IN_PROGRESS','REVIEWING'].includes(c.status)||c.paper_required&&!c.paper_reviewed_at,'count',['DRAFT','IN_PROGRESS'].includes(c.status)?'overview':'details');
 for(const p of stock.positions||[])if(p.state==='THAWING'&&p.quantity>0&&p.ready_at&&Date.parse(p.ready_at)<=Date.now())add('stock',p.id,`${stock.products?.find(x=>x.id===p.product_id)?.name||p.product_name||p.name||'解凍品項'}・確認可用狀態`,`${p.zone_name}・${p.quantity} ${p.unit}`,p.ready_at,true,'stock');
 let progress:ReturnType<typeof countProgress>|undefined;const active=counts.data?.find(c=>['DRAFT','IN_PROGRESS'].includes(c.status));
 if(active){const [drafts,zones]=await Promise.all([supabase.from('count_drafts').select('zone_id,product_id,quantity').eq('session_id',active.id),supabase.from('count_zone_progress').select('zone_id,status').eq('session_id',active.id)]);if(drafts.error||zones.error)throw drafts.error||zones.error;progress=countProgress((active.snapshot as {zones?:{zone_id:string;product_id:string}[]})?.zones||[],drafts.data||[],zones.data||[]);}
 if(alive&&request===sequence){setSnapshot({scope,rows,progress});setError('');}
 }catch(e){if(alive&&request===sequence)setError(appError(e));}};void run();const timer=setInterval(()=>void run(),30000);const focus=()=>void run();window.addEventListener('focus',focus);return()=>{alive=false;sequence++;clearInterval(timer);window.removeEventListener('focus',focus);};},[scope,store,month,reload]);
 return {rows:snapshot?.scope===scope?snapshot.rows:undefined,progress:snapshot?.scope===scope?snapshot.progress:undefined,error,refresh:()=>setReload(r=>r+1)};
}
export default function WorkFeed({store,mode,onOpen,handover=false}:{store:AppStore;mode:'activity'|'tasks'|'notifications';onOpen:(row:WorkEntry,month:string)=>void;handover?:boolean}){
 const[month,setMonth]=useUiState('work-month',localMonth);const[category,setCategory]=useUiState(`work-category:${mode}`,'all');const[search,setSearch]=useUiState(`work-search:${mode}`,'');const data=useWorkFeed(store,mode==='activity'?month:taipeiDate().slice(0,7));const[selected,setSelected]=useState<WorkEntry>();const visible=visibleWork(data.rows||[],mode,month,category,search);
 return <>{!handover&&<h1>{mode==='activity'?'作業紀錄':mode==='tasks'?'待辦':'通知'}</h1>}<p className="shell-note">{store.name}（{store.store_code}）{mode!=='activity'?'・所有尚未完成事項':''}</p>{handover&&<section className="shell-card completion-card"><strong>目前盤點進度</strong><p>{data.progress?`已盤 ${data.progress.filled} / ${data.progress.total} 項・完成 ${data.progress.completedZones} / ${data.progress.zones} 區`:'目前沒有進行中的盤點'}</p>{data.progress&&<small>暫存數量仍需完成區域，才算完成盤點。</small>}</section>}{mode==='activity'&&<label className="field">月份<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label>}<label className="field">分類<select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(workCategories).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label className="field">搜尋<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="品項、門市或事項"/></label>{data.error&&<p role="alert">{data.error}<button className="text-button" onClick={data.refresh}>重新讀取</button></p>}{!data.rows&&!data.error?<p role="status">正在讀取…</p>:<><p role="status">{visible.length} 筆</p><div className="shell-card shell-list">{visible.map(r=><button type="button" className="shell-list-row" key={r.key} onClick={()=>r.detail?setSelected(r):onOpen(r,month)}><span><strong>{r.title}</strong><small>{workCategories[r.category]}・{r.copy}</small><small>{displayTime(r.at)}</small></span><b>›</b></button>)}</div>{!visible.length&&<p>目前沒有符合的{mode==='activity'?'紀錄':'待處理事項'}。</p>}</>}{selected&&<section className="shell-card completion-card"><strong>{selected.title}</strong><p>{selected.copy}</p><p>{selected.detail}</p><small>{displayTime(selected.at)}</small><button className="text-button" onClick={()=>setSelected(undefined)}>返回列表</button></section>}</>;
}
