begin;
do $$
declare actor uuid:=gen_random_uuid();viewer uuid:=gen_random_uuid();staff uuid:=gen_random_uuid();org uuid;store_id uuid;data jsonb;z uuid;p uuid;p2 uuid;cs uuid;oldcs uuid;month date:=date_trunc('month',now() at time zone 'Asia/Taipei')::date;stamp timestamptz;oldstamp timestamptz;payload jsonb;result jsonb;req uuid:=gen_random_uuid();denied boolean;before_snapshot jsonb;
begin
 insert into auth.users(id,email,email_confirmed_at) select id,id||'@receipt-detail.invalid',now() from unnest(array[actor,viewer,staff])id;
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 data:=public.owner_setup();
 data:=public.owner_setup('business',jsonb_build_object('organization_name','進貨隔離測試','business_type','SINGLE_RESTAURANT','store_mode','SINGLE'),0);
 data:=public.owner_setup('store',data->'draft'||jsonb_build_object('store_name','BeApe','store_code','QAREVIEW'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)),'staff_login_mode','NAME_OR_NICKNAME'),(data->>'revision')::integer);
 data:=public.owner_setup('identity',data->'draft'||'{"work_role":"OWNER"}',(data->>'revision')::integer);
 data:=public.owner_setup('complete',data->'draft',(data->>'revision')::integer);
 org:=(data->>'organization_id')::uuid;store_id:=(data->>'store_id')::uuid;

 insert into public.count_zones(organization_id,store_id,name) values(org,store_id,'食材') returning id into z;
 insert into public.products(organization_id,name,base_unit,count_unit) values(org,'後腳','公斤','公斤') returning id,updated_at into p,stamp;
 insert into public.products(organization_id,name,base_unit,count_unit) values(org,'未盤品項','包','包') returning id into p2;
 insert into public.zone_products(zone_id,product_id,count_unit) values(z,p,'公斤'),(z,p2,'包');
 before_snapshot:=jsonb_build_object('zones',jsonb_build_array(jsonb_build_object('zone_id',z,'zone_name','食材','product_id',p,'product_name','後腳','unit','公斤'),jsonb_build_object('zone_id',z,'zone_name','食材','product_id',p2,'product_name','未盤品項','unit','包')));
 insert into public.inventory_count_sessions(organization_id,store_id,started_by,status,snapshot,started_at,completed_at) values(org,store_id,actor,'REVIEWING',before_snapshot,now()-interval '2 hours',now()-interval '1 hour') returning id into oldcs;
 insert into public.count_entries(organization_id,session_id,zone_id,product_id,quantity,unit,entered_by,entry_type) values(org,oldcs,z,p,1,'公斤',actor,'INITIAL_COUNT');
 insert into public.inventory_count_sessions(organization_id,store_id,started_by,status,snapshot) values(org,store_id,actor,'IN_PROGRESS',before_snapshot) returning id into cs;
 insert into public.count_zone_progress(organization_id,session_id,zone_id,status) values(org,cs,z,'IN_PROGRESS');
 result:=public.save_pilot_count_drafts_v2(cs,gen_random_uuid(),jsonb_build_array(jsonb_build_object('zone_id',z,'product_id',p,'quantity',0,'note','目前沒在使用','expected_updated_at',null)));
 oldstamp:=(result->0->>'updated_at')::timestamptz;
 set local role authenticated;
 data:=public.baihuayuan_inventory_month(store_id,month);
 reset role;
 assert data->>'source_id'=cs::text,'admin selects old completed session';
 assert (select r->>'current_quantity'='0.000' or (r->>'current_quantity')::numeric=0 from jsonb_array_elements(data->'rows')r where r->>'product_id'=p::text),'zero missing from admin';
 assert (select r#>>'{zones,0,note}'='目前沒在使用' from jsonb_array_elements(data->'rows')r where r->>'product_id'=p::text),'note missing from admin';
 assert (select r->>'current_quantity' is null from jsonb_array_elements(data->'rows')r where r->>'product_id'=p2::text),'blank became zero';
 assert not (data->>'source_complete')::boolean,'draft falsely complete';
 payload:=jsonb_build_object('id',p,'name','後腳','unit','支','specification','','updated_at',stamp,'unit_price',null,'count_session_id',cs,'expected_count_unit','公斤');
 set local role authenticated;
 result:=public.app_operation(store_id,'count.catalog-edit',payload,req);
 assert result=public.app_operation(store_id,'count.catalog-edit',payload,req),'edit retry differs';
 reset role;
 assert (select d.unit='支' and d.quantity=0 and d.note='目前沒在使用' and d.updated_at<>oldstamp from public.count_drafts d where d.session_id=cs and d.product_id=p),'draft unit not synchronized or content lost';
 assert (select snapshot#>>'{zones,0,unit}'='支' from public.inventory_count_sessions where id=cs),'current unit stale';
 assert (select snapshot=before_snapshot from public.inventory_count_sessions where id=oldcs),'historical snapshot modified';
 assert (select unit='公斤' and quantity=1 from public.count_entries where session_id=oldcs),'historical count modified';
 data:=public.baihuayuan_inventory_month(store_id,month);
 assert (select r->>'unit'='支' and (r->>'current_quantity')::numeric=0 from jsonb_array_elements(data->'rows')r where r->>'product_id'=p::text),'admin unit stale';
 denied:=false;begin perform public.save_pilot_count_drafts_v2(cs,gen_random_uuid(),jsonb_build_array(jsonb_build_object('zone_id',z,'product_id',p,'quantity',36,'note','old device','expected_updated_at',oldstamp)));exception when others then denied:=true;end;assert denied,'stale device overwrites corrected unit';
 denied:=false;begin perform public.app_operation(store_id,'count.catalog-edit',payload,gen_random_uuid());exception when serialization_failure then denied:=true;end;assert denied,'stale edit accepted';
 -- Administrative field-note editing is visible to the same supervisor draft.
 data:=public.baihuayuan_inventory_month(store_id,month);
 payload:=jsonb_build_object('session_id',cs,'revision',data->>'revision','row_key',p::text||':支','acknowledged',false,'note','行政核對中','unit_price',null,'field_notes',jsonb_build_object((select id::text from public.count_drafts where session_id=cs and product_id=p),'已與現場確認'));
 set local role authenticated;
 result:=public.baihuayuan_inventory_month(store_id,month,'review',payload);
 reset role;
 assert (select note='已與現場確認' and quantity=0 and unit='支' from public.count_drafts where session_id=cs and product_id=p),'admin note did not sync back';
 assert (select r#>>'{zones,0,note}'='已與現場確認' from jsonb_array_elements(result->'rows')r where r->>'product_id'=p::text),'admin note missing on reload';
 denied:=false;begin perform public.baihuayuan_inventory_month(store_id,month,'review',payload);exception when serialization_failure then denied:=true;end;assert denied,'stale note overwrite';
 -- A supervisor with a valid store membership cannot read any spot-check data.
 insert into public.organization_members(organization_id,user_id,role,work_role) values(org,viewer,'SUPERVISOR','SUPERVISOR');
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) values(org,viewer,'現場主管',actor);
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,work_role,assigned_by,access_mode) values(store_id,org,viewer,'qa-supervisor','SUPERVISOR','SUPERVISOR',actor,'EDIT');
 perform set_config('request.jwt.claim.sub',viewer::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',viewer,'role','authenticated')::text,true);
 denied:=false;begin perform public.baihuayuan_spot_check(store_id,'list',jsonb_build_object('month',to_char(month,'YYYY-MM')));exception when insufficient_privilege then denied:=true;end;assert denied,'supervisor sees spot plans';
 denied:=false;begin perform public.baihuayuan_spot_check(store_id,'detail',jsonb_build_object('id',gen_random_uuid()));exception when insufficient_privilege then denied:=true;end;assert denied,'supervisor direct spot entry';
 perform set_config('request.jwt.claim.sub',actor::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 result:=public.baihuayuan_spot_check(store_id,'list',jsonb_build_object('month',to_char(month,'YYYY-MM')));
 assert result is not null,'owner cannot read spot';
 select updated_at into stamp from public.products where id=p;
 payload:=jsonb_build_object('id',p,'name','後腳','unit','支','updated_at',stamp,'count_session_id',cs,'expected_count_unit','支');
 -- Completed entry prevents relabelling numeric history.
 insert into public.count_entries(organization_id,session_id,zone_id,product_id,quantity,unit,entered_by,entry_type) values(org,cs,z,p,0,'支',actor,'INITIAL_COUNT');
 select updated_at into stamp from public.products where id=p;
 payload:=payload||jsonb_build_object('unit','箱','updated_at',stamp,'expected_count_unit','支');
 denied:=false;begin perform public.app_operation(store_id,'count.catalog-edit',payload,gen_random_uuid());exception when others then denied:=sqlerrm='COUNT_UNIT_COMPLETED_REVIEW_REQUIRED';end;assert denied,'completed entry relabelled';
 data:=public.baihuayuan_inventory_month(store_id,month);
 assert (select jsonb_array_length(r->'zones')=1 from jsonb_array_elements(data->'rows')r where r->>'product_id'=p::text),'draft and completed entry duplicated';
 perform set_config('request.jwt.claim.sub',staff::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'role','authenticated')::text,true);
 denied:=false;begin perform public.baihuayuan_inventory_month(store_id,month);exception when insufficient_privilege then denied:=true;end;assert denied,'unauthorized monthly read';
 denied:=false;begin perform public.app_operation(store_id,'count.catalog-edit',payload,req);exception when insufficient_privilege then denied:=true;end;assert denied,'unauthorized cached edit';
end $$;
rollback;
select 'PASS: admin field note write/read, stale overwrite denied, supervisor spot list/detail denied, owner allowed, quantity and history preserved' as result;
