begin;
do $$
declare owner_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); org uuid; unused uuid; s uuid; other_store uuid; p uuid; z uuid; z2 uuid; c uuid; pos uuid; payload jsonb; r jsonb; retry uuid; first_result jsonb; token text:=repeat('a',64); failed boolean; amount numeric;
begin
 insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) values(owner_id,owner_id||'@eight.invalid',now(),now(),now()),(staff_id,staff_id||'@eight.invalid',now(),now(),now());
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 r:=public.owner_setup();r:=public.owner_setup('business','{"organization_name":"八項隔離驗收","business_type":"SINGLE_RESTAURANT","store_mode":"MULTI","work_role":"SUPERVISOR"}',0);
 r:=public.owner_setup('store',r->'draft'||jsonb_build_object('store_name','隔離甲店','store_code','QA8'||substr(replace(gen_random_uuid()::text,'-',''),1,14),'staff_login_mode','NAME_OR_NICKNAME'),(r->>'revision')::int);
 r:=public.owner_setup('complete','{}',(r->>'revision')::int);org:=(r->>'organization_id')::uuid;s:=(r->>'store_id')::uuid;
 insert into public.stores(organization_id,name,store_code,created_by) values(org,'隔離乙店','QA8B'||substr(replace(gen_random_uuid()::text,'-',''),1,14),owner_id) returning id into other_store;
 update public.profiles set organization_id=org,role='STAFF' where id=staff_id;
 insert into public.organization_members(organization_id,user_id,role) values(org,staff_id,'STAFF');
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) values(org,staff_id,'員工八',owner_id);
 insert into public.store_memberships(store_id,organization_id,user_id,role,login_identifier,assigned_by) values(s,org,staff_id,'STAFF','staff8',owner_id);
 perform public.issue_staff_activation(staff_id,token);
 perform public.bind_staff_invitation(staff_id,s,token);
 assert public.get_staff_invitation(token)->>'status'='VALID','bound invitation invalid';
 assert public.get_staff_invitation('invalid')->>'status'='INVALID','invalid token accepted';
 update private.staff_activation_tokens set expires_at=now()-interval '1 minute' where user_id=staff_id;
 assert public.get_staff_invitation(token)->>'status'='EXPIRED','expired token accepted';
 update private.staff_activation_tokens set expires_at=now()+interval '7 days',consumed_at=now() where user_id=staff_id;
 assert public.get_staff_invitation(token)->>'status'='USED','consumed token accepted';
 update private.staff_activation_tokens set consumed_at=null where user_id=staff_id;
 assert not has_function_privilege('authenticated','public.get_staff_invitation(text)','EXECUTE'),'token context exposed directly';
 insert into public.products(organization_id,name,base_unit,count_unit) values(org,'火腿','包','包') returning id into p;
 insert into private.product_details(product_id,safety_quantity,updated_by) values(p,8,owner_id);
 z:=private.stock_default_zone(s,p);
 insert into public.count_zones(store_id,organization_id,name,sort_order) values(s,org,'冷藏解凍區',2) returning id into z2;
 -- A zero is explicitly counted here; unknown opening quantities are never inferred.
 c:=public.start_pilot_count(s);
 insert into public.count_entries(organization_id,session_id,zone_id,product_id,quantity,unit,entered_by) values(org,c,z,p,0,'包',owner_id);
 update public.inventory_count_sessions set status='CLOSED',completed_at=now() where id=c;
 perform set_config('request.jwt.claim.sub',staff_id::text,true);
 assert jsonb_array_length(public.get_app_dashboard(s)->'shortages')=1,'initial shortage absent';
 retry:=gen_random_uuid();payload:=jsonb_build_object('mode','loan','other_store_id',other_store,'product_id',p,'name','火腿','quantity',3,'unit','包');
 first_result:=public.app_operation(s,'movement.create',payload,retry);
 assert public.app_operation(s,'movement.create',payload,retry)=first_result,'borrow retry changed response';
 assert (private.stock_snapshot(s,p,'包')->>'available')::numeric=3,'borrow posted more than once';
 assert (public.get_app_dashboard(s)->'shortages'->0->>'remaining')::numeric=5,'partial shortage wrong';
 perform public.app_operation(s,'movement.create',payload||'{"quantity":5}',gen_random_uuid());
 assert jsonb_array_length(public.get_app_dashboard(s)->'shortages')=0,'full shortage not cleared';
 assert (select count(*) from private.store_movements where to_store_id=s and status='OPEN')=2,'unreturned loans disappeared';
 perform public.app_operation(s,'movement.create',payload||'{"quantity":2,"unit":"自訂籃"}',gen_random_uuid());
 assert (private.stock_snapshot(s,p,'包')->>'available')::numeric=8,'unconverted unit mixed';
 assert exists(select 1 from private.store_units where store_id=s and unit='自訂籃'),'custom unit not saved';
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform public.app_operation(s,'stock.settings',jsonb_build_object('product_id',p,'thaw_enabled',true,'thaw_minutes',60),gen_random_uuid());
 perform set_config('request.jwt.claim.sub',staff_id::text,true);
 select id into pos from private.stock_positions where store_id=s and product_id=p and unit='包' and quantity=5;
 retry:=gen_random_uuid();payload:=jsonb_build_object('position_id',pos,'revision',1,'quantity',5,'zone_id',z,'state','FROZEN');
 first_result:=public.app_operation(s,'stock.move',payload,retry);
 assert public.app_operation(s,'stock.move',payload,retry)=first_result,'move retry changed';
 select id into pos from private.stock_positions where store_id=s and product_id=p and unit='包' and quantity=3;
 perform public.app_operation(s,'stock.move',jsonb_build_object('position_id',pos,'revision',1,'quantity',2,'zone_id',z2,'state','THAWING'),gen_random_uuid());
 assert (private.stock_snapshot(s,p,'包')->>'total')::numeric=8,'movement changed total';
 assert (private.stock_snapshot(s,p,'包')->>'available')::numeric=1,'thaw counted available';
 select id into pos from private.stock_positions where store_id=s and product_id=p and state='THAWING';
 failed:=false;begin perform public.app_operation(s,'stock.move',jsonb_build_object('position_id',pos,'revision',1,'quantity',3,'zone_id',z2,'state','READY'),gen_random_uuid());exception when others then failed:=true;end;assert failed,'overdraw accepted';
 failed:=false;begin perform public.app_operation(s,'stock.move',jsonb_build_object('position_id',pos,'revision',1,'quantity',2,'zone_id',z2,'state','READY'),gen_random_uuid());exception when others then failed:=sqlerrm='THAW_NOT_DUE';end;assert failed,'premature thaw accepted';
 update private.stock_positions set ready_at=now()-interval '1 minute' where id=pos;
 assert (private.stock_snapshot(s,p,'包')->>'available')::numeric=1,'due time automatically confirmed';
 perform public.app_operation(s,'stock.move',jsonb_build_object('position_id',pos,'revision',1,'quantity',2,'zone_id',z2,'state','READY'),gen_random_uuid());
 assert (private.stock_snapshot(s,p,'包')->>'available')::numeric=3,'human confirmation absent';
 assert (private.stock_snapshot(s,p,'包')->>'total')::numeric=8,'confirmation changed total';
 failed:=false;begin perform public.app_operation(other_store,'stock.open',jsonb_build_object('product_id',p),gen_random_uuid());exception when insufficient_privilege then failed:=true;end;assert failed,'unauthorized store exposed';
 failed:=false;begin perform public.app_operation(s,'product.lifecycle',jsonb_build_object('mode','DISABLE','ids',jsonb_build_array(p)),gen_random_uuid());exception when insufficient_privilege then failed:=true;end;assert failed,'staff disabled catalog';
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 r:=public.app_operation(s,'product.lifecycle',jsonb_build_object('mode','DELETE','ids',jsonb_build_array(p)),gen_random_uuid());
 assert exists(select 1 from public.products where id=p and not is_active),'historical product deleted';
 perform public.app_operation(s,'product.lifecycle',jsonb_build_object('mode','RESTORE','ids',jsonb_build_array(p)),gen_random_uuid());
 assert exists(select 1 from public.products where id=p and is_active),'restore failed';
 insert into public.products(organization_id,name,base_unit,count_unit) values(org,'誤建無引用','包','包') returning id into unused;
 perform public.app_operation(s,'product.lifecycle',jsonb_build_object('mode','DELETE','ids',jsonb_build_array(unused)),gen_random_uuid());
 assert not exists(select 1 from public.products where id=unused),'unreferenced product not deleted';
 -- Explicit conversion is opt-in; adding it must not mutate historical units.
 insert into private.stock_unit_conversions(store_id,product_id,from_unit,to_unit,multiplier) values(s,p,'自訂籃','包',2);
 assert (private.stock_snapshot(s,p,'包')->>'total')::numeric=12,'configured conversion missing';
 delete from private.stock_unit_conversions where store_id=s and product_id=p;
 -- A later appended correction adjusts the baseline delta, not later receipts.
 insert into public.count_entries(organization_id,session_id,zone_id,product_id,quantity,unit,entered_by,entry_type,parent_entry_id)
 select org,c,z,p,1,'包',owner_id,'CORRECTION',id from public.count_entries where session_id=c limit 1;
 assert (private.stock_snapshot(s,p,'包')->>'total')::numeric=9,'correction replaced subsequent stock';
 insert into private.waste_records(organization_id,store_id,store_name,name,quantity,unit,reason,source,product_id,zone_name,erp_required,created_by,actor_name)
 values(org,s,'隔離甲店','火腿',1,'包','品質異常','FIELD',p,(select name from public.count_zones where id=z),false,owner_id,'主管八');
 assert (private.stock_snapshot(s,p,'包')->>'total')::numeric=8,'waste did not debit non-ready stock';
 assert not exists(select 1 from private.stock_positions where store_id=s and quantity<0),'negative physical position';
 update public.store_memberships set is_active=false where store_id=s and user_id=staff_id;
 assert public.get_staff_invitation(token)->>'status'='REVOKED','revoked invitation accepted';
 perform set_config('request.jwt.claim.sub',staff_id::text,true);
 failed:=false;begin perform public.app_workspace(s,'stock');exception when insufficient_privilege then failed:=true;end;assert failed,'revoked staff read stock';
end $$;
rollback;
