-- Disposable fixtures on an existing QA store. Every data change is rolled back.
begin;
do $$
declare
 store uuid; org uuid; staff uuid; manager uuid; zone uuid; item uuid; risk uuid; key uuid;
 payload jsonb; r jsonb; again jsonb; data jsonb; w uuid; w2 uuid; old_ids jsonb; risk_version text;
 n bigint; failed boolean; today date:=(now() at time zone 'Asia/Taipei')::date;
begin
 select id,organization_id into strict store,org from public.stores where store_code='QA0907UI';
 select user_id into strict staff from public.store_memberships where store_id=store and role='STAFF' and is_active;
 select user_id into strict manager from public.store_memberships where store_id=store and role='SUPERVISOR' and is_active;
 select id into zone from public.count_zones where store_id=store and is_active order by sort_order limit 1;
 perform set_config('request.jwt.claim.sub',staff::text,true);
 key:=gen_random_uuid(); payload:=jsonb_build_object('name','QA SQL overdue','expires_on',today-1,'zone_id',zone,'attention_reason','保存期限短');
 r:=public.save_pilot_expiry_waste(store,key,'REMINDER',payload); item:=(r->>'id')::uuid;
 if public.save_pilot_expiry_waste(store,key,'REMINDER',payload)<>r then raise exception 'ASSERT reminder retry'; end if;
 failed:=false;begin perform public.save_pilot_expiry_waste(store,key,'REMINDER',payload||'{"name":"changed"}');exception when others then failed:=sqlerrm like '%REQUEST_REUSED%';end;
 if not failed then raise exception 'ASSERT same id different data accepted';end if;
 data:=public.get_pilot_expiry_waste(store,today,today);
 if not exists(select 1 from jsonb_array_elements(data->'items') e where e->>'id'=item::text and e->>'category'='urgent') then raise exception 'ASSERT staff pending';end if;
 failed:=false;begin perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'WASTE',jsonb_build_object('expiry_id',item,'quantity',1,'unit','瓶'));exception when others then failed:=sqlerrm like '%DELAY_REASON_REQUIRED%';end;
 if not failed or exists(select 1 from private.expiry_resolutions where expiry_id=item) then raise exception 'ASSERT overdue delay required atomically';end if;
 perform set_config('request.jwt.claim.sub',manager::text,true);
 key:=gen_random_uuid();payload:=jsonb_build_object('expiry_id',item,'quantity',1.25,'unit','瓶','delay_reason','QA 交接遺漏');
 r:=public.save_pilot_expiry_waste(store,key,'WASTE',payload); w:=(r->>'id')::uuid;
 if public.save_pilot_expiry_waste(store,key,'WASTE',payload)<>r then raise exception 'ASSERT waste retry';end if;
 data:=public.get_pilot_expiry_waste(store,today,today);
 if exists(select 1 from jsonb_array_elements(data->'items') e where e->>'id'=item::text) then raise exception 'ASSERT completed item remains pending';end if;
 if not exists(select 1 from jsonb_array_elements(data->'waste') e where e->>'id'=w::text and e->>'delay_reason'='QA 交接遺漏' and e->>'quantity'='1.250') then raise exception 'ASSERT manager audit/quantity';end if;
 perform set_config('request.jwt.claim.sub',staff::text,true);
 again:=public.save_pilot_expiry_waste(store,gen_random_uuid(),'USED',jsonb_build_object('expiry_id',item));
 if again->>'id'<>w::text or again->>'type'<>'WASTE' or (select count(*) from private.waste_records where expiry_id=item)<>1 then raise exception 'ASSERT cross-actor retry duplicated outcome';end if;
 data:=public.get_pilot_expiry_waste(store,today,today);
 if exists(select 1 from jsonb_array_elements(data->'items') e where e->>'id'=item::text) or exists(select 1 from jsonb_array_elements(data->'waste') e where e->>'id'=w::text and e->>'delay_reason' is not null) then raise exception 'ASSERT shared completion or staff delay leak';end if;
 if (data->>'has_erp')::boolean or jsonb_array_length(data->'erp_pending')<>0 then raise exception 'ASSERT ERP disabled';end if;
 if (select reference_price from private.waste_records where id=w) is not null or exists(select 1 from public.inventory_lot_events where source_id=w) then raise exception 'ASSERT guessed price or inventory';end if;
 failed:=false;begin perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'WASTE','{"name":"bad","quantity":0,"unit":"包","reason":"其他"}');exception when others then failed:=sqlerrm like '%QUANTITY_UNIT_REQUIRED%';end;
 if not failed then raise exception 'ASSERT zero waste';end if;
 failed:=false;begin perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'RISK_SAVE','{}');exception when others then failed:=sqlerrm like '%FIELD_MANAGER_REQUIRED%';end;
 if not failed then raise exception 'ASSERT staff altered risk';end if;
 perform set_config('request.jwt.claim.sub',manager::text,true);
 key:=gen_random_uuid();payload:=jsonb_build_object('zone_id',zone,'name','QA SQL shelf','detail','後方','cadence','DAILY');
 r:=public.save_pilot_expiry_waste(store,key,'RISK_SAVE',payload);risk:=(r->>'id')::uuid;
 perform public.save_pilot_expiry_waste(store,key,'RISK_SAVE',payload);
 if (select count(*) from private.expiry_risk_events where risk_id=risk)<>1 then raise exception 'ASSERT risk retry';end if;
 select updated_at::text into risk_version from private.expiry_risk_locations where id=risk;
 perform set_config('request.jwt.claim.sub',staff::text,true);
 select count(*) into n from private.expiry_risk_events where risk_id=risk;
 perform public.get_pilot_expiry_waste(store,today,today);
 if (select count(*) from private.expiry_risk_events where risk_id=risk)<>n then raise exception 'ASSERT reading records inspection';end if;
 key:=gen_random_uuid();payload:=jsonb_build_object('risk_id',risk,'type','LABEL','note','QA 日期模糊');
 r:=public.save_pilot_expiry_waste(store,key,'RISK_ISSUE',payload);
 if public.save_pilot_expiry_waste(store,key,'RISK_ISSUE',payload)<>r then raise exception 'ASSERT issue retry';end if;
 key:=gen_random_uuid();payload:=jsonb_build_object('new_expiry',jsonb_build_object('risk_id',risk,'zone_id',zone,'name','QA found expired','expires_on',today));
 select count(*) into n from private.expiry_items where store_id=store;
 failed:=false;begin perform public.save_pilot_expiry_waste(store,key,'WASTE',payload);exception when others then failed:=sqlerrm like '%QUANTITY_UNIT_REQUIRED%';end;
 if not failed or (select count(*) from private.expiry_items where store_id=store)<>n then raise exception 'ASSERT failed risk outcome left reminder';end if;
 r:=public.save_pilot_expiry_waste(store,key,'USED',payload);
 if public.save_pilot_expiry_waste(store,key,'USED',payload)<>r or (select count(*) from private.expiry_items where store_id=store)<>n+1 then raise exception 'ASSERT discovered expiry retry';end if;
 perform set_config('request.jwt.claim.sub',manager::text,true);
 failed:=false;begin perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'RISK_SAVE',jsonb_build_object('id',risk,'updated_at','2000-01-01'));exception when others then failed:=sqlerrm like '%RISK_CHANGED%';end;
 if not failed then raise exception 'ASSERT stale risk update';end if;
 perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'RISK_SAVE',jsonb_build_object('id',risk,'updated_at',risk_version,'zone_id',zone,'name','QA SQL shelf','detail','後方','cadence','DAILY','is_active',false));
 perform set_config('request.jwt.claim.sub',staff::text,true);
 data:=public.get_pilot_expiry_waste(store,today,today);
 if exists(select 1 from jsonb_array_elements(data->'risks') e where e->>'id'=risk::text) then raise exception 'ASSERT disabled risk visible';end if;
 if not exists(select 1 from jsonb_array_elements(data->'issues') e where e->'snapshot'->>'name'='QA SQL shelf') then raise exception 'ASSERT disabled risk lost history';end if;
 -- ERP is organization configuration, independent of restaurant type.
 update public.organizations set has_erp=true where id=org;
 key:=gen_random_uuid();payload:='{"name":"QA ERP one","quantity":1,"unit":"包","reason":"其他"}';
 r:=public.save_pilot_expiry_waste(store,key,'WASTE',payload);w:=(r->>'id')::uuid;
 failed:=false;begin perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'ERP_COMPLETE',jsonb_build_object('work_date',today,'waste_ids',jsonb_build_array(w)));exception when others then failed:=sqlerrm like '%FIELD_MANAGER_REQUIRED%';end;
 if not failed then raise exception 'ASSERT staff ERP manager action';end if;
 perform set_config('request.jwt.claim.sub',manager::text,true);
 old_ids:=jsonb_build_array(w);
 r:=public.save_pilot_expiry_waste(store,gen_random_uuid(),'WASTE','{"name":"QA ERP two","quantity":2,"unit":"瓶","reason":"品質異常"}');w2:=(r->>'id')::uuid;
 failed:=false;begin perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'ERP_COMPLETE',jsonb_build_object('work_date',today,'waste_ids',old_ids));exception when others then failed:=sqlerrm like '%ERP_LIST_CHANGED%';end;
 if not failed then raise exception 'ASSERT stale ERP snapshot acknowledged new row';end if;
 key:=gen_random_uuid();payload:=jsonb_build_object('work_date',today,'waste_ids',jsonb_build_array(w,w2));
 r:=public.save_pilot_expiry_waste(store,key,'ERP_COMPLETE',payload);
 if public.save_pilot_expiry_waste(store,key,'ERP_COMPLETE',payload)<>r then raise exception 'ASSERT ERP retry';end if;
 data:=public.get_pilot_expiry_waste(store,today,today);
 if jsonb_array_length(data->'erp_pending')<>0 then raise exception 'ASSERT completed ERP pending';end if;
 perform public.save_pilot_expiry_waste(store,gen_random_uuid(),'WASTE','{"name":"QA ERP later","quantity":3,"unit":"份","reason":"其他"}');
 data:=public.get_pilot_expiry_waste(store,today,today);
 if jsonb_array_length(data->'erp_pending')<>1 then raise exception 'ASSERT later waste lost after ERP completion';end if;
 if has_function_privilege('anon','public.get_pilot_expiry_waste(uuid,date,date)','EXECUTE') or has_function_privilege('anon','public.save_pilot_expiry_waste(uuid,uuid,text,jsonb)','EXECUTE') then raise exception 'ASSERT anonymous access';end if;
 if has_table_privilege('authenticated','private.waste_records','SELECT') then raise exception 'ASSERT direct table access';end if;
 perform set_config('request.jwt.claim.sub',null,true);
 failed:=false;begin perform public.get_pilot_expiry_waste(store,today,today);exception when others then failed:=sqlerrm like '%STORE_ACCESS_DENIED%';end;
 if not failed then raise exception 'ASSERT no login';end if;
end $$;
rollback;
select 'PASS: shared reminder/resolution, immutable history, roles, overdue reason, actual quantity, risk settings/read-only/history, discovered-item atomicity, ERP snapshot/retry/later additions, anonymous and direct table denial' as expiry_waste_tests;
