-- Safe against a linked database: all fixtures are in a deliberately rolled-back subtransaction.
do $test$
declare owner_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); limited_id uuid:=gen_random_uuid(); other_id uuid:=gen_random_uuid();
 org uuid;a uuid;b uuid;data jsonb;person jsonb;before_auth jsonb;before_pin jsonb;result jsonb;revision text;req uuid:=gen_random_uuid();denied boolean;
 name text:='功能測試'||substr(gen_random_uuid()::text,1,8); login text:='FA'||replace(gen_random_uuid()::text,'-',''); code text:='FA'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,16)); scopes jsonb;
begin
 begin
 insert into auth.users(id,email,email_confirmed_at) select id,id||'@functions-qa.invalid',now() from unnest(array[owner_id,staff_id,limited_id,other_id])id;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 data:=public.owner_setup();
 data:=public.owner_setup('business',jsonb_build_object('organization_name','功能權限隔離測試','business_type','SINGLE_RESTAURANT','store_mode','MULTI'),0);
 data:=public.owner_setup('store',data->'draft'||jsonb_build_object('store_name','BeApe','store_code',code,'staff_login_mode','NAME_OR_NICKNAME'),(data->>'revision')::int);
 data:=public.owner_setup('identity',data->'draft'||'{"work_role":"OWNER"}',(data->>'revision')::int);
 data:=public.owner_setup('complete',data->'draft',(data->>'revision')::int);a:=(data->>'store_id')::uuid;org:=(data->>'organization_id')::uuid;
 data:=public.app_operation(a,'store.create','{"name":"Gras"}',gen_random_uuid());b:=(data->>'id')::uuid;
 insert into public.organization_members(organization_id,user_id,role,work_role,can_manage_business) values(org,staff_id,'STAFF','STAFF',false),(org,limited_id,'SUPERVISOR','SUPERVISOR',true),(org,other_id,'STAFF','STAFF',false);
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) values(org,staff_id,name,owner_id),(org,limited_id,'limited-'||name,owner_id),(org,other_id,'other-'||name,owner_id);
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,work_role,assigned_by,can_manage_business) values(a,org,staff_id,login,'STAFF','STAFF',owner_id,false),(a,org,limited_id,'limited-'||login,'SUPERVISOR','SUPERVISOR',owner_id,true),(a,org,other_id,'other-'||login,'STAFF','STAFF',owner_id,false);
 insert into private.staff_pin_credentials(user_id,pin_hash) values(staff_id,extensions.crypt('482613',extensions.gen_salt('bf')));
 select to_jsonb(u) into before_auth from auth.users u where id=staff_id;
 select to_jsonb(c) into before_pin from private.staff_pin_credentials c where user_id=staff_id;
 select value into person from jsonb_array_elements(public.get_baihuayuan_people(a)->'partners') where value->>'user_id'=staff_id::text;revision:=person->>'revision';
 scopes:=jsonb_build_array(jsonb_build_object('store_id',a,'access_mode','EDIT'),jsonb_build_object('store_id',b,'access_mode','EDIT'));
 result:=public.save_person_function_access(a,staff_id,revision,name,scopes,array['FIELD','OFFICE'],b,req);
 assert (result->>'saved')::boolean,'save not confirmed';
 assert public.save_person_function_access(a,staff_id,revision,name,scopes,array['FIELD','OFFICE'],b,req)=result,'retry not idempotent';
 assert (select count(*)=2 from public.store_memberships where user_id=staff_id and is_active),'two-store access missing';
 assert (select to_jsonb(u) from auth.users u where id=staff_id)=before_auth,'auth identity changed';
 assert (select to_jsonb(c) from private.staff_pin_credentials c where user_id=staff_id)=before_pin,'PIN row changed';
 assert (select login_identifier from public.store_memberships where user_id=staff_id and store_id=a)=login,'existing login changed';
 assert public.resolve_staff_login(name)->>'loginIdentifier'=login,'name resolver failed';
 assert public.resolve_staff_login(login)->>'storeCode'=(select store_code from public.stores where id=b),'default store not used';
 assert exists(select 1 from public.verify_staff_pin(code,login,'482613') where outcome='OK'),'existing PIN no longer accepted';
 denied:=false;begin perform public.save_person_function_access(a,staff_id,revision,name,scopes,array['FIELD'],b,gen_random_uuid());exception when serialization_failure then denied:=true;end;assert denied,'stale update accepted';
 perform set_config('request.jwt.claim.sub',staff_id::text,true);
 assert private.app_role(a)='LOGISTICS','office bundle missing';
 assert private.has_active_store_role(a,array['STAFF']::public.app_role[]),'combined field access missing';
 assert private.can_manage_members(a) and private.can_administer_people(a) and not private.can_manage_business(a),'office people/system capabilities mixed';
 assert (public.get_app_context()->'stores'->0->>'default_store_id')::uuid=b,'default not in app context';
 denied:=false;begin perform public.save_person_function_access(a,staff_id,result->'person'->>'revision',name,scopes,array['FIELD','OFFICE','MANAGE'],b,gen_random_uuid());exception when insufficient_privilege then denied:=true;end;assert denied,'self elevation allowed';
 denied:=false;begin perform public.save_person_function_access(a,staff_id,revision,name,scopes,array['FIELD','OFFICE'],b,req);exception when insufficient_privilege then denied:=true;end;assert denied,'cached result bypassed authorization';
 perform set_config('request.jwt.claim.sub',limited_id::text,true);
 denied:=false;begin perform public.save_person_function_access(a,staff_id,result->'person'->>'revision',name,scopes,array['FIELD'],b,gen_random_uuid());exception when insufficient_privilege then denied:=true;end;assert denied,'out-of-scope manager changed global permissions';
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 revision:=result->'person'->>'revision';
 denied:=false;begin perform public.save_person_function_access(a,owner_id,'x',name,scopes,array['FIELD'],b,gen_random_uuid());exception when insufficient_privilege then denied:=true;end;assert denied,'owner modified';
 denied:=false;begin perform public.save_person_function_access(a,staff_id,revision,name,scopes,array['OWNER'],b,gen_random_uuid());exception when invalid_parameter_value then denied:=true;end;assert denied,'unknown function accepted';
 denied:=false;begin perform public.save_person_function_access(a,staff_id,revision,name,scopes,array['FIELD'],gen_random_uuid(),gen_random_uuid());exception when invalid_parameter_value then denied:=true;end;assert denied,'unassigned default accepted';
 scopes:=jsonb_build_array(jsonb_build_object('store_id',b,'access_mode','VIEW'));
 result:=public.save_person_function_access(a,staff_id,revision,name,scopes,array['FIELD'],b,gen_random_uuid());
 perform set_config('request.jwt.claim.sub',staff_id::text,true);
 assert private.app_role(a) is null,'removed store remains visible';
 assert jsonb_array_length(public.get_app_context()->'stores')=1,'removed store in context';
 assert private.app_role(b)='STAFF','field-only retains office role';
 denied:=false;begin perform public.app_operation(b,'record.save','{}',gen_random_uuid());exception when others then denied:=sqlerrm='STORE_READ_ONLY';end;assert denied,'read-only writes allowed';
 assert public.resolve_staff_login(login) is not null,'login lost after origin-store removal';
 update public.staff_identities set display_name=name where user_id=other_id;
 assert public.resolve_staff_login(name) is null,'ambiguous name selected a person';
 assert public.resolve_staff_login(login) is not null,'unique identifier did not resolve duplicate name';
 assert not has_function_privilege('anon','public.resolve_staff_login(text)','execute'),'public roster resolution exposed';
 assert not has_function_privilege('authenticated','public.resolve_staff_login(text)','execute'),'resolver exposed to browser';
 assert not has_function_privilege('anon','public.save_person_function_access(uuid,uuid,text,text,jsonb,text[],uuid,uuid)','execute'),'anonymous writes enabled';
 raise exception using errcode='Z9901',message='FUNCTION_ACCESS_TEST_ROLLBACK';
 exception when sqlstate 'Z9901' then null;
 end;
end $test$;
