begin;
do $test$
declare s uuid;u uuid;staff uuid;sid uuid:=gen_random_uuid();old_sid uuid:=gen_random_uuid();shared_sid uuid:=gen_random_uuid();staff_sid uuid:=gen_random_uuid();d uuid:=gen_random_uuid();other_d uuid:=gen_random_uuid();r jsonb;denied boolean;clock_before timestamptz; atomic_sid uuid:=gen_random_uuid(); atomic_device uuid:=gen_random_uuid();
begin
 select id into s from public.stores where store_code='QAFULLINDEP';
 select sm.user_id into u from public.store_memberships sm join public.organization_members om on om.user_id=sm.user_id and om.organization_id=sm.organization_id where sm.store_id=s and om.is_owner;
 select sm.user_id into staff from public.store_memberships sm where sm.store_id=s and sm.role='STAFF' and sm.is_active limit 1;
 assert u is not null and staff is not null,'QA fixtures missing';
 insert into auth.sessions(id,user_id,created_at,updated_at) values(sid,u,now(),now()),(old_sid,u,now()-interval '1 hour',now()),(shared_sid,u,now(),now()),(staff_sid,staff,now(),now());
 perform set_config('request.jwt.claim.sub',u::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'session_id',sid,'role','authenticated')::text,true);
 perform public.register_app_device(s,d);
 perform public.app_operation(s,'device.authorize',jsonb_build_object('id',d,'device_type','PERSONAL'),gen_random_uuid());
 r:=public.choose_app_devices(array[s],d,true);
 assert r->>'authorized'='true' and r->>'device_type'='PERSONAL' and r->>'reauth_days'='30','personal choice failed';
 assert not (r->>'choice_required')::boolean,'choice repeated after registration';
 update private.app_session_access set last_active_at=now()-interval '29 days' where session_id=sid;
 assert private.app_session_valid(s),'personal login expired before 30 days';
 select last_active_at into clock_before from private.app_session_access where session_id=sid and store_id=s;
 assert public.choose_app_devices(array[s],d,true)=r,'idempotent retry changed choice';
 assert (select last_active_at=clock_before from private.app_session_access where session_id=sid and store_id=s),'retry extended idle clock';
 perform public.touch_app_session(s,false);
 assert (select last_active_at=clock_before from private.app_session_access where session_id=sid and store_id=s),'background polling extended idle clock';
 perform public.touch_app_session(s,true);
 assert (select last_active_at>clock_before from private.app_session_access where session_id=sid and store_id=s),'real activity failed to renew';
 denied:=false;begin perform public.choose_app_device(s,other_d,true);exception when insufficient_privilege then denied:=true;end;assert denied,'session rebound to different device';
 update private.app_session_access set last_active_at=now()-interval '31 days' where session_id=sid;
 assert not private.app_session_valid(s),'personal login exceeded 30 days';
 denied:=false;begin perform public.touch_app_session(s,true);exception when insufficient_privilege then denied:=true;end;assert denied,'expired session revived itself';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'session_id',old_sid,'role','authenticated')::text,true);
 denied:=false;begin perform public.choose_app_device(s,d,true);exception when insufficient_privilege then denied:=true;end;assert denied,'old session could newly trust a device';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'session_id',shared_sid,'role','authenticated')::text,true);
 r:=public.choose_app_device(s,d,false);
 assert r->>'device_type'='SHARED' and r->>'idle_minutes'='15','shared mode not independent of personal login';
 update private.app_session_access set last_active_at=now()-interval '14 minutes' where session_id=shared_sid;
 assert private.app_session_valid(s),'shared login expired too early';
 update private.app_session_access set last_active_at=now()-interval '16 minutes' where session_id=shared_sid;
 assert not private.app_session_valid(s),'shared login did not lock';
 perform set_config('request.jwt.claim.sub',staff::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'session_id',staff_sid,'role','authenticated')::text,true);
 denied:=false;begin perform public.choose_app_devices(array[s],other_d,true);exception when insufficient_privilege then denied:=true;end;assert denied,'staff self-authorized an unapproved device';
 -- An approved device may be remembered by staff, but only after manager authorization.
 update private.app_devices set authorized_at=now(),authorized_by=u,device_type='PERSONAL' where id=d and store_id=s;
 r:=public.choose_app_devices(array[s],d,true);
 assert r->>'device_type'='PERSONAL','staff cannot remember a manager-approved device';
 denied:=false;begin perform public.app_operation(s,'device.authorize',jsonb_build_object('id',other_d,'device_type','PERSONAL'),gen_random_uuid());exception when insufficient_privilege then denied:=true;end;assert denied,'staff elevated manager privileges';
 denied:=false;begin perform public.choose_app_devices(array[s,gen_random_uuid()],gen_random_uuid(),true);exception when insufficient_privilege then denied:=true;end;assert denied,'cross-store access permitted';
 update private.app_devices set revoked_at=now()+interval '1 second' where id=d and store_id=s;
 assert not private.app_session_valid(s),'revocation ignored for manager-approved device';
 denied:=false;begin perform public.choose_app_device(s,d,true);exception when insufficient_privilege then denied:=true;end;assert denied,'revoked device self-reauthorized';
 insert into auth.sessions(id,user_id,created_at,updated_at) values(atomic_sid,staff,now(),now());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',staff,'session_id',atomic_sid,'role','authenticated')::text,true);
 denied:=false;begin perform public.choose_app_devices(array[s,gen_random_uuid()],atomic_device,false);exception when insufficient_privilege then denied:=true;end;assert denied,'unknown store accepted';
 assert not exists(select 1 from private.app_device_sessions where session_id=atomic_sid),'multi-store choice partially committed';
 assert not exists(select 1 from private.app_devices where id=atomic_device),'failed multi-store choice left a device';
 assert not has_function_privilege('anon','public.choose_app_devices(uuid[],uuid,boolean)','execute'),'anonymous choice allowed';
 assert not has_table_privilege('authenticated','private.app_device_sessions','update'),'client can change session policy directly';
end $test$;
rollback;
select 'PASS: 30-day inactivity, real activity only, 15-minute shared lock, idempotency, freshness, device binding, staff scope, cross-store denial, revocation, grants; fixtures rolled back' result;
