-- Isolated fixture, fully rolled back. No production credentials or real user data.
begin;
do $test$
declare
 owner_id uuid:=gen_random_uuid();admin_id uuid:=gen_random_uuid();staff_id uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();
 org uuid:=gen_random_uuid();a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();foreign_org uuid:=gen_random_uuid();foreign_store uuid:=gen_random_uuid();
 batch uuid;receipt uuid;pending_id uuid:=gen_random_uuid();created jsonb;row_data jsonb;payload jsonb;response jsonb;req uuid:=gen_random_uuid();
 before_receipt jsonb;before_lines jsonb;before_members jsonb;before_pin text;actor uuid;
begin
 assert not has_function_privilege('anon','public.get_baihuayuan_receipt_accounting(uuid)','EXECUTE'),'anonymous read grant';
 assert not has_function_privilege('anon','public.save_baihuayuan_receipt_reconciliation(uuid,uuid,jsonb,uuid)','EXECUTE'),'anonymous write grant';
 assert not has_table_privilege('authenticated','private.receipt_reconciliations','SELECT,INSERT,UPDATE,DELETE'),'table access exposed';
 insert into auth.users(id,email,email_confirmed_at,created_at,updated_at) select id,id||'@receipt-check.invalid',now(),now(),now() from unnest(array[owner_id,admin_id,staff_id,outsider]) id;
 insert into public.profiles(id,display_name) select id,'對帳回滾測試' from unnest(array[owner_id,admin_id,staff_id,outsider]) id on conflict(id) do nothing;
 insert into public.organizations(id,name,business_type,store_mode) values(org,'對帳隔離測試','SINGLE_RESTAURANT','MULTI'),(foreign_org,'對帳跨組織','SINGLE_RESTAURANT','MULTI');
 insert into public.stores(id,organization_id,name,store_code,created_by) values(a,org,'BeApe','RA'||substr(a::text,1,8),owner_id),(b,org,'Gras','RA'||substr(b::text,1,8),owner_id),(foreign_store,foreign_org,'BeApe','RA'||substr(foreign_store::text,1,8),outsider);
 insert into public.organization_members(organization_id,user_id,role,is_owner,can_manage_business) values(org,owner_id,'OWNER',true,true),(org,admin_id,'LOGISTICS',false,false),(org,staff_id,'STAFF',false,false),(foreign_org,outsider,'OWNER',true,true);
 insert into public.staff_identities(organization_id,user_id,display_name,created_by) select org,id,'對帳回滾測試',owner_id from unnest(array[owner_id,admin_id,staff_id]) id;
 insert into public.store_memberships(store_id,organization_id,user_id,login_identifier,role,work_role,assigned_by,can_manage_business) values(a,org,owner_id,'ra-owner','OWNER','OWNER',owner_id,true),(a,org,admin_id,'ra-admin','LOGISTICS','LOGISTICS',owner_id,false),(a,org,staff_id,'ra-staff','STAFF','STAFF',owner_id,false),(b,org,owner_id,'ra-owner-b','OWNER','OWNER',owner_id,true);
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 created:=public.create_baihuayuan_direct_receipt(a,'隔離供應商','2026-09-15','QA-ONLY',jsonb_build_array(jsonb_build_object('product_name','測試麵粉','unit','包','quantity',2,'unit_price',50)));
 batch:=(created->>'batch_id')::uuid;receipt:=(created->>'receipt_id')::uuid;
 select to_jsonb(g) into before_receipt from public.goods_receipts g where id=receipt;
 select jsonb_agg(to_jsonb(l) order by l.id) into before_lines from public.receipt_lines l where receipt_id=receipt;
 select jsonb_agg(to_jsonb(sm) order by sm.store_id,sm.user_id) into before_members from public.store_memberships sm where organization_id=org;
 select md5(coalesce(jsonb_agg(to_jsonb(p) order by p.user_id)::text,'')) into before_pin from private.staff_pin_credentials p;
 row_data:=public.get_baihuayuan_receipt_accounting(a)->0;
 assert row_data->>'batch_id'=batch::text and row_data->>'status'='MISSING','direct receipt not listed';
 assert row_data->'tax'='null'::jsonb and row_data->'total'='null'::jsonb,'missing tax treated as zero or inclusive';
 assert (row_data->>'net')::numeric=100,'wrong fallback';
 payload:=jsonb_build_object('revision',row_data->'revision','source_fingerprint',row_data->>'source_fingerprint','amount_override',null,'note','','checked',true);
 begin perform public.save_baihuayuan_receipt_reconciliation(a,batch,payload,gen_random_uuid());raise exception 'missing tax checked';exception when invalid_parameter_value then null;end;
 payload:=payload||jsonb_build_object('amount_override',jsonb_build_object('net',100,'tax',5,'total',105),'note','原單確認');
 response:=public.save_baihuayuan_receipt_reconciliation(a,batch,payload,req);
 assert (response->>'saved')::boolean and (response->>'checked')::boolean,'save unconfirmed';
 assert public.save_baihuayuan_receipt_reconciliation(a,batch,payload,req)=response,'retry response changed';
 assert (select count(*) from private.receipt_reconciliations where batch_id=batch)=1,'duplicate check';
 assert (select count(*) from public.audit_logs where attempt_id=req and action='receipt.reconcile')=1,'duplicate audit';
 assert (public.get_baihuayuan_receipt_accounting(a)->0->>'total')::numeric=105,'tax doubled';
 assert public.get_baihuayuan_receipt_accounting(a)->0->>'status'='CHECKED','check not persisted';
 begin perform public.save_baihuayuan_receipt_reconciliation(a,batch,payload||'{"note":"other"}',req);raise exception 'changed retry accepted';exception when unique_violation then null;end;
 begin perform public.save_baihuayuan_receipt_reconciliation(a,batch,payload,gen_random_uuid());raise exception 'stale revision accepted';exception when serialization_failure then null;end;
 begin perform public.save_baihuayuan_receipt_reconciliation(b,batch,payload,gen_random_uuid());raise exception 'cross-store write';exception when insufficient_privilege then null;end;
 assert public.get_baihuayuan_receipt_accounting(b)='[]'::jsonb,'cross-store read';
 begin perform public.get_baihuayuan_receipt_accounting(foreign_store);raise exception 'foreign org read';exception when insufficient_privilege then null;end;
 assert (select to_jsonb(g) from public.goods_receipts g where id=receipt)=before_receipt,'source receipt rewritten';
 assert (select jsonb_agg(to_jsonb(l) order by l.id) from public.receipt_lines l where receipt_id=receipt)=before_lines,'source lines rewritten';
 assert (select jsonb_agg(to_jsonb(sm) order by sm.store_id,sm.user_id) from public.store_memberships sm where organization_id=org)=before_members,'permissions rewritten';
 assert (select md5(coalesce(jsonb_agg(to_jsonb(p) order by p.user_id)::text,'')) from private.staff_pin_credentials p)=before_pin,'PINs rewritten';
 update public.goods_receipts set document_number='QA-CHANGED' where id=receipt;
 assert public.get_baihuayuan_receipt_accounting(a)->0->>'status'='RECHECK','changed source still checked';
 row_data:=public.get_baihuayuan_receipt_accounting(a)->0;
 payload:=jsonb_build_object('revision',row_data->'revision','source_fingerprint',row_data->>'source_fingerprint','amount_override',jsonb_build_object('net',100,'tax',0,'total',100),'note','確認零稅額','checked',true);
 response:=public.save_baihuayuan_receipt_reconciliation(a,batch,payload,gen_random_uuid());
 assert (public.get_baihuayuan_receipt_accounting(a)->0->>'tax')::numeric=0,'explicit zero tax lost';
 row_data:=public.get_baihuayuan_receipt_accounting(a)->0;
 payload:=payload||jsonb_build_object('revision',row_data->'revision','source_fingerprint',row_data->>'source_fingerprint','checked',false,'note','待廠商確認');
 response:=public.save_baihuayuan_receipt_reconciliation(a,batch,payload,gen_random_uuid());
 assert public.get_baihuayuan_receipt_accounting(a)->0->>'status'='UNCHECKED','undo check failed';
 assert public.get_baihuayuan_receipt_accounting(a)->0->>'note'='待廠商確認','note lost';
 update public.store_memberships set access_mode='VIEW' where store_id=a and user_id=owner_id;
 begin perform public.save_baihuayuan_receipt_reconciliation(a,batch,payload,req);raise exception 'view-only write accepted';exception when insufficient_privilege then null;end;
 update public.store_memberships set access_mode='EDIT' where store_id=a and user_id=owner_id;
 foreach actor in array array[staff_id,outsider] loop
  perform set_config('request.jwt.claim.sub',actor::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
  begin perform public.get_baihuayuan_receipt_accounting(a);raise exception 'unauthorized read';exception when insufficient_privilege then null;end;
  begin perform public.save_baihuayuan_receipt_reconciliation(a,batch,payload,req);raise exception 'unauthorized write';exception when insufficient_privilege then null;end;
 end loop;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
 assert jsonb_array_length(public.get_baihuayuan_receipt_accounting(a))=1,'administration cannot read';
 row_data:=public.get_baihuayuan_receipt_accounting(a)->0;
 payload:=payload||jsonb_build_object('revision',row_data->'revision','source_fingerprint',row_data->>'source_fingerprint');
 response:=public.save_baihuayuan_receipt_reconciliation(a,batch,payload,gen_random_uuid());
 update public.store_memberships set is_active=false where store_id=a and user_id=admin_id;
 begin perform public.get_baihuayuan_receipt_accounting(a);raise exception 'revoked member read';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 insert into public.receipt_upload_batches(id,organization_id,store_id,store_name,work_date,uploaded_by,batch_number) values(pending_id,org,a,'BeApe','2026-09-16',owner_id,'QA-PENDING');
 assert exists(select 1 from jsonb_array_elements(public.get_baihuayuan_receipt_accounting(a)) r where r->>'batch_id'=pending_id::text and r->>'status'='PENDING'),'pending receipt vanished';
 row_data:=(select r from jsonb_array_elements(public.get_baihuayuan_receipt_accounting(a)) r where r->>'batch_id'=pending_id::text);
 payload:=jsonb_build_object('revision',0,'source_fingerprint',row_data->>'source_fingerprint','amount_override',jsonb_build_object('net',100,'tax',5,'total',105),'note','','checked',true);
 begin perform public.save_baihuayuan_receipt_reconciliation(a,pending_id,payload,gen_random_uuid());raise exception 'pending checked';exception when invalid_parameter_value then null;end;
 assert private.receipt_account_date('2026-02-30') is null and private.receipt_account_date('115/09/15')='2026-09-15'::date,'date normalization';
 assert private.receipt_account_number('NaN') is null and private.receipt_account_number('') is null,'invalid amount coerced';
 perform public.set_baihuayuan_record_state(a,'RECEIPT_BATCH',batch,'REMOVED','隔離測試');
 row_data:=(select r from jsonb_array_elements(public.get_baihuayuan_receipt_accounting(a)) r where r->>'batch_id'=batch::text);
 assert row_data->>'record_state'='REMOVED','removed not distinguished';
 begin perform public.save_baihuayuan_receipt_reconciliation(a,batch,payload,gen_random_uuid());raise exception 'removed write accepted';exception when insufficient_privilege then null;end;
 raise notice 'receipt reconciliation: permissions, store isolation, missing/zero tax, retries, revisions, source changes, notes, undo, pending and preservation passed';
end;$test$;
rollback;
