import{emptyState,escapeHtml}from'../components/layout.js';
const statusLabel={IN_PROGRESS:'盤點中',REVIEWING:'待主管處理差異',CLOSED:'已完成'};
const reasonOptions=[['INPUT_ERROR','輸入錯誤'],['MISSED_OR_WRONG_ZONE','漏盤／區域錯誤'],['WASTE_NOT_RECORDED','報廢未記錄'],['TRANSFER_NOT_RECORDED','調撥未記錄'],['RECEIPT_NOT_RECORDED','進貨未記錄'],['OTHER','其他']];

export function countPage(data,{canManage,context={}}={}){
  const{sessions=[],zones=[],products=[],assignments=[],progress=[],entries=[],drafts=[],discrepancies=[]}=data;
  if(context.sessionId&&context.zoneId){const zone=zones.find(z=>z.id===context.zoneId);const assigned=assignments.filter(a=>a.zone_id===context.zoneId).map(a=>products.find(p=>p.id===a.product_id)).filter(Boolean);return `<h2 class="page-title">${escapeHtml(zone?.name||'區域盤點')}</h2><p class="blind-note">盲盤模式｜不顯示上次數量、差異、成本或金額</p><form id="blind-count" data-session="${context.sessionId}" data-zone="${context.zoneId}" class="list">${assigned.map(p=>{const draft=drafts.find(d=>d.product_id===p.id);return `<label class="card count-input-row"><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.product_code)}</small></span><span class="quantity-input"><input data-count-product="${p.id}" data-unit="${escapeHtml(p.count_unit)}" type="number" min="0" step="0.001" value="${draft?.quantity??''}" inputmode="decimal" placeholder="數量"><b>${escapeHtml(p.count_unit)}</b></span><em data-save-state="${p.id}">${draft?'已自動保存':''}</em></label>`}).join('')}<button class="primary" type="submit">完成此區域</button><p class="error" data-error></p></form>`}
  const active=sessions.find(s=>['IN_PROGRESS','REVIEWING'].includes(s.status));
  return `<h2 class="page-title">盤點</h2><p class="muted">員工只看區域與盲盤輸入；送出後由主管處理差異。</p>
  ${!products.length||!zones.length||!assignments.length?`<section class="card empty setup-empty"><span class="empty-icon">＋</span><strong>完成盤點前置設定</strong><p>不用 SQL，可直接從這裡建立正式資料。</p><div class="empty-actions"><button class="primary" data-feature="catalog">建立商品</button><button class="secondary" data-feature="zones">建立區域</button><button class="secondary" data-feature="catalog" data-import-intent="true">匯入商品 Excel</button><button class="secondary" data-create-count ${products.length&&zones.length&&assignments.length?'':'disabled'}>建立盤點任務</button></div></section>`:''}
  ${canManage&&products.length&&zones.length&&assignments.length&&!active?`<section class="card settings-card"><h3>本日盤點任務</h3><p class="muted">依目前區域與商品建立正式盤點快照。</p><button class="primary" data-create-count>建立本日盤點任務</button><p class="error" data-action-error></p></section>`:''}
  ${active?.status==='IN_PROGRESS'?`<section class="section"><div class="section-head"><h2>進行中的任務</h2><span>${escapeHtml(statusLabel[active.status])}</span></div><div class="list">${zones.map(z=>{const p=progress.find(x=>x.session_id===active.id&&x.zone_id===z.id);return `<article class="card zone-row"><div><strong>${escapeHtml(z.name)}</strong><small>${p?.status==='COMPLETED'?'已完成':'等待盤點'}</small></div>${p?.status==='COMPLETED'?'<span class="status">完成</span>':`<button class="secondary" data-open-count data-session="${active.id}" data-zone="${z.id}">進入盲盤</button>`}</article>`}).join('')}</div></section>`:''}
  ${canManage&&active?.status==='REVIEWING'?`<section class="section"><div class="section-head"><h2>盤點差異</h2><span>不可覆寫原始盤點</span></div>${discrepancies.length?`<div class="list">${discrepancies.map(d=>{const p=products.find(x=>x.id===d.product_id);return `<article class="card discrepancy-card"><div><strong>${escapeHtml(p?.name||'商品')}</strong><p>期初 ${d.previous_quantity} → 實盤 ${d.estimated_quantity}，差異 ${d.difference}</p></div><form data-resolve-discrepancy="${d.id}" class="resolution-form"><label class="field">原因<select name="reason" required><option value="">選擇原因</option>${reasonOptions.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label class="field">處理方式<select name="action"><option value="RECOUNT">建立重盤事件</option><option value="CORRECTION">建立更正事件</option></select></label><label class="field">確認數量<input name="quantity" type="number" min="0" step="0.001" required></label><button class="primary">保存事件</button><p class="error" data-error></p></form></article>`}).join('')}</div>`:emptyState('沒有差異','本次盤點與期初數量相符。')}</section>`:''}
  ${sessions.length?`<section class="section"><div class="section-head"><h2>作業紀錄</h2></div><div class="list">${sessions.map(s=>`<article class="card setup-row"><div><strong>${escapeHtml(statusLabel[s.status]||s.status)}</strong><small>${escapeHtml(s.started_at)}</small></div></article>`).join('')}</div></section>`:''}`;
}
