import{emptyState,escapeHtml}from'../components/layout.js';

const statusLabel={IN_PROGRESS:'盤點中',REVIEWING:'待主管處理差異',CLOSED:'已完成'};
const reasonOptions=[['INPUT_ERROR','輸入錯誤'],['MISSED_OR_WRONG_ZONE','漏盤／區域錯誤'],['WASTE_NOT_RECORDED','報廢未記錄'],['TRANSFER_NOT_RECORDED','調撥未記錄'],['RECEIPT_NOT_RECORDED','進貨未記錄'],['OTHER','其他']];

function mode(businessType){return businessType==='CHAIN_RESTAURANT'?'chain':'small'}
function accessFor(role,legacyCanManage=false){if(role==='STAFF')return{kind:'staff',canCount:true,canConfigure:false,canReview:false};if(role==='ADMIN'||role==='SUPERVISOR')return{kind:'manager',canCount:true,canConfigure:true,canReview:true};if(role==='LOGISTICS')return{kind:'logistics',canCount:false,canConfigure:false,canReview:false};if(role==='OWNER')return{kind:'owner',canCount:false,canConfigure:false,canReview:false};return legacyCanManage?{kind:'manager',canCount:true,canConfigure:true,canReview:true}:{kind:'staff',canCount:true,canConfigure:false,canReview:false}}
function focusSession(data){return data.focusSession||data.sessions?.find(session=>['IN_PROGRESS','REVIEWING'].includes(session.status))||data.sessions?.[0]||null}
function completedZones(data,session){return data.progress.filter(item=>item.session_id===session?.id&&item.status==='COMPLETED').length}
function totalItems(data){return data.assignments.length}
function differenceCount(data){return data.discrepancies.filter(item=>item.status!=='RESOLVED').length}
function roleIntro(label,copy){return `<div class="count-role-intro"><span>${escapeHtml(label)}</span><small>${escapeHtml(copy)}</small></div>`}
function modeBadge(businessType){return `<span class="count-mode-badge">${mode(businessType)==='chain'?'連鎖餐飲模式':'中小餐廳模式'}</span>`}
function countStats(items){return `<div class="count-stat-grid">${items.map(([value,label])=>`<div><strong>${escapeHtml(value)}</strong><small>${escapeHtml(label)}</small></div>`).join('')}</div>`}
function emptySetupForStaff(){return emptyState('主管尚未完成盤點設定','盤點區域與品項設定完成後，任務會自動出現在這裡。')}

function blindCountPage(data,context){
  const zone=data.zones.find(item=>item.id===context.zoneId);
  const assigned=data.assignments.filter(item=>item.zone_id===context.zoneId).map(item=>data.products.find(product=>product.id===item.product_id)).filter(Boolean);
  return `${roleIntro('員工','只輸入現場數量')}<div class="count-heading"><div><h2 class="page-title">${escapeHtml(zone?.name||'區域盤點')}</h2><p>已填 ${assigned.filter(product=>data.drafts.some(draft=>draft.product_id===product.id)).length}／${assigned.length} 項</p></div><span class="count-icon">▣</span></div><p class="blind-note">盲盤模式｜不顯示上次數量、差異、成本或金額</p><p class="count-lock-note">離開可續作；完成前會攔截漏填。跨裝置區域鎖定將於 Supabase 串接階段啟用。</p><form id="blind-count" data-session="${escapeHtml(context.sessionId)}" data-zone="${escapeHtml(context.zoneId)}" class="list count-entry-list">${assigned.map(product=>{const draft=data.drafts.find(item=>item.product_id===product.id);return `<label class="card count-input-row"><span><strong>${escapeHtml(product.name)}</strong><small>${escapeHtml(product.product_code)}</small></span><span class="quantity-input"><input data-count-product="${product.id}" data-unit="${escapeHtml(product.count_unit)}" type="number" min="0" step="0.001" value="${draft?.quantity??''}" inputmode="decimal" placeholder="數量" required><b>${escapeHtml(product.count_unit)}</b></span><em data-save-state="${product.id}">${draft?'已自動保存':''}</em></label>`}).join('')}<button class="primary" type="submit">完成此區域</button><p class="error" data-error></p></form>`;
}

function paperGuidePage(data,{context,businessType}){
  const session=data.sessions.find(item=>item.id===context.paperSessionId)||focusSession(data);
  if(mode(businessType)!=='chain')return emptyState('此商家未啟用紙本謄寫','請返回盤點完成頁查看或匯出明細。');
  if(context.paperComplete)return `${roleIntro('員工','連鎖餐飲盤點後作業')}<section class="count-complete-card"><span class="count-check">✓</span><h2>紙本謄寫已確認</h2><p>本次前端流程已完成；正式經手人與時間將於 Supabase 階段跨裝置保存。</p></section><div class="count-actions"><button class="primary" data-export-count="${escapeHtml(session?.id||'')}" type="button">匯出本次盤點明細</button><button class="secondary" data-route="home" type="button">返回首頁</button></div>`;
  return `${roleIntro('員工','連鎖餐飲盤點後作業')}<div class="count-heading"><div><h2 class="page-title">謄寫店內紙本</h2><p>依公司既有盤點表完成謄寫</p></div><span class="count-icon count-icon-orange">▤</span></div><section class="card paper-guide"><ol><li><strong>開啟本次盤點明細</strong><small>依區域與紙本順序查看</small></li><li><strong>將數量謄寫到店內紙本</strong><small>不需要把紙本內容再輸回 App</small></li><li><strong>完成後交由主管稽查</strong><small>系統保留完成時間與經手人</small></li></ol></section><div class="count-actions"><button class="secondary" data-export-count="${escapeHtml(session?.id||'')}" type="button">先匯出盤點明細</button><button class="primary" data-paper-complete="${escapeHtml(session?.id||'')}" type="button">我已完成紙本謄寫</button></div><p class="count-preview-note">目前為前端驗收流程，正式完成紀錄待 Supabase 階段啟用。</p>`;
}

function countDetailPage(data,{context,businessType,role}){
  const session=data.sessions.find(item=>item.id===context.detailSessionId)||focusSession(data);
  const entries=data.entries.filter(item=>item.session_id===session?.id);
  const label=role==='STAFF'?'員工':role==='ADMIN'||role==='SUPERVISOR'?'店長／主管':role==='LOGISTICS'?'後勤':'Owner／管理者';
  if(!session)return emptyState('找不到盤點明細','請返回盤點頁重新選擇紀錄。');
  return `${roleIntro(label,'查看、匯出與列印')}<div class="count-heading"><div><h2 class="page-title">本次盤點明細</h2><p>${escapeHtml(session.started_at||'本次盤點')}・${entries.length} 筆紀錄</p></div>${modeBadge(businessType)}</div><div class="card count-detail-list">${entries.length?entries.map(entry=>{const product=data.products.find(item=>item.id===entry.product_id);const zone=data.zones.find(item=>item.id===entry.zone_id);return `<article><span><strong>${escapeHtml(product?.name||'商品')}</strong><small>${escapeHtml(zone?.name||'未分類區域')}・${escapeHtml(product?.product_code||'')}</small></span><b>${escapeHtml(entry.quantity)} ${escapeHtml(entry.unit||product?.count_unit||'')}</b></article>`}).join(''):`<div class="empty compact-empty"><strong>本次尚無盤點紀錄</strong><p>完成區域盤點後，明細會顯示在這裡。</p></div>`}</div><p class="count-detail-note">原始實盤數量僅供查看；任何更正都必須新增事件並保留紀錄。</p><div class="count-actions"><button class="primary" data-export-count="${escapeHtml(session.id)}" data-export-kind="fillback" type="button">匯出原格式回填版</button><button class="secondary" data-export-count="${escapeHtml(session.id)}" data-export-kind="audit" type="button">匯出完整稽核明細</button><button class="secondary" data-print-count type="button">列印／另存 PDF</button></div>`;
}

function zoneProgress(data,session,{manager=false}={}){
  return `<section class="section"><div class="section-head"><h2>${manager?'區域進度':'今天要盤的區域'}</h2><span>${completedZones(data,session)}／${data.zones.length}</span></div><div class="list">${data.zones.map(zone=>{const progress=data.progress.find(item=>item.session_id===session.id&&item.zone_id===zone.id);const itemCount=data.assignments.filter(item=>item.zone_id===zone.id).length;return `<article class="card zone-row count-zone-row"><span class="count-row-icon">${progress?.status==='COMPLETED'?'✓':'▣'}</span><div><strong>${escapeHtml(zone.name)}</strong><small>${itemCount} 項・${progress?.status==='COMPLETED'?'已完成':'等待盤點'}</small></div>${progress?.status==='COMPLETED'?'<span class="status">完成</span>':manager?'<span class="count-muted">進行中</span>':`<button class="secondary" data-open-count data-session="${session.id}" data-zone="${zone.id}">進入盲盤</button>`}</article>`}).join('')}</div></section>`;
}

function staffCompletion(data,{businessType}){
  const session=focusSession(data);
  const chain=mode(businessType)==='chain';
  if(!session)return emptyState('目前沒有盤點任務','主管發布任務後會顯示在這裡。');
  return `${roleIntro('員工',chain?'盤點、謄寫與備存':'盤點與備存')}<div class="count-heading"><div><h2 class="page-title">盤點完成</h2><p>${escapeHtml(session.started_at||'本次盤點')}</p></div>${modeBadge(businessType)}</div><section class="count-complete-card"><span class="count-check">✓</span><h2>${completedZones(data,session)}／${data.zones.length} 區域已完成</h2><p>本次共盤點 ${totalItems(data)} 項</p></section><div class="section-head count-after-title"><h2>盤點後作業</h2><span>${chain?'1 項必做':'全部可使用'}</span></div><div class="card count-after-list">${chain?`<button class="paper-task" data-paper-count="${session.id}" type="button"><span class="count-row-icon orange">▤</span><span><strong>謄寫店內紙本</strong><small>必做・留下經手人與完成時間</small></span><b>去完成</b></button>`:''}<button type="button" data-export-count="${session.id}" data-export-kind="fillback"><span class="count-row-icon">⇩</span><span><strong>匯出原格式回填版</strong><small>依匯入表的位置與順序，${chain?'方便謄寫':'方便對照備存'}</small></span><b>›</b></button><button type="button" data-export-count="${session.id}" data-export-kind="audit"><span class="count-row-icon">☷</span><span><strong>匯出完整稽核明細</strong><small>含來源、經手人、時間與事件紀錄</small></span><b>›</b></button><button type="button" data-count-detail="${session.id}"><span class="count-row-icon">☷</span><span><strong>查看本次明細</strong><small>${totalItems(data)} 項・可列印或另存 PDF</small></span><b>›</b></button></div><div class="count-actions">${chain?`<button class="primary" data-paper-count="${session.id}" type="button">開始謄寫紙本</button>`:`<button class="primary" data-export-count="${session.id}" data-export-kind="fillback" type="button">匯出原格式回填版</button>`}<button class="secondary" data-route="home" type="button">返回首頁</button></div>`;
}

function staffCountPage(data,options){
  const session=focusSession(data);
  if(!data.products.length||!data.zones.length||!data.assignments.length)return `${roleIntro('員工','完成主管指派的盤點')}${emptySetupForStaff()}`;
  if(session?.status==='IN_PROGRESS')return `${roleIntro('員工','今天只要完成盤點')}<div class="count-heading"><div><h2 class="page-title">今日盤點</h2><p>${escapeHtml(session.started_at||'進行中')}</p></div><span class="count-icon">▣</span></div>${countStats([[`${completedZones(data,session)}／${data.zones.length}`,'區域進度'],[String(totalItems(data)),'盤點品項'],['盲盤','盤點方式']])}${zoneProgress(data,session)}`;
  return staffCompletion(data,options);
}

function discrepancyList(data){
  const pending=data.discrepancies.filter(item=>item.status!=='RESOLVED');
  return `<section class="section"><div class="section-head"><h2>差異原因確認</h2><span>${pending.length} 項待處理</span></div>${pending.length?`<div class="list">${pending.map(item=>{const product=data.products.find(product=>product.id===item.product_id);return `<article class="card discrepancy-card"><div><strong>${escapeHtml(product?.name||'商品')}</strong><p>期初 ${item.previous_quantity} → 實盤 ${item.estimated_quantity}，差異 ${item.difference}</p></div><form data-resolve-discrepancy="${item.id}" class="resolution-form"><label class="field">原因<select name="reason" required><option value="">選擇原因</option>${reasonOptions.map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select></label><label class="field">處理方式<select name="action"><option value="RECOUNT">建立重盤事件</option><option value="CORRECTION">建立更正事件</option></select></label><label class="field">確認數量<input name="quantity" type="number" min="0" step="0.001" required></label><button class="primary">保存事件</button><p class="error" data-error></p></form></article>`}).join('')}</div>`:emptyState('沒有待處理差異','本次差異已完成整理。')}</section>`;
}

function importValidationCard(context={}){
  const preview=context.importPreview;
  const counts=preview?.counts||{matched:0,unmatched:0,duplicates:0,missingUnit:0,invalid:0};
  return `<section class="card count-import-card"><div class="count-card-heading"><span class="count-row-icon">⇧</span><div><strong>匯入原盤點表</strong><small>先預覽驗證，確認後才正式寫入</small></div></div><label class="secondary file-button count-import-button">選擇 CSV／Excel 檔<input data-count-import-file type="file" accept=".csv,.xlsx" hidden></label><div data-count-import-preview>${preview?`<div class="count-import-source"><strong>${escapeHtml(preview.fileName||'已選擇檔案')}</strong><small>工作表：${escapeHtml(preview.sheetName||'待確認')}・${preview.rows?.length||0} 列・${escapeHtml(preview.templateVersion||'')}</small></div>`:'<p class="count-import-empty">選檔後會檢查商品、單位、重複列與來源位置。</p>'}${countStats([[String(counts.matched),'已對應'],[String(counts.unmatched),'將新建'],[String(counts.duplicates),'重複'],[String(counts.missingUnit),'缺少單位']])}${preview?`<div class="count-import-sample">${preview.rows.slice(0,5).map(row=>`<div><span>${escapeHtml(row.zoneName)}</span><strong>${escapeHtml(row.productCode)}・${escapeHtml(row.productName)}</strong><small>原表第 ${row.sourceRow} 列</small></div>`).join('')}</div><p class="${preview.canPublish?'helper':'error'}">${preview.canPublish?'驗證通過：正式匯入會保存原檔、工作表、欄位與列號。':`尚不能匯入：重複 ${counts.duplicates} 列，缺少必要欄位 ${counts.invalid} 列。`}</p><button class="primary" data-publish-count-import type="button" ${preview.canPublish?'':'disabled'}>確認並正式匯入 ${preview.rows.length} 項</button><p class="error" data-count-import-error></p>`:'<p class="count-import-empty">來源工作表／欄位／列號會一併保留。</p>'}</div><p class="count-preview-note">正式匯入後，員工只會看到主管發布的區域與品項；匯出時依原列號回填數量。</p></section>`;
}

function taskSelectionCard(data,{businessType}){
  const chain=mode(businessType)==='chain';
  const assignedIds=new Set(data.assignments.map(item=>item.product_id));
  return `<section class="card count-selection-card"><div class="count-card-heading"><span class="count-row-icon">✓</span><div><strong>本次盤點品項</strong><small>${chain?'由公司範本固定，門市不可自行取消':'可勾選本次需要盤點的品項'}</small></div></div>${!chain?'<button class="text-button reuse-selection" data-reuse-count-selection type="button">沿用上次選擇</button>':''}<div class="count-selection-list">${data.products.length?data.products.map(product=>`<label><input type="checkbox" data-count-task-product="${escapeHtml(product.id)}" data-count-task-code="${escapeHtml(product.product_code)}" ${assignedIds.has(product.id)?'checked':''} ${chain?'disabled':''}><span><strong>${escapeHtml(product.name)}</strong><small>${escapeHtml(product.product_code)}・${escapeHtml(product.count_unit)}</small></span></label>`).join(''):'<p class="count-import-empty">尚無商品，請先匯入盤點表或建立商品。</p>'}</div><div class="count-source-lock"><span>來源保留</span><p>正式發布時會保存工作表、欄位、列號與範本版本；員工只能依主管發布內容盤點。</p></div></section>`;
}

function managerCountPage(data,{businessType,context={}}){
  const active=data.activeSession||data.sessions?.find(item=>['IN_PROGRESS','REVIEWING'].includes(item.status))||null,session=active||focusSession(data),ready=data.products.length&&data.zones.length&&data.assignments.length,chain=mode(businessType)==='chain';
  return `${roleIntro('店長／主管','設定、總結與現場稽查')}<div class="count-heading"><div><h2 class="page-title">本店盤點管理</h2><p>${active?escapeHtml(statusLabel[active.status]||active.status):session?'上次盤點已完成':'尚未建立今日任務'}</p></div>${modeBadge(businessType)}</div>${countStats([[String(data.zones.length),'盤點區域'],[String(totalItems(data)),'盤點品項'],[String(differenceCount(data)),'差異待確認']])}<section class="card count-manager-setup"><div><strong>盤點設定</strong><small>區域、品項、順序、單位與盲盤規則</small></div><div class="button-row"><button class="secondary" data-feature="zones" type="button">區域與品項</button><button class="secondary" data-feature="catalog" type="button">商品設定</button></div></section>${importValidationCard(context)}${!active?taskSelectionCard(data,{businessType}):'<p class="count-lock-note">目前任務使用發布當下的快照；新匯入設定會套用到下一次盤點，不會改動本次實盤。</p>'}${!ready?`<section class="card empty setup-empty"><span class="empty-icon">＋</span><strong>完成盤點前置設定</strong><p>先建立商品、區域並將商品加入區域。</p><div class="empty-actions"><button class="primary" data-feature="catalog">建立商品</button><button class="secondary" data-feature="zones">建立區域</button></div></section>`:''}${ready&&!active?`<section class="card settings-card count-create-task"><h3>建立今日盤點任務</h3><p class="muted">依目前區域、來源位置與勾選品項建立不可回寫的盤點快照。</p><button class="primary" data-create-count>發布今日盤點任務</button><p class="error" data-action-error></p></section>`:''}${active?.status==='IN_PROGRESS'?zoneProgress(data,active,{manager:true}):''}${differenceCount(data)?discrepancyList(data):''}${chain&&session&&session.status!=='IN_PROGRESS'?`<section class="section"><div class="section-head"><h2>紙本稽查</h2><span>連鎖模式</span></div><article class="card count-audit-row"><span class="count-row-icon orange">▤</span><div><strong>確認員工紙本謄寫</strong><small>核對完成時間、經手人與紙本一致性</small></div><span class="status orange-status">待稽查</span></article></section>`:''}${session&&session.status!=='IN_PROGRESS'?`<div class="count-actions"><button class="primary" data-print-count type="button">查看本店盤點總結</button><button class="secondary" data-export-count="${session.id}" data-export-kind="audit" type="button">匯出完整稽核明細</button></div>`:''}`;
}

function logisticsCountPage(data){
  const session=focusSession(data),pending=differenceCount(data);
  return `${roleIntro('後勤','整理、檢討與分析')}<div class="count-heading"><div><h2 class="page-title">盤點資料工作台</h2><p>${data.sessions.length} 次盤點紀錄・資料依門市同步</p></div><span class="count-icon count-icon-blue">▥</span></div>${countStats([[String(data.sessions.length),'資料批次'],[String(pending),'差異待分類'],[String(session?1:0),'報表待產出']])}<section class="section"><div class="section-head"><h2>後勤工作</h2><span>不改原始實盤</span></div><div class="card count-work-list"><button type="button" data-print-count><span class="count-row-icon blue">☷</span><span><strong>整理盤點明細</strong><small>單位、批次、來源與缺漏檢查</small></span><b>›</b></button><button type="button"><span class="count-row-icon blue">⇄</span><span><strong>差異分類與檢討</strong><small>耗損、漏登、單位錯誤、移撥差異</small></span><b>›</b></button><button type="button"><span class="count-row-icon blue">▥</span><span><strong>建立分析報告</strong><small>跨店比較、趨勢與異常品項</small></span><b>›</b></button></div></section>${session?`<div class="count-actions"><button class="primary" data-print-count type="button">開始整理今日資料</button><button class="secondary" data-export-count="${session.id}" type="button">匯出分析明細</button></div>`:emptyState('尚無盤點資料','門市完成盤點後，資料會出現在這裡。')}`;
}

function ownerCountPage(data,{businessType}){
  const session=focusSession(data),pending=differenceCount(data),chain=mode(businessType)==='chain';
  return `${roleIntro('Owner／管理者','看結論、決策與稽核')}<div class="count-heading"><div><h2 class="page-title">盤點管理摘要</h2><p>後勤整理後的營運結論</p></div>${modeBadge(businessType)}</div>${countStats([[String(data.sessions.filter(item=>item.status==='CLOSED').length),'已完成盤點'],[String(pending),'重大異常'],[chain?'1':'0','門市待稽核']])}<section class="section"><div class="section-head"><h2>盤點政策</h2><span>目前設定</span></div><div class="count-policy-list"><span>盲盤</span><span>差異需原因</span>${chain?'<span>紙本謄寫追蹤</span>':''}<span>明細匯出</span></div></section><section class="section"><div class="section-head"><h2>管理重點</h2><span>${session?'2':'0'} 項</span></div>${session?`<div class="card count-work-list"><button type="button"><span class="count-row-icon purple">▥</span><span><strong>查看後勤分析結論</strong><small>只呈現重大差異與改善重點</small></span><b>›</b></button><button type="button" data-print-count><span class="count-row-icon purple">✓</span><span><strong>門市稽核追蹤</strong><small>盤點紀錄、紙本與差異處理</small></span><b>›</b></button></div>`:emptyState('目前沒有管理異常','完成盤點後會顯示整理後的結論。')}</section>${session?'<div class="count-actions"><button class="primary" data-print-count type="button">查看本月管理總結</button></div>':''}`;
}

export function countPage(data,{role='STAFF',businessType='SINGLE_RESTAURANT',context={},canManage=false}={}){
  const access=accessFor(role,canManage);
  if(context.sessionId&&context.zoneId){if(!access.canCount)return emptyState('此角色不執行現場盲盤','請返回角色專屬的盤點頁。');return blindCountPage(data,context)}
  if(context.paperSessionId)return paperGuidePage(data,{context,businessType});
  if(context.detailSessionId)return countDetailPage(data,{context,businessType,role});
  if(access.kind==='manager')return managerCountPage(data,{businessType,context});
  if(access.kind==='logistics')return logisticsCountPage(data);
  if(access.kind==='owner')return ownerCountPage(data,{businessType});
  return staffCountPage(data,{businessType});
}
