import{emptyState,escapeHtml}from'../components/layout.js';
const roleContent={
  OWNER:{kicker:'商家總覽',title:'完成 Pilot 基礎設定',copy:'先確認門市、主管與員工身分，再開始建立正式作業資料。',primary:'管理商家',feature:'profile',actions:[['門市設定','新增或切換正式門市','⌂','profile'],['成員與權限','建立主管與員工身分','◎','profile'],['盤點設定','正式商品與區域建置狀態','✓','count'],['進貨管理','查看正式收據處理狀態','▤','receiving']]},
  ADMIN:{kicker:'管理重點',title:'確認今天需要處理的異常',copy:'正常資料保持收起；待確認項目會在正式資料建立後集中顯示。',primary:'查看作業紀錄',feature:'activity',actions:[['盤點差異','查看差異與未回覆原因','△','count'],['進貨管理','查看待核對正式收據','▤','receiving'],['門市設定','商品、區域與人員','⌂','profile'],['寄庫管理','與實體庫存分開管理','□','consignment']]},
  SUPERVISOR:{kicker:'主管重點',title:'安排門市今天的作業',copy:'建立與指派工作後，員工只會看到需要執行的快速操作。',primary:'查看作業紀錄',feature:'activity',actions:[['盤點任務','建立與指派盲盤','✓','count'],['盤點差異','處理差異與原因','△','count'],['進貨核對','確認收貨與 ERP 提醒','▤','receiving'],['員工管理','建立、停用與重設 PIN','◎','profile']]},
  LOGISTICS:{kicker:'後勤重點',title:'集中處理待核對進貨',copy:'原圖、OCR 原值與人工修正會分開保存；正式資料建立前不顯示假結果。',primary:'進入進貨管理',feature:'receiving',actions:[['今日進貨','依門市與日期查看','▤','receiving'],['待人工核對','處理辨識疑問與編碼','?','receiving'],['作業紀錄','回查正式收據與狀態','☷','activity'],['通知','查看失敗與待處理提醒','◔','notifications']]},
  STAFF:{kicker:'今日工作',title:'準備開始今天的現場作業',copy:'只顯示主管指派與需要完成的項目；盲盤不會顯示帳面數字。',primary:'查看今日作業',feature:'activity',actions:[['開始盲盤','依區域輸入實際數量','✓','count'],['進貨上傳','拍攝多張真實貨單','▤','receiving'],['作業紀錄','查看自己完成的工作','☷','activity'],['通知','查看主管交辦與提醒','◔','notifications']]}
};
export function homePage({role='STAFF',storeName='',hasOperationalData=false}={}){
  const content=roleContent[role]||roleContent.STAFF;
  return `<main><section class="card focus-card"><div class="eyebrow">${escapeHtml(content.kicker)}</div><h2>${escapeHtml(content.title)}</h2><p>${escapeHtml(content.copy)}</p><div class="focus-actions"><button class="primary" data-feature="${content.feature}">${escapeHtml(content.primary)}</button></div></section><section class="section"><div class="section-head"><h2>今日摘要</h2><span>正式 Supabase</span></div><div class="summary-grid"><article class="card summary-card"><span>需要處理</span><strong>—</strong></article><article class="card summary-card"><span>進行中</span><strong>—</strong></article><article class="card summary-card"><span>已完成</span><strong>—</strong></article></div></section><section class="section"><div class="section-head"><h2>快速工作</h2><span>依角色顯示</span></div><div class="action-grid">${content.actions.map(([title,copy,icon,feature])=>`<button class="card action-card" data-feature="${feature}"><span class="action-icon">${icon}</span><strong>${escapeHtml(title)}</strong><p>${escapeHtml(copy)}</p></button>`).join('')}</div></section>${hasOperationalData?'':`<div class="build-state"><strong>${escapeHtml(storeName)}｜封閉 Pilot 建置狀態</strong><br>目前尚無可顯示的正式營運資料。系統不會載入 mock、seed 或 localStorage；請由 Owner／主管完成門市、成員與期初資料設定。</div>`}<section class="section">${emptyState('今天尚無正式待辦','完成正式門市與資料設定後，角色對應的工作會顯示在這裡。')}</section></main>`;
}
