import { escapeHtml, formalUiText } from '../components/layout.js';
import { daisyMark, icon } from '../components/icons.js';

const daisy = daisyMark;

function authShell(content, { identity = false } = {}) {
  return `<div class="admin-login-stage ${identity ? 'identity-stage' : ''}"><section class="admin-login-frame ${identity ? 'identity-frame' : ''}" aria-labelledby="admin-login-title">${identity ? '' : `<header class="admin-login-topbar"><span class="topbar-daisy">${daisy}</span><strong>PantryFlow</strong></header>`}${content}</section></div>`;
}

function backButton(view = 'identity', label = '返回登入首頁') { return `<button class="auth-back link" type="button" data-auth-view="${view}">‹ ${label}</button>`; }
function steps(active) { return `<div class="registration-steps" aria-label="建立新商家步驟">${['帳號','商家','門市','管理者'].map((label,index)=>`<span class="${index + 1 <= active ? 'active' : ''}"><b>${index + 1}</b><small>${label}</small></span>`).join('')}</div>`; }

function devicePolicySummary(context = {}, { staff = false } = {}) {
  const policy = context.devicePolicy || context;
  const authorized = policy.authorized === true;
  const remembered = authorized && policy.remember === true;
  const timeoutDays = Number(policy.timeoutDays);
  const credential = staff ? 'PIN' : '密碼';
  const device = staff ? (policy.deviceMode === 'SHARED' ? '店內共用裝置' : '個人裝置') : '管理裝置';
  const rule = remembered
    ? `${device}｜${timeoutDays === 0 ? `每次開啟需重新輸入${credential}` : `${[1,7,30].includes(timeoutDays) ? timeoutDays : 7} 天未使用需重新輸入 ${credential}`}`
    : `尚未由主管授權｜本次登入後不記住裝置`;
  return `<section class="device-policy-summary" aria-label="主管設定的裝置政策"><span aria-hidden="true">裝</span><div><strong>裝置政策由主管設定</strong><small>${escapeHtml(rule)}</small></div></section>`;
}

export function loginPage() {
  return authShell(`<div class="identity-content"><div class="brand-lockup"><span class="brand-glyph">${daisy}</span><span><strong>PantryFlow</strong><small>餐飲營運管理</small></span></div><div class="identity-heading"><h1 id="admin-login-title">歡迎回來</h1><p>選擇你的登入方式</p></div><div class="identity-list"><button class="identity-choice primary-choice" type="button" data-auth-view="employee-store"><span class="identity-icon">${icon('user')}</span><span><strong>員工快速登入</strong><small>門市、個人身分、6 位 PIN</small></span><b>${icon('arrowRight')}</b></button><button class="identity-choice" type="button" data-auth-view="manager"><span class="identity-icon">${icon('shield')}</span><span><strong>管理帳號登入</strong><small>店長、主管、後勤與 Owner</small></span><b>${icon('arrowRight')}</b></button></div><button class="new-business-link" type="button" data-auth-view="register">建立新商家</button></div>`, { identity: true });
}

export function managementLoginPage(context = {}) {
  return authShell(`<div class="admin-login-content">${backButton()}<div class="admin-login-heading"><h1 id="admin-login-title">管理帳號登入</h1><p>店長、主管、後勤與 Owner 使用同一入口，登入後依權限顯示內容。</p></div><form id="management-login" class="admin-login-form"><label class="field">Email<input name="email" type="email" autocomplete="username" value="${escapeHtml(context.email)}" placeholder="name@restaurant.com" required></label><label class="field">密碼<input name="password" type="password" autocomplete="current-password" placeholder="輸入密碼" required></label><div class="form-links"><button class="text-button" type="button" data-auth-view="forgot-password">忘記密碼？</button></div>${devicePolicySummary(context)}<p class="error admin-login-error" data-error aria-live="polite"></p><button class="primary" type="submit">登入</button></form></div>`);
}

export function employeeStorePage({ storeCode = '' } = {}) { return authShell(`<div class="admin-login-content employee-login-panel">${backButton()}<div class="admin-login-heading"><p class="eyebrow">員工快速登入 1／5</p><h1 id="admin-login-title">輸入門市代碼</h1><p>門市代碼由主管提供；裝置是否記住由主管統一設定。</p></div><form id="staff-store" class="admin-login-form"><label class="field">門市代碼<input name="storeCode" autocomplete="organization" value="${escapeHtml(storeCode)}" placeholder="例如 BEAPE01" pattern="[A-Za-z0-9][A-Za-z0-9_-]{1,31}" required autofocus></label><p class="error admin-login-error" data-error></p><button class="primary" type="submit">下一步</button></form></div>`); }

export function employeeStoreConfirmPage({ storeCode = '', storeName = '' } = {}) { const name = storeName || `門市代碼 ${storeCode}`;return authShell(`<div class="admin-login-content employee-login-panel">${backButton('employee-store','重新輸入')}<div class="admin-login-heading"><p class="eyebrow">員工快速登入 2／5</p><h1 id="admin-login-title">確認門市</h1><p>確認後再選擇你的員工身分。</p></div><article class="confirm-card store-confirm"><span aria-hidden="true">店</span><strong>${escapeHtml(name)}</strong><small>${escapeHtml(storeCode)}</small></article><button class="primary" type="button" data-confirm-store>這是我的門市</button></div>`); }

export function employeeIdentityPage({ storeCode = '', identifier = '', mode = 'NAME_OR_NICKNAME' } = {}) { const numberMode = mode === 'EMPLOYEE_NUMBER';return authShell(`<div class="admin-login-content employee-login-panel">${backButton('employee-store-confirm','返回門市確認')}<div class="admin-login-heading"><p class="eyebrow">員工快速登入 3／5</p><h1 id="admin-login-title">選擇員工身分</h1><p>登入方式由門市設定，員工不可自行切換。</p></div><form id="staff-identity" class="admin-login-form"><input name="storeCode" type="hidden" value="${escapeHtml(storeCode)}"><input name="mode" type="hidden" value="${escapeHtml(mode)}"><label class="field">${numberMode?'員工編號':'姓名／暱稱'}<input name="identifier" autocomplete="username" value="${escapeHtml(identifier)}" placeholder="${numberMode?'輸入員工編號':'輸入姓名或暱稱'}" required autofocus></label><p class="error admin-login-error" data-error></p><button class="primary" type="submit">下一步</button></form><div class="helper">員工身分由主管在「設定 → 員工與權限」建立</div></div>`); }

export function employeeIdentityConfirmPage(context = {}) { return authShell(`<div class="admin-login-content employee-login-panel">${backButton('employee-identity','修改身分')}<div class="admin-login-heading"><p class="eyebrow">員工快速登入 4／5</p><h1 id="admin-login-title">確認是你嗎？</h1><p>確認操作紀錄會綁定正確的個人身分。</p></div><article class="confirm-card identity-confirm"><span aria-hidden="true">人</span><strong>${escapeHtml(context.identifier)}</strong><small>${escapeHtml(context.storeName || context.storeCode)}｜員工</small></article><button class="primary" type="button" data-confirm-employee>確認身分</button><button class="link" type="button" data-auth-view="employee-identity">不是我</button></div>`); }

export function employeePinPage(context = {}) { return authShell(`<div class="admin-login-content employee-login-panel">${backButton('employee-confirm','返回身分確認')}<div class="admin-login-heading"><p class="eyebrow">員工快速登入 5／5</p><h1 id="admin-login-title">輸入 6 位 PIN</h1><p>${escapeHtml(context.identifier)}｜${escapeHtml(context.storeName || context.storeCode)}</p></div><form id="staff-pin-login" class="admin-login-form"><input name="storeCode" type="hidden" value="${escapeHtml(context.storeCode)}"><input name="identifier" type="hidden" value="${escapeHtml(context.identifier)}"><input name="loginMode" type="hidden" value="${escapeHtml(context.loginMode || context.mode || 'NAME_OR_NICKNAME')}"><label class="field">6 位 PIN<input class="pin-input" name="pin" type="password" inputmode="numeric" autocomplete="current-password" pattern="[0-9]{6}" maxlength="6" placeholder="••••••" required autofocus></label>${devicePolicySummary(context,{staff:true})}<p class="error admin-login-error" data-error></p><button class="primary" type="submit">進入今日工作</button></form><div class="helper lock-note">連續錯誤 5 次將鎖定 15 分鐘；忘記 PIN 請主管重設</div></div>`); }

export function registrationPage({ message = '', email = '' } = {}) { return authShell(`<div class="admin-login-content">${backButton()}${steps(1)}<div class="admin-login-heading"><h1 id="admin-login-title">建立管理帳號</h1><p>先建立個人帳號，再驗證 Email。</p></div>${message ? `<p class="success-message" role="status">${escapeHtml(message)}</p><div class="registration-next-step"><strong>驗證後怎麼繼續？</strong><p>點 Email 裡的驗證連結會自動回到 PantryFlow「建立商家」。如果這個 Email 已註冊，請直接用原密碼登入；忘記密碼可重新設定。</p></div><button class="primary full-button" type="button" data-auth-view="manager">我已完成驗證，登入並繼續</button><button class="text-button full-button" type="button" data-auth-view="forgot-password">收不到信／忘記密碼</button>` : `<div class="helper">建立新商家需使用尚未註冊 PantryFlow 的 Email；既有管理帳號請回登入頁。</div><form id="owner-registration" class="admin-login-form"><label class="field">姓名<input name="displayName" autocomplete="name" required maxlength="60"></label><label class="field">Email<input name="email" type="email" autocomplete="username" value="${escapeHtml(email)}" required></label><label class="field">密碼<input name="password" type="password" autocomplete="new-password" minlength="8" required></label><label class="field">再次輸入密碼<input name="passwordConfirm" type="password" autocomplete="new-password" minlength="8" required></label><p class="error admin-login-error" data-error></p><button class="primary" type="submit">寄送驗證信</button></form>`}</div>`); }

export function businessSetupPage(context = {}) { const erpEnabled = context.businessType === 'CHAIN_RESTAURANT';return authShell(`<div class="admin-login-content">${steps(2)}<div class="admin-login-heading"><p class="eyebrow">Email 已驗證</p><h1 id="admin-login-title">建立商家</h1><p>所有餐廳使用同一套功能，只需決定是否啟用 ERP 輔助。</p></div><form id="owner-business" class="admin-login-form"><label class="field">餐廳／品牌名稱<input name="organizationName" value="${escapeHtml(context.organizationName)}" required maxlength="80"></label><label class="field">所屬公司（可選；資料串接後開放）<input name="companyName" value="" maxlength="80" disabled aria-describedby="company-name-pending"></label><p class="helper" id="company-name-pending">目前資料庫尚無公司欄位，因此先停用，避免送出後未保存。</p><label class="field">公司 ERP 輔助<select name="businessType"><option value="SINGLE_RESTAURANT" ${erpEnabled?'':'selected'}>不啟用｜PantryFlow 獨立整理進貨資料</option><option value="CHAIN_RESTAURANT" ${erpEnabled?'selected':''}>啟用｜提醒驗收並保存現場差異</option></select></label><div class="business-mode-note"><span aria-hidden="true">✦</span><p>此選項只決定 ERP 輔助的預設值，不會切割盤點、進貨或匯出功能；PantryFlow 不取代公司 ERP。</p></div><p class="error admin-login-error" data-error></p><button class="primary" type="submit">下一步</button></form><button class="secondary full-button sign-out-button" data-sign-out type="button">登出</button></div>`); }

export function firstStoreSetupPage(context = {}) { const numberMode = context.loginMode === 'EMPLOYEE_NUMBER';return authShell(`<div class="admin-login-content">${backButton('business-setup','返回建立商家')}${steps(3)}<div class="admin-login-heading"><h1 id="admin-login-title">建立第一間門市</h1><p>門市代碼會提供員工首次登入使用。</p></div><form id="owner-store" class="admin-login-form"><label class="field">門市名稱<input name="storeName" value="${escapeHtml(context.storeName)}" required maxlength="80"></label><label class="field">門市代碼<input name="storeCode" value="${escapeHtml(context.storeCode)}" pattern="[A-Za-z0-9][A-Za-z0-9_-]{1,31}" placeholder="例如 BEAPE01" required></label><label class="field">員工登入方式<select name="loginMode"><option value="NAME_OR_NICKNAME" ${numberMode?'':'selected'}>姓名／暱稱</option><option value="EMPLOYEE_NUMBER" ${numberMode?'selected':''}>員工編號</option></select></label><p class="error admin-login-error" data-error></p><button class="primary" type="submit">下一步</button></form></div>`); }

export function firstManagerSetupPage(context = {}) { return authShell(`<div class="admin-login-content">${backButton('first-store','返回門市設定')}${steps(4)}<div class="admin-login-heading"><h1 id="admin-login-title">建立第一位管理者</h1><p>第一位管理者就是目前已驗證的帳號。</p></div><article class="confirm-card manager-confirm"><span aria-hidden="true">管</span><strong>${escapeHtml(context.displayName || '新管理者')}</strong><small>Owner／管理者</small></article><form id="owner-business-setup" class="admin-login-form"><p class="error admin-login-error" data-error></p><button class="primary" type="submit">完成設定</button></form><div class="helper">新增員工不會阻塞註冊；登入後可到「設定 → 員工與權限」處理。</div></div>`); }

export function ownerSetupPage(displayName = '') { return businessSetupPage({ displayName }); }
export function forgotPasswordPage({ sent = false } = {}) { return authShell(`<div class="admin-login-content">${backButton('manager','返回管理登入')}<div class="admin-login-heading"><h1 id="admin-login-title">忘記密碼</h1><p>輸入管理帳號 Email，我們會寄出重設連結。</p></div>${sent ? '<p class="success-message" role="status">如果此 Email 已有帳號，重設連結將寄到信箱。請查看收件匣與垃圾郵件。</p>' : `<form id="forgot-password" class="admin-login-form"><label class="field">Email<input name="email" type="email" autocomplete="username" required></label><p class="error admin-login-error" data-error></p><button class="primary" type="submit">寄送重設連結</button></form>`}</div>`); }
export function updatePasswordPage({ complete = false } = {}) { return authShell(`<div class="admin-login-content"><div class="admin-login-heading"><h1 id="admin-login-title">設定新密碼</h1><p>${complete ? '密碼已更新，請回登入頁重新登入。' : '請輸入新的管理帳號密碼。'}</p></div>${complete ? '<button class="primary" type="button" data-auth-view="identity">回登入頁</button>' : `<form id="update-password" class="admin-login-form"><label class="field">新密碼<input name="password" type="password" autocomplete="new-password" minlength="8" required></label><label class="field">再次輸入新密碼<input name="passwordConfirm" type="password" autocomplete="new-password" minlength="8" required></label><p class="error admin-login-error" data-error></p><button class="primary" type="submit">更新密碼</button></form>`}</div>`); }
export function storePickerPage(stores) { return authShell(`<div class="admin-login-content"><div class="admin-login-heading"><p class="eyebrow">已指派門市</p><h1 id="admin-login-title">選擇作業門市</h1><p>你的角色與資料權限會依門市切換。</p></div><div class="list">${stores.map(store => `<button class="secondary admin-store-choice" data-store="${store.id}"><strong>${escapeHtml(formalUiText(store.name,'門市'))}</strong><small>${escapeHtml(formalUiText(store.store_code,'門市代碼'))}｜${escapeHtml(store.role)}</small></button>`).join('')}</div></div>`); }
export function unassignedStorePage() { return authShell(`<div class="admin-login-content admin-empty-state"><span class="admin-empty-icon">!</span><div class="admin-login-heading"><h1 id="admin-login-title">尚未指派門市</h1><p>請聯絡商家 Owner 或管理者完成指派。</p></div><button class="secondary" data-sign-out type="button">登出</button></div>`); }
export function unavailableRolePage(role='') { const known=role==='OWNER'||role==='LOGISTICS';return authShell(`<div class="admin-login-content admin-empty-state"><span class="admin-empty-icon">!</span><div class="admin-login-heading"><h1 id="admin-login-title">${known?'此角色首頁尚未開放':'尚未指派角色／門市'}</h1><p>${known?'此帳號已有門市角色，但本版本不以其他角色首頁替代。':'請聯絡管理者確認門市權限。'}</p></div><button class="secondary" data-sign-out type="button">登出</button></div>`); }
