import{emptyState,escapeHtml}from'../components/layout.js';

const fieldLabels={subtotal_ex_tax:'未稅小計',tax:'稅額',total_inc_tax:'含稅總額',supplier_name:'供應商',document_number:'貨單號碼',invoice_number:'貨單號碼',receipt_date:'到貨日期',product:'品名',product_name:'品名',specification:'規格',quantity:'數量',unit:'單位',unit_price_ex_tax:'未稅單價',line_total_inc_tax:'含稅金額'};
const moneyFields=new Set(['subtotal_ex_tax','tax','total_inc_tax','unit_price_ex_tax','line_total_inc_tax']);
const statusLabels={UPLOADED:'等待辨識',PROCESSING:'識別中',READY_FOR_REVIEW:'待後勤核對',REVIEWING:'核對中',COMPLETED:'已完成',FAILED:'識別失敗'};

function roleKind(role){if(role==='LOGISTICS')return'logistics';if(role==='OWNER')return'owner';if(role==='ADMIN'||role==='SUPERVISOR')return'manager';return'staff'}
function roleIntro(label,copy){return `<div class="count-role-intro receiving-role-intro"><span>${escapeHtml(label)}</span><small>${escapeHtml(copy)}</small></div>`}
function statusLabel(value){return statusLabels[value]||value||'等待處理'}
function displayStatus(batch){return batch.ui_status||batch.status}
function statusCount(batches,status){return batches.filter(item=>displayStatus(item)===status).length}
function receiptRows(batches,{emptyTitle='尚無進貨紀錄',emptyCopy='拍攝或上傳貨單後，處理狀態會顯示在這裡。'}={}){
  if(!batches.length)return emptyState(emptyTitle,emptyCopy);
  return `<div class="list receiving-batch-list">${batches.map(batch=>`<button class="card receipt-row" data-open-receipt="${escapeHtml(batch.id)}" type="button"><span><strong>${escapeHtml(batch.batch_number)}</strong><small>${escapeHtml(batch.work_date||'')}・${batch.receipt_documents?.length||0} 張原圖</small></span><span class="status receipt-status status-${escapeHtml(String(displayStatus(batch)||'').toLowerCase())}">${escapeHtml(statusLabel(displayStatus(batch)))}</span></button>`).join('')}</div>`;
}
function receivingStats(batches){return `<div class="count-stat-grid receiving-stats"><div><strong>${batches.length}</strong><small>今日到貨</small></div><div><strong>${statusCount(batches,'READY_FOR_REVIEW')+statusCount(batches,'REVIEWING')}</strong><small>待核對</small></div><div><strong>${statusCount(batches,'FAILED')}</strong><small>異常待確認</small></div></div>`}
function captureCard(){
  return `<section class="card receiving-capture-card"><div class="receiving-card-heading"><span>▤</span><div><h2>拍攝到貨單</h2><p>員工與店長都可上傳；辨識後再依品項確認實收與差異。</p></div></div><form id="receipt-upload"><fieldset class="receipt-group-mode"><legend>這批照片屬於</legend><label><input type="radio" name="documentMode" value="SAME_RECEIPT" checked><span><strong>同一張貨單</strong><small>多頁或多角度</small></span></label><label><input type="radio" name="documentMode" value="SEPARATE_RECEIPTS"><span><strong>不同貨單</strong><small>每張各自辨識</small></span></label></fieldset><label class="secondary file-button receiving-file-button">拍攝／選擇多張照片<input name="files" data-receipt-files type="file" accept="image/*,application/pdf" multiple required hidden></label><p class="receiving-upload-limit">最多 10 張，可連續拍攝或從相簿多選。</p><div class="receipt-photo-preview" data-receipt-photo-preview></div><div class="duplicate-warning" data-receipt-duplicate-warning hidden></div><button class="primary" type="submit">上傳並開始辨識</button><p class="error" data-error></p></form></section>`;
}
function modeNotice({settings={},role}){
  if(settings.erp_assist_enabled)return `<section class="receiving-mode-notice"><strong>ERP 輔助已啟用</strong><p>PantryFlow 保存現場點貨證據、少送／多送回報，並於 ${escapeHtml(settings.erp_reminder_time||'17:00')} 提醒門市確認 ERP 驗收；不直接修改或取代 ERP。</p>${role==='ADMIN'||role==='SUPERVISOR'?'<button class="text-button" data-feature="profile" type="button">調整 ERP 驗收提醒</button>':''}</section>`;
  return `<section class="receiving-mode-notice"><strong>PantryFlow 進貨紀錄</strong><p>辨識、實收與差異會整理成營運資料；金額僅供庫存與營運分析，不作為報稅或會計帳。</p>${role==='ADMIN'||role==='SUPERVISOR'?'<button class="text-button" data-feature="profile" type="button">啟用 ERP 輔助</button>':''}</section>`;
}
function capturePage({batches,detail,settings,role}){
  const manager=role==='ADMIN'||role==='SUPERVISOR';
  return `${roleIntro(manager?'店長／主管':'員工',manager?'現場驗收、差異與數據管理':'拍貨單、點貨與即時回報')}<div class="count-heading"><div><h1 class="page-title">今日到貨驗收</h1><p>識別速度與精確度優先，原圖永遠保留</p></div><span class="count-icon">▤</span></div>${receivingStats(batches)}${modeNotice({settings,role})}${detail?receiptDetail(detail,{canCorrect:manager,canConfirmSite:true}):captureCard()}<section class="section"><div class="section-head"><h2>今日進度</h2><span>識別中 → 現場確認 → 資料核對</span></div>${receiptRows(batches)}</section>`;
}
function reviewField(field,corrections,batchId){
  const corrected=corrections.find(item=>item.ocr_field_id===field.id),shown=corrected?.new_value??field.normalized_value??field.raw_value??'',oldValue=field.normalized_value??field.raw_value??null;
  return `<form data-correct-receipt-field="${escapeHtml(field.id)}" data-batch="${escapeHtml(batchId)}" class="review-field"><label class="field">${escapeHtml(fieldLabels[field.field_name]||field.field_name)}<input name="value" value="${escapeHtml(typeof shown==='object'?JSON.stringify(shown):shown)}"><input name="oldValue" type="hidden" value="${escapeHtml(JSON.stringify(oldValue))}"></label><small>AI 原值：${escapeHtml(JSON.stringify(field.raw_value??null))}・${escapeHtml(field.review_status||'待判定')}</small><button class="secondary">保存人工修正</button><p class="error" data-error></p></form>`;
}
function lineReviewStatus(fields){if(fields.some(field=>field.review_status==='UNREADABLE'))return'有欄位無法判讀';if(fields.some(field=>field.review_status==='REVIEW'))return'需要核對';return'辨識清楚'}
function groupLineFields(fields){const rows=new Map;for(const field of fields){if(field.row_key==='document')continue;if(!rows.has(field.row_key))rows.set(field.row_key,[]);rows.get(field.row_key).push(field)}return[...rows.entries()].sort(([a],[b])=>String(a).localeCompare(String(b),undefined,{numeric:true})).map(([rowKey,rowFields])=>({rowKey,fields:rowFields}))}
function shownValue(field,corrections){if(!field)return'—';const corrected=corrections.find(item=>item.ocr_field_id===field.id);return corrected?.new_value??field.normalized_value??field.raw_value??'—'}
function receiptLine(row,corrections,siteChecks,batchId,ocrRunId,{canCorrect=false,canConfirmSite=false}={}){
  const byName=name=>row.fields.find(field=>field.field_name===name),product=byName('product')||byName('product_name'),quantity=shownValue(byName('quantity'),corrections),unit=shownValue(byName('unit'),corrections),price=shownValue(byName('unit_price_ex_tax'),corrections),subtotal=shownValue(byName('subtotal_ex_tax'),corrections);
  const latestCheck=siteChecks.find(item=>item.row_key===row.rowKey),checkLabel={MATCH:'數量相符',SHORT:'少送',OVER:'多送',NOT_DELIVERED:'未送',WRONG_ITEM:'送錯品項'}[latestCheck?.discrepancy];
  return `<article class="receipt-line-card"><header><span>第 ${escapeHtml(row.rowKey)} 項</span><strong>${escapeHtml(lineReviewStatus(row.fields))}</strong></header><h4>${escapeHtml(shownValue(product,corrections))}</h4><div class="receipt-line-summary"><span>貨單數量 <b>${escapeHtml(quantity)} ${escapeHtml(unit)}</b></span><span>未稅單價 <b>${escapeHtml(price)} TWD</b></span><span>未稅小計 <b>${escapeHtml(subtotal)} TWD</b></span></div>${latestCheck?`<div class="site-check-result"><strong>${escapeHtml(checkLabel||latestCheck.discrepancy)}</strong><span>實收 ${escapeHtml(latestCheck.received_quantity)} ${escapeHtml(latestCheck.unit||unit)}</span><small>${escapeHtml(latestCheck.note||'已保存現場確認紀錄')}</small></div>`:''}${canConfirmSite?`<form data-receipt-site-check="${escapeHtml(batchId)}" class="site-check-form"><input type="hidden" name="ocrRunId" value="${escapeHtml(ocrRunId||'')}"><input type="hidden" name="rowKey" value="${escapeHtml(row.rowKey)}"><input type="hidden" name="orderedQuantity" value="${escapeHtml(quantity)}"><input type="hidden" name="unit" value="${escapeHtml(unit)}"><label class="field">實收數量<input name="receivedQuantity" type="number" min="0" step="0.001" value="${escapeHtml(latestCheck?.received_quantity??quantity)}" required></label><label class="field">到貨狀況<select name="discrepancy" required><option value="MATCH">數量相符</option><option value="SHORT">少送</option><option value="OVER">多送</option><option value="NOT_DELIVERED">未送</option><option value="WRONG_ITEM">送錯品項</option></select></label><label class="field">備註（選填）<input name="note" maxlength="200" placeholder="例如：少送 1 箱，已通知供應商"></label><button class="secondary">保存現場確認</button><p class="error" data-error></p></form>`:''}${canCorrect?`<details><summary>修正這筆辨識</summary>${row.fields.map(field=>reviewField(field,corrections,batchId)).join('')}</details>`:''}</article>`;
}
function receiptDetail({batch,documents=[],runs=[],fields=[],corrections=[],siteChecks=[]},{canCorrect=false,canConfirmSite=false}={}){
  const latest=runs[0],latestFields=latest?fields.filter(field=>field.ocr_run_id===latest.id):[],documentFields=latestFields.filter(field=>field.row_key==='document'),priority=['supplier_name','document_number','invoice_number','receipt_date','subtotal_ex_tax','tax','total_inc_tax'],reviewFields=priority.map(name=>documentFields.find(field=>field.field_name===name)).filter(Boolean),lineRows=groupLineFields(latestFields);
  return `<section class="section receipt-detail"><div class="section-head"><h2>${canCorrect?'進貨資料與現場驗收':'進貨憑證'}｜${escapeHtml(batch.batch_number)}</h2><span>${escapeHtml(statusLabel(displayStatus(batch)||latest?.status))}</span></div><div class="receipt-evidence-note"><strong>完整證據鏈</strong><p>保留原始照片、AI 原值、人工修正、實收差異、操作人與時間；原始結果不可覆蓋。</p></div><div class="receipt-review-grid"><div class="card receipt-images">${documents.map(document=>document.signedUrl&&document.mime_type.startsWith('image/')?`<figure><img src="${escapeHtml(document.signedUrl)}" alt="${escapeHtml(document.original_filename)}"><figcaption>原始第 ${document.page_order} 頁｜${escapeHtml(document.original_filename)}</figcaption></figure>`:`<a class="secondary" href="${escapeHtml(document.signedUrl||'#')}" target="_blank" rel="noreferrer">開啟原始檔 ${document.page_order}</a>`).join('')}</div><div class="card settings-card receipt-fields"><h3>辨識結果 ${latest?`v${latest.version}`:'尚未建立'}</h3>${latest?`<p class="muted">${escapeHtml(latest.provider)}／${escapeHtml(latest.model)}・${escapeHtml(statusLabel(latest.status))}</p>`:''}<div class="receipt-currency"><span>幣別</span><strong>TWD／新台幣</strong></div>${reviewFields.length?reviewFields.map(field=>canCorrect?reviewField(field,corrections,batch.id):`<div class="receipt-readonly-field"><span>${escapeHtml(fieldLabels[field.field_name]||field.field_name)}</span><strong>${escapeHtml(shownValue(field,corrections))}${moneyFields.has(field.field_name)?' TWD':''}</strong></div>`).join(''):`<div class="helper">${latest?.status==='FAILED'?`辨識失敗：${escapeHtml(latest.error_message||'可保留原圖後重新辨識。')}`:'正在背景辨識，通常數十秒內完成。'}</div>`}<p class="receipt-tax-note">未稅小計、稅額、含稅總額分開保存；固定以 TWD／新台幣顯示，不會把單筆小計當成整張貨單總額。</p><section class="receipt-lines"><div class="section-head"><h3>辨識品項與實收</h3><span>${lineRows.length} 項</span></div>${lineRows.length?lineRows.map(row=>receiptLine(row,corrections,siteChecks,batch.id,latest?.id,{canCorrect,canConfirmSite})).join(''):'<div class="receipt-lines-empty"><strong>沒有辨識到品名</strong><p>請保留原圖並重新辨識；不得把只有表頭的結果當成完整進貨資料。</p></div>'}</section><div class="button-row"><button class="secondary" data-refresh-receipt="${escapeHtml(batch.id)}" type="button">重新整理狀態</button>${latest?.status==='FAILED'||latest&&!lineRows.length?`<button class="primary" data-retry-receipt="${escapeHtml(batch.id)}" type="button">重新辨識</button>`:''}</div><p class="error" data-receipt-action-error></p></div></div></section>`;
}
function logisticsPage({batches,detail,settings}){
  const pending=batches.filter(batch=>displayStatus(batch)!=='COMPLETED');
  return `${roleIntro('後勤','整理、修正與發布正式進貨資料')}<div class="count-heading"><div><h1 class="page-title">進貨資料核對</h1><p>只有完成核對資料會進入正式統計</p></div><span class="count-icon count-icon-blue">▥</span></div><div class="count-stat-grid receiving-stats"><div><strong>${statusCount(batches,'PROCESSING')}</strong><small>識別中</small></div><div><strong>${statusCount(batches,'READY_FOR_REVIEW')+statusCount(batches,'REVIEWING')}</strong><small>待核對</small></div><div><strong>${statusCount(batches,'COMPLETED')}</strong><small>已完成</small></div></div>${modeNotice({settings,role:'LOGISTICS'})}${detail?receiptDetail(detail,{canCorrect:true}):`<section class="section"><div class="section-head"><h2>待核對資料</h2><span>${pending.length} 批</span></div>${receiptRows(pending,{emptyTitle:'目前沒有待核對資料',emptyCopy:'現場上傳並完成辨識後會出現在這裡。'})}</section>`}<section class="receiving-policy-note"><strong>單位與幣別</strong><p>保留貨單原始單位；金額固定以 TWD 顯示。只有既有明確換算規則時才產生標準化數量。</p></section>`;
}
function ownerPage({batches,settings}){
  const published=batches.filter(batch=>displayStatus(batch)==='COMPLETED');
  return `${roleIntro('Owner／營運主管','看發布後的總結、重大異常與稽查')}<div class="count-heading"><div><h1 class="page-title">進貨管理摘要</h1><p>不進入後勤逐張修整工作台</p></div><span class="count-icon">▥</span></div><div class="count-stat-grid receiving-stats"><div><strong>${published.length}</strong><small>已發布批次</small></div><div><strong>${statusCount(batches,'FAILED')}</strong><small>重大異常</small></div><div><strong>${batches.length-published.length}</strong><small>尚未發布</small></div></div>${modeNotice({settings,role:'OWNER'})}<section class="section"><div class="section-head"><h2>主管查看範圍</h2><span>已發布資料・TWD</span></div><div class="card count-work-list"><button type="button"><span class="count-row-icon purple">▥</span><span><strong>供應商與品項趨勢</strong><small>最新／平均單價、分類與進貨總額</small></span><b>›</b></button><button type="button"><span class="count-row-icon purple">!</span><span><strong>少送／多送與重大異常</strong><small>門市確認結果與後勤整理結論</small></span><b>›</b></button><button type="button"><span class="count-row-icon purple">✓</span><span><strong>驗收稽查</strong><small>原圖、修正紀錄、發布人與時間</small></span><b>›</b></button></div></section>`;
}
export function receivingPage({batches=[],detail=null},{role='STAFF',workflowSettings:settings={}}={}){
  const kind=roleKind(role);
  if(kind==='logistics')return logisticsPage({batches,detail,settings});
  if(kind==='owner')return ownerPage({batches,settings});
  return capturePage({batches,detail,settings,role});
}
