import{backButton,emptyState,escapeHtml}from'../components/layout.js';

export function catalogPage({products=[]}){
  return `${backButton()}<h2 class="page-title">商品建檔</h2><p class="muted">資料直接寫入正式 Supabase catalog；期初數量建立後不可覆蓋。</p>
  <section class="card settings-card"><h3>手動建立商品</h3><form id="create-product" class="form-grid two">
    <label class="field">商品名稱<input name="name" required maxlength="80"></label>
    <label class="field">商品編碼<input name="productCode" required maxlength="40"></label>
    <label class="field">盤點單位<input name="countUnit" required placeholder="例如：公斤"></label>
    <label class="field">進貨單位<input name="purchaseUnit" required placeholder="例如：箱"></label>
    <label class="field">正式期初數量<input name="openingQuantity" type="number" min="0" step="0.001" required></label>
    <div><button class="primary" type="submit">建立正式商品</button></div><p class="error" data-error></p>
  </form></section>
  <section class="section"><div class="section-head"><h2>Excel／CSV 匯入</h2></div><article class="card settings-card"><p class="muted">請到盤點設定選檔、預覽並確認寫入；不在商品頁保留第二套匯入流程。</p><div class="button-row"><button class="secondary" type="button" data-download-catalog-template>下載 CSV 相容範本</button><button class="primary" type="button" data-route="count">前往盤點設定匯入</button></div></article></section>
  <section class="section"><div class="section-head"><h2>正式商品</h2><span>${products.length} 項</span></div>${products.length?`<div class="list">${products.map(p=>`<article class="card setup-row"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.product_code)} · ${escapeHtml(p.count_unit)}／進貨 ${escapeHtml(p.base_unit)}</small></div><span class="status">已啟用</span></article>`).join('')}</div>`:emptyState('尚無商品','請先手動建立一項商品，或使用固定範本匯入。')}</section>`;
}
export function zonesPage({zones=[],products=[],assignments=[]}){
  return `${backButton()}<h2 class="page-title">區域與商品</h2><p class="muted">先建立現場盤點區域，再把正式商品加入區域。</p>
  <section class="card settings-card"><h3>建立區域</h3><form id="create-zone" class="form-grid"><label class="field">區域名稱<input name="name" required maxlength="60" placeholder="例如：冷藏庫"></label><button class="primary" type="submit">建立區域</button><p class="error" data-error></p></form></section>
  <section class="section"><div class="section-head"><h2>區域設定</h2><span>${zones.length} 區</span></div>${zones.length?`<div class="list">${zones.map((z,index)=>{const ids=assignments.filter(a=>a.zone_id===z.id).map(a=>a.product_id),assigned=products.filter(p=>ids.includes(p.id));return `<article class="card settings-card zone-settings-card"><div class="section-head"><h3>${escapeHtml(z.name)}</h3><div class="button-row compact"><button class="text-button" data-move-zone="${z.id}" data-direction="up" ${index===0?'disabled':''}>上移</button><button class="text-button" data-move-zone="${z.id}" data-direction="down" ${index===zones.length-1?'disabled':''}>下移</button></div></div><form data-rename-zone="${z.id}" class="inline-form"><input name="name" value="${escapeHtml(z.name)}" maxlength="60" required><button class="secondary">重新命名</button><p class="error" data-error></p></form><div class="zone-product-list">${assigned.length?assigned.map(p=>`<div><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.product_code)}・${escapeHtml(p.count_unit||'')}</small></span><button class="text-button danger" data-unassign-product="${p.id}" data-zone="${z.id}" type="button">移除</button></div>`).join(''):'<p class="muted">尚未加入商品</p>'}</div>${products.length?`<form data-assign-product="${z.id}" class="inline-form"><select name="productId" required><option value="">選擇商品</option>${products.filter(p=>!ids.includes(p.id)).map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('')}</select><button class="secondary">加入區域</button><p class="error" data-error></p></form>`:'<p class="error">請先建立商品。</p>'}<button class="text-button danger zone-deactivate" data-deactivate-zone="${z.id}" type="button">停用此區域</button></article>`}).join('')}</div>`:emptyState('尚無盤點區域','建立第一個區域後，再將商品加入。')}</section>`;
}
