import{backButton,emptyState,escapeHtml,formalUiText}from'../components/layout.js';

function staffManager({store,staff,canCreateSupervisor,currentUserId}){
  const needsEmployeeNumber=store.staff_login_mode==='EMPLOYEE_NUMBER';
  return `<section class="section"><div class="section-head"><h2>門市成員</h2><span>${escapeHtml(formalUiText(store.name,'門市'))}</span></div><div class="card member-list">${staff.length?staff.map(item=>{const person=item.identity||{},manageable=item.user_id!==currentUserId&&item.is_active&&person.is_active!==false;return `<article class="member-row"><div><strong>${escapeHtml(formalUiText(person.display_name||item.login_identifier,'成員'))}</strong><small>${escapeHtml(formalUiText(person.nickname||person.employee_number||person.job_title||item.login_identifier,'成員資料'))}｜${escapeHtml(item.role)}</small></div><span class="status">${item.is_active&&person.is_active!==false?'啟用':'停用'}</span>${manageable?`<form class="inline-pin-form" data-reset-pin="${item.user_id}"><input name="pin" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="新 6 位 PIN" required><button class="secondary" type="submit">重設</button><p class="error" data-error></p></form><button class="text-button danger-text" data-disable-staff="${item.user_id}" type="button">停用</button>`:''}</article>`}).join(''):'<div class="empty compact-empty">尚無正式員工。請由主管建立第一位員工。</div>'}</div></section>
  <section class="section card settings-card"><div class="section-head"><h2>建立員工</h2><span>正式 Supabase</span></div><form id="create-staff"><input name="storeId" type="hidden" value="${escapeHtml(store.id)}"><div class="form-grid two"><label class="field">姓名<input name="displayName" required></label><label class="field">暱稱<input name="nickname"></label></div><div class="form-grid two"><label class="field">職稱<input name="jobTitle"></label><label class="field">員工編號<input name="employeeNumber" ${needsEmployeeNumber?'required':''}></label></div><label class="field">門市角色<select name="role"><option value="STAFF">員工</option>${canCreateSupervisor?'<option value="SUPERVISOR">主管／店長</option>':''}</select></label><label class="field">6 位個人 PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></label><p class="error" data-error></p><button class="primary" type="submit">建立正式員工身分</button></form><div class="helper">員工不會收到 Email 註冊入口；每人仍有獨立 Auth 身分、門市 membership 與 audit log。</div></section>`;
}

export function utilityPage(page,{canManage=false,store=null,staff=[],isOwner=false,currentUserId=''}={}){
  const labels={activity:['作業紀錄','尚無目前門市的正式紀錄。'],scan:['掃描','請從已開放的作業入口啟動掃描。'],notifications:['通知','目前沒有正式待處理通知。'],profile:['我的','帳號、門市與角色資料來自 Supabase Auth 與 memberships。'],waste:['廢棄','此作業尚未開放。'],expiry:['效期巡檢','此作業尚未開放。'],other:['其他作業','此作業尚未開放。']};
  const [title,copy]=labels[page];
  const storeForm=page==='profile'&&canManage?`<section class="section card settings-card"><div class="section-head"><h2>新增正式門市</h2><span>Owner／管理者</span></div><form id="create-store"><label class="field">門市名稱<input name="name" required></label><label class="field">門市代碼<input name="storeCode" pattern="[A-Za-z0-9][A-Za-z0-9_-]{1,31}" required></label><label class="field">員工登入方式<select name="loginMode"><option value="NAME_OR_NICKNAME">姓名／暱稱＋6 位 PIN</option><option value="EMPLOYEE_NUMBER">員工編號＋6 位 PIN</option></select></label><p class="error" data-error></p><button class="primary" type="submit">建立門市</button></form></section>`:'';
  return `${backButton()}<h1 class="page-title">${title}</h1>${emptyState(title,copy)}${page==='profile'&&canManage&&store?staffManager({store,staff,canCreateSupervisor:isOwner||store.role==='ADMIN',currentUserId}):''}${storeForm}${page==='profile'?'<button class="secondary sign-out-button" data-sign-out>登出</button>':''}`;
}
