import{backButton,emptyState,escapeHtml,formalUiText}from'../components/layout.js';

function devicePolicyManager(){return `<section class="section card settings-card device-policy-manager"><div class="section-head"><h2>登入與裝置</h2><span>Owner／主管</span></div><label class="check-row"><input type="checkbox" checked disabled><span><strong>允許記住已授權裝置</strong><small>登入者不能自行修改</small></span></label><label class="field">未使用多久重新驗證<select disabled><option>7 天（預設）</option></select></label><div class="form-grid two"><label class="field">此裝置類型<select disabled><option>個人裝置</option><option>店內共用裝置</option></select></label><label class="field">授權狀態<input value="等待主管授權" disabled></label></div><button class="primary" type="button" disabled>儲存裝置政策</button><div class="helper">裝置授權功能尚未啟用；啟用前，新裝置登入後不會被記住。</div></section>`}

function staffManager({store,staff,canCreateSupervisor,currentUserId}){
  const needsEmployeeNumber=store.staff_login_mode==='EMPLOYEE_NUMBER';
  return `<section class="section"><div class="section-head"><h2>員工與權限</h2><span>${escapeHtml(formalUiText(store.name,'門市'))}</span></div><div class="card member-list">${staff.length?staff.map(item=>{const person=item.identity||{},manageable=item.user_id!==currentUserId&&item.is_active&&person.is_active!==false;return `<article class="member-row"><div><strong>${escapeHtml(formalUiText(person.display_name||item.login_identifier,'成員'))}</strong><small>${escapeHtml(formalUiText(person.nickname||person.employee_number||person.job_title||item.login_identifier,'成員資料'))}｜${escapeHtml(item.role)}</small></div><span class="status">${item.is_active&&person.is_active!==false?'啟用':'停用'}</span>${manageable?`<form class="inline-pin-form" data-reset-pin="${item.user_id}"><input name="pin" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="新 6 位 PIN" required><button class="secondary" type="submit">重設</button><p class="error" data-error></p></form><button class="text-button danger-text" data-disable-staff="${item.user_id}" type="button">停用</button>`:''}</article>`}).join(''):'<div class="empty compact-empty">尚未建立員工，可現在新增或稍後設定。</div>'}</div></section>
  <section class="section card settings-card"><div class="section-head"><h2>新增員工</h2><span>設定</span></div><form id="create-staff"><input name="storeId" type="hidden" value="${escapeHtml(store.id)}"><div class="form-grid two"><label class="field">姓名<input name="displayName" required></label><label class="field">暱稱<input name="nickname"></label></div><div class="form-grid two"><label class="field">職稱<input name="jobTitle"></label><label class="field">員工編號<input name="employeeNumber" ${needsEmployeeNumber?'required':''}></label></div><label class="field">門市角色<select name="role"><option value="STAFF">員工</option>${canCreateSupervisor?'<option value="SUPERVISOR">主管／店長</option>':''}</select></label><label class="field">6 位個人 PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></label><p class="error" data-error></p><button class="primary" type="submit">新增員工</button></form><div class="helper">員工不自行註冊 Email；每人仍有獨立身分、門市權限與操作紀錄。</div></section>`;
}

export function utilityPage(page,{canManage=false,store=null,staff=[],isOwner=false,currentUserId='',role='STAFF'}={}){
  const taskCopy={STAFF:'整理你尚未完成的今日工作。',ADMIN:'整理需要主管處理的異常與確認事項。',SUPERVISOR:'整理需要主管處理的異常與確認事項。',LOGISTICS:'整理後勤待核對的資料與作業。',OWNER:'整理需要決策或確認的管理事項。'}[role]||'整理目前尚未完成的工作。';
  const labels={activity:['作業紀錄','尚無目前門市的正式紀錄。'],tasks:['待辦',taskCopy],notifications:['通知','目前沒有正式待處理通知。'],profile:['設定','管理帳號、門市、員工與角色權限。'],waste:['廢棄','此作業尚未開放。'],expiry:['效期巡檢','此作業尚未開放。'],other:['其他作業','此作業尚未開放。']};
  const [title,copy]=labels[page];
  const storeForm=page==='profile'&&canManage?`<section class="section card settings-card"><div class="section-head"><h2>新增正式門市</h2><span>Owner／管理者</span></div><form id="create-store"><label class="field">門市名稱<input name="name" required></label><label class="field">門市代碼<input name="storeCode" pattern="[A-Za-z0-9][A-Za-z0-9_-]{1,31}" required></label><label class="field">員工登入方式<select name="loginMode"><option value="NAME_OR_NICKNAME">姓名／暱稱＋6 位 PIN</option><option value="EMPLOYEE_NUMBER">員工編號＋6 位 PIN</option></select></label><p class="error" data-error></p><button class="primary" type="submit">建立門市</button></form></section>`:'';
  return `${backButton()}<h1 class="page-title">${title}</h1>${emptyState(title,copy)}${page==='profile'&&canManage?devicePolicyManager():''}${page==='profile'&&canManage&&store?staffManager({store,staff,canCreateSupervisor:isOwner||store.role==='ADMIN',currentUserId}):''}${storeForm}${page==='profile'?'<button class="secondary sign-out-button" data-sign-out>登出</button>':''}`;
}
