-- Preserve the same role-based field visibility when reading inactive-store receipts.
create or replace function private.store_archive(s uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare role text:=private.store_scope_role(s);org public.organizations;begin
 if role is null and not private.can_manage_store_scope(s) then raise exception 'APP_FORBIDDEN' using errcode='42501';end if;
 select o.* into org from public.organizations o join public.stores st on st.organization_id=o.id where st.id=s;
 return jsonb_build_object('role',coalesce(role,'OWNER'),'store',(select to_jsonb(st) from public.stores st where st.id=s),'can_settle',role in ('STAFF','SUPERVISOR'),'counts',
 (select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'status',c.status,'started_at',c.started_at,'completed_at',c.completed_at,'lines',(select coalesce(jsonb_agg(jsonb_build_object('name',coalesce(item->>'product_name',item->>'name','未提供'),'quantity',e.quantity,'unit',e.unit,'zone',item->>'zone_name')),'[]') from public.count_entries e left join lateral(select item from jsonb_array_elements(coalesce(c.snapshot->'zones','[]')) item where item->>'product_id'=e.product_id::text and item->>'zone_id'=e.zone_id::text limit 1) snap on true where e.session_id=c.id)) order by c.started_at desc),'[]') from public.inventory_count_sessions c where c.store_id=s),
 'receipts',(select coalesce(jsonb_agg(jsonb_build_object('id',b.id,'name',b.batch_number,'status',b.status,'created_at',b.uploaded_at,'lines',(select coalesce(jsonb_agg(jsonb_build_object('name',coalesce(l.human_correction#>>'{effective_fields,product}',l.ai_original->>'raw_product_name','未對應'),'quantity',l.quantity,'unit',l.unit) order by l.created_at,l.source_row_key),'[]') from public.goods_receipts g join public.receipt_lines l on l.receipt_id=g.id where g.source_batch_id=b.id and g.store_id=s),'fields',(select coalesce(jsonb_agg(jsonb_build_object('row_key',f.row_key,'field_name',f.field_name,'value',coalesce((select c.new_value from public.receipt_review_corrections c where c.ocr_field_id=f.id order by c.modified_at desc limit 1),f.normalized_value)) order by f.row_key,f.field_name),'[]') from public.receipt_ocr_fields f where f.batch_id=b.id and (role<>'STAFF' and org.business_type::text='SINGLE_RESTAURANT' or f.field_name in ('product','raw_product_name','supplier_name','receipt_date','document_number','quantity','unit','specification')))) order by b.uploaded_at desc),'[]') from public.receipt_upload_batches b where b.store_id=s and (role<>'STAFF' or b.uploaded_by=auth.uid())),
 'expiry',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'name',e.name,'expires_on',e.expires_on,'zone',e.zone_name,'resolved',exists(select 1 from private.expiry_resolutions er where er.expiry_id=e.id)) order by e.expires_on),'[]') from private.expiry_current e where e.store_id=s),
 'waste',(select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'name',w.name,'quantity',w.quantity,'unit',w.unit,'reason',w.reason,'created_at',w.created_at,'actor_name',w.actor_name) order by w.created_at desc),'[]') from private.waste_records w where w.store_id=s),
 'movements',(select coalesce(jsonb_agg(to_jsonb(m)||jsonb_build_object('from_name',fs.name,'to_name',ts.name,'actor_name',p.display_name,'events',(select coalesce(jsonb_agg(to_jsonb(e)||jsonb_build_object('actor_name',ep.display_name) order by e.created_at),'[]') from private.store_movement_events e left join public.profiles ep on ep.id=e.actor_id where e.movement_id=m.id)) order by m.created_at desc),'[]') from private.store_movements m join public.stores fs on fs.id=m.from_store_id join public.stores ts on ts.id=m.to_store_id left join public.profiles p on p.id=m.created_by where s in (m.from_store_id,m.to_store_id)));
end $$;
