import{db}from'./supabase.js';
export async function signIn(email,password){const{data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;return data.session}
export async function signUpOwner(displayName,email,password){const{data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}${location.pathname}`,data:{display_name:displayName,account_type:'OWNER_REGISTRATION'}}});if(error)throw error;return data}
export async function requestPasswordReset(email){const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}${location.pathname}`});if(error)throw error}
export async function updatePassword(password){const{data,error}=await db.auth.updateUser({password});if(error)throw error;return data.user}
export function listenAuthChanges(handler){return db.auth.onAuthStateChange((event,currentSession)=>handler(event,currentSession))}
export async function staffPinLogin(storeCode,identifier,pin){const{data,error}=await db.functions.invoke('staff-pin-login',{body:{storeCode,identifier,pin}});if(error||!data?.session)throw new Error(data?.error||'STAFF_LOGIN_FAILED');const result=await db.auth.setSession({access_token:data.session.access_token,refresh_token:data.session.refresh_token});if(result.error)throw result.error;return data.storeId}
export async function signOut(){const{error}=await db.auth.signOut();if(error)throw error}
export async function profile(userId){const{data,error}=await db.from('profiles').select('id,organization_id,display_name,role').eq('id',userId).single();if(error)throw error;if(data.organization_id){const[member,organization]=await Promise.all([db.from('organization_members').select('is_owner').eq('organization_id',data.organization_id).eq('user_id',userId).single(),db.from('organizations').select('business_type').eq('id',data.organization_id).single()]);if(member.error)throw member.error;if(organization.error)throw organization.error;data.is_owner=Boolean(member.data?.is_owner);data.business_type=organization.data?.business_type||'SINGLE_RESTAURANT'}return data}
export async function createOwnerBusiness(input){const{data,error}=await db.rpc('create_owner_business',{p_organization_name:input.organizationName,p_business_type:input.businessType,p_store_name:input.storeName,p_store_code:input.storeCode,p_staff_login_mode:input.loginMode});if(error)throw error;return data}
export async function createStore(input){const{data,error}=await db.functions.invoke('manage-staff',{body:{action:'create_store',name:input.name,storeCode:input.storeCode,loginMode:input.loginMode,isPilotStore:true}});if(error||data?.error)throw new Error(data?.error||'STORE_CREATE_FAILED');return data}
export async function createStaff(input){const{data,error}=await db.functions.invoke('manage-staff',{body:{action:'create',storeId:input.storeId,displayName:input.displayName,nickname:input.nickname||null,jobTitle:input.jobTitle||null,employeeNumber:input.employeeNumber||null,role:input.role||'STAFF',pin:input.pin}});if(error||data?.error)throw new Error(data?.error||'STAFF_CREATE_FAILED');return data}
export async function resetStaffPin(staffId,pin){const{data,error}=await db.functions.invoke('manage-staff',{body:{action:'reset_pin',staffId,pin}});if(error||data?.error)throw new Error(data?.error||'PIN_RESET_FAILED');return data}
export async function disableStaff(staffId){const{data,error}=await db.functions.invoke('manage-staff',{body:{action:'disable',staffId}});if(error||data?.error)throw new Error(data?.error||'STAFF_DISABLE_FAILED');return data}
