import{db}from'./supabase.js';
export async function stores(userId){const{data:memberships,error}=await db.from('store_memberships').select('store_id,role').eq('user_id',userId).eq('is_active',true);if(error)throw error;if(!memberships?.length)return[];const{data,error:storeError}=await db.from('stores').select('id,name,store_code,staff_login_mode').in('id',memberships.map(x=>x.store_id)).eq('is_active',true);if(storeError)throw storeError;return(data||[]).map(store=>({...store,role:memberships.find(x=>x.store_id===store.id)?.role}))}
export async function countOverview(storeId){const{data,error}=await db.from('inventory_count_sessions').select('id,status,started_at,completed_at').eq('store_id',storeId).order('started_at',{ascending:false}).limit(30);if(error)throw error;return data||[]}
export async function countWorkspace(storeId,userId,access={}){
  const includeDiscrepancies=typeof access==='boolean'?access:Boolean(access.includeDiscrepancies);
  const [sessionResult,zoneResult,productResult,assignmentResult]=await Promise.all([
    db.from('inventory_count_sessions').select('id,status,started_at,completed_at').eq('store_id',storeId).order('started_at',{ascending:false}).limit(30),
    db.from('count_zones').select('id,name,sort_order,is_active').eq('store_id',storeId).eq('is_active',true).order('sort_order'),
    db.from('products').select('id,product_code,name,base_unit,count_unit,is_active').eq('is_active',true).order('name'),
    db.from('zone_products').select('zone_id,product_id,sort_order').order('sort_order')
  ]);
  for(const result of[sessionResult,zoneResult,productResult,assignmentResult])if(result.error)throw result.error;
  const sessions=sessionResult.data||[],active=sessions.find(x=>['IN_PROGRESS','REVIEWING'].includes(x.status)),focus=active||sessions[0];
  let progress=[],entries=[],drafts=[],discrepancies=[];
  if(focus){const results=await Promise.all([
    db.from('count_zone_progress').select('session_id,zone_id,status,completed_at').eq('session_id',focus.id),
    db.from('count_entries').select('id,session_id,zone_id,product_id,quantity,unit,entry_type,entered_at').eq('session_id',focus.id),
    active?db.from('count_drafts').select('session_id,zone_id,product_id,quantity,unit,updated_at').eq('session_id',focus.id).eq('entered_by',userId):Promise.resolve({data:[],error:null}),
    includeDiscrepancies?db.from('inventory_count_discrepancies').select('id,session_id,zone_id,product_id,previous_quantity,estimated_quantity,difference,status').eq('session_id',focus.id):Promise.resolve({data:[],error:null})
  ]);for(const result of results)if(result.error)throw result.error;[progress,entries,drafts,discrepancies]=results.map(x=>x.data||[])}
  return{sessions,zones:zoneResult.data||[],products:productResult.data||[],assignments:assignmentResult.data||[],progress,entries,drafts,discrepancies,activeSession:active||null,focusSession:focus||null};
}
export async function countExportRows(storeId,sessionId){const{data:entries,error}=await db.from('count_entries').select('session_id,zone_id,product_id,quantity,unit,entry_type,entered_at').eq('session_id',sessionId).order('entered_at');if(error)throw error;const productIds=[...new Set((entries||[]).map(x=>x.product_id))],zoneIds=[...new Set((entries||[]).map(x=>x.zone_id))];const[productResult,zoneResult,sourceResult]=await Promise.all([productIds.length?db.from('products').select('id,product_code,name').in('id',productIds):Promise.resolve({data:[],error:null}),zoneIds.length?db.from('count_zones').select('id,name').eq('store_id',storeId).in('id',zoneIds):Promise.resolve({data:[],error:null}),zoneIds.length?db.from('zone_products').select('zone_id,product_id,source_sheet,source_row,source_quantity_column,source_values').in('zone_id',zoneIds):Promise.resolve({data:[],error:null})]);if(productResult.error)throw productResult.error;if(zoneResult.error)throw zoneResult.error;if(sourceResult.error)throw sourceResult.error;return(entries||[]).map(entry=>{const source=sourceResult.data?.find(x=>x.zone_id===entry.zone_id&&x.product_id===entry.product_id);return{盤點時間:entry.entered_at,區域:zoneResult.data?.find(x=>x.id===entry.zone_id)?.name||'',商品編碼:productResult.data?.find(x=>x.id===entry.product_id)?.product_code||'',商品名稱:productResult.data?.find(x=>x.id===entry.product_id)?.name||'',數量:entry.quantity,單位:entry.unit,紀錄類型:entry.entry_type,來源工作表:source?.source_sheet||'',來源列號:source?.source_row||null,數量欄位:source?.source_quantity_column||null,來源原列:source?.source_values||null}})}
export async function catalogWorkspace(storeId){const[productsResult,balanceResult]=await Promise.all([db.from('products').select('id,product_code,name,base_unit,count_unit,is_active').order('created_at'),db.from('store_product_opening_balances').select('product_id,quantity,unit,created_at').eq('store_id',storeId)]);if(productsResult.error)throw productsResult.error;if(balanceResult.error)throw balanceResult.error;return{products:productsResult.data||[],balances:balanceResult.data||[]}}
export async function zoneWorkspace(storeId){const[zoneResult,productResult,assignmentResult]=await Promise.all([db.from('count_zones').select('id,name,sort_order,is_active').eq('store_id',storeId).eq('is_active',true).order('sort_order'),db.from('products').select('id,product_code,name,count_unit,is_active').eq('is_active',true).order('name'),db.from('zone_products').select('zone_id,product_id,sort_order').order('sort_order')]);for(const result of[zoneResult,productResult,assignmentResult])if(result.error)throw result.error;return{zones:zoneResult.data||[],products:productResult.data||[],assignments:assignmentResult.data||[]}}
export async function createPilotProduct(storeId,values){const{data,error}=await db.rpc('create_pilot_product',{p_store_id:storeId,p_product_code:values.productCode,p_name:values.name,p_count_unit:values.countUnit,p_purchase_unit:values.purchaseUnit,p_opening_quantity:Number(values.openingQuantity)});if(error)throw error;return data}
export async function createPilotZone(storeId,name){const{data,error}=await db.rpc('create_pilot_zone',{p_store_id:storeId,p_name:name});if(error)throw error;return data}
export async function assignPilotProduct(zoneId,productId){const{error}=await db.rpc('assign_pilot_product_to_zone',{p_zone_id:zoneId,p_product_id:productId});if(error)throw error}
export async function renamePilotZone(zoneId,name){const{error}=await db.rpc('rename_pilot_zone',{p_zone_id:zoneId,p_name:name});if(error)throw error}
export async function deactivatePilotZone(zoneId){const{error}=await db.rpc('set_pilot_zone_active',{p_zone_id:zoneId,p_active:false});if(error)throw error}
export async function reorderPilotZones(storeId,zoneIds){const{error}=await db.rpc('reorder_pilot_zones',{p_store_id:storeId,p_zone_ids:zoneIds});if(error)throw error}
export async function unassignPilotProduct(zoneId,productId){const{error}=await db.rpc('unassign_pilot_product_from_zone',{p_zone_id:zoneId,p_product_id:productId});if(error)throw error}
export async function publishCountImport(store,profile,preview){const batchId=crypto.randomUUID(),safeName=preview.fileName.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${profile.organization_id}/${store.id}/${batchId}/${safeName}`;const upload=await db.storage.from('count-imports').upload(path,preview.file,{upsert:false,contentType:preview.mimeType});if(upload.error)throw upload.error;const created=await db.from('count_import_batches').insert({id:batchId,organization_id:profile.organization_id,store_id:store.id,source_filename:preview.fileName,source_mime_type:preview.mimeType,source_storage_path:path,source_sheet:preview.sheetName,template_version:preview.templateVersion,headers:preview.headers,imported_by:profile.id,status:'DRAFT'});if(created.error)throw created.error;const{data,error}=await db.rpc('publish_pilot_count_import',{p_batch_id:batchId,p_rows:preview.rows});if(error)throw error;return{batchId,rowCount:data}}
export async function createPilotCountSession(storeId){const{data,error}=await db.rpc('create_pilot_count_session',{p_store_id:storeId});if(error)throw error;return data}
export async function saveCountDraft(profile,sessionId,zoneId,productId,quantity,unit){const value=Number(quantity);if(!Number.isFinite(value)||value<0)throw new Error('COUNT_QUANTITY_INVALID');const now=new Date().toISOString();const{error}=await db.from('count_drafts').upsert({organization_id:profile.organization_id,session_id:sessionId,zone_id:zoneId,product_id:productId,quantity:value,unit,entered_by:profile.id,entered_at:now,updated_at:now},{onConflict:'session_id,zone_id,product_id'});if(error)throw error}
export function createThrottledDraftSaver(save,{wait=650,onState=()=>{}}={}){const pending=new Map,inflight=new Set;async function persist(key){const item=pending.get(key);if(!item)return;pending.delete(key);onState(key,'saving');const operation=Promise.resolve().then(()=>save(...item)).then(()=>onState(key,'saved'),error=>{onState(key,'failed',error);throw error}).finally(()=>inflight.delete(operation));inflight.add(operation);return operation}return{schedule(key,...args){const previous=pending.get(key);if(previous?.timer)clearTimeout(previous.timer);const item=args;item.timer=setTimeout(()=>{persist(key).catch(()=>{})},wait);pending.set(key,item);onState(key,'pending')},cancel(key){const item=pending.get(key);if(item?.timer)clearTimeout(item.timer);pending.delete(key)},async flush(){for(const[key,item]of[...pending]){if(item.timer)clearTimeout(item.timer);await persist(key)}await Promise.all([...inflight])},hasPending(){return pending.size>0||inflight.size>0}}}
export async function completePilotCountZone(sessionId,zoneId){const{error}=await db.rpc('complete_pilot_count_zone',{p_session_id:sessionId,p_zone_id:zoneId});if(error)throw error}
export async function resolvePilotCountDiscrepancy(id,values){const{data,error}=await db.rpc('resolve_pilot_count_discrepancy',{p_discrepancy_id:id,p_reason:values.reason,p_action:values.action,p_quantity:Number(values.quantity)});if(error)throw error;return data}
export async function receiptOverview(storeId){const{data,error}=await db.from('receipt_upload_batches').select('id,batch_number,status,uploaded_at,work_date,receipt_documents(id)').eq('store_id',storeId).order('uploaded_at',{ascending:false}).limit(30);if(error)throw error;const batches=data||[],ids=batches.map(item=>item.id);if(!ids.length)return batches;const runs=await db.from('receipt_ocr_runs').select('batch_id,version,status,error_code,error_message,completed_at').in('batch_id',ids).order('version',{ascending:false});if(runs.error)throw runs.error;return batches.map(batch=>{const latest=(runs.data||[]).find(run=>run.batch_id===batch.id);return{...batch,latestRun:latest||null,ui_status:latest?.status==='FAILED'?'FAILED':batch.status}})}
export async function receiptWorkbench(storeId,batchId){const batches=await receiptOverview(storeId);if(!batchId)return{batches,detail:null};const batch=batches.find(x=>x.id===batchId);if(!batch)throw new Error('BATCH_NOT_FOUND');const[docsResult,runsResult,fieldsResult,correctionsResult]=await Promise.all([db.from('receipt_documents').select('id,storage_path,original_filename,mime_type,page_order,created_at').eq('batch_id',batchId).order('page_order'),db.from('receipt_ocr_runs').select('id,version,status,provider,model,started_at,completed_at,error_message').eq('batch_id',batchId).order('version',{ascending:false}),db.from('receipt_ocr_fields').select('id,ocr_run_id,row_key,field_name,raw_value,normalized_value,confidence,review_status').eq('batch_id',batchId).order('row_key'),db.from('receipt_review_corrections').select('id,ocr_field_id,old_value,new_value,modified_at,modified_by').eq('batch_id',batchId).order('modified_at',{ascending:false})]);for(const result of[docsResult,runsResult,fieldsResult,correctionsResult])if(result.error)throw result.error;const documents=[];for(const doc of docsResult.data||[]){const signed=await db.storage.from('receipt-documents').createSignedUrl(doc.storage_path,600);documents.push({...doc,signedUrl:signed.data?.signedUrl||null})}return{batches,detail:{batch,documents,runs:runsResult.data||[],fields:fieldsResult.data||[],corrections:correctionsResult.data||[]}}}
export async function correctReceiptField(profile,batchId,fieldId,oldValue,newValue){const{error}=await db.from('receipt_review_corrections').insert({organization_id:profile.organization_id,batch_id:batchId,ocr_field_id:fieldId,old_value:oldValue,new_value:newValue,modified_by:profile.id});if(error)throw error}
export async function retryReceiptOcr(batchId){const queued=await db.functions.invoke('enqueue-receipt-ocr',{body:{batchIds:[batchId]}});if(queued.error)throw queued.error;return queued.data}
export async function uploadReceipts(store,profile,files){const batchNo=`#${new Date().toISOString().replace(/\D/g,'').slice(4,15)}`;const{data:batch,error}=await db.from('receipt_upload_batches').insert({organization_id:profile.organization_id,store_id:store.id,batch_number:batchNo,uploaded_by:profile.id,store_name:store.name,work_date:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'}),status:'PROCESSING'}).select().single();if(error)throw error;for(let i=0;i<files.length;i++){const file=files[i],path=`${profile.organization_id}/${batch.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await db.storage.from('receipt-documents').upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});if(up.error)throw up.error;const doc=await db.from('receipt_documents').insert({organization_id:profile.organization_id,batch_id:batch.id,storage_path:path,original_filename:file.name,mime_type:file.type||'image/jpeg',page_order:i+1,uploaded_by:profile.id});if(doc.error)throw doc.error}const queued=await db.functions.invoke('enqueue-receipt-ocr',{body:{batchIds:[batch.id]}});if(queued.error)throw queued.error;return batch}
export async function storeStaff(storeId){const{data:memberships,error}=await db.from('store_memberships').select('user_id,login_identifier,role,is_active,created_at').eq('store_id',storeId).order('created_at',{ascending:true});if(error)throw error;if(!memberships?.length)return[];const{data:identities,error:identityError}=await db.from('staff_identities').select('user_id,display_name,nickname,job_title,employee_number,is_active').in('user_id',memberships.map(x=>x.user_id));if(identityError)throw identityError;return memberships.map(item=>({...item,identity:identities?.find(x=>x.user_id===item.user_id)||null}))}
